### ISSUE TITLE
Out of memory failures look like successful runs

### ISSUE THREAD

**Issue by aaronstgeorge-wf** [dart-lang/test#1003]
We've found that if the browser runs out of memory while running unit tests (due to memory leaks in the dart code under test) the test runner reports success. It seems like some sort of error should be reported.

Example:
```dart
@TestOn("browser")

import 'dart:html';
import 'dart:math';

import "package:test/test.dart";

void createMemoryLeak() {
  var a = new List.filled(100000000, pow(2, 53));
  window.onClick.listen((_) {
    print(a);
  });
}

void main() {
  test("leak a bunch of memory 1", () {
    createMemoryLeak();
  });

  test("leak a bunch of memory 2", () {
    createMemoryLeak();
  });

  test("leak a bunch of memory 3", () {
    createMemoryLeak();
  });

  test("leak a bunch of memory 4", () {
    createMemoryLeak();
  });

  test("this test should fail", () async {
    expect(true, isFalse);
  });
}
```
Running this test suite on my machine in chrome only gets through three of the tests but reports success with a `0` exit code.
```bash
~/Dev/dart/oom pub run test -p chrome test/oom_test.dart --reporter=expanded
00:00 +0: compiling test/oom_test.dart
Compiled 8,598,577 characters Dart to 1,021,698 characters JavaScript in 4.33 seconds
Dart file (/private/var/folders/mm/5_ns8ybs7pngk54qtdmcc8j40000gp/T/dart_test_WuvG1r/runInBrowser.dart) compiled to JavaScript: /private/var/folders/mm/5_ns8ybs7pngk54qtdmcc8j40000gp/T/dart_test_wdfpNc/test_W2KUPN/oom_test.dart.browser_test.dart.js

00:00 +0: leak a bunch of memory 1
01:03 +1: leak a bunch of memory 2
02:05 +2: leak a bunch of memory 3
02:11 +2: All tests passed!
~/Dev/dart/oom echo $?
0
```

**Comment by grouma** [comment]
Thanks for the issue. This seems like a fun one :P

I did a little initial digging. 

For some reason the engine is reporting success here:
https://github.com/dart-lang/test/blob/master/pkgs/test_core/lib/src/runner/engine.dart#L94

This comment seems very problematic:
https://github.com/dart-lang/test/blob/master/pkgs/test_api/lib/src/backend/state.dart#L16

I don't have the context for why that decision was made so we'll have to investigate further to see how changing that assumption impacts the engine.

**Comment by robbecker-wf** [comment]
Any progress here?

**Comment by grouma** [comment]
I haven't had time to spend cycles on this one yet unfortunately.

We basically need to adjust this line here: https://github.com/dart-lang/test/blob/master/pkgs/test_api/lib/src/backend/live_test_controller.dart#L82

One potential fix is to assume tests have failed while pending but I don't know the repercussions of that change. For example the test runner is likely to report a number of errors if you prematurely exit a test run using ctrl + c.

If that proves problematic, we can alternatively introduce another result type like "notRun" and set all pending tests to this value. The engine can adjust its reporting to consider those tests as failed if it "completes" prematurely.

I don't anticipate getting to this issue in the near future so if you want to take a stab at it I'd be happy to review a PR.

**Comment by grouma** [comment]
Note that I will start tackling this now.

**Comment by robbecker-wf** [comment]
Thanks @grouma This will be a big help! I assume it will ship in test 1.6.3 ?

**Comment by grouma** [comment]
Yes. I'll publish shortly.
