### ISSUE TITLE
Snapshot Testing

### ISSUE THREAD

**Issue by listepo** [dart-lang/test#1004]
Are there any plans for [Snapshot Testing](https://jestjs.io/docs/ru/snapshot-testing)?
I think this might be useful for testing code generation tools and etc.

**Comment by allentv** [comment]
I do like snapshot testing especially automatic updates in the watch mode :-)

Were you thinking about serializing the object attributes and then checking if test produces the same attribute values? Since there is new UI elements to dump as with React, objects were the only stateful entity I could think of. Would there be anything else to be included?

**Comment by grouma** [comment]
If I'm not mistaken the Flutter test framework supports golden image testing. 

@jonahwilliams do we have documentation around this?

If we wanted to add support inside `package:test` itself it should be pretty straightforward for the Browser platform. I'd be open to review PRs but this is likely something I can't get to in the near term.

**Comment by jakemac53** [comment]
This is likely something that could exist as a separate package as well. It probably doesn't need to be a part of the core framework.

**Comment by allentv** [comment]
External package sounds good. Would serialization and deserialization of objects be a good starting point?

**Comment by jonahwilliams** [comment]
The golden framework testing is pretty bespoke. I would give something like https://pub.dev/packages/goldenrod a shot instead of trying to imitate flutter

**Comment by gsouf** [comment]
@grouma flutter golden is dedicated to test widget screenshots? What if I want to test a string or json serializable as something that is not a flutter project?

**Comment by jakemac53** [comment]
If all you want to do is compare JSON strings that should be trivial to do in the normal test framework, you can just use normal string matchers. Can you explain the use case more?

**Comment by jakemac53** [comment]
Ok, so if I understand correctly the primary issue is around the generation of the goldens themselves, and the workflows for approving/checking in changes to them?

**Comment by matsp** [comment]
Yes exactly.

**Comment by jakemac53** [comment]
What I would suggest, and how many tools I have used previously do it, is a package which releases a combination of a command line tool to update goldens as well as a custom matcher, which in its failure message would log the command to run to update the golden.

**Comment by matsp** [comment]
@jakemac53 Coming back after using an env variable as workaround to detect recreation of golden files. It just feels wrong 😉 Would it be a big effort to allow custom flags e.g. `dart test -f my_custom_flag` like `dart test -t tag` and pass them in the `test(...)` function?
