### ISSUE TITLE
Test coverage marks asserts as unexecuted if the clause evaluates to true

### ISSUE THREAD

**Issue by xster** [dart-lang/test#1006]
There's a lot of code in Flutter where we're verifying our assumptions and states via asserts in code like https://coveralls.io/builds/22463149/source?filename=lib/src/foundation/binding.dart#L211

Though they all seem to report DA:x,0 after running tests with coverage collection. 

Evaluating to false like https://coveralls.io/builds/22463149/source?filename=lib/src/cupertino/date_picker.dart#L179 or evaluating a closure like https://coveralls.io/builds/22463149/source?filename=lib/src/widgets/heroes.dart#L222 seem to get counted though.

Any thoughts on what this might be and if it's intended behavior?

**Comment by grouma** [comment]
`package:test` doesn't support coverage directly yet. I believe Flutter test coverage is supported by `package:coverage`. I'd suggest opening up an issue here: https://github.com/dart-lang/coverage

**Comment by xster** [comment]
My bad, moved to #251
