### ISSUE TITLE
Content shell never exits after tests run

### ISSUE THREAD

**Issue by danschultz** [dart-lang/test#101]
When running tests with `-p content-shell`, Content Shell never closes and the test process never exits. This causes issues when running tests as part of a build process, because the tests will never complete. This also happens when running with `-p dartium`.

I'm running Dart 1.10 on Mac 10.10.3 with v0.12.0 of the test package.

**Comment by nex3** [comment]
Are you sure you have the latest content shell and Dartium? It's easy for it to get out-of-sync with your VM, and older versions can fail strangely.

> I'm running Dart 1.11 on Mac 10.10.3 with v0.12.0 of the test package.

Dart 1.11 hasn't been released yet. Are you on the dev channel? What dev version are you using?

**Comment by danschultz** [comment]
@nex3 sorry, I'm running Dart 1.10.0. I've installed Content Shell through brew.

**Comment by danschultz** [comment]
I've confirmed that I'm running the latest Content Shell:

```
dan$ which content_shell
/usr/local/bin/content_shell
dan$ ls -la /usr/local/bin/ | grep content_shell
lrwxr-xr-x    1 dan   admin        42 May  4 23:44 content_shell -> ../Cellar/dartium/1.10.0/bin/content_shell
```

**Comment by kevmoo** [comment]
@danschultz Do me a favor

Delete `.pub` directory and re-run `pub install`

**Comment by danschultz** [comment]
@kevmoo no dice.

When I manually download Content Shell and add it to my path, the process closes normally. This issue seems to only happen when installing Content Shell through brew.

**Comment by nex3** [comment]
Closing this out 'cause it doesn't look like an issue with `test`.
