### ISSUE TITLE
Proposal: add a utility method 'flushMicrotasks()' to dart:test

### ISSUE THREAD

**Issue by enetor** [dart-lang/test#1010]
Library developers often need to test asynchronous code. It is quite common to see the following pattern:

```
test('my async test', () async {
  // my async setup.
  await Future.delayed(Duration.zero);  // Flush microtasks.
  await expect(...);
});
```

In fact, this pattern is seen in multiple places in this library's tests:

https://github.com/dart-lang/test/search?q=Duration.zero&unscoped_q=Duration.zero

I wonder if we can include a common utility method in dart:test? This can be something like:

```
/// Flushes the microtasks queue. This is typically awaited in asynchronous tests so
/// enqueued microtasks can finish before moving on.
Future<Null> flushMicrotasks() => Future<Null>.delayed(Duration.zero);
```

**Comment by grouma** [comment]
We offer `pumpEventQueue`: https://github.com/dart-lang/test/blob/master/pkgs/test_api/lib/src/frontend/utils.dart#L14

I think that's what you want.

**Comment by grouma** [comment]
As for why we have tests with the above pattern. We added `pumpEventQueue` pretty late in development: https://github.com/dart-lang/test/blob/8529cf4241041fd90bc5dfd8455ad600d565dfe2/pkgs/test/CHANGELOG.md#012281

We should probably clean those use cases up.

Let me know if you have any issues and thanks for the suggestion!

**Comment by enetor** [comment]
Thanks for the prompt response, Gary! That answers my question!

**Comment by humblerookie** [comment]
@grouma Is there any limitation that prevents the api from figuring out pending items on the event queue rather than user supplying this on a guesstimate basis?

**Comment by grouma** [comment]
@humblerookie I think that's what the test framework already does. We track ongoing work with a heart beat to determine if we should timeout the test.

See this:
https://github.com/dart-lang/test/blob/92eccb2a13a43a53c9d7da97d3b4d84a9464d8c8/pkgs/test_api/lib/src/backend/invoker.dart#L223

Also some updated documentation:
https://github.com/dart-lang/test/pull/1204

**Comment by natebosch** [comment]
> Is there any limitation that prevents the API from figuring out pending items on the event queue rather than the user supplying this on a guesstimate basis?

Doing so would require a very complex `ZoneSpecification` that interacts deeply with async behavior (similar to `FakeAsync` in terms of complexity) and it would also slow down everything async running in that zone. It's not a feature we plan to target.
