### ISSUE TITLE
Allow tests to load package resources from their regular path

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/test#103]
When DOM testing Angular components setup usually involves preloading the component template into Angulars `TemplateCache` (unless the template is so small that it's inlined with the component declaration). This is done by just doing a http request for the template, typically something like  `/packages/myapp/mycomponent.html` and then putting the result in the cache under that path. 

When you run tests with Karma this just works, but when using `test` my package is put under some subpath like `http://localhost:60675/XsRqXVS980xbKCCQL_4m8H9DKzRNxl4m/packages/...`
I can fetch the template if I prepend the path with the test ID (or whatever it is), but this puts some unwelcome knowledge about the test environment into the test code. 

Would it be possible to either (in order of preference)...
* Make packages resolvable from the root so you could just fetch `/packages/myapp/mycomponent.html` instead of `/some-generated-test-ID/packages/myapp/mycomponent.html`
* Add API to the test package for doing this URL transform or getting the package path prefix. It's of course trivial to do this yourself but it seems wrong for my test code to assume anything about what path it is served from and which may change with new versions of the test package.

**Comment by nex3** [comment]
The blob at the beginning of the URL is there to ensure that other users on the same machine can't snoop on your HTTP server while you're running tests.

Is there any reason your URLs have to be absolute? If you make them relative (`packages/myapp/mycomponent.html`) they'll work anywhere beneath the initial blob.

**Comment by lassedamgaard** [comment]
Yes it works with relative URLs. The reason for using absolute URLs is that it's a little easier to work with when using pushstate routes. It's no big deal but just seems suboptimal that the test framework more or less forces you do to this. 

If the path prefix is only there for security reasons, could it then be made optional? It's not really a concern in my setup.

**Comment by nex3** [comment]
I'm pretty reticent to add more options that aren't clearly necessary—every option adds friction for people who don't use it. In general it's a good practice not to assume absolute URLs anyway, so I think I'm going to close this out.
