### ISSUE TITLE
expectAsync0 fails within callbacks with non-zero count

### ISSUE THREAD

**Issue by grouma** [dart-lang/test#1035]
See the sample PR: https://github.com/dart-lang/test/pull/1034

**Comment by natebosch** [comment]
@joshprzybyszewski-wf

The syntax in the PR would be expected to fail. The returned value from the `expecteAsync0` call is never used, never called, and so it should time out. `expectAsync*` should not be used _inside_ some callback that is expected to be called, it should _wrap_ a callback that is expected to be called.

An explanation of what is happening.

```dart
  var callbackFn = (){
    expectAsync0(() {}, count: 1); // Returns a value that is ignored
  };
  callbackFn(); // Calls something that _sets up_ and expectAsync, but doesn't _execute_ the wrapped callback.
```

The correct way to write the code to satisfy your goal:

```dart
  var callbackFn = expectAsync0(() {}, count: 1); // Returns a value that is used
  callbackFn(); // Calls the wrapped callback.
```
