### ISSUE TITLE
\n newline characters in json output

### ISSUE THREAD

**Issue by raubreysmith** [dart-lang/test#1037]
We're using `flutter test --machine` to output results for our CI process. The error and stacktrace properties include `\n` characters.

Stacktrace characters are escaped while error message characters are not.

```
// newline.test.dart
import "package:test/test.dart";

void main() {
  test('Newline test', () {
    expect(false, true, reason: 'unescaped chars in reason C:\new folder\notes');
  });
}
```

```
// pub run test test/newline.test.dart --reporter json
...
{"testID":3,"error":"Expected: <true>\n  Actual: <false>\nunescaped chars in reason C:\new folder\notes\n","stackTrace":"package:test_api            expect\ntest\\newline.test.dart 5:5  main.<fn>\n","isFailure":true,"type":"error","time":1170}
...
```

While not a major issue to parse and handle, I would expect the output to be consistent.

```
pub -v
FINE: Pub 2.3.0
``` 

Possibly related to https://github.com/dart-lang/matcher/issues/40

**Comment by natebosch** [comment]
As far as I can tell everything is working as expected here.

Your `reason` string has literal newlines in it. If you were to `print` that string, you'd see it across multiple lines in the output. We expect that literal newlines get emitted as `\n` in the JSON output.
