### ISSUE TITLE
How to write tests that depend on unknown data?

### ISSUE THREAD

**Issue by komapeb** [dart-lang/test#1051]
So... I have a git repository, which is basically data-only and I'm writing a framework (package) that parses it and builds some complex objects around the data. This package has its own tests but it's so tightly-coupled with the data that it doesn't mean anything only by itself, that's why I also need to test the data (said cloned repo is not a Dart package, it just contains some JSON files and assets).
In my tests I have a `setUpAll` that clones the data repo in a tmp dir on the local drive (where tests are being run) and a `tearDownAll` that deletes said repo. So far so good...

Problem:
I'm going through some directories, parsing (JSON) files in a loop (the loop itself is not in a `test()`) and on each iteration I'd like to run some dynamic tests, with the parsed JSONs. The loop itself depends on some kind of an initialization, which is based on the cloned data-repo, which I need to wait for before it's cloned. Since the loop isn't in a `test()` though, `setUpAll()` doesn't help.

How would one go about solving such this?

*(If your suggestion is to make the data part of the framework, it wouldn't work, since I need it to be separate. Multiple frameworks, written in different languages will be working with this same data-repository.)*

**Comment by jakemac53** [comment]
You can set up tests asynchronously if you don't put them in a `setUpAll`. Note that there are some negative consequences of this, it will run this code just in order to figure out if the the tests should even be ran (based on name/tags/etc), where `setUpAll` would not run if no tests needed to be ran. Basically something like this:

```dart
import 'package:test/test.dart';

void main() async {
  // Not in a setUpAll so that we can define tests using this result data.
  var data = await Future.delayed(Duration(seconds: 1), () async => ["a", "b"]);

  tearDownAll(() {
    data.clear();
  });

  for (var item in data) {
    test('$item is $item', () {
      expect(item, equals(item));
    });
  }
}
```

**Comment by komapeb** [comment]
This does the job, thanks.
