### ISSUE TITLE
How to print info messages in dart:test?

### ISSUE THREAD

**Issue by AlexanderArendar** [dart-lang/test#1070]
When writing tests with dart:test how to print info messages such that they appear interleaved with tests output? If I use print then it prints in the end, after all tests output.

I've come from Scala ecosystem and looking for analog of `info()` method in `ScalaTest`.
The need is not only for debugging but also for being able to implement tests style similar to [FunSpec](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwjZtvvF6MPkAhVDposKHWp-DwYQFjAAegQIABAB&url=http%3A%2F%2Fwww.scalatest.org%2Fgetting_started_with_fun_spec&usg=AOvVaw0LYTRUjh8k8LQX-6InUXRx).

**Comment by jakemac53** [comment]
In general I believe you are discouraged from doing your own logging in order to reduce noise. Only failed tests should have output.

There is the [printOnFailure](https://pub.dev/documentation/test_api/latest/test_api/printOnFailure.html) method for that purpose, which is what would be generally advised to use.

The `expect` method also has a `reason` named argument which if provided will be logged if that expect fails along with the information about the failure.

**Comment by AlexanderArendar** [comment]
Jacob, I am aware about `printOnFailure` and `reason`. So I was not posting this issue as a bug or something, it was a mere question since I am reviewing strengths and weaknesses of `dart:test`. 
You have an awesome framework but other test frameworks from other ecosystems evolve in one or another way to provide richer logging support.
So if it is a philosophy of the `dart:test` that `Only failed tests should have output.` then I can live with that but let me try to explain you from my experience and experience of others why we, users or the framework, may need such features.
For example, consider how the following test is written:
```
"For new event there" should "not be any price packages configured by default" in {
    val event = Editable(Event.testEvent)
    Test {
      Given("a new event")
      createEvent(event)
      When("event organizer logs in to this event and navigates to Price Packages view")
      withNewTab(EventOrganizerDashboardPage.navigateToEventSiteURL(event)) {
        EventLandingPage.loginUserOnEventSite(User.QAEventOrganizer)
        EventOrganizerOutdoorMapPage.openPricePackages
        Then("no price packages should be shown there")
        PricePackagesPage.pricePackageListEmpty shouldBe true
      }
    } afterThat {
      EventOrganizerDashboardPage.cleanUpEvent(event)
    }
  }
```

I think that such (and others existing test styles) allows more flexible approach and allows a developer to select from more than one ways to write tests.
This test produces following output
```
08:43:36 [info] PricePackagesLocalFirefoxTest:
08:43:36 [info] For new event there
08:44:14 [info] - should not be any price packages configured by default
08:44:14 [info]   + Given a new event 
08:44:14 [info]   + When event organizer logs in to this event and navigates to Price Packages view 
08:44:14 [info]   + Then no price packages should be shown there 
```

This is way more informative than having mere ability to only provide a test description as a string I believe. If the test asserts fail the output will have these assertion errors inserted correctly in the right place.

Such things are possible because test framework developers decided at some moment of time that the philosophy `Only failed tests should have output.` is probably not the best one.

I think it would not hurt anyone if `dart:test` provides at least some `print`/`log` method which allows tests to log some info in the test suite output in a proper way. Probably having such feature will allow creative developers to implement something more than a test with a single string description and callback body.

Hope my example gives the idea and hope that `dart:test` evolve and does not stay at one place :)

**Comment by AlexanderArendar** [comment]
@grouma by the way, is it a good practice to close a question when the OP did not even had a chance to add a comment yet? I think it is not.

**Comment by jakemac53** [comment]
If you use the `expanded` reporter with `print` you can basically recreate this behavior it seems like - you would also probably want to use `-j 1` so multiple tests can't run at once.

```dart
import 'package:test/test.dart';

void main() async {
  group("For new event there", () {
    test("should not be any price packages configured by default", () {
      print("Given a new event");
      print("When event organizer logs ...");
      print("no price packages should be shown...");
      expect([1], isEmpty);
    });
  });
}
```

pub run test -j 1 --reporter=expanded

```
00:00 +0: test/example_test.dart: For new event there should not be any price packages configured by default
Given a new event
When event organizer logs ...
no price packages should be shown...
00:00 +0 -1: test/example_test.dart: For new event there should not be any price packages configured by default [E]
  Expected: empty
    Actual: [1]
  
  package:test_api            expect
  test/example_test.dart 9:7  main.<fn>.<fn>
  
00:00 +0 -1: Some tests failed.
```

**Comment by jakemac53** [comment]
> @grouma by the way, is it a good practice to close a question when the OP did not even had a chance to add a comment yet? I think it is not.

It is easy to re-open issues - since there wasn't much information in the original issue it seemed like it was resolved.

We do tend to fairly aggressively close issues otherwise the issue trackers become unmanageable, and often times people never respond so we don't tend to wait.

**Comment by AlexanderArendar** [comment]
Jacob, thanks a lot. This is precisely what I was looking for. `--reporter=expanded` makes the `print` output look in place. Cool :)
