### ISSUE TITLE
Enable cron job for this repo

### ISSUE THREAD

**Issue by grouma** [dart-lang/test#1075]

**Comment by kevmoo** [comment]
Travis cron runs weekly against master. 

See https://travis-ci.org/dart-lang/test/builds

Want it more often?

**Comment by grouma** [comment]
Thanks for the quick response. 

Weekly is fine. We thought there wasn't a cron job since it took a while to discover the issue resolved by: https://github.com/dart-lang/test/pull/1074

I'm still a little confused as to why the corresponding test did not start failing earlier.
