### ISSUE TITLE
Shard options are hidden

### ISSUE THREAD

**Issue by willdrach-wk** [dart-lang/test#1086]
I'm curious the reasoning behind the `--total-shards` and `--shard-index` options being hidden. We have a use case to utilize those, but obviously don't want to hook our CI up to an unsupported API.

**Comment by grouma** [comment]
This package transitioned ownership and certain things certainly fell through the cracks. This is used pretty extensively so it's probably fine to expose it.

**Comment by jakemac53** [comment]
+1 this was originally only written for internal use but I don't see any reason not to make it officially supported. We have been using it on travis in package:build for a long time now and it seems perfectly stable and very useful.
