### ISSUE TITLE
Feature Request: isAssertionError

### ISSUE THREAD

**Issue by srawlins** [dart-lang/test#1094]
As an [AssertionError](https://api.dartlang.org/stable/1.24.3/dart-core/AssertionError-class.html) is thrown when an `assert` is given `false`, which is a core language thing, it would be nice to have a handy `throwsAssertionError` matcher.

**Comment by natebosch** [comment]
For some reason our throws matchers are defined in the test package, not the matcher package... Moved the issue.

**Comment by natebosch** [comment]
cc @jonahwilliams - `flutter_test` currently defines a `throwsAssertionError`.
https://github.com/flutter/flutter/blob/a62bb3d9abe416a77d785ea712416a208946d406/packages/flutter_test/lib/src/matchers.dart#L181

Are the versions pinned such that if I add one here you'll be able to migrate to it without breaking users in the meantime?

**Comment by jonahwilliams** [comment]
@natebosch should be fine to add, we can delete ours in the PR that rolls in a new test version

**Comment by natebosch** [comment]
This is challenging to roll out because we need to be synchronized with flutter when we roll into google3. I don't plan on pushing on this - someone else can pick it up if it is urgent.

**Comment by natebosch** [comment]
See https://github.com/dart-lang/test/issues/904#issuecomment-580947127

I think we want to move in the other direction and stop adding `throws*` and `is*` variables.

We will not plan on adding `isAssertionError`, and in the long term we'll hopefully get rid of existing ones.

I'm going to close this issue as not planned and we'll keep the other opened for tracking work.
