### ISSUE TITLE
Feature request: `flutter` platform for boolean selectors

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#1096]
This would be based on whether the current sdk is the flutter sdk or the dart sdk.

This can be detected based on the `Platform.version` which will either contain the text `flutter` or not.

**Comment by natebosch** [comment]
What is the use case?

**Comment by jakemac53** [comment]
To run tests that are only relevant on flutter - we currently have a few test files that do this manually. It isn't that hard to do on your own though, so we could close this.

We would probably need to support a `-p flutter` command at that point which i don't want to do.

**Comment by natebosch** [comment]
Yeah I worry this is too specialized. The only tests that should care about this selector is the code that already has other special awareness of the difference between the two SDKs and so it make sense for that code to also do the check between them. Exposing it in this package feels to me like it would be encouraging complexity in other places that don't need it.
