### ISSUE TITLE
activate or skip tests based on execution mode (checked vs. production)

### ISSUE THREAD

**Issue by chalin** [dart-lang/test#111]
From [this May 12, 2015][1] Dart-misc post:
> Does the new test package provide/suggest a way to determine if tests are being executed in check vs. production mode? I can write my own boolean isCheckedMode() function and use it, e.g., as a value for the "skip" named parameter, but it might be useful to provide such a functionality as part of the test package, if it isn't there already.

To give concrete examples: maybe something like 

```dart
@TestOn("vm && productionMode")
```

or possibly

```dart
test("error-checking test", () {
  // ...
}, skip: checkedMode);
```

[1]: https://groups.google.com/a/dartlang.org/d/msg/misc/BdYTxNKzark/lInlJ-exG0kJ

**Comment by eernstg** [comment]
On Wed, May 13, 2015 at 4:01 PM, Patrice Chalin <notifications@github.com>
wrote:

> From this May 12, 2015
> <https://groups.google.com/a/dartlang.org/d/msg/misc/BdYTxNKzark/lInlJ-exG0kJ>
> Dart-misc post:
>
> Does the new test package provide/suggest a way to determine if tests are
> being executed in check vs. production mode? I can write my own boolean
> isCheckedMode() function and use it,
>
>
Just in case that turns out to be relevant, here's one that is used with
the co19 test suite:

isCheckedMode() {
  try {
    var i = 1;
    String s = i;
    return false;
  } on TypeError catch(e) {
    return true;
  }
}

  best regards,

-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by nex3** [comment]
I don't want to encourage users to write code that works in unchecked mode and not checked mode, or vice versa. While there may be some valid use-cases, I think most of the time it's a bad enough idea that it would provide negative value to bake it into the test infrastructure.

**Comment by chalin** [comment]
It is fundamental to Dart that code can behave differently in checked vs. production mode. Having the test package provide a definition like the `isCheckeMode()` that Erik suggested earlier does nothing to encourage or discourage users from writing code that will exhibit differing behavior based on the execution mode. It just provides standard support for the need to test in both modes. My 2 cents. (It might be worth conducting a quick informal survey to find out how many folks test in both modes. I don't mind posting such a question on, say, Dart-misc, if you might be swayed to re-open this issue :). )

**Comment by chalin** [comment]
FYI, went ahead add created [this simple poll on +Dartisans](https://plus.google.com/+PatriceChalin/posts/2Jbxk2pBEL2).

**Comment by nex3** [comment]
A poll is not going to sway my opinion.

**Comment by zoechi** [comment]
Preventing ugly things produces uglier workarounds.
Mine is:

```dart
bool isCheckedMode = false;
assert(() => isCheckedMode = true);
if(isCheckedMode) {
   ...
}
```
When code uses assertions it may fail in checked mode but not in production mode (just one prominent example), this has to be taken into account for testing.

**Comment by chalin** [comment]
@nex3, the poll is to collect information about usage as well as comments about use cases. Currently, 30% of respondents run at least some tests in production mode. In case you are not following the thread of discussion associated with the poll, here was one of my responses about use cases:

> programs (and libraries / third party packages) don't have to behave the same in checked vs. production mode for any number of reasons. E.g., logging / debugging code elimination (see @sethladd 's blog entry on ["Compile-time dead code elimination"](http://blog.sethladd.com/2013/12/compile-time-dead-code-elimination-with.html) for an example) might change behavior in unanticipated ways.

Paul Brauner also mentioned load tests / benchmarks.

If one is targeting 'vm' and 'chrome' it seems reasonable to test on both. Likewise, it seems reasonable to test in the mode that the deployed code will _actually_ be running in (most likely production mode), as well as checked mode.

@zoechi, clever mechanism for setting a flag based on the mode. Thanks for sharing.
