### ISSUE TITLE
flutter web testing does not work

### ISSUE THREAD

**Issue by PavelPZ** [dart-lang/test#1111]
I installed newest flutter (in dev channel) and created new project:
```
> flutter channel dev
> flutter upgrade
> flutter create pom
> cd pom
```
I added  ```build_web_compilers``` and ```build_test``` to dev_dependencies.

## Running with error:
Than I tried all of the possibilites I found for chrome testing, without success:
- **> pub run test -p chrome** (hundreds of error lines)
- **> flutter pub run test -p chrome** (hundreds of error lines)
- **> flutter test --platform chrome** (*Failed to load "C:\temp\pom\test\widget_test.dart, Failed to load script at http://localhost:53183/widget_test.dart.browser_test.dart.js.*)

## Running well:
- **> flutter run -d chrome** 
- **> flutter test**

**Comment by natebosch** [comment]
We don't expect `pub run test` or `pub run build_runner` test to work for flutter web.

If `flutter test` doesn't work for web tests we'll need an issue filed against the flutter repo. I don't think this is actionable here.

**Comment by natebosch** [comment]
cc @jonahwilliams - what is the expected way to run flutter tests on the web?

**Comment by jonahwilliams** [comment]
No, you'll need to run `flutter test`. We also _lightly_ support `flutter test --platform=chrome` to run in browsers, but this is still highly experimental

**Comment by natebosch** [comment]
Sounds like this is behaving as expected today and there aren't any actions to take here.

**Comment by PavelPZ** [comment]
How to understand test package documentation [here](https://pub.dev/packages/test):

> *By default, tests are run in the Dart VM, but you can run them in the browser as well by passing pub run test -p chrome path/to/test.dart. test will take care of starting the browser and loading the tests, and all the results will be reported on the command line just like for VM tests. In fact, you can even run tests on both platforms with a single command: pub run test -p "chrome,vm" path/to/test.dart.*

**Comment by jakemac53** [comment]
The docs for this package only apply to Dart applications - Flutter applications are different even though they use the Dart language and can use any dart package, the reverse is not true.

You need a flutter specific platform to run flutter tests and that lives in the flutter SDK itself and not in this package because this package can't have a flutter dependency (or else it wouldn't be usable from normal dart apps).

**Comment by jakemac53** [comment]
It would make sense for us to add some specific disclaimer to this effect though to the docs

**Comment by PavelPZ** [comment]
@jakemac53, thanks a lot for explanation. I will try to solve this problem in flutter repo.
