### ISSUE TITLE
Test Timeout Running Unit Tests on DDC on Linux

### ISSUE THREAD

**Issue by todbachman-wf** [dart-lang/test#1113]
I've run into this test timeout issue on DDC again: dart-lang/test#1043 . I'm using the `1.9.4` release of the test package, so I should have the fix that that was put in place to addressed that issue. Once again, the issue is only happening in CI (where we run on Linux VMs) and not on a local Macbook pro. I've debugged this on a Linux VM and found that when the timeout occurs there is a requirejs error in the chrome dev console:

```bash
Uncaught Error: Load timeout for modules: language_test.dart.browser_test.dart.bootstrap
http://requirejs.org/docs/errors.html#timeout
    at makeError (:41593/RtPbIlR80P1hudA2GrzJ2EH6l95nHTOA/test/packages/build_web_compilers/src/dev_compiler/require.js:168)
    at checkLoaded (:41593/RtPbIlR80P1hudA2GrzJ2EH6l95nHTOA/test/packages/build_web_compilers/src/dev_compiler/require.js:698)
    at :41593/RtPbIlR80P1hudA2GrzJ2EH6l95nHTOA/test/packages/build_web_compilers/src/dev_compiler/require.js:719
```

I've tried setting the requirejs `waitSeconds` setting to `0`. When I do that the suite loads consistently, but then I see a unit test timeout after ~30 seconds.

I have found a workaround, which is to set concurrency to `1`, which surprised me a bit. I don't have good repro steps at this time, as we've only encountered this on one of our many, many internal Dart projects.

**Dart version: 2.6.1
Chrome: 78**

**Comment by kevmoo** [comment]
Still an issue? How are you running tests w/ DDC? (build_test, I'm guessing)

**Comment by todbachman-wf** [comment]
I just ran our unit tests in CI 30 times without the concurrency workaround applied and the tests passed every time. So it appears this is no longer an issue for us. Just fyi, we're running tests using build_test.

**Comment by grouma** [comment]
Thanks for the update. I'm going to close this one out.
