### ISSUE TITLE
[test_core] (flutter drive) Ability to change ExpandedReporter to custom reporter

### ISSUE THREAD

**Issue by defint** [dart-lang/test#1117]
Hi!

https://github.com/dart-lang/test/blob/master/pkgs/test_core/lib/test_core.dart#L63

Here we have ExpandedReporter, but for CI/CD we need to have custom reporter (or JSON reporter), because `flutter drive` uses this declarer for own purposes.

Can you add possibility to inject custom reporter on this place? Or maybe you have another solution for `flutter drive`.

**Comment by grouma** [comment]
You can register a custom reporter:
https://github.com/dart-lang/test/blob/17850e02e6359ce9fc9349aa769521a2e84b22c8/pkgs/test_core/lib/src/runner/configuration/reporters.dart#L53

I think that's what you are looking for?

**Comment by defint** [comment]
But how `flutter drive` can use this registered reporter? As I see it is only for `flutter test` runner.

**Comment by grouma** [comment]
I'm not familiar with `flutter drive`. It's probably best to open up an issue under the flutter repository: https://github.com/flutter/flutter

Note this package is intended for general VM / Browser testing purposes and is used by the Flutter package.
