### ISSUE TITLE
Add option to randomize test execution order

### ISSUE THREAD

**Issue by dnfield** [dart-lang/test#1124]
I want to be able to shuffle or randomize the order of the tests that I run. I want to do this because sometimes, I accidentally write a test that modifies some global state.  I then write another test that looks right to me, but actually is getting messed up by the global state.  I know I should avoid modifying global state in tests, but sometimes it's really hard to understand that I'm doing so (or, even harder, I just miss that someone else has modified it somewhere else in the file I'm adding a test to).  If I could shuffle my tests, I'd be hardened a bit more against that.  Ideally, in this scenario, the shuffling would be repeatable so that if I find a shuffle order that fails, I could consistently re-run tests in that order.

I believe this is as simple as adding some way to shuffle this list: https://github.com/dart-lang/test/blob/master/pkgs/test_api/lib/src/backend/declarer.dart#L264-L273

/cc @goderbauer @jonahwilliams @tvolkert @hixie who probably have more thoughts on this.

**Comment by jakemac53** [comment]
I believe this was already recently added, let me see if I can dig up the docs...

**Comment by jakemac53** [comment]
Ah ya, try `--test-randomize-ordering-seed=random`

**Comment by jakemac53** [comment]
This does appear in the command line help output but isn't otherwise documented as far as I can tell, we should probably add something to the README.md.

**Comment by jakemac53** [comment]
Note that you can provide an explicit seed (a 32 bit int) to get a reproducible order as well - I don't know that it will tell you the seed that was used on failure though.

**Comment by dnfield** [comment]
That is _exactly_ what I wanted, thanks!

**Comment by jakemac53** [comment]
If you do end up needing to know the seed and its not surfaced feel free to file and issue and we can likely do something :D

**Comment by dnfield** [comment]
It looks like it's printed out here: https://github.com/dart-lang/test/blob/c0f4f232d4fecf5a051d3ae50e9cb141399464a6/pkgs/test_core/lib/src/runner/configuration/args.dart#L219

**Comment by jakemac53** [comment]
nice! I suppose I shouldn't be surprised as this was designed to integrate with some internal tools that already worked for other languages and have been pretty fully fleshed out :)
