### ISSUE TITLE
test output to dartium (or chrome)

### ISSUE THREAD

**Issue by Bluenuance** [dart-lang/test#113]
I really loved the old output (with links - to run a specific test again) inside the Dartium browser (or chrome if compiled to js)
Is it possible to somehow achieve the same with the new test package?

versions:
Dart VM version: 1.10.0-dev.1.10 (Thu Apr 23 01:02:11 2015) on "windows_x64"

test:
  description: test
  source: hosted
  version: "0.12.0"

**Comment by zoechi** [comment]
I think this would be a use case of #23

**Comment by nex3** [comment]
Closing as a duplicate.
