### ISSUE TITLE
Error loading transformer

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#114]
I created a new project directory with this `pubspec.yaml`
```yaml
name: test_iconset_svg
dependencies:
  bwu_fontawesome_iconset_svg: '>=0.1.3 <0.2.0'
```
then I run `pub upgrade` and got
```
Resolving dependencies... (6.6s) 
+ analyzer 0.25.0+1
+ args 0.13.0
  ...
+ string_scanner 0.1.3+1
+ template_binding 0.14.0+2
+ test 0.12.1
+ utf 0.9.0+2
+ watcher 0.9.5
+ web_components 0.11.4+1
+ when 0.2.0
+ which 0.1.3
+ yaml 2.1.2
Changed 43 dependencies!
Precompiling dependencies... 
Loading source assets... 
Error on line 1, column 1 of https://pub.dartlang.org/api/packages/bwu_fontawesome_iconset_svg: Error loading transformer "test/pub_serve": package "test" is not a dependency.
```
The `pubspec.yaml` of the dependency is https://github.com/bwu-dart/bwu_fontawesome_iconset_svg/blob/v0.1.3/pubspec.yaml

Is this caused by http://dartbug.com/22629 ?
Do I have to move the test package to normal dependencies in bwu_fontawesome_iconset_svg?

**Comment by nex3** [comment]
Can you re-file this against pub? It should see `$include: test/**_test{.*,}.dart` and know that the transformer doesn't need to be loaded when used as a dependency.

**Comment by zoechi** [comment]
http://dartbug.com/23480
