### ISSUE TITLE
Support for Edge

### ISSUE THREAD

**Issue by nturgut** [dart-lang/test#1142]
We are adding Edge support to our test harness in Flutter for Web: [PR](https://github.com/flutter/engine/pull/15641)

Is it possible to add Edge as a supported [Runtime](https://github.com/dart-lang/test/blob/master/pkgs/test_api/lib/src/backend/runtime.dart)?

I added Edge Browser to Flutter for Web test runner, we can also add it to dart test [browsers](https://github.com/dart-lang/test/tree/master/pkgs/test/lib/src/runner/browser).

**Comment by grouma** [comment]
Happy to accept PRs here!
