### ISSUE TITLE
Remove support for phantom_js

### ISSUE THREAD

**Issue by natebosch** [dart-lang/test#1145]
I think the main value has since been superseded by chrome headless. Unless this is buying a lot of value we should simplify and drop the platform. One thing that is tricky is we don't know for sure how much it is getting used.

Proposal:

- Deprecate the platform. Make the test runner fail when you use it unless you pass `--force-keep-phantom-js`.
- Point to this issue from the failure message.
- Wait for a while and see how many complaints we get. Evaluate whether we can remove support entirely.

**Comment by jakemac53** [comment]
+1, I don't understand what this provides that chrome headless doesn't.

note also that development phantom JS as a whole has been suspended as of 2018-03-03.

**Comment by natebosch** [comment]
@grouma will add a warning about the future deprecation. We will remove it entirely in `2.0.0` which should come with our null safety migration. In the mean time we will also just skip the tests on travis since they are failing there but passing locally and it isn't worth the effort to figure out why.

**Comment by natebosch** [comment]
Closed by 12b2d8e9
