### ISSUE TITLE
unit tests ignore -j1 flag

### ISSUE THREAD

**Issue by bsutton** [dart-lang/test#1157]
I'm the author of the dshell package and I'm trying to write unit tests that modify the file system.

https://pub.dev/packages/dshell/versions

dshell is a library and tooling for writing command line scripts.

As such, I have a significant no. of unit tests that modify the file system.
These tests include the need to install a copy of dshell (dshell has a post activation install that needs to be run) before the tests can be run.

Because I modify the file system in many of the unit tests, I need to ensure that either the unit tests run in an isolated area of the filesystem or they run serially with each unit test library establishing its own copy of the dshell.

To achieve this I've been trying to use the -j1 command which as I understand it is meant to run each unit test one at a time.

The first problem is that there is no documentation on -j1. The only way I know about it is that I ran across an issue describing it (which I can't find now).

I've also had a look at shards but again the documentation is rather lacking and provides no explanation as to exactly what a shard is (is it a process, an isolate or some other unit test magic).

When running with -j1 it I'm seeing four isolates launched in the debugger and it appears that two of these are running unit tests simultaneously.
This is not my understanding of what is meant to occur when running with -j1.

you can see from the process list what is being started:
```
4851  /bin/sh -c "/usr/lib/dart/bin/dart" "/usr/lib/dart/bin/snapshots/analysis_server.dart.snapshot" "--client-id=Dart-Code.dart-code" "--client-version=3.7.1"
4852  /usr/lib/dart/bin/dart /usr/lib/dart/bin/snapshots/analysis_server.dart.snapshot --client-id=Dart-Code.dart-code --client-version=3.7.1
11892  /bin/sh -c "/usr/lib/dart/bin/dart" "--enable-vm-service=0" "--pause_isolates_on_start=true" "/usr/lib/dart/bin/snapshots/pub.dart.snapshot" "run" "test" "-r" "json" "-j1" "test" "-j1"
11893  /usr/lib/dart/bin/dart --enable-vm-service=0 --pause_isolates_on_start=true /usr/lib/dart/bin/snapshots/pub.dart.snapshot run test -r json -j1 test -j1

```

My vs-code launch config is:
```
{
            "name": "All Test",
            "type": "dart",
            "program": "test/",
            "request": "launch",
            "args": [
                "-j1"
            ]
        },
```

So the question is how do I get unit tests to run one test at a time.

Note: I've tried separating the filesystem by using an ioZone with a memory based file system but due to a bug in dart this solution doesn't work.

**Comment by jakemac53** [comment]
This sounds like it is likely related to the vscode launch config and not the test runner. I don't know what that launch config means, my guess it is running several instances of the test runner or something.

If you run the test runner directly `pub run test -j1` that should work.

It also sounds like the [test_descriptor](https://github.com/dart-lang/test_descriptor) package would be useful for you in terms of managing separate temp directories for each test.

If that solves the issue please close, thanks!

**Comment by bsutton** [comment]
Given that I'm seeing two isolates with the same PID I don't see how it could be a vs-code issue.

**Comment by bsutton** [comment]
I've just run the test from the cli with the -j1 does seem to behaviour correctly as for the first time ever all my unit tests passed in a single run.

**Comment by bsutton** [comment]
The test_descriptor package looks interesting but won't help me as the code I'm testing is manipulating the file system as opposed to the unit tests creating directory structures.

Alas I've tried many methods and been blocked every time.
The -j1 option gets me most of the way.

My final problem is being able to order the tests.
Is there some way to control the test order across test files?

**Comment by jakemac53** [comment]
> The test_descriptor package looks interesting but won't help me as the code I'm testing is manipulating the file system as opposed to the unit tests creating directory structures.

If you are invoking a library method which writes to the current working directory, you can I believe set `Directory.current` inside of `setUp` and restore it in `tearDown`. You would set it to the [sandbox](https://pub.dev/documentation/test_descriptor/latest/test_descriptor/sandbox.html) dir. 

If you are running a new process you can set the working directory for that process when you spawn it.

> The -j1 option gets me most of the way.

This would also be required if you are going to set `Directory.current` I think.

> My final problem is being able to order the tests.
> Is there some way to control the test order across test files?

We don't expose anything or have any guarantees around test ordering. In general it is considered an anti-pattern to have tests that have to be ran in a certain order. You should for instance be able to skip any test in a suite and not have that cause other tests to fail.

If ordering is required, one option is to make a single test for the entire portion that is order dependent. You can move a lot of code to `setUp` and `tearDown` or create helper methods if you want to reuse code between multiple tests. Note that `expect` can be used within `setUp` and `tearDown` as well as tests.

That being said today I think it is the case that tests within a single suite(~file) run in sequential order. There is a flag to explicitly run in a random order but you have to enable it.

**Comment by jakemac53** [comment]
Closing this issue but feel free to continue to respond on it

**Comment by jakemac53** [comment]
See also the [DartCode](https://gitter.im/dart-code/Dart-Code) gitter for help with vscode configs

**Comment by bsutton** [comment]
thanks for the link.
