### ISSUE TITLE
unit test throws an exception on completion.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/test#1158]
I have a suite of 75 unit tests that manipulate the file system, spawn processes and read/write directly to stdout/stderr.

All my unit tests pass but at the end of the test run I get an error:

```
                                                                         
Unhandled exception:
FileSystemException: Couldn't determine file type of stdin (fd 0), path = ''
#0      _StdIOUtils._getStdioInputStream (dart:io-patch/stdio_patch.dart:21:9)
#1      stdin (dart:io/stdio.dart:408:26)
#2      stdinLines (package:test_core/src/util/io.dart:60:50)
#3      stdinLines (package:test_core/src/util/io.dart:60:7)
#4      completeShutdown (package:test_core/src/executable.dart:51:3)
#5      main (package:test_core/src/executable.dart:37:3)
<asynchronous suspension>
#6      main (package:test/src/executable.dart:22:9)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
Unhandled exception:
The command [pub run test -j1] failed with exitCode: 255
```

**Comment by jakemac53** [comment]
I haven't seen this before - maybe you are spawning a process with inheritStdio and that causes some problems?

If you can give us a repro case that would help as well

**Comment by alestiago** [comment]
Hi @jakemac53 and @bsutton (and new readers) , I have also experienced this issue. Precisely when running a fresh Ubuntu machine and with a codebase that uses `stdin` from (dart:io). I'm struggling to make a minimal sample that reproduces this exception. 

The exception is being thrown from [here](https://github.com/dart-lang/sdk/blob/b8fb4a537c315ae6abe6b8dd5932b1b9adecfbad/sdk/lib/io/stdio.dart#L429).

Doing something as simple as the following, does not throw the error.
```dart
void main() {
  test('stdio', () {
    final input = io.stdin;
    io.stdioType(input);
    expect(input, isNotNull);
  });
}
```

I have not seen this issue on MacOs. 

@jakemac53 , if you're interested I have a non-minimal sample that shows the issue. Let me know if you're interested.
