### ISSUE TITLE
Targetted tests

### ISSUE THREAD

**Issue by dnfield** [dart-lang/test#1170]
I suspect this might be out of scope for this repo, but it's a feature that I'd really like and I figured I'd ask.

Larger projects (like Flutter) end up having lots of tests. We shard those tests to try to run them in a reasonable amount of time, but sharding gets harder and harder over time for a few reasons - we only have so many machines we can reasonably shard over, the sharding arguments for package test don't quite work with`flutter test`, and the shards have no clue about how long existing tests take to run (so, for example, we have 2 really slow integration tests and 10 really fast unit tests - using tags to split those up gets hard as the numbers grow).

It would be really nice if there was some way to discover what tests are impacted based a list of classes/packages/methods touched, feeding it through something like the analyzer or language server, and getting a list of tests that should be run based on those changes.

**Comment by dnfield** [comment]
The idea being that on presubmits, we could run potentially a very small subset of tests that the change impacted, but on post submits we run everything.

**Comment by dnfield** [comment]
Another way of getting at this:

- Find all the tests that directly or indirectly import a file changed by this commit
- From that, find all the tests that actually touch the line(s) changed.

Could be a fun way to find out if changes have tests or not :D

**Comment by grouma** [comment]
@jakemac53 @natebosch 

We've discussed this issue a handful of times. The idea is that we would use `package:build_test` to support this behavior as the build package has a strong understanding of what is impacted by a given change. I'm not sure what currently works but @jakemac53 should be able to elaborate.

**Comment by jakemac53** [comment]
This issue comes up fairly often and is a totally reasonable request. It is also my opinion that we can't really accept a solution that is any less 100% correct. This package should value correctness over all else given that the whole point is to validate the correctness of _other_ programs.

That makes things pretty difficult. There are a lot of edge cases such as data files that are read during a test. If you change a golden file you need to rerun tests for instance.

The good news is this package already exposes all the api you would need to build something on top of it, and I think that is ultimately the best option. That is for instance exactly what we do in bazel.

Hermetic build systems in general are a good fit for this (hermetic here is important, ninja would be a terrible fit). Build systems already have all the primitives in place - you can just model your tests as a build step (typically they would just output some file that indicates success/failure) and then do an incremental "build" of all your tests.

**Comment by dnfield** [comment]
Can you provide some pointers to the API that would make this work?

**Comment by natebosch** [comment]
To clarify, this isn't something which can be solved cheaply. See our internal bazel integration for an example of what we mean by the api to make this work. The test package makes it possible to integrate the test runner with a build system. A hermetic build system, or at least one able to reliably track change impacts, is required.

Change impact detection is most likely out of scope for the test runner. In trivial cases we can probably make some ground. In complex cases like the flutter SDK, or any case with integration tests, things are riskier.

**Comment by jakemac53** [comment]
For the most part you could do a build system integration that only uses the command line interface. You would tell it to typically run a single suite (*_test.dart file) explicitly for each build action.

The effectiveness of this would largely be based on how fine grained your deps are in your build rules, which typically takes a fair bit of maintenance.

> Change impact detection is most likely out of scope for the test runner.

Agreed, it just doesn't know enough about the rest of the system to be able to effectively or accurately do this. Tests can do pretty much anything and depend on all kinds of state that it can't track.

From the outside though you can build solutions that are more targeted at specific use cases, and can be relatively more sane.

**Comment by dnfield** [comment]
Hmm.  Maybe we'd get more out of just teaching flutter test to build out package:build_test files that we could cache until we rev dart.  Presumably, doing incremental builds on those should be faster than what we have now, and the test execution should be faster with the pre-builts.

I don't think that's trivial for us to do, but it's probably more sustainable than trying to get the whole Flutter repo to conform to a new build system.

Is it possible to do this given dart:ui?

**Comment by jakemac53** [comment]
> Hmm. Maybe we'd get more out of just teaching flutter test to build out package:build_test files that we could cache until we rev dart. Presumably, doing incremental builds on those should be faster than what we have now, and the test execution should be faster with the pre-builts.

`build_test` won't help today - its just the package we would likely put this "test as a build step" functionality in to if we had time to invest in it.

The overall idea there was it would be a build step whose inputs are the generated kernel files for the test + explicitly defined data files. It would then run each test in a sandboxed directory where it can't access any data files it didn't specify, and it would fail the build if a test fails.

> I don't think that's trivial for us to do, but it's probably more sustainable than trying to get the whole Flutter repo to conform to a new build system.

I agree that getting the whole flutter repo to use a new build system isn't really a viable option. Unfortunately the existing build system isn't well suited to this need either.

However individual parts of the repo (packages within it) may be able to opt into something.

> Is it possible to do this given dart:ui?

That complicates things - one idea would be to essentially rely on tree shaking. If the tests are compiled with tree shaking enabled at the kernel level (not sure how hard this is or what the state of it is), then in theory any api that wasn't used wouldn't affect the kernel output of the test.

At that point for unit tests that don't have any deps other than dart code could be re-ran only when the contents of those kernel outputs changed.

**Comment by jakemac53** [comment]
cc @alexmarkov who I hear knows more about the state of tree shaking in aot/kernel :)

**Comment by dnfield** [comment]
Alex knows more than I do, but to get the full benefits of tree shaking you really need a VM optimization pass.  Kernel only does some of the work - it does a good job around constant evaluation, but much less work about optimizations the VM knows how to do (which is a lot of what I think of as tree shaking).

Regardless of the build system the Flutter tree uses (we could certainly switch it if there's a compelling reason to do so!), is there anything in the build or test packages today that would let me do something like the following:

- Given a previous compilation result and a new set of sources, build a new blob that represents only the incremental difference and its direct dependencies
- Run that blob

As far as tests accessing external data files, we really try to avoid that.  We do it for goldens testing, but we should be covered in that case because something that could change a golden should have changed the test that checked the golden - and for engine rolls, we would want to just always run the full test suite (since Skia could change without a Dart change).

**Comment by jakemac53** [comment]
I would start by looking at the [flutter test platform](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/flutter_platform.dart).

This handles compiling and running the tests. I think you should have a mechanism within that to mark a `RunnerSuite` as skipped. I am not completely sure that is actually possible to do today, but conceptually that is what you would want to do.

> As far as tests accessing external data files, we really try to avoid that. We do it for goldens testing, but we should be covered in that case because something that could change a golden should have changed the test that checked the golden - and for engine rolls, we would want to just always run the full test suite (since Skia could change without a Dart change).

Integration tests are another thing to consider here. Really I think this strategy is only applicable for basic unit tests. It starts getting very dubious for anything else if you don't have a way of sandboxing the tests.

**Comment by jakemac53** [comment]
For standard vm tests we don't actually create kernel files at all we run them in isolates so there is no previous compilation result to compare against.

Unless you run tests with `pub run build_runner test` in which case they are precompiled. In that scenario you would have to do your own storing/diffing of results it does not expose previous build artifacts explicitly.

**Comment by dnfield** [comment]
Yes, we would have to run integration tests using a different strategy.

**Comment by alexmarkov** [comment]
> That complicates things - one idea would be to essentially rely on tree shaking. If the tests are compiled with tree shaking enabled at the kernel level (not sure how hard this is or what the state of it is), then in theory any api that wasn't used wouldn't affect the kernel output of the test.

Tree shaking is a quite time-consuming process - it would slow down compilation of tests considerably. Also, it may not be enough to check if there are changes in a tree-shaken code: if tree shaking removed certain code, and then that code was changed to introduce a new entry point (e.g. there is a new call from C++ engine code into Dart land), then it would invalidate results of tree shaking and we need to re-run tests. So I don't think we can use tree shaking to approximate dependencies of tests.

Our kernel compilers are able to provide list of dependencies (e.g. list of transitively imported sources) for the resulting dill file. This list is usually fed to build systems to make sure dill files are recompiled when sources are changed. We can use that as a rough approximation to decide if we need to recompile a test.

Maybe we can also use code coverage to figure out dependencies of a test more accurately.

**Comment by jakemac53** [comment]
> Tree shaking is a quite time-consuming process - it would slow down compilation of tests considerably.

Definitely true, and given that this is only really applicable to unit tests and not slower tests (integration tests) that could easily make the situation worse not better :).

@dnfield that makes me wonder actually how much value could be gained out of this at all? Do we have any rough approximation of how much time is spent total running unit tests versus integration/golden tests?

**Comment by dnfield** [comment]
Integration tests take longer for sure.

I would want to group golden tests in with unit tests here though.  And I'm not really concerned with tree shaking so much as knowing whether a change in the source code should run a test or not.  IOW, for a given source code change, I want to know all of the tests that are impacted by that change, and run them.  It would also be nice to assert there's at lesat one test impacted.

So I suppose something like finding all of the dependencies of the tests, and then running only the ones that have dependencies  on something that has changed.  But I'm starting to think that will be not much faster than just running all the tests...

**Comment by jakemac53** [comment]
> I would want to group golden tests in with unit tests here though.

That is likely where the biggest win would come from, and they are sort of a restricted type of integration test. This might be worth while.

> But I'm starting to think that will be not much faster than just running all the tests...

Right, that is what I am wondering now as well. Unit tests are usually quite fast - we already likely spend more time compiling them than running them in a lot of cases.

I bet the largest impact would actually be avoiding the compile step entirely - which changes the invalidation strategy.

**Comment by dnfield** [comment]
Yes - if we could somehow _only_ compiile the targets we need, that would be better.

**Comment by jakemac53** [comment]
What proportion of flutter repo tests are vm platform tests versus flutter platform tests do you know? I am also curious how the golden tests work and if this approach would actually apply or not - do the tests themselves import the flutter framework or are they vm tests which launch a flutter app?

**Comment by dnfield** [comment]
The breakdown is:

Flutter Platform tests (and some VM tests):

- packages/flutter
- dev/, examples/
- packages/flutter_goldens (tests for the golden client, not all goldens tests)
- packages/flutter_localizations
- packages/flutter_driver
- packages/flutter_test
- packages/flutter_web_plugins

The main source for VM tests is:

- packages/flutter_tools and
- packages/fuchsia_remote_debug_protocol

But the others have some VM tests sprinkled in.

**Comment by dnfield** [comment]
Some of the tests in packages/flutter_tools are integration tests that spawn Flutter.

**Comment by jakemac53** [comment]
I am going to close this as not planned.

I think this should really be handled at a build system level - or by some other package which wraps this package.

Solutions are likely to be quite different for the different use cases, as well as the tolerance level for how accurate the results need to be etc.
