### ISSUE TITLE
Coverage is useless?

### ISSUE THREAD

**Issue by cedx** [dart-lang/test#1179]
When I generate the code coverage using the `--coverage` option, I expect that the coverage include the files in the `lib` directory. Instead, I only get code coverage for the files in the `test` directory.

The interest of the tests is to know if I correctly cover the files of the "lib" folder.
Is there something I am doing wrong or I have forgotten?

A sample coverage report when using the `--coverage` option:
https://coveralls.io/builds/28691972

A sample report when I use the `coverage` package directly:
https://coveralls.io/builds/28653626

**Comment by grouma** [comment]
Can you give a sample `.json` output for your coverage run?

Are you passing the `--packages` argument to the `format_coverage` command? If not, it's likely any `package:` URI will not be resolved and therefore not show up in your coverage report.

**Comment by cedx** [comment]
Of course: I forgot the `--packages` argument! Thanks @grouma: now the coverage works as expected.

**Comment by xuning0** [comment]
@cedx Did you write like `--packages=.packages` ? I try to write like this but it generates a lcov.info file containing all referenced packages.

**Comment by cedx** [comment]
@xuning0  With the latest Dart SDK releases, you must use `--packages=.dart_tool/package_config.json` and you must filter the files covered by using the `--report-on` parameter. For example:

```shell
pub run test --coverage=output_dir
pub run coverage:format_coverage --in=output_dir/test --lcov --out=output_dir/lcov.info --packages=.dart_tool/package_config.json --report-on=lib
```

**Comment by xuning0** [comment]
@cedx Thanks! The point is that I did not add `--report-on=lib`. By the way, the `SF` in lcov.info is an absolute path, can i get a relative path starting with `lib/`?

**Comment by cedx** [comment]
I don't think so but you could use the [`lcov` package](https://pub.dev/packages/lcov) to parse the LCOV file and re-format it to your needs (alonside the [`path` package](https://pub.dev/packages/path) to convert the absolute paths to relative ones).
