### ISSUE TITLE
StreamMatchers should cancel any StreamQueue that they create once done matching

### ISSUE THREAD

**Issue by simolus3** [dart-lang/test#1183]
The following test will print "tearDown - start" but then time out. The test hangs in the `tearDown` method at `await controller.close()`.
```dart
import 'dart:async';
import 'package:test/test.dart';

void main() {
  StreamController<String> controller;

  setUp(() {
    controller = StreamController.broadcast();
  });

  tearDown(() async {
    print('tearDown - start');
    await controller.close(); // this future never completes
    print('tearDown - done');
  });

  test('this test times out', () async {
    final stream = controller.stream;

    final expectation = expectLater(stream, emitsInOrder([isNull, isNotNull, isNull]));

    controller..add(null)..add('foo')..add(null);
    await expectation;
    print('matched expected items, test body done');
  });
}

```

Is this expected? If so, is there anything users can do to prevent it?

**Comment by jakemac53** [comment]
It looks like this is a result of the StreamQueue used by the matcher, this also hangs:

```
test('can close a stream wrapped in a queue', () async {
  var controller = StreamController<String>();
  var queue = StreamQueue(controller.stream);
  var done = queue.next;
  controller..add('foo');
  print(await done);
  await controller.close(); // hangs here
  print('done');
});
```

**Comment by jakemac53** [comment]
This is likely because the `StreamQueue` never consumes the `done` event. I don't know what the solution is here other than just not awaiting the `close` call.

**Comment by jakemac53** [comment]
See also https://github.com/dart-lang/sdk/issues/19095#issuecomment-471722971

After talking with @natebosch we decided the fix would be to cancel the implicit stream queue that is created (only if we create it). This might be breaking for some scenarios so we would have to do some investigation into that or land it with the NNBD changes.

**Comment by jakemac53** [comment]
The recommendation in general is to not await the `close` method - as that can always arbitrarily block if you have a subscriber that is paused.

**Comment by jakemac53** [comment]
Note that I have made the change to cancel any stream queues we create in the matchers and ran that through an internal presubmit without finding any failures. So it should be safe to make that change and land it as non-breaking.

This should make it a lot less likely to run into this type of failure.
