### ISSUE TITLE
Extra newlines with print inside tests

### ISSUE THREAD

**Issue by tobindh** [dart-lang/test#1190]
Any printed messages are adding an extra line inside the test.  I would expect the print method to stay consistent inside of the tests.

For example, the following program:

````dart
import 'package:test/test.dart';

main(){
  
  run();

  test("Test Print",
    () => run()
  );
}

void run() async {
  print("Start Print");
  print("ABC");
  print("1234");
  print("456");
}
````

Results in this output:
![image](https://user-images.githubusercontent.com/43450893/75372903-db88d700-588e-11ea-82c6-da32a136ffba.png)

**Comment by jddeep** [comment]
cc: @jakemac53

**Comment by natebosch** [comment]
This does not repro for me. How are you invoking the test runner?

**Comment by natebosch** [comment]
Closing for now. We can revisit with a reproduction case.
