### ISSUE TITLE
Timeout doesn't work for package:webdev test

### ISSUE THREAD

**Issue by grouma** [dart-lang/test#1203]
Remove the `registerExtension` call here:
https://github.com/dart-lang/webdev/blob/6dec3735b18ec19d1d3221a003167d98584538f5/example/web/main.dart#L13

Next run this test:
https://github.com/dart-lang/webdev/blob/6dec3735b18ec19d1d3221a003167d98584538f5/webdev/test/daemon/app_domain_test.dart#L61

This `expectLater` will now fail:
https://github.com/dart-lang/webdev/blob/6dec3735b18ec19d1d3221a003167d98584538f5/webdev/test/daemon/app_domain_test.dart#L69

However, the test never times out. The test runner hasn't completely stalled as it continually reports the elapsed time.

**Comment by natebosch** [comment]
Broken by https://github.com/dart-lang/test_process/pull/17

**Comment by natebosch** [comment]
This is approximately working as intended. Closing this in favor of the feature request to add a configuration for the timeout that would do what you hoped for here.

https://github.com/dart-lang/test/issues/1205
