### ISSUE TITLE
How to actually set SILENT_OBSERVATORY?

### ISSUE THREAD

**Issue by Anrock** [dart-lang/test#1206]
So, there is a warning about observatory output messing up various reporters (jUnit json in my case) which tells to define `DART_VM_OPTIONS=-DSILENT_OBSERVATORY` to workaround this.

`Runner` from `test_core` reads it as `bool.fromEnvironment` that doesn't read process environment but actually reads `dart -D...` options. 

There is no way (at least that I'm aware of) to pass options to VM when executing `pub run test`.

So how do I pass this option actually? Do I have to write my own version of `test_core` to have control over actual `dart` process invocation to pass this option or there is another way?

P.S. Running `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true pub run test -r json --coverage coverage` seems to supress observatory output but the warning message is still printed so reporter still breaks, ironically.

**Comment by grouma** [comment]
Hmm this seems less than ideal.

You can run the test executable directly to set the VM option:
https://github.com/dart-lang/test/blob/master/pkgs/test/lib/src/executable.dart

So basically `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true dart path/to/executable.dart`

@natebosch is there a better way?

**Comment by natebosch** [comment]
> So basically `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true dart path/to/executable.dart`

This isn't correct. What you would want is

`dart -DSILENT_OBSERVATORY=true path/to/executable.dart`


I do expect that the correct way to suppress this is `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true pub run test -r json --coverage coverage` and I'm surprised that doesn't work.

**Comment by natebosch** [comment]
Oh, I bet I know what's happening here, we precompile the test runner and I suspect that the `-D` variables don't work that way...

cc @jakemac53

**Comment by suztomo** [comment]
I use Flutter in IntelliJ, in which also observe the warning message. However I’m not sure what to do in IntelliJ.

Does this issue solve my problem eventually or should I follow another repository?

![image](https://user-images.githubusercontent.com/28604/83957105-dbf02100-a832-11ea-9583-43d6c8473d46.jpeg)

**Comment by jakemac53** [comment]
cc @sigurdm did you end up enabling general vm args for pub run or just specifically enable-experiment?

**Comment by sigurdm** [comment]
For now we did just `enable-experiment`. I started implementing that all unrecognized arguments would get passed to the VM as you suggested, but it got quite unwieldy, and @jonasfj and I decided to kick it a bit down the road.

**Comment by natebosch** [comment]
Would it be possible to avoid using the precompiled script when there is a `DART_VM_OPTIONS` argument for the outer `pub run`?

**Comment by jonasfj** [comment]
> Would it be possible to avoid using the precompiled script when there is a `DART_VM_OPTIONS` argument for the outer pub run?

Seems reasonable, but is this a good solution for the problem. The `DART_VM_OPTIONS` affects how we run `pub`, I think it's better to pass arguments through `pub run` to the VM instead.

**Comment by sigurdm** [comment]
Possible? - yes.

The whole situation seems a bit messy using a single environment variable for vm options when pub (or the new dartDev) is involved. Should DART_VM_OPTIONS also affect these runner programs? If it runs the `package:test` runner - should that be affected or only the test that runs in the end?
Ideally we should be able to toggle VM options on all of these individually.

I think we should move forward on `pub run` being able to pass arbitrary vm args to the VM.
I just am still not sure if we want these to be top-level arguments to `pub run`. It seems elegant, but there is a number of corner-cases that makes it somewhat tricky.

**Comment by jakemac53** [comment]
> It seems elegant, but there is a number of corner-cases that makes it somewhat tricky.

What makes `pub run` different/harder than the `dart` vm (or dartdev tool) in this respect?

**Comment by jonasfj** [comment]
> It seems elegant, but there is a number of corner-cases that makes it somewhat tricky.

@sigurdm, isn't this mostly to do with `dartdev run` when triggering the default command? Which strictly speaking doesn't affect `pub run` (maybe I'm forgetting something).

**Comment by sigurdm** [comment]
pub takes its own arguments (`--verbose`, `--trace`) these have to be filtered out. To this list we might want to add `--no-precompile` that doesn't exist yet, but makes sense in a `pub run` context.

Then there is the help-text that either should replicate the vm's help text or just point at `dart --help`

Some vm-options make less sense with pub run (`--snapshot`, `--help` comes to mind).

Maybe it's not all that bad - there are just a number of things to consider before passing all args along to the vm.

**Comment by subzero911** [comment]
I ran into this too.
I tried to setup a system environment variable but it didn't help
![image](https://user-images.githubusercontent.com/12999702/85420134-7ebad600-b57b-11ea-84d3-b75efa522ef6.png)

I also tried to run in terminal the following line but nothing happens
![image](https://user-images.githubusercontent.com/12999702/85420255-a1e58580-b57b-11ea-92d1-ddd85dc01ab9.png)

**Comment by franferri** [comment]
I just got the last flutter/dart plugins updated in android studio and I see the same, and there is no human way of setting this setting anywhere. Environmental variables, user variables, etc... Running the commands by console or android studio complain in the same way: https://twitter.com/franciscoferri/status/1277246156368678913?s=20

Can anybody explain how to setup this variable in android studio? or flutter configuration file? or dart... or ...

Any help will be much appreciated

**Comment by matpag** [comment]
This is still a problem.
This is what I get when running Flutter unit test from Android Studio:
```
/Users/$USER/Library/Flutter/bin/flutter --no-color test --machine --start-paused --plain-name "example" test/example_test.dart
Warning: You should set `SILENT_OBSERVATORY` to true when debugging the VM as it will output the observatory URL by default.
This breaks the various reporter contracts.
To set the value define `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true`.
```

**Comment by SebastianJL** [comment]
I get the same error on `Android Studio`:
```bash
...
/home/$USER/opt/flutter/bin/flutter --no-color test --machine --start-paused --plain-name StudyPlanCubit test/bloc_test.dart
Warning: You should set `SILENT_OBSERVATORY` to true when debugging the VM as it will output the observatory URL by default.
This breaks the various reporter contracts.
To set the value define `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true`.
```

**Comment by helin24** [comment]
@matpag @SebastianJL are you having problems executing your unit tests? If you are on v48.1.2, then tests in all scopes should execute, but you will still see the warning message. If you're having a problem running tests, please file a separate issue describing what happens with your test and your flutter doctor output.

**Comment by grouma** [comment]
Note the underlying issue that this warning is highlighting is slated to be resolved in the September SDK milestone. See https://github.com/dart-lang/sdk/issues/31308

**Comment by SebastianJL** [comment]
> @matpag @SebastianJL are you having problems executing your unit tests? If you are on v48.1.2, then tests in all scopes should execute, but you will still see the warning message. If you're having a problem running tests, please file a separate issue describing what happens with your test and your flutter doctor output.

No my tests run fine.

> Note the underlying issue that this warning is highlighting is slated to be resolved in the September SDK milestone. See [dart-lang/sdk#31308](https://github.com/dart-lang/sdk/issues/31308)

Thanks for the info. I'll just ignore it then.
