### ISSUE TITLE
Short url for json_reporter.md is outdated

### ISSUE THREAD

**Issue by simolus3** [dart-lang/test#1223]
This line shows up when running `pub run test --help`:

https://github.com/dart-lang/test/blob/17850e02e6359ce9fc9349aa769521a2e84b22c8/pkgs/test_core/lib/src/runner/configuration/reporters.dart#L42

However, https://goo.gl/gBsV1a points to https://github.com/dart-lang/test/blob/master/doc/json_reporter.md which doesn't exist. I think it should point to https://github.com/dart-lang/test/blob/master/pkgs/test/doc/json_reporter.md instead.

**Comment by grouma** [comment]
I assume @nex3 owns the shortened URl. Is this something you can quickly fix? Otherwise we'll need to land a PR and migrate to a different URL shortening tool.

**Comment by nex3** [comment]
As far as I know those short links are mutable.
