### ISSUE TITLE
test_api/lib/src/frontend/future_matchers.dart documentation is contradictory

### ISSUE THREAD

**Issue by ravenblackx** [dart-lang/test#1224]
Twice in `future_matchers.dart` there's

```dart
/// Note that this creates an asynchronous expectation. The call to `expect()`
/// that includes this will return immediately and execution will continue.
/// Later, when the future completes, the actual expectation will run.
///
/// To test that a Future completes with an exception, you can use [throws] and
/// [throwsA].
///
/// This returns an [AsyncMatcher], so [expect] won't complete until the matched
/// future does.
```
The last paragraph contradicts the first paragraph. This probably should be corrected to have a reference to expectLater in one of the paragraphs.

**Comment by grouma** [comment]
I believe the first reference should be `expectLater`.

cc @natebosch

**Comment by natebosch** [comment]
I think it should be the second reference. Although, it looks to me like the last sentence is superfluous entirely.
