### ISSUE TITLE
reving `package:webkit_inspection_protocol`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/test#1235]
Hi, I see that `package:test` has a dep on `package:webkit_inspection_protocol` (https://github.com/dart-lang/test/blob/master/pkgs/test/pubspec.yaml#L33). I'm about to publish a new major version (`0.7.0`), and am wondering what the best way to coordinate that with `test` would be.

I think that the version will not be breaking from `package:test`s POV, but haven't confirmed.

There are a few clients that will have deps on both `package:test` and `package:webkit_inspection_protocol`, including flutter_tools (which from memory, has a dep on a specific version of test).

**Comment by grouma** [comment]
The package is only used from Chrome [coverage](https://github.com/dart-lang/test/blob/master/pkgs/test/lib/src/runner/browser/chrome.dart) collection. I'd do a path override and run the coverage related [tests](https://github.com/dart-lang/test/blob/master/pkgs/test/test/runner/coverage_test.dart). If they pass we should be able to easily bump the version.
