### ISSUE TITLE
null safety: test wrapper logic must mirror language version of wrapped _test.dart file

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#1236]
https://github.com/dart-lang/test/blob/0022fbd1be5faf373986369a050d6b2a088f71b7/pkgs/test_core/lib/src/runner/vm/platform.dart#L128-L143

If the wrapped `_test.dart` file sets a language version, it should be mirrored in the generated data URI so the null-safe opt-in logic is preserved.

**Comment by jakemac53** [comment]
This is done in the null_safety branch now
