### ISSUE TITLE
"browser" as platform should not be mentioned in readme

### ISSUE THREAD

**Issue by Pacane** [dart-lang/test#124]
Is the documentation out of date?

When I put

`@TestOn("browser")` at the top of my test and then run `pub run test:test -p browser`

it outputs:

`"browser" is not an allowed value for option "platform".`

**Comment by kevmoo** [comment]
Please see `pub run test --help`

```
-p, --platform                 The platform(s) on which to run the tests.
                               [vm (default), dartium, content-shell, chrome, phantomjs, firefox, safari]
```

**Comment by Pacane** [comment]
@kevmoo browser is still in the readme in the platform section (that's why I opened this issue)

**Comment by kevmoo** [comment]
@Pacane Good call. Will fix.

Or a pull request from you is welcome. :smile:

**Comment by Pacane** [comment]
Sure, I'll pr it. Just wanted to confirm if it was really not supported anymore.

**Comment by Pacane** [comment]
Just to confirm, only those in the --help are supported right?
`vm (default), dartium, content-shell, chrome, phantomjs, firefox`

All the others are not?

**Comment by kevmoo** [comment]
@Pacane Yup. The output from `--help` is truth. It maps to the internal parser.
