### ISSUE TITLE
Expose whether setup has been called

### ISSUE THREAD

**Issue by har79** [dart-lang/test#1263]
I have some setup for a common service that should always be called inside the `setUp` method to ensure it's reset before every test. Is there a public property for whether setUp has been called or can one be added?

Ideally I'd like to be able to do something like:

```
class MyService {
  MyService() {
    if (testIsSetup) {
      _init();
    else {
      setUp(_init);
    }
  }
  ...
```

Currently I can get this with `try/catch`:

```
try {
  setUp(_init);
} on StateError {
  _init();
}
```

but that seems hacky. Afaict the property already exists and it's just a matter of exposing it: https://github.com/dart-lang/test/blob/64cef5a4a32b22b43ca9aeacd333d635922cfca4/pkgs/test_api/lib/src/backend/declarer.dart#L84

Would this be a reasonable change?

**Comment by natebosch** [comment]
> ensure it's reset before every test.

If you do the reset in a callback with [`addTearDown`](https://pub.dev/documentation/test_api/latest/test_api/addTearDown.html) you can do whatever state reset needs to happen is done following any test that uses it. The `addTearDown` call is specific to that test case. Any checking that the object isn't used following the tear down until after it is set up can be handled within the class. I think `addTearDown` is already only callback from within a setup or a test case, so this should also prevent the case where it is constructed outside of any test or setup.

We do not plan on exposing any additional internal state.
