### ISSUE TITLE
broadcast not working in tests

### ISSUE THREAD

**Issue by amantoux** [dart-lang/test#1276]
Hi,

I don't understand why this test fails

```
void main() {
  test('async bool', () async {
    final controller = StreamController<int>.broadcast();
    var stream = controller.stream;
    controller.add(1);
    expectLater(stream, emits(anything));
    controller.close();
  });
}
```

If it remove the '.broadcast', the test succeeds

Can you please help?

Thank!

**Comment by grouma** [comment]
A broadcast stream does not cache events. You listen to the stream after an event is added and therefore miss it.

**Comment by amantoux** [comment]
Thanks for the explanation!
