### ISSUE TITLE
Node tests fail on macOS

### ISSUE THREAD

**Issue by jathak** [dart-lang/test#1278]
Dart Sass is failing when running tests in Node on macOS starting with version 1.15.0.

From [the error](https://travis-ci.org/github/sass/dart-sass/jobs/699863268), it seems like this is likely related to the IPv6 change mentioned in the changelog, but I don't have a Mac available to test on manually.

**Comment by natebosch** [comment]
@jathak - can you try a dependency override to the branch in https://github.com/dart-lang/test/pull/1279 and see if that works on travis for you?

**Comment by jathak** [comment]
The tests now seem to pass, but then it hangs until Travis's timeout is reached. Not sure if that's an issue with Travis or with the test runner on macOS, but Travis does work when we lock the test package at 1.14.7.

**Comment by natebosch** [comment]
I pushed up another commit that I think should fix the non-exit on travis. Can you rerun the travis job so it picks up the latest to verify?

**Comment by jathak** [comment]
It works now: https://travis-ci.org/github/sass/dart-sass/jobs/699863268

**Comment by natebosch** [comment]
New version is published, you should be good to remove the pinning to the older working one.
