### ISSUE TITLE
Polymer test not working with Chrome

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#128]
(#106)
I have a [Polymer test](https://github.com/bwu-dart/bwu_utils_dev/tree/master/test/testing/polymer_test_example) with two elements in their own files (same directory as the main test files)

Running with Dartium works fine. 
```
 (master) $ pub run test -pdartium test/testing/polymer_test_example/
00:00 +3: All tests passed!  
```
or
```
 (master) $ pub run test -pdartium test/testing/polymer_test_example/ --pub-serve=8080
00:00 +3: All tests passed!     
```

Running with Chrome (dart2js) fails

```
 (master) $ pub run test -pchrome test/testing/polymer_test_example/
Compiling test/testing/polymer_test_example/html_test.dart...
/tmp/dart_test_B7Th5g/runInBrowser.dart:

... lot of dart2js output about mirrors

00:00 +0 -1: load error                                                                             
  Failed to load "test/testing/polymer_test_example/html_test.dart": Unable to find library at http://localhost:57285/_19GE_MMg_Uh7tt6nYTeZgpS8MJFysY3/test/testing/polymer_test_example/child_element.dart.
  html_test.dart.browser_test.dart.js 4440:17    dart.wrapException
  html_test.dart.browser_test.dart.js 4453:15    dart.throwExpression
  html_test.dart.browser_test.dart.js 120978:19  run
  html_test.dart.browser_test.dart.js 4817:13    _wrapJsFunctionForAsync_closure._captured_protected_1
  html_test.dart.browser_test.dart.js 6849:14    _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$1
  html_test.dart.browser_test.dart.js 97208:36   dirtyCheckZoneSpec_wrapUnaryCallback_closure.dart.dirtyCheckZoneSpec_wrapUnaryCallback_closure.call$1
  html_test.dart.browser_test.dart.js 14747:18   dart._rootRunUnary
  html_test.dart.browser_test.dart.js 23864:137  _CustomZone.dart._CustomZone.runUnary$2
  html_test.dart.browser_test.dart.js 17009:80   _Future__propagateToListeners_handleValueCallback.dart._Future__propagateToListeners_handleValueCallback.call$0
  html_test.dart.browser_test.dart.js 16878:159  dart._Future.static._Future__propagateToListeners
  
00:00 +0 -1: Some tests failed.                                                              
```

It works the 2nd try using `pub serve`
*1st try*
```
 (master) $ pub run test -pchrome test/testing/polymer_test_example/ --pub-serve=8080
"pub serve" is compiling test/testing/polymer_test_example/html_test.dart...
00:00 +0 -1: load error                                                                             
  Failed to load "test/testing/polymer_test_example/html_test.dart": Timed out waiting for the test suite to connect on Chrome.
00:00 +0 -1: Some tests failed.           
```
(error about 15 seconds after browser window opens)
Increasing https://github.com/dart-lang/test/blob/master/lib/src/runner/browser/browser_manager.dart#L82 doesn't seem to have any effect.

*2nd try*
```
 (master) $ pub run test -pchrome test/testing/polymer_test_example/ --pub-serve=8080
00:00 +3: All tests passed! 
```

**Comment by zoechi** [comment]
I checked out `test` and changed the timeout there (from 15 to 60 seconds) and used a path dependency for `test`. Previously I just changed it in `packages/test/src/runner/browser/browser_manager.dart` but this doesn't seem to have an effect when `pub run test` is run.
My notebook is quite old already, but I think it's still a reasonable machine
12GB RAM, SSD, 8 core i7 CPU Q 720  @ 1.60GHz

**Comment by zoechi** [comment]
With `pub serve` it works with a timeout of 20 seconds (`pub serve` restarted before each try) but without `pub serve` it still fails with 120 seconds timeout (with Chrome/dart2js).

**Comment by nex3** [comment]
What version of `test` are you using? Judging by the JS stack trace, I'm guessing it's not 0.12.2. What happens if you run with 0.12.2?

> Running with Chrome (dart2js) fails

According to @jakemac53, Polymer tests don't support being run via dart2js directly. They need to be run through `pub serve`.

**Comment by zoechi** [comment]
The checked-in `pubspec.lock` says 0.12.2. I'm quite sure this is the version I used. 
I also tried with the version from Git (master, where I modified the timeout) with the same result.
Thanks for the info. I try to memorize that ;-)

**Comment by zoechi** [comment]
What do you think about using `pub serve` by default instead of dart2js. `pub serve`/`pub build` are the default tools for Dart projects, it's quite cumbersome to automate launching of `pub serve` and then launching `pub run test` while passing the port from `pub serve`. Sure it's not too difficult either but quite cumbersome and inefficient that everyone has to find a solution for this common use case. I assume Polymer is not the only framework which requires `pub serve`, probably every framework which uses transformers.

**Comment by jakemac53** [comment]
Fwiw, polymer may actually work through dart2js directly if all your dart files are included directly from your entry point script. I think the only reason it doesn't work today is because of dart files that are only imported via script tags in html imports, although I haven't tested that theory.

**Comment by zoechi** [comment]
So when I import the elements using Dart imports and the `@HtmlImport` annotation then it might work? 
I had to add `<script src="packages/polymer_interop/src/js/polymer.js"></script>` but still got a timeout therefore I can't tell if it works.

I guess it would be more efficient to launch `pub serve` and then run all HTML tests through this `pub serve` instance, instead of using `dart2js`. I don't know if `pub serve` supports `--mode=release` - probably important for tests.
I also don't know enough how `test` works behind the scenes :-(

**Comment by kevmoo** [comment]
@zoechi We're investigating an evolution of our tooling model to hopefully improve a lot of cases where transformers are required – so we're making sure the test runner works at a very basic level (without requiring pub serve).

That said, I hope the test infrastructure will make it easy to coordinate things like pub server when running tests. Chatting w/ @nex3 now...

**Comment by kevmoo** [comment]
Generally speaking, I think this request aligns with https://github.com/dart-lang/test/issues/18 – how can tests effectively/efficiently coordinate long-lived dependencies (like servers)

**Comment by zoechi** [comment]
ok, I stay tuned. I can live with running pub serve, I have it skripted.  The timeout issue is a real blocker currently.
