### ISSUE TITLE
Support test with regular webserver

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/test#129]
If I start the test with mylocalserver --port 8080 I get 

```
 GET http://localhost:8080/test.dart.browser_test.dart dart.js:67 window.onload
```

this is my custom html file
```html
<!doctype html>
<!-- custom_html_test.html -->
<html>
<head>
    <title>Custom HTML Test</title>
    <link rel="x-dart-test" href="test.dart">
    <!-- it works if I uncomment the following line but then I get the above error message --> 
    <!--<script async type="application/dart" src="test.dart"></script>-->
    <script src="packages/test/dart.js"></script>

    <link rel="stylesheet" href="packages/mdl/assets/styles/material.min.css">
</head>
<body>

<div class="ui-test ui-test-button">
    <button id="button1" class="mdl-button mdl-js-button">Flat</button>
</div>

</body>
</html>
```

It works fine with
```shell
pub run test:test -p dartium test/unit/test.dart
```

The problem is that with `pub run test:test -p dartium test/unit/test.dart` the browser pops up, runs the test and closes. This is not enough. In my case there is also a visual test necessary - means I have to see!!!! how my Dart-Script modified the button.
![screenshot-1786](https://cloud.githubusercontent.com/assets/116654/7863840/eb157d6e-055e-11e5-903b-49a5666d0b74.png)

See my SS - I must see how "FLAT" looks like

**Comment by zoechi** [comment]
If you need to see it you will probably need to change `<link rel="x-dart-test" href="test.dart">` to a proper dart script tag, then you can launch the HTML page manually. 
I have no idea how this will work out when this way of running tests is deprecated (as announced). For automatic test runs such a manual visual check wouldn't make much sense anyway (maybe using WebDriver, which can be used in combination with this test package).

**Comment by nex3** [comment]
The `test` package is designed for automated testing; manual testing is a non-goal. You'll be able to see the results of the tests with #45, but that's not going to be its primary purpose. I suggest you don't use this test framework for writing manual tests.
