### ISSUE TITLE
test_core broken with meta 1.2

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/test#1292]
Just doing a pub update on any project depending on test breaks...

```
Failed to precompile test:test:
../../../../../../../.pub-cache/hosted/pub.dartlang.org/test_core-0.3.8/lib/test_core.dart:69:5: Error: 'unawaited' is imported from both 'package:meta/meta.dart' and 'package:test_api/src/utils.dart'.
    unawaited(Future.error('Dummy exception to set exit code.'));
    ^^^^^^^^^
```

Maybe meta should have some tests!

Example for failed job on travis: https://travis-ci.org/github/tekartik/sembast.dart/jobs/705443785

**Comment by grouma** [comment]
Need to publish: https://github.com/dart-lang/test/pull/1290

**Comment by alextekartik** [comment]
Event `test` package must be updated and published (it has an explicit dependency on `test_core` 3.9.0)

**Comment by grouma** [comment]
Correct. Just waiting on a clean run: https://github.com/dart-lang/test/pull/1293

**Comment by alextekartik** [comment]
Thanks, that fixes one issue. However tests are still broken, now when using `pub run build_runner test`, see https://github.com/dart-lang/build/issues/2745. This issue seems new after the test package update (I have tests that were working on travis 10 hours ago that are now broken)
