### ISSUE TITLE
Run tests with checked mode turned on

### ISSUE THREAD

**Issue by sethladd** [dart-lang/test#130]
Running tests seems like the perfect opportunity to run in checked mode. The test runner probably should default to checked mode turned on.

This is a tracking issue for the test runner, so we have something to follow. Sounds like we're waiting for https://code.google.com/p/dart/issues/detail?id=21791 to land.

**Comment by zoechi** [comment]
See also #50

**Comment by sethladd** [comment]
:bowtie:
