### ISSUE TITLE
flutter_test from sdk is incompatible with test >=1.15.3.

### ISSUE THREAD

**Issue by Inffinite** [dart-lang/test#1308]
# I keep getting this error 

Running "flutter pub get" in school...                          
Because every version of flutter_test from sdk depends on test_api 0.2.15 and test >=1.15.3 depends on test_api 0.2.18, flutter_test from sdk is incompatible with test >=1.15.3.

So, because school depends on both test ^1.15.3 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because school depends on both test ^1.15.3 and flutter_test any from sdk, version solving failed.)
exit code 1

# pubspec.yml
![image](https://user-images.githubusercontent.com/51359048/88689037-b0870580-d102-11ea-8895-236807514433.png)

# flutter doctor
![image](https://user-images.githubusercontent.com/51359048/88689630-63576380-d103-11ea-95b9-90a8a8c553a3.png)

Help me out

**Comment by jakemac53** [comment]
This is a flutter issue - they have chosen to pin all of their dependencies to exact versions for each release.

You can expand your constraint on package:test to so you get an older version, something like `test: ^1.0.0` (I don't know the exact version that would work, but that is certainly wide enough).

If you want a new feature from package:test you would have to wait until the next release of flutter, or move to a different flutter channel that is newer (dev or master).

**Comment by jakemac53** [comment]
I am going to close this here but feel free to open an issue on the flutter repo https://github.com/flutter/flutter (I would transfer this but i can't transfer it between orgs).
