### ISSUE TITLE
Upgrading form 1.14.4 to 1.15.0 causes emitsInOrder to not work properly

### ISSUE THREAD

**Issue by JacobT14** [dart-lang/test#1317]
Hey everyone!

I don't have much to really show.  I have the following code that works in 1.14.4, but not 1.15.0
`  await expect(queue, emitsInOrder(matchers));`

Stumbled upon this upgrading from 1.17.5 flutter to 1.20 today.  This is a blocker for me to upgrading to flutter 1.20.

The test failure is as follows:
`Expected: should emit an event that PaperlessStateClockedIn:<PaperlessStateClockedIn{currentShift: 701B0E57-BC17-46E3-97BE-E47345D067FE}>
  Actual: <Instance of 'StreamQueue<PaperlessState>'>
   Which: emitted • PaperlessStateUninitialized{}
`

**Comment by JacobT14** [comment]
Think I may have found a pattern...

I'm using bloc and the creating a StreamQueue from the bloc.  If no events have come in, BEFORE I create the StreamQueue, the emitsInOrder function essentially acts like it's still in the initialState.  Not really sure if it's an issue with this library or not, but I can work around it.  If I simply add a dummy event to the bloc at the beginning it fixes it.

**Comment by jakemac53** [comment]
It sounds like possibly some other timing thing subtly changed during the flutter upgrade? You could try overriding to the old package:test to confirm the source of the issue (you might run into other issues doing this though).

In your pubspec.yaml:

```
dependency_overrides:
  test: 1.14.4
```

If that makes the test pass then something did likely change in the test package that affected you, if not then it was more likely something on the flutter side of things.

**Comment by JacobT14** [comment]
Agreed.  Definitely a timing thing because if I also add delayed future of 1 ms after the first event is added that fixes it.  I'm going to close this as I've fixed it, but maybe someone will save a little time from this haha!

**Comment by JacobT14** [comment]
And, it doesn't let me override down to 1.14.4 due to dependency conflicts with flutter_driver and flutter_test

**Comment by jakemac53** [comment]
> And, it doesn't let me override down to 1.14.4 due to dependency conflicts with flutter_driver and flutter_test

You might be able to work around those by also overriding the `test_api` and/or `test_core` packages, but ya it might just not be worth doing.

**Comment by JacobT14** [comment]
Yea, not really worth it since I worked around it.  It is what it is, don’t want people wasting a bunch of time to fix a minor issue.
