### ISSUE TITLE
Cannot expect a Type with a specific generic

### ISSUE THREAD

**Issue by MilesAdamson** [dart-lang/test#1336]
I have an object of class `ModelsLoadError<Division>`. `Division` extends `Identifiable`, a base class for models with an id and stuff. It represents a failure to load divisions from the server. In a unit test, I wrote the following:

```
print(state.runtimeType);
expect(state.runtimeType, ModelsLoadError);
```

It fails with the following console error (and prints the type above):

```
ModelsLoadError<Division>
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following TestFailure object was thrown building BlocBuilder<ModelsBloc<Division>,
ModelsState<Division>>(dirty, state: _BlocBuilderBaseState<ModelsBloc<Division>,
ModelsState<Division>>#fc692):
  Expected: Type:<ModelsLoadError<Identifiable>>
  Actual: Type:<ModelsLoadError<Division>>
```

I cannot add a generic type to the `expect`, it isn't valid dart code.

![image](https://user-images.githubusercontent.com/29047682/92804471-984b0d00-f375-11ea-9762-cdc947748126.png)

How do I change my test to pass and check the type of `ModelsLoadError<Division>`?

Interestingly, I can change it to use `is`:

```
expect(state is ModelsLoadError<Division>, true);
```

But this makes my test case fail with true/false, opposed to a much clearer case as to what I expect (the type `ModelsLoadError<Division>`)

**Comment by natebosch** [comment]
The recommended way to write this expectation is

```dart
expect(state, isA<ModelsLoadError>());
```

or

```dart
expect(state, isA<ModelsLoadError<Division>>());
```

The `isA` matcher returns a `TypeMatcher` so you can also chain `.having` calls off of it to add more expectations.

https://pub.dev/documentation/matcher/latest/matcher/isA.html
https://pub.dev/documentation/matcher/latest/matcher/TypeMatcher/having.html
