### ISSUE TITLE
Doesn't work with stable flutter?

### ISSUE THREAD

**Issue by Mereep** [dart-lang/test#1349]
I followed the descriptions given here: https://flutter.dev/docs/cookbook/testing/unit/introduction

giving me:
```yaml
dev_dependencies:
  test: 1.15.4
```

however, when using fetching the dependencies on a freshly installed framework (stable) it does not resolve:

```text
Because every version of flutter_test from sdk depends on test_api 0.2.17 and test >=1.15.3 <1.16.0-nullsafety depends on test_api 0.2.18, flutter_test from sdk is incompatible with test >=1.15.3 <1.16.0-nullsafety.
So, because wir_in_der_region depends on both test 1.15.4 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because project depends on both test 1.15.4 and flutter_test any from sdk, version solving failed.)
```

How can this be resolved? Is there a workaround?

**Comment by jakemac53** [comment]
You should use a constraint like `^1.15.4` - please file a bug on the docs there to suggest that.

**Comment by Mereep** [comment]
It is not workung with `^1.15.4` either, surely I tried that

**Comment by jakemac53** [comment]
What is the message you get with the `^1.15.4` constraint? Most likely some other dependency is preventing you from getting the latest test but we can likely help to interpret the pub error messages as they can be a bit difficult to parse.

**Comment by Mereep** [comment]
> What is the message you get with the `^1.15.4` constraint? Most likely some other dependency is preventing you from getting the latest `test` but we can likely help to interpret the pub error messages as they can be a bit difficult to parse.

Its basically the same. I reported it also in the `flutter` repository. It seems just like the latest stable `flutter` release doesnt want to play with the latest `test` release. They suggest using an older version of the `test` package. Also, switching `flutter` to the` beta channel` fixed it for me.

**Comment by jakemac53** [comment]
Right, `flutter` pins specific versions of packages so you have to be able to get exactly the version they want. If flutter stable pins an older test version then you would need to lower the constraint to allow that.
