### ISSUE TITLE
Cannot test null safety project with a non null safety dependency

### ISSUE THREAD

**Issue by giorgiofran** [dart-lang/test#1352]
I'm starting to move to null safety. Most of the packages I have as dependencies already moved.
Only one is still in the non-null safety version.
When I work on the sources the analyser works fine and I'm able to do all changes as expected, but, when it comes to testing, I get the following error:
**Unable to spawn isolate: Error: Cannot run with sound null safety as one or more dependencies do not
support null safety:

 - package:fixnum**

**Comment by jakemac53** [comment]
You can run your tests in "mixed" mode (which disabled null safety checks) by either opting the tests themselves out (using a language comment like `// @dart=2.9`), or you can pass the `--no-sound-null-safety` flag (so something like `pub run --enable-experiment=non-nullable --no-sound-null-safety test`).

There is also an option to enable runtime null safety assertions in mixed mode which gets you some safety but I don't think that `pub` supports it - cc @jonasfj

**Comment by jakemac53** [comment]
Note that in general we encourage strongly fully bottom-up migrations which avoids this problem and ensures your package is indeed migrated correctly - but this gets especially tricky for tests as they typically have far more dependencies.

**Comment by giorgiofran** [comment]
Thanks, I wanted to to test what does it mean to move to null safety, so I took a small project and started to modify it. I simply checked that I was in the right direction. For production I certainly wait for all the dependencies to be migrated. The `--no-sound-null-safety` flag worked fine
