### ISSUE TITLE
Skip tests during execution

### ISSUE THREAD

**Issue by passsy** [dart-lang/test#1355]
## Context

I have a test suite of end-to-end tests for a backend delivering live Formula 1 data. Depending on the race calendar - whether it's a racing weekend, midweek or a bye week - the backend sends different data and some endpoints (live timings) error.

## Problem

Currently, I have to collect all data for all tests upfront to then decide if a test should be run or skipped.

```dart
// run_all.dart

/// When live == true race is live 
bool live;

Future<void> runAll() async {
  // load all information upfront before declaring the tests
  await _loadServerConfig();

  get_drivers.main();
  lap_times.main();
  // ...
}

Future<void> _loadServerConfig() {
  final status = await api.apiStatus();
  live = status.phase == "live";
}
```

```dart
// lap_times.dart

Future<void> main() async {
  test(
    "GET /race/timings/:player_id",
    () async {
      final players = await api.allPlayers();
      final timings = await api.getLiveTimings(players.first);

	  for (final time in timings) {
        expect(time.current, isNotNull);
        expect(time.lap, isNotNull);
      }
    },
    skip: () {
      // test executed without run_all.dart, always execute
      if (live == null) return false;
	  if (!live) return "race is not live";
	  
      // race live
      return false;
    }(),
  );
}
```
Note: It is not possible to split the upfront logic and move it into the `main()` methods of the other files because once the first call to `test` happened, all tests have to be added synchronously. Any async call between `test` calls results in an error. Moving the upfront logic into the `setup` method also doesn't work because it is executed after the tests are declared, therefore it is not possible to adjust the `skip` flag.

## Expectation

It would be much easier when a test could be skipped after it was started. This would drastically decrease complexity.

```dart
// lap_times.dart

Future<void> main() async {
  test( "GET /race/timings/:player_id", () async {
    final status = await api.apiStatus();
    final live = status.phase == "live";
    if (!live) {
      skip("Race is not live"); // Skip tests here, test should not continue
    }

    final players = await api.allPlayers();
    final timings = await api.getLiveTimings(players.first);

    for (final time in timings) {
      expect(time.current, isNotNull);
      expect(time.lap, isNotNull);
    }
  );
}
```

`skip`, analog to `fail`, throws a specific Exception caught by the test framework to mark the test as skipped.
```dart 
@alwaysThrows
void skip(String message) {
  throw SkipException(message);
}
```

## Other ways to stop test execution

Stopping test execution is currently only possible with
- `return;` which marks the test as passed and
- `throw "skip";` which marks the test as failed.

Both exit conditions do not match was actually happened, which is that the test was skipped and did not reach the necessary assertions for success.

___

The `test` package isn't defined as "unit test" package, therefore I think better support for end-to-end tests could be in the package scope.

**Comment by jakemac53** [comment]
Note that the `expect` function does support `skip` - does that support your use case?

> Note: It is not possible to split the upfront logic and move it into the `main()` methods of the other files because once the first call to `test` happened, all tests have to be added synchronously. Any async call between `test` calls results in an error. Moving the upfront logic into the `setup` method also doesn't work because it is executed after the tests are declared, therefore it is not possible to adjust the `skip` flag.

You should not generally need a single file with a `runAll` method if you use the test runner (`pub run test`) - these tests can live in their own files and do their own async setup code before the tests run and all tests will be ran individually.

**Comment by passsy** [comment]
I wasn't aware of `skip` in `expect`. This is how it looks like when using it

```dart
if (!live) {
  // Skip when not live
  expect(null, null, skip: "Race is not live");
}
```

## Unexpected behaviour

First I was very confused that this skips even when the assertion is `true`. I expected it to skip only when the assertion fails and started with this

```dart
// does always skip, unexpected
expect(live, isFalse, skip: "Race is not live");
```

Also, the fact that the first two positional, required arguments of `expect` aren't required at all leaves a bad feeling.


## Undefined and undocumented behaviour

Skipping tests during execution with `expect(skip: )` only works via CLI. IntelliJ marks those tests as "success", only printing the skip message to console. I don't know which behaviour is correct. 

```
/// If [skip] is a string, it should explain why the assertion is skipped; this
/// reason will be printed when running the test.
```

From the documentation I have to assume that skipping the test is only a side-effect and the `expect(skip: )` argument should *only* skips the assertion, resulting in "success" or "error".


## Explicit skip API

Under the hood `expect` calls `Invoker.current.skip(String)` which isn't part of the public `test` API. But it could be. I still think that a dedicated `skip` function would improve the test package.

By thowing and catching an internal Exception this `skip` function could end execution early. Annotating `skip` with `@alwaysThrows` doesn't seem very useful after a second thought.

**Comment by jakemac53** [comment]
I think the main thing missing from the existing api is as you mentioned a more direct way to explicitly skip something, and then also return from the test function immediately and not continue the test. I would probably not add the additional `skipIf` api as it is easy enough to do on your own.

Note that throwing an error alone will not terminate any ongoing async tasks that might have been scheduled, but it is probably good enough. The test runner will wait for those to complete afaik. That could lead to deadlocks in some scenarios but if people are using `setUp` and `tearDown` it shouldn't be a problem.

> First I was very confused that this skips even when the assertion is `true`. I expected it to skip only when the assertion fails and started with this

This behaves the same as the other `skip` arguments - see the doc comments for the `expect` method. You can pass a boolean `false` for `skip` and it won't be skipped. That is at least consistent with the other existing apis which is good.

> Also, the fact that the first two positional, required arguments of `expect` aren't required at all leaves a bad feeling.

I agree with that - using a meaningless expect just to mark the test as skipped definitely doesn't feel right.

> Skipping tests during execution with `expect(skip: )` only works via CLI. IntelliJ marks those tests as "success", only printing the skip message to console. I don't know which behaviour is correct.

The behavior is pretty well documented here - see the doc comments for expect. Please send a PR with expanded docs if you have some suggestions on how to make it more clear.

As far as IntelliJ goes that sounds like a bug with their handling - they are only looking at the skip metadata on the first message for the test and not the result at the end which they should be. Below is some example output from the json reporter which looks correct:

```
{"test":{"id":4,"name":"expect with skip","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":21,"column":3,"url":"..."},"type":"testStart","time":3250}
{"testID":4,"messageType":"skip","message":"Skip expect: skipped!","type":"print","time":3263}
{"testID":4,"result":"success","skipped":true,"hidden":false,"type":"testDone","time":3264}
```

Regardless of how an execution time skip is implemented IntelliJ is going to have this problem.

**Comment by natebosch** [comment]
We spent a few minutes chatting about this today.

I'm in favor of adding an API like `markSkipped(String reason)` or `markTestSkipped(String reason)`. We can consider whether the argument should be optional. This would behave like `expect(null, null, skip: reason)` in that it marks the test as skipped, and it would be the test authors responsibility to return.

This will serve as a generalization of the `expect` skipping, it still allows other validation to happen if necessary. I believe it's a more general API than throwing an exception. It also saves complexity, it's not totally clear to me that everyone will have the same expectations around how a throwing `skip` should work. Any failed `expect` or any other thrown exception still causes a test to fail even after `markSkipped` has been called.

**Comment by natebosch** [comment]
cc @jonahwilliams  in case you have any thoughts on this. I would imagine that `flutter_test` will want to export this new API.

**Comment by jonahwilliams** [comment]
Seems like a useful feature, no concerns with exporting it though I would double check for name clashes first (I took a cursory glance and didn't see any)
