### ISSUE TITLE
tests that heavily use async/await become very slow due to chaining

### ISSUE THREAD

**Issue by mraleph** [dart-lang/test#1358]
One of my tests which reads a large file line by line using a couple of `async*` function becomes 10x slower under package:test due to chaining. 

I found troubleshooting this issue somewhat confusing - I wrote a test which was timing out, even though I knew that it is not doing anything too complicated because I tested program behaviour before and it took 4s to run outside of test. I used Observatory to profile it and noticed that `StackTrace.current` is taking a lot of time (>80% to be precise) - at which point I realized that it is package:stack_trace that the root cause - after some searching around I managed to find `--[no-]chain-stack-traces` command line option. But that's only because I _knew_ what I am looking for - there is nothing in `package:test` documentation that warns you about this and points you towards the option. Furthermore using option is not very ergonomic: it means I have to run my tests in a custom way, rather than just doing `pub run test` and have it pick all necessary tweaks from annotations and test suite configuration. 

Is there any reason why stack trace chaining is on by default on VM even though VM provides causal stack traces?

**Comment by natebosch** [comment]
> Is there any reason why stack trace chaining is on by default on VM even though VM provides causal stack traces?

Mostly legacy reasons. Internally we disable them by default and I think include in the error message a note about how to enable them if we show a stack trace. I think I'd be OK doing something similar externally.

What do you think @grouma @jakemac53

**Comment by grouma** [comment]
> Mostly legacy reasons. Internally we disable them by default and I think include in the error message a note about how to enable them if we show a stack trace. I think I'd be OK doing something similar externally.

We don't disable chained stack traces for VM tests however. Last I checked there was essentially no overhead with chaining on the VM side so we left them enabled.

> What do you think @grouma @jakemac53

I'm fine with disabling chaining by default if we provide clear documentation on how to enable them.

**Comment by jakemac53** [comment]
I would be fine with disabling them by default for vm tests, if we think the existing stack traces are now good enough. It gets a bit weird if they are enabled in one environment and not the other though, or look different.
