### ISSUE TITLE
spawnHybridUri and NNBD opt-out

### ISSUE THREAD

**Issue by mraleph** [dart-lang/test#1363]
It seems that using `spawnHybridUri` in web tests does not opt target out if the spawner is opted-out. 

See this test in grpc package: https://github.com/grpc/grpc-dart/blob/master/test/grpc_web_test.dart running it on `dev` channel without manually opting `grpc_web_server.dart` out (spawned here: https://github.com/grpc/grpc-dart/blob/master/test/grpc_web_test.dart#L21) causes the test to fail with 

```
  IsolateSpawnException: Unable to spawn isolate: http://localhost:35703/gxi6aFI%2BPNmQ1A8pOnIQZwHWxkCs8Onb/test/grpc_web_server.dart:80:31: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
        final port = int.parse(m[1]);
```

/cc @jakemac53

**Comment by jakemac53** [comment]
This looks like a fair bit of reworking is in order. We currently pass the `packageConfig` from the current isolate on the server side in order to spawn the isolate, but the URI we spawn with is an http uri that loads the file from the browser.

I am not sure why/if loading it as an http uri is actually desirable, we could instead pass the relative uri down to the test runner, and let it create an absolute _file_ uri. 

We could also create a custom package config that understands the http uris.

**Comment by nex3** [comment]
This is still broken on the released branch, and it's [breaking our CI](https://travis-ci.com/github/sass/dart-sass/jobs/439795491).

**Comment by jakemac53** [comment]
> This is still broken on the released branch, and it's [breaking our CI](https://travis-ci.com/github/sass/dart-sass/jobs/439795491).

To clarify, does this work if you opt out the file with `// @dart=2.9`?

**Comment by nex3** [comment]
No, it doesn't.

**Comment by jakemac53** [comment]
I think this might be something node specific, we will have to take a look.

**Comment by mraleph** [comment]
FWIW it does not work for gRPC test either (the one which prompted me to file the issue). If I remove opt out from [here](https://github.com/grpc/grpc-dart/blob/master/test/grpc_web_server.dart#L1) then [this spawn](https://github.com/grpc/grpc-dart/blob/master/test/grpc_web_test.dart#L122) fails.

**Comment by jakemac53** [comment]
Thanks for pointing at a repro I will take a look at the grpc scenario

**Comment by jakemac53** [comment]
@mraleph it looks to me like things are working as expected - i am getting a different unrelated failure locally but the `spawnHybridUri` call does succeed without issues for me after removing the language comment.

**Comment by jathak** [comment]
Any updates on this? It's still [breaking Dart Sass's CI when running on Node](https://github.com/sass/dart-sass/pull/1247/checks?check_run_id=2034298372), which is forcing us to pin our SDK version to 2.11 (and preventing us from starting the move to null safety)

**Comment by mraleph** [comment]
@jathak I think this PR should fix it: https://github.com/sass/dart-sass/pull/1249/files

**Comment by mraleph** [comment]
FWIW I think now problem is with `spawnHybridCode` and not `spawnHybridUri` (which seems to work). I have made the following test: 

```dart
// test/hybrid_code.dart

bool runningWithNullSafety() {
  try {
    null as String;
    return false;
  } catch (_) {
    return true;
  }
}

void hybridMain(dynamic channel) async {
  channel.sink.add(runningWithNullSafety());
  channel.sink.close();
}
```

```dart
// test/with_hybrid_code_test.dart

@TestOn('node')
@Tags(['node'])

import 'package:test/test.dart';

import 'dart:js';

import './hybrid_code.dart' show runningWithNullSafety;

void main() {
  final fs = context.callMethod('require', ['fs']);

  ({
    'spawnHybridCode': () => spawnHybridCode(
        fs.callMethod('readFileSync', ['test/hybrid_code.dart', 'utf8'])),
    'spawnHybridUri': () => spawnHybridUri('hybrid_code.dart'),
  }).forEach((name, spawn) {
    test(name, () async {
      final channel = spawn();
      final result = await channel.stream.single;
      expect(result, equals(runningWithNullSafety()),
          reason: 'Expected null-safety mode in child to match that of parent');
    });
  });
}
```

When I run it from a package which opts-out from NNBD (`sdk: '>=2.10.0 <3.0.0'`), I get the following output: 

```dart
$ dart pub run test -p node -t node
Deprecated. Use `dart run instead`
00:05 +0: compiling test/with_hybrid_code_test.dart                                                                                                                                                                                                                                                             
Hint: When run on the command-line, the compiled output might require a preamble file located in:
  <sdk>/lib/_internal/js_runtime/lib/preambles.
Compiled 6,132,011 characters Dart to 1,193,001 characters JavaScript in 5.31 seconds
Dart file /private/var/folders/vg/yc7lgjmn63x0rwycng5kxt3r00375p/T/dart_test_mE970R/runInBrowser.dart compiled to JavaScript: /private/var/folders/vg/yc7lgjmn63x0rwycng5kxt3r00375p/T/dart_test_cQ7mtg/test_vKys6j/with_hybrid_code_test.dart.node_test.dart.js

00:07 +0 -1: test/with_hybrid_code_test.dart: spawnHybridCode [E]                                                                                                                                                                                                                                               
  Expected: <false>
    Actual: <true>
  Expected null-safety mode in child to match that of parent
  
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 1130:37   Object.wrapException
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 1161:25   Object.throwExpression
  package:test_api                                                          Object.expect
  test/with_hybrid_code_test.dart 21:7                                      <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 316:19  _wrapJsFunctionForAsync.closure.$protected
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 341:23  _wrapJsFunctionForAsync.<fn>
  ===== asynchronous gap ===========================
  org-dartlang-sdk:///lib/async/zone.dart 1293:34                           _CustomZone.registerBinaryCallback
  org-dartlang-sdk:///lib/async/zone.dart 569:30                            Object._wrapJsFunctionForAsync
  org-dartlang-sdk:///lib/async/zone.dart 1354:12                           StaticClosure._rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1257:34                           _CustomZone.run
  org-dartlang-sdk:///lib/async/zone.dart 1788:10                           Object._runZoned
  ===== asynchronous gap ===========================
  org-dartlang-sdk:///lib/async/zone.dart 1293:34                           _CustomZone.registerBinaryCallback
  org-dartlang-sdk:///lib/async/zone.dart 569:30                            Object._wrapJsFunctionForAsync
  org-dartlang-sdk:///lib/async/zone.dart 1354:12                           StaticClosure._rootRun
  org-dartlang-sdk:///lib/async/zone.dart 1257:34                           _CustomZone.run
  org-dartlang-sdk:///lib/async/zone.dart 1788:10                           Object._runZoned
  
00:07 +1 -1: Some tests failed.  
```

So it seems `spawnHydridUri` works as expected, but `spawnHybridCode` does not.

**Comment by jakemac53** [comment]
> So it seems `spawnHydridUri` works as expected, but `spawnHybridCode` does not.

The question I think is what the "uri" for the code passed to `spawnHybridCode` should be. That is what determines the language version of that code, which in turn determines the language version. I believe today it is just a `data` uri which matches no package in the package config, and so it gets the latest language version (opting it _in_ to null safety).

We could inject a language version marker into the code which matches the current packages language version, if no other language version exists. That might be the most useful behavior? cc @natebosch.

Note that you could add your own language marker to work around this easily today as well.

**Comment by natebosch** [comment]
> We could inject a language version marker into the code which matches the current packages language version, if no other language version exists. That might be the most useful behavior? cc @natebosch.

This does sound useful.
