### ISSUE TITLE
Testing dart library with multiple (old, new) sdks scenario

### ISSUE THREAD

**Issue by jjangga0214** [dart-lang/test#1365]
Hi, I am a library author.

I want to make my library compatible with old sdk.

To make it sure, I want to test it with multiple sdks(old one(e.g. 2.5.0) and the latest one) on CI.

Though I am new to dart ecosystem, I think this, as a library author, is a sane and common scenario.

However, `package:test` has so narrow(intentionally?) sdk support range.

https://github.com/dart-lang/test/blob/ee8c5faef0d58f6335da7b4def385592721ca1af/pkgs/test/pubspec.yaml#L6-L8

Therefore, no matter which version of `package:test` I take, CI fails.

Why does this happen, and is this 'narrow' sdk support range really necessary?

I see 

> \# This must remain a tight constraint until nnbd is stable 

and is this somehow related?

Thanks.

**Comment by jakemac53** [comment]
The narrow SDK is a requirement right now and will be increased very soon to `2.12.0`. You can  however use an older version of this package which supports older sdks.

**Comment by jjangga0214** [comment]
@jakemac53 Thanks a lot!

For clarification, I want to ask it again.

> will be increased very soon to 2.12.0

Does this mean, after dart _stable_ v2.12.0 is released, `package:test` can support wide range of SDK?

> You can however use an older version of this package which supports older sdks.

This is so tricky.. Once I use _an older version of this package_, it will fail with latest sdk(e.g. 2.10.x).
So I have to use 
_an older version of this package_ with old sdk,
and 
_an newer version of this package_ with new sdk,
respectively, on CI.

How can I achieve it? 

Keeping two pubspec.yaml files with different `package:test` version might make it work, but so far from the ideal.

**Comment by jakemac53** [comment]
> Does this mean, after dart _stable_ v2.12.0 is released, `package:test` can/will support a wide range of SDK? (e.g. `>=2.5.0 <3.0.0`)

No, you _must_ set your min sdk to >=2.12.0 in order to use null safety, and this will be our min sdk going forward. There is no alternative available because we are using features that only exist in 2.12.

> This is so tricky.. Once I use '_an older version of this package_', it will fail with latest sdk(e.g. 2.10.x).

Pub will resolve this for you. You should have a dependency constraint on package:test which allows all the versions you require, something like `test: >=1.15.4 <2.0.0`.

**Comment by jjangga0214** [comment]
@jakemac53 Thank you!

> Pub will resolve this for you. You should have a dependency constraint on package:test which allows all the versions you require, something like test: >=1.15.4 <2.0.0.

This works like a charm. Thanks for the solution again :)
