### ISSUE TITLE
Could not find a file named "pubspec.yaml" in "...Cache\hosted\pub.dartlang.org\_fe_analyzer_shared-12.0.0".

### ISSUE THREAD

**Issue by shinayser** [dart-lang/test#1367]
Everytime I try to run my tests using `pub run test` I get this error:

```
Could not find a file named "pubspec.yaml" in "C:\Users\shina\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\_fe_analyzer_shared-12.0.0".
```

If you need any more info please, just ask!

**Comment by jakemac53** [comment]
It sounds like your pub cache was corrupted, you can delete that directory `"C:\Users\shina\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\_fe_analyzer_shared-12.0.0"` to force it to be re-downloaded or you can run `pub cache repair` to repair the entire caceh.

**Comment by shinayser** [comment]
> It sounds like your pub cache was corrupted, you can delete that directory `"C:\Users\shina\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\_fe_analyzer_shared-12.0.0"` to force it to be re-downloaded or you can run `pub cache repair` to repair the entire cache.

The pub repair didint work. And deleting the folder will not work too because the folder doesn't exist, and probably that is the problem. Check this out:

![image](https://user-images.githubusercontent.com/1146982/98041624-00abed00-1e01-11eb-83d9-5683afd9357b.png)

**Comment by jakemac53** [comment]
Right sorry i forgot to mention but you need to run `pub get` or `pub upgrade` again after deleting the directory.

**Comment by shinayser** [comment]
I found the problem.

I was running the tests with a 'Dart tests' configuration on Intellij instead of a 'Flutter tests' run configuration.

Thanks for the help!
