### ISSUE TITLE
Hybrid testing is choking on Windows paths

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#1382]
A recent release of the `test` package seems to have broken hybrid tests on Windows. See [this failing Travis build](https://travis-ci.com/github/sass/dart-sass/jobs/443956550) for an example error:

```
00:00 +0 -1: [VM] test\cli\node\colon_args_test.dart: (setUpAll) [E]
  Invalid argument(s): Illegal character in path
  dart:core                                              new _Uri.file
  package:analyzer/src/string_source.dart 24:53          new StringSource
  package:analyzer/dart/analysis/utilities.dart 80:16    parseString
  package:test_core/src/runner/spawn_hybrid.dart 124:16  _languageVersionCommentFor
  ===== asynchronous gap ===========================
  package:test_core/src/runner/spawn_hybrid.dart 42:17   spawnHybridUri.<fn>
  package:test_core/src/runner/spawn_hybrid.dart 81:4    spawnHybridUri
  package:test_core/src/runner/runner_test.dart 74:13    RunnerTest.load.<fn>.<fn>
```

As far as I can tell, there's nothing unusual about the path on Travis other than being in Windows format.

Note that it's possible that this is an error with the `analyzer` package. I haven't been able to debug deeper because I don't have access to a Windows development machine locally.

**Comment by jakemac53** [comment]
The analyzer wasn't in the loop here at all before and I don't think it accepts windows file paths so it looks like we will need to convert it.
