### ISSUE TITLE
The testrunner should report the number of skipped tests and tests within skipped groups

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#14]
I saw that `skip_*` was deprecated. I think it is important to see if and how many tests are disabled, and it should be reported in the result output.

**Comment by nex3** [comment]
Agreed. Although `skip_test` is deprecated, we plan to add support some means of skipping tests within a test file, and that information should absolutely be surfaced.

**Comment by zoechi** [comment]
Good to hear :-)
