### ISSUE TITLE
Support the null-safe glob package

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#1400]
`test_core` currently depends on `glob ^1.0.0`, which doesn't support null-safety. This means that a package that uses both `test` and `glob` can't upgrade both to null-safe versions at once. Please release a new version that supports the latest `glob` (and any other null-safe dependency versions that have since been released).

**Comment by jakemac53** [comment]
Blocked on https://github.com/dart-lang/sdk/issues/44429

**Comment by jakemac53** [comment]
Actually, I can confidently say the package works so I will go ahead and update the constraint even though we can't resolve for it right now (we are using the latest version of glob internally and in the sdk). You will still be blocked on analyzer though.

**Comment by nex3** [comment]
What's the plan going forward for the analyzer? The [migration guide](https://dart.dev/null-safety/migration-guide) suggests that tests should be run in sound null-safety mode, but as I understand it that's not possible if `test` imports a null-unsafe `analyzer`. On the other hand, [this comment](https://github.com/dart-lang/sdk/issues/44290#issuecomment-733181379) suggests that `analyzer` won't be null-safe until the end of March at the earliest. Is the expectation that most users won't migrate to null safety in the short term?

**Comment by jakemac53** [comment]
`analyzer` is not imported by _user code_ in the test package - it is only used by the test runner. So you can write sound null safe tests today and run them, just the test runner won't be running in sound mode until analyzer is migrated.

**Comment by nex3** [comment]
Ah, got it. Are `dart test` and `pub run test` smart enough to know to invoke the test runner in unsound mode without an extra flag?

**Comment by jakemac53** [comment]
> Ah, got it. Are `dart test` and `pub run test` smart enough to know to invoke the test runner in unsound mode without an extra flag?

Yes, this works just like all the normal defaults. So since the entrypoint (bin/test.dart) is opted out it runs in unsound mode.

The test package does the same for your tests, it will run them in a mode determined by the language version of the test being ran.
