### ISSUE TITLE
Provide different exit code for failed and empty tests

### ISSUE THREAD

**Issue by Nikarous** [dart-lang/test#1418]
Hi,

when running tests with no tests defined flutter prints "No tests ran." message and exit with exit code 1. The same as when tests actually fails. This is misleading and I would like to ask you to provide different non-zero exit code for empty tests so user can process response in correct way.

**Comment by jakemac53** [comment]
This was an explicit decision, see the discussion here https://github.com/dart-lang/test/issues/764

**Comment by jakemac53** [comment]
Oh sorry I didn't fully understand the request, it might be reasonable to change the exit code to something other than 1, not sure how breaking that might be. cc @natebosch for thoughts.

**Comment by natebosch** [comment]
I think there is precedent for this. According to https://elinux.org/Test_Result_Codes`pytest` uses exit code 5 for this situation.

It's not a trivial change, we'll have to track extra information or abuse the global `exitCode=` and be careful not to overwrite it which would end up fairly brittle. I'd like to understand more about the value it would bring before we add the complexity and extra tests.

We'll also have to check whether `flutter test` is forwarding the exit code, or if it only distinguishes success/failure.

> so user can process response in correct way.

How would you handle this case differently? What are you writing which invokes the test runner and distinguishes between the error codes?

**Comment by Nikarous** [comment]
Hi, sorry for delayed answer.

We are developing flutter app right now and team still doesn't created all the tests (yeah I know but what will you do). Still they have a placeholder test files prepared. If I as a creator of a pipeline run flutter test on the directory it will fail because some tests are not implemented. I could filter such exit code if it would be different than "standard" fail and just log a warning as this is expected currently.

**Comment by Nikarous** [comment]
Also I really think that tests should not stop at first failure, instead run all tests and collect report.

**Comment by jakemac53** [comment]
> I as a creator of a pipeline run flutter test on the directory it will fail because some tests are not implemented.

I would recommend adding a single placeholder test in these files that passes?

> Also I really think that tests should not stop at first failure, instead run all tests and collect report.

At least in the default framework this is the behavior... I don't know if flutter_test does something different here?

**Comment by Nikarous** [comment]
> I would recommend adding a single placeholder test in these files that passes?

That is what we did at the end.

> At least in the default framework this is the behavior... I don't know if flutter_test does something different here?

It seems so but I will take it to Flutter team then I guess. Thank you for discussion and help!
