### ISSUE TITLE
Sharding doesn't seem to save much time

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/test#1452]
For the pub client we  manually split the test files into shards, before invoking the test-runner: https://github.com/dart-lang/pub/blob/master/.github/workflows/test.yaml.

Here is a run of the pub client tests using package test sharding (30 mins for a single pub run test shard):
https://github.com/athomas/pub/runs/1551758458?check_suite_focus=true (7 shards).

Here is a run using file-level shards: https://github.com/dart-lang/pub/runs/2055512496 ~ 5 minutes per shard.

While this is a lot less fine-grained it saves a lot of runtime, and seems to work fine in practice.

No matter how fine grained you split the tests you anyway do not have a guarantee that the shards will take an equal amount of time.

It seems that running with `--shard-index=M --total-shards=N` will load all tests before splitting them up.

This could be what takes too much time, proportional with the number of tests, independent of N.

**Comment by jakemac53** [comment]
I believe that the current sharding strategy does indeed need to load all test files. It also will run the entire `setUpAll`/`tearDownAll` for any test suite where it chooses to run a single test which often involves most of the work of the test.

I am not sure what the implications of changing the strategy would be on internal tests which is I believe what this feature was really designed for, but splitting along file boundaries might make sense.

There is also a larger issue here of not sharing any work between tests (each one is compiled in isolation from the other tests). There is some work to use frontend server to share the work across them, which  may resolve this issue somewhat.

**Comment by jakemac53** [comment]
Another idea is to actually have custom sharding strategy where you can mark each test file with `@Shard(<int>)`? We read that metadata without actually loading the tests so we could efficiently determine which tests to load/run in each shard. I think we would only want to support file level sharding but it would give fine grained control.

**Comment by natebosch** [comment]
We could consider adding a `--shard-by-file` flag to change the behavior of sharding without impacting existing usages, I don't know how much additional complexity that would entail. It would really only make sense to use it if your test files are mostly comparatively sized.

Another thing we could consider is some heuristics around letting you annotate with approximate test sizes, and allowing that to influence file level sharding decisions. That could be a follow-on if the use case arises.

**Comment by jakemac53** [comment]
@sigurdm can you try out the same thing you used to do but with the latest test package? We have made a change to test loading that should reduce the time to load tests dramatically.

**Comment by jakemac53** [comment]
I am going to close this under the assumption the changes we made do in fact resolve this issue (if a bit indirectly). Sharding should be a lot more beneficial than it previously was, as loading time should be dramatically improved.

**Comment by sigurdm** [comment]
Yes indeed! This seems to take an appropriate amount of time now.
Thanks!
