### ISSUE TITLE
Hybrid testing has a breaking change in null-safe mode

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#1469]
In a non-null-safe world, the following code worked fine:

```dart
import 'package:test/test.dart';

import 'test/ensure_npm_package.dart';

void main() {
  test("test", () async {
    var channel = spawnHybridCode("""
      import 'package:stream_channel/stream_channel.dart';

      void hybridMain(StreamChannel<Object> channel) {
        channel.sink.close();
      }
    """);
    await channel.stream.toList();
  });
}
```

But when null-safety is enabled, it produces this cryptic error:

```
00:02 +0 -1: test [E]                                                                                                                
  Top-level hybridMain() function must take one or two arguments.
  package:test_core/src/runner/hybrid_listener.dart 85:67  _sendError
  package:test_core/src/runner/hybrid_listener.dart 57:9   listen.<fn>.<fn>
  dart:async                                               runZoned
  package:test_core/src/runner/hybrid_listener.dart 40:5   listen.<fn>
  package:stack_trace                                      Chain.capture
  package:test_core/src/runner/hybrid_listener.dart 39:9   listen
  data:... 7:36                                            main
  
00:02 +0 -1: Some tests failed.
```

(Adding another parameter doesn't fix the issue.) I'm guessing the issue is that behind the scenes, this switched to checking the callback against `StreamChannel<Object?>`, but that's not clear to the user and it's not as backwards-compatible as it could be. Could you instead add checks for `StreamChannel<Object>` and cast the channel appropriately?

**Comment by jakemac53** [comment]
It looks like we check `if (main is Function(StreamChannel))`. We can change that to a `StreamChannel<Object>` check which allows any type of stream channel.

It does require an explicit cast later on, but we only want to do the cast in the case that it is a `StreamChannel<Object>`.

Something basically like this appears to do the trick, if a bit verbose:

```dart
      if (main is Function(StreamChannel)) {
        main(transformedChannel);
      } else if (main is Function(StreamChannel<Object>)) {
        main(transformedChannel.cast<Object>());
      } else if (main is Function(StreamChannel, Never)) {
        (main as dynamic)(transformedChannel, message);
      } else {
        assert(main is Function(StreamChannel<Object>, Never));
        main(transformedChannel.cast<Object>(), message);
      }
```

**Comment by jakemac53** [comment]
Hmm, this still doesn't allow things like `StreamChannel<int>` or other more specific types.

For that reason I am somewhat inclined to not do anything here, and enforce that a `StreamChannel<dynamic>` is used.

@natebosch thoughts?

**Comment by jakemac53** [comment]
(to be clear we should still improve the error message though)

**Comment by natebosch** [comment]
There isn't anything we can do about this other than to special case `Object` as a pretend top-type, but I suspect that is likely to cause friction in other places.

The "breaking change" that happened here is the language breaking change - `Object` is no longer a top type so it can no longer be used in this position. The `package:test` restriction has always been (since Dart 2 anyway) that the `StreamChannel` must be a `StreamChannel<⊤>`, we just weren't very explicit about it.

When you migrate the language version, you'll have to make sure the argument tales a `StreamChannel<⊤>` - @jakemac53 has a PR that should make this more clear and explicitly inform users to use `dynamic` or `Object?`.

**Comment by jakemac53** [comment]
Closing this with the updated the error message as the resolution.
