### ISSUE TITLE
Include line numbers in test reports 

### ISSUE THREAD

**Issue by fkorotkov** [dart-lang/test#1488]
It will be great if the machine readable test output could emit line numbers for tests. 

## Use case

With line numbers it's possible to provide better tooling support, including adding CI annotation for failed tests.

**Comment by jakemac53** [comment]
The JSON reporter does emit line numbers for tests, it appears in the first message for the test (with `"type": "testStart"`). You would need to remember that information (associate it with the test id) and you can later retrieve it when you see a test failure with that id.

The schema for the `Test` message which you get in that event is here https://github.com/dart-lang/test/blob/master/pkgs/test/doc/json_reporter.md#test (lots of more info in that doc as well).
