### ISSUE TITLE
Way to additionally save machine readable report

### ISSUE THREAD

**Issue by fkorotkov** [dart-lang/test#1494]
Right now it's only possible to either print human readable test report to stdout or print a machine readable stream of JSONs.

Problem here is that it's not possible to have both. My use case is CI. It will be great to print human readable output for humans in the CI UI but at the same time save the JSON report for CI to analyze (show annotations, record flaky tests, etc.).

**Comment by natebosch** [comment]
You can use the `--file-reporter` flag to write any reporter's output to a file.

`pub run test --file-reporter json:test_report.json` or `dart test --file-reporter json:test_report.json`.
