### ISSUE TITLE
test 1.17.1 fails on GitHub Actions / Windows

### ISSUE THREAD

**Issue by timsneath** [dart-lang/test#1506]
Compare:
https://github.com/timsneath/winmd/runs/2424326028?check_suite_focus=true (1.17.1)
with
https://github.com/timsneath/winmd/runs/2424365294?check_suite_focus=true (1.16.8)

The only difference between these two passes is the version of the test package. 

/cc @jakemac53

**Comment by jakemac53** [comment]
Note that you can refer to the old behavior with the `--use-data-isolate-strategy` flag until I can track this down

**Comment by jakemac53** [comment]
I also can't see the logs, not sure if I might need some special permissions for that? If you can paste the failure here that would help.

**Comment by timsneath** [comment]
Oh, I'm sorry -- thought the logs would be public.

Here -- this is the error:
https://gist.github.com/timsneath/11fb8891278a60824de2810515afed76#file-1-17-1-txt-L424

The same gist contains a run with test 1.16.8, which is successful. Key line looks like:

```
2021-04-24T00:32:04.5309203Z Invalid argument(s): Illegal character in path
2021-04-24T00:32:04.5310067Z #0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1642:11)
2021-04-24T00:32:04.5311118Z #1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1729:9)
2021-04-24T00:32:04.5311717Z #2      new _Uri.file (dart:core/uri.dart:1609:11)
```

**Comment by jakemac53** [comment]
> Oh, I'm sorry -- thought the logs would be public.

Weirdly I can see them now... I was on my phone maybe the GH app doesn't actually allow you to see logs or something 🤷‍♂️ .

In any case I have a fix coming soon I think here.

**Comment by timsneath** [comment]
Can confirm this fix worked for the above package:
https://github.com/timsneath/winmd/runs/2440189198?check_suite_focus=true (1.17.2)

Thanks!

**Comment by jakemac53** [comment]
Thanks for the reports and good details!
