### ISSUE TITLE
Add support for frameworks that wrap calls to `test`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/test#1514]
Currently with `flutter_test` tests the call to `test` happens in flutter SDK code, not in the user's test suite.

We collect a `Trace` at the call to `group` or `test` to know where the test was defined. We assume a hardcoded number of frames between the user code and the implementation. This doesn't work when a testing framework introduces extra frames in between.

https://github.com/dart-lang/test/blob/4f90091595ef4e82b883507947df204ee9a139fe/pkgs/test_api/lib/src/backend/declarer.dart#L204

See https://github.com/flutter/flutter-intellij/issues/5367

**Comment by jakemac53** [comment]
Note that we do populate information regarding the first frame in the actual test file. In the issue filed above you can see it was properly tracked and reported (the `root_*` fields).

Should we just suggest they navigate there if available?

**Comment by jakemac53** [comment]
I think we can close this right @natebosch ? The root_* fields I do believe resolve this for most cases.

**Comment by natebosch** [comment]
Yeah I think the root URI fields should be sufficient here - it's probably the best heuristic we can find. The only more reliably approach would be to allow wrapping frameworks to pass through the stack trace themselves - we could explore that if we need to but I'll close for now.
