### ISSUE TITLE
Race condition between compiling and spawning

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/test#1516]
In 
https://github.com/dart-lang/test/blob/4f90091595ef4e82b883507947df204ee9a139fe/pkgs/test_core/lib/src/runner/vm/test_compiler.dart#L97-L151

it compiles with a `Pool` of `1` which I'm guessing means only one at a time. So far so good.
It always compiles to the same file which isn't a problem per say as it's only running one at a time.
It then copies to another file that is also the same every time, and this file (uri) is returned. That's bad. Because when called from outside here:
https://github.com/dart-lang/test/blob/4f90091595ef4e82b883507947df204ee9a139fe/pkgs/test_core/lib/src/runner/vm/platform.dart#L144-L157
which can and does run multiple at the same time a new copy can be mid-way before the VM is finished spawning the isolate (and thus reading the file).

So the process can be this:
Queue spawn 1 (i.e. test 1)
Queue spawn 2 (i.e. test 2)
Compile 1 (i.e. test 1) and copy to `foo.dill` (from start to finish, we can only run 1 at a time).
Spawn 1 (i.e. test 1) asks the VM to spawn an isolate from `foo.dill`.
Compile 2 (i.e. test 2) and copy to `foo.dill`.
Spawn 2 (i.e. test 2) asks the VM to spawn an isolate from `foo.dill`.
Spawn 1 (i.e. test 1) finishes.
Spawn 2 (i.e. test 2) finishes.

So depending on how far the VM comes any of these things might happen:
* Spawn 1 (i.e. test 1) reads `foo.dill` before the file is overwritten (and spawn 2 (i.e. test 2) is read fine too) --- and everything is fine.
* Spawn 1 (i.e. test 1) reads parts of `foo.dill` before the file is overwritten, but then the file is overwritten, reading fails, the VM says it's not a dill file, proceeds to parse it as a dart file (that's not what we want). (This will probably give an error of some sort --- internally we've seen it cause the scanner to go into an infinite loop (which we'll fix)). Spawn 2 (i.e. test 2) will read fine and be happy.
* Spawn 1 (i.e. test 1) reads nothing of `foo.dill` before the file is overwritten. Ends up reading `foo.dill` *after*, i.e. it actually reads test 2. Spawn 2 (i.e. test 2) reads fine and is happy. We end up executing the same test twice. We probably won't be notified, we will probably claim to have run both test 1 and test 2 while we have in fact run test 2 twice.

One solution is to copy to a different file each time (something like `final kernelReadyToRun = await outputFile.copy('${tempFile.path}_${compileNumber++}.dill');` with `int compileNumber = 0;` as an instance field).

**Comment by jakemac53** [comment]
Thanks for the investigation @jensjoha
