### ISSUE TITLE
dart run test returns 1 when no tests are run.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/test#1518]
Normally dart run test returns an exit code of 0 when all test succeed and 1 when any tests fail.

The problem I'm having is that if you use the --exclude-tags option and it results in no tests being run then dart run tests returns 1.

I believe that if no tests are run then it should still return 0, otherwise you can't reliably determine if any tests failed.

An exit code of 1 should be reserved for when at least one test fails.

**Comment by jakemac53** [comment]
This is working as intended - see the discussion here https://github.com/dart-lang/test/issues/764.

There was another discussion about using a different exit code so you could distinguish between these failure modes here https://github.com/dart-lang/test/issues/1418.
