### ISSUE TITLE
Add a reporter that suppresses stdout/stderr output from tests

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/test#1521]
This is useful for running tests that are expected to fail, e.g. to make sure a test harness fails when it's expected to fail. When output from such tests is printed to CI logs, it confuses people.

Currently, due to https://github.com/dart-lang/test/blob/e5b2739ed8dedd8f20c8ad033917ed07d07c7cb4/pkgs/test_core/lib/src/runner.dart#L89, you can only _add_ a file reporter but not replace the standard reporter.

The docs in https://github.com/dart-lang/test/blob/master/pkgs/test/doc/json_reporter.md should also be updated to not say "instead of stdout". It would be more accurate to say "in addition to the reporter specified via `--reporter`".

**Comment by natebosch** [comment]
`--reporter silent`  was added in #2093 and should work for this use case.
