### ISSUE TITLE
Links to function docs from README are all broken

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/test#1526]
The links to Dart Test API functions seem to be all broken in the README (both from GitHub and from pub.dev).

For example, in the first section, "Writing tests", the first sentence says:

```
Tests are specified using the top-level [`test()`] function, and test assertions
are made using [`expect()`]:

[`test()`]: https://pub.dev/documentation/test_core/latest/test_core/test.html
[`expect()`]: https://pub.dev/documentation/test_api/latest/test_api/expect.html
```

The correct links seem to be now:

* `test()`: https://pub.dev/documentation/test_core/latest/test_core.scaffolding/test.html
* `expect()`: https://pub.dev/documentation/test_api/latest/expect/expect.html

**Comment by jakemac53** [comment]
cc @natebosch I wonder if since these are now exported and not wrapped we no longer get docs for them from dartdoc?

**Comment by natebosch** [comment]
I filed https://github.com/dart-lang/dartdoc/issues/2663

We can probably just update the links in the short term, but in the longer term it would be nice if the "canonical" place to import them is also a working canonical link to the docs.

**Comment by jakemac53** [comment]
Ah ya I see its just old links that are broken, the apis are still documented and just link directly to the place its exported from. A redirect seems like it would solve that problem if feasible.

**Comment by natebosch** [comment]
FIxed by https://github.com/dart-lang/test/pull/1527
