### ISSUE TITLE
json_reporter.md `AllSuitesEvent` class should extend `Event`

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/test#1536]
I am auto-generating a Dart Model after extracting the class definitions documented in [json_reporter.md](https://github.com/dart-lang/test/blob/master/pkgs/test/doc/json_reporter.md).

The auto-generated code does not compile when I try to return `Event` from a parse function because `AllSuitesEvent` does not extend `Event`.

Could you please fix that so that the model is more or less valid?

**Comment by jakemac53** [comment]
It looks like it doesn't extend `Event` because it doesn't have a `time` field. I can see if we could add that field though.
