### ISSUE TITLE
json_reporter.md does not show correct nullable fields

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/test#1537]
When running my Dart tests, I see the `test` event looks like this:

```json
{"test":{"id":1,"name":"loading test/test_report_parser_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":3}
```

Notice how `line`, `column` and `url` are `null`.

But the types are not marked as nullable in the `Test` class definition in [json_reporter.md](https://github.com/dart-lang/test/blob/master/pkgs/test/doc/json_reporter.md), despite the comments saying they can be `null`.

```dart
class Test {
  // ...

  // The (1-based) line on which the test was defined, or `null`.
  int line;

  // The (1-based) column on which the test was defined, or `null`.
  int column;

  // The URL for the file in which the test was defined, or `null`.
  String url;
```

The same fields are also not marked as nullable in `Group` as well.

```dart
class Group {
  // ...

  // The ID of the group's parent group, unless it's the root group.
  int? parentID;

  // The number of tests (recursively) within this group.
  int testCount;

  // The (1-based) line on which the group was defined, or `null`.
  int line;

  // The (1-based) column on which the group was defined, or `null`.
  int column;

  // The URL for the file in which the group was defined, or `null`.
  String url;

  // This field is deprecated and should not be used.
  Metadata metadata;
}
```

Notice above that at least  `parentId` was properly marked as being nullable, so the fact that the other nullable fields are not marked as such is probably an oversight.

Could you please mark those nullable fields in `Test` and `Group` as nullable?

**Comment by renatoathaydes** [comment]
BTW Just noticed that `root_line` should also be `null`.

**Comment by jakemac53** [comment]
Ya I think this wasn't updated when we migrated to null safety, we should update the docs.

**Comment by renatoathaydes** [comment]
Thank you. Here's the auto-generated Dart Model I extracted from the docs: https://github.com/renatoathaydes/test_report_parser.dart/blob/master/lib/src/model.g.dart

**Comment by jakemac53** [comment]
Note that the `time` field on the `AllSuitesEvent` is actually null in the latest released version, it will be non-null in the next release. I do plan to push out a release here soon though I just wanted to let the change bake for a day in our internal codebase before releasing.

**Comment by renatoathaydes** [comment]
Ah ok, should be alright for now to use the previous version if that goes wrong...

**Comment by jakemac53** [comment]
Ya, I did just release it though.

**Comment by jakemac53** [comment]
But note that flutter users won't get this version for a long while, at least until the next stable flutter release, because flutter_test pins test_api to 0.4.0 and these packages require 0.4.1.
