### ISSUE TITLE
Add ability to turn off shuffling of tests on a per-suite or per group basis.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/test#1539]
Currently the shuffling of test order as implemented for https://github.com/dart-lang/test/issues/1124 defines the shuffling seed for the entire run.

Flutter would like to transition our framework tests to use randomized ordering for the tests, but since there are a large number of failures from dependent tests when we turn this on, previous attempts to make this transition have failed because the PRs are too huge, and merge conflicts occur too frequently to make landing the PR feasible.

Therefore, we'd like to migrate our tests to shuffled order one file at a time, by turning on the flag globally, disabling shuffle for each of the files that have failures, and then we can then come back at our leisure and fix each file, and turn on shuffle for that file until they're all complete.

I *think* the randomization happens per file or per group (it's not entirely clear to me from looking at the code and docs), but if that's not the case, then this would have to be implemented by running the tests in two groups (one in original order, and one shuffled).

cc @dnfield @jakemac53

**Comment by dnfield** [comment]
One way we could do this without changes it to use tags. We could start tagging tests that we know are safe to run in random order with some special tag, and just increase that (or vice versa, tag all existing tests and start removing the tag to burn down).

I _think_ you can do `@Tag` on a per file basis. https://pub.dev/packages/test#tagging-tests

**Comment by jakemac53** [comment]
Yes tags should be a good way to do this today.

**Comment by gspencergoog** [comment]
OK, it looks like that works, but two things might be confusing:

I used this config file:

```yaml
tags:
  no-shuffle:
    test-randomize-ordering-seed: 0
  shuffle:
    test-randomize-ordering-seed: 123
```

And ran it with `flutter test --test-randomize-ordering-seed=123`, and files that had `@Tags(['no-shuffle'])` in them that would normally fail with that seed would then pass, which is my intent.

But, (confusing thing number one) when I replaced the "no-shuffle" with "shuffle" in one of the tests that would normally fail, and did not specify a seed on the command line, those tagged tests continued to pass, presumably because they still weren't being reordered. Same thing if I change the 0 to 123 for `no-shuffle` in the config file: tagged tests succeed, and untagged ones fail, regardless of the value of the argument. Commenting out the argument in the yaml file makes tagged and untagged tests fail again when the command line arg is given.

And (confusing thing number two), while this is hardly surprising, it prints `Shuffling test order with --test-randomize-ordering-seed=123` at the start of testing, but there's no way to see if the seed is in effect for the particular test suite. I don't think this is a big deal, but it might be misleading.

**Comment by jakemac53** [comment]
I don't think that `test-randomize-ordering-seed` is actually configurable via the `dart_test.yml` (that doesn't make a lot of sense to do because then it isn't random on each run any more). If it seemed to work that was probably just a coincidence.

What you should do instead to work with tags is to make two separate invocations of the test runner, one that only runs the tests with a certain tag and one that runs all the tests except those with a certain tag:

```
flutter test -x shuffle
flutter test -t shuffle --test-randomize-ordering-seed=random
```

**Comment by gspencergoog** [comment]
Well, regardless of whether it was meant to be set that way, it does work.  I agree it's pretty useless to set it to a value, but it is useful to be able to set it to "0" or "random", as in this case.

**Comment by jakemac53** [comment]
> Well, regardless of whether it was meant to be set that way, it does work.

Are you sure? I wasn't sure what was actually intended so I looked in the code here https://github.com/dart-lang/test/blob/dc6c06418466ac6f2d42e5b2e83752ab484a4bbf/pkgs/test_core/lib/src/runner/configuration/load.dart and I don't see it reading this configuration... it's certainly possible I am missing something though.

**Comment by gspencergoog** [comment]
All I know is that when I comment out `test-randomize-ordering-seed: 0` in the config file and pass the seed on the command line, my tests consistently fail.  When I uncomment it, then tagged tests consistently succeed, regardless of whether I supply a seed on the command line or not. Untagged tests fail with a command line seed, and pass without one, and are unaffected by the existence of the config line.

**Comment by natebosch** [comment]
We appear to have a bug where an invalid configuration resets things in a suite to the default or something like that. Using the configuration `test-randomize-ordering-seed: 0` has the same behavior as `bogus-key: bogus`.

**Comment by natebosch** [comment]
Looking again, the configuration doesn't need to be invalid, just non-empty. We have a bug where any tag level configuration disables shuffling for all suites with that tag.

**Comment by natebosch** [comment]
@gspencergoog - I just published a version that fixes the bug you were seeing where any config for a tag would disable shuffling.

Can you confirm if the two run approach suggestion will work for you?

```
flutter test -x shuffle
flutter test -t shuffle --test-randomize-ordering-seed=random
```

**Comment by gspencergoog** [comment]
Yes, that will work fine.  I mean, I liked the simplicity of not having to document it for folks when they run locally, but it works fine for the CI case.

**Comment by natebosch** [comment]
Sounds good. I'll close this for now as not planned. If we find out more use cases for this behavior we can revisit it.

**Comment by gspencergoog** [comment]
@natebosch Actually, after implementing this in https://github.com/flutter/flutter/pull/85159, I would still like to request the ability to turn on and off shuffle based on a tag. The lack of that feature, combined with the missing feature in https://github.com/dart-lang/test/issues/1546 means that the implementation is complex (have to parse test output to know if it failed), and explaining how to run it locally is also complex.

If I could just specify that a certain tag had a seed of zero, then I wouldn't need to modify our test runner at all, could just do it in the configuration, and wouldn't need to explain the new way to run the tests.

**Comment by gspencergoog** [comment]
@natebosch So I had to revert my change https://github.com/flutter/flutter/pull/85159 to randomize our tests because it seems that _not_ running tests that don't match a filter seems to take almost as long as running them, which causes our tests to take 40-100%+ longer to run (since I'm now invoking `flutter test` twice for each tested directory), and so that made test timeouts are quite frequent.

Having the ability to just run things once, where the random seed option was set differently for different tags would probably solve that problem.

**Comment by dnfield** [comment]
Can we build the tests once and then run them with the right tagging arguments?

**Comment by gspencergoog** [comment]
For example:

```
# With inclusion tag filter:
packages/flutter % time flutter test -t no-shuffle --track-widget-creation --null-assertions --sound-null-safety test/widgets
01:11 +294 ~1: All tests passed!                                                                                                   

real	1m13.871s
user	3m46.871s
sys	2m39.498s
# With exclusion tag filter:
packages/flutter % time flutter test -x no-shuffle --test-randomize-ordering-seed=20210630 --track-widget-creation --null-assertions --sound-null-safety test/widgets
Shuffling test order with --test-randomize-ordering-seed=20210630
01:26 +3088 ~3: All tests passed!                                                                                                  

real	1m28.834s
user	7m53.652s
# Without tag filters:
packages/flutter % time flutter test  --track-widget-creation --null-assertions --sound-null-safety test/widgets
01:28 +3382 ~4: All tests passed!                                                                                                  

real	1m30.431s
user	8m11.767s
sys	3m10.840s
```

**Comment by gspencergoog** [comment]
> Can we build the tests once and then run them with the right tagging arguments?

Isn't that what would happen if we allowed this kind of config?:

```
tags:
  no-shuffle:
    test-randomize-ordering-seed: 0
  shuffle:
```

And then specify `--test-randomize-ordering-seed=20210630` on the command line?

**Comment by jakemac53** [comment]
Ya test loading times do often dominate the overall test time, especially when you have large numbers of test suites (files) that only contain unit tests (so the tests themselves run very quickly).

Re-opened this issue to track some other solution that won't require multiple runs. 

> Isn't that what would happen if we allowed this kind of config?:

In general I believe the `dart_test.yml` file has the lowest precedence when merging configs. Basically it is intended to change the defaults. So providing a different config on the command line would override it, afaik. I need to confirm that is also the case for tag level configuration though.

I also have general concerns about exposing this argument specifically, through any kind of static config. The only valid thing to configure statically is either "0" or "random" - in other words enabling or disabling test randomization entirely. I think we probably would want some more direct configuration to explicitly enable or disable test randomization as a whole.

**Comment by gspencergoog** [comment]
It seems like it would be an easy change to add a configuration-file-only option that turns on or off the shuffling. Then if that is set, it can override the command line option.

**Comment by jakemac53** [comment]
The configuration for the test runner is unfortunately very complex, as far as configuration goes at least haha. But ya it is manageable, just a lot harder than you would think :).

**Comment by gspencergoog** [comment]
Sorry, I didn't mean to comment on how hard it would be to implement, just that it seems conceptually to be an easy to understand change in the usage. I did look at the code, and indeed, it is complex. :-)

**Comment by jakemac53** [comment]
@natebosch I think I will go with a new option `allowTestRandomization` on the `SuiteConfiguration` class. It will default to `true`, and if set to `false` then the suite will never use test randomization. Does that sound good to you?

**Comment by natebosch** [comment]
> @natebosch I think I will go with a new option `allowTestRandomization` on the `SuiteConfiguration` class. It will default to `true`, and if set to `false` then the suite will never use test randomization. Does that sound good to you?
> 
> I can start with just allowing this to be configured in the `dart_test.yml`, but we could also add a metadata annotation for it.

SGTM
