### ISSUE TITLE
Link to configuration docs are broken

### ISSUE THREAD

**Issue by RatakondalaArun** [dart-lang/test#1555]
https://github.com/dart-lang/test/blob/52b9babb527073ce9f329215e5eafc63720a8af7/pkgs/test_core/lib/scaffolding.dart#L105

maybe it should point to https://github.com/dart-lang/test/blob/master/pkgs/test/doc/configuration.md

Can I raise a PR?

**Comment by jakemac53** [comment]
Yes a PR would happily be accepted for this 👍
