### ISSUE TITLE
.gitignore to ignore IDE folders

### ISSUE THREAD

**Issue by asashour** [dart-lang/test#1556]
On using IntelliJ IDEA, I would expect that `.idea` folder is excluded in `.gitignore`.

I guess the same applies for other IDEs as well, and I wonder which one the team uses and why it is not in `.gitignore`.

**Comment by natebosch** [comment]
> I wonder which one the team uses

The team uses a wide variety - the editors of this repo in particular mostly use VSCode or vim.

> and why it is not in `.gitignore`.

File ignores that are particular to editors and their choice of editors stay in their own config. The project `.gitignore` ignores files related to the specific project.

I'd recommend adding `.idea/` in a global ignore file so you don't need to worry about having it in every project you work on.
https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer
