### ISSUE TITLE
test_api 0.4.4 is incompatible with Flutter

### ISSUE THREAD

**Issue by jpnurmi** [dart-lang/test#1591]
Running `flutter test` fails for any Dart package that resolves its `test_api` dependency to 0.4.4. The Flutter SDK itself depends on 0.4.3, but pure Dart packages can pick 0.4.4.

When tests are run with the Flutter tool, the deserialized metadata message in `RemoteListener.start()` does not contain the `allowDuplicateTestNames` field. Thus, a null value is casted as non-nullable bool:
https://github.com/dart-lang/test/blob/master/pkgs/test_api/lib/src/backend/remote_listener.dart#L110, added in commit https://github.com/dart-lang/test/commit/4de96a734cf466b6d706b2810ed3f623aa054bae.

#### Dart project
- run `dart create -t package-simple foo`
- run `flutter test`

  Result:
  ```
  $ flutter test
  Running "flutter pub get" in foo...                          3.1s
  00:00 +0 -1: loading /path/to/test/foo_test.dart [E]                                                                                               
    Failed to load "/path/to/test/foo_test.dart": type 'Null' is not a subtype of type 'bool' in type cast
    package:test_api  RemoteListener.start.<fn>.<fn>
    
  00:00 +0 -1: Some tests failed.                      
  ```

#### Flutter project
- run `flutter create foo`
- add to `pubspec.yaml`:
    ```yaml
    dependency_overrides:
      test_api: 0.4.4
    ```
- run `flutter test`

  Result:
  ```
  $ flutter test
  Warning: You are using these overridden dependencies:
  ! test_api 0.4.4
  Running "flutter pub get" in foo...                      833ms
  00:05 +0 -1: loading /path/to/test/widget_test.dart [E]                                                                                                
    Failed to load "/path/to/test/widget_test.dart": type 'Null' is not a subtype of type 'bool' in type cast
    package:test_api  RemoteListener.start.<fn>.<fn>
    
  00:05 +0 -1: Some tests failed. 
  ```

Why this matters is that for multi-package projects, there's often a mixture of Flutter and Dart packages. A convenient way to run all tests is to use a tool like Melos and let it execute `flutter test` in all packages. Furthermore, unlike `dart test`, `flutter test --coverage` is also conveniently able to collect code coverage for pure Dart packages too.

**Comment by jakemac53** [comment]
Interesting, I wasn't aware it was even possible to use `flutter test` on a Dart package. This isn't a supported use case that we can guarantee will generally work, since the version constraints that keep it working are enforced by the `flutter_test` package. So I fully expect this to be broken again in the future, just as an FYI. 

As far as this particular fix though I think we can accept it, as it is pretty harmless.

**Comment by natebosch** [comment]
Adding a dependency on `flutter_test` seems like the most straightforward way to make sure that the `flutter test` command works.

**Comment by jakemac53** [comment]
> Adding a dependency on `flutter_test` seems like the most straightforward way to make sure that the `flutter test` command works.

I don't think that you can add this dependency in a dart project?

**Comment by natebosch** [comment]
> I don't think that you can add this dependency in a dart project?

Not if you want to `dart pub get`, but if you are using `flutter test` you may as well use `flutter pub get`.

**Comment by jakemac53** [comment]
> Not if you want to `dart pub get`, but if you are using `flutter test` you may as well use `flutter pub get`.

Oh interesting that does work, ya that seems like the best option then. Do you think we should still do https://github.com/dart-lang/test/pull/1592 at all? I am leaning towards not given this fix.

**Comment by jakemac53** [comment]
We should probably file an issue on flutter to check for a `flutter_test` dependency instead?

**Comment by natebosch** [comment]
> Do you think we should still do #1592 at all? I am leaning towards not given this fix.

I would be fine either way. I think striving for backwards compatibility in `test_api` as much as possible is a good thing in general, since we still have leaky abstractions and external dependencies on the details.

**Comment by jakemac53** [comment]
Ok, I will go ahead and roll with it. I do think we should file an issue on `flutter test` to check for the dep though, as its all but guaranteed similar issues will happen at some point with no version constraints taking effect.

**Comment by jakemac53** [comment]
Packages are published @jpnurmi

**Comment by jakemac53** [comment]
Filed https://github.com/flutter/flutter/issues/91107 for the flutter team
