### ISSUE TITLE
Live Test names are not visible against black terminal backgrounds

### ISSUE THREAD

**Issue by jagthebeetle** [dart-lang/test#1596]
In test_core/lib/src/runner/reporter/expanded.dart

running tests are printed with ANSI SGR styling of:

$_bold$_gray$name$_noColor

bold gray resolves to: [1m[1;30m

On most of my (default) dark terminal themes, this is pretty hard to read, since it's basically just bold black text. Could it just be bold, or an explicit foreground set so I don't have to override my ANSI codes?

**Comment by jakemac53** [comment]
@natebosch wdyt about teal or some other brighter color?

**Comment by jakemac53** [comment]
In general we don't want to emphasize these more than other lines (they are probably less important if anything). So I don't think we want to bold them, but we could look at other styling.

We could look at setting the background color also -but we probably would want to do that for _all_ lines if we did, and that gets a bit weird looking.
