### ISSUE TITLE
Add a more precise way to start multiple specific tests at the same time

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/test#1598]
Hello!   Some context:

I am working on a custom test renderer and I was trying to implement "execute only failed tests from the previous run" among other things.
I was able to get the list of failing tests, with their suites and names/ids. But I haven't found a way to start them all _at the same time_ while skipping the rest

I was innocently thinking that we could do:

```sh
dart test test/foo_test.dart --name "a" test/bar_test.dart --name "b"
```

to run the test "a" from `foo_test` and "b" from `bar_test`, but this isn't the case because of various issues:

- `--name` filters aren't specific to a test file.
- When multiple `--name` queries are defined, they perform an AND filter instead of an OR filter
- There doesn't seem to be a way to have a strict name filter (as in not perform a "contains" comparison but an ==).
  So `--name "hello"` will run both `test('hello', ...)` and `test('hello world', ...)`

As such I think thinking: Would it be possible to add a more specific filter?  

If updating `--name` to behave as described isn't possible due to being a breaking change, what about something like:   
`dart test --test file=test/foo_test.dart name="a" --test file="test/bar_test.dart name="b"`

I'd be more than happy to raise a pull request about this.

**Comment by jakemac53** [comment]
> Mainly that it's hard to get right. Characters need to be URI escaped and the vast majority of test cases will have spaces. We could instead say we aren't using a URI fragment, but just a `#` followed by the name and then maybe users only need to worry about using quotes to make sure the args get split up right.

We would just be talking about a small number of tools (not package:test users) using this option. So I don't think its much of an issue to require the fragment be properly encoded.

> In any case, my intuition is that round tripping a test ID which we own 100% may be less brittle than defining a scheme that needs to be maintained backwards-compatible for a long time.

We can't make a stable test ID afaik though in the face of new tests being added and such, unless we also base it off the name. So I don't really see what it buys us? But we could give the user a URL safe ID in the json protocol for each test, and then require them to pass that for the fragment instead?

**Comment by DanTup** [comment]
I'd be interested in something like this too. VS Code's new test runner lets a user multi-select a bunch of tests and run them, and today I had to make this split them by file and run multiple debug sessions to pass the names - which is a lot slower than running them all in a single process (not to mention clumsy for some other reasons, like if the user hits Stop on the debug toolbar it only stops one of them).

VS Code currently only uses regexes, though there's been talk of supporting line/col in another issue - if something was added, it could be nice to support both of those (since in the short-term, VS Code will likely continue to use names, but would probably migrate to line/col).

On the subject of an interactive/server process, it may be worth keeping an eye on https://github.com/microsoft/vscode/issues/134455. VS Code has a new test runner and it seems to me like it would make a nice "Test Adapter Protocol" similar to LSP/DAP that could be run out-of-process and communicated with via JSON. LSP and DAP both have gotten good traction, so a common interface that other languages/editors might use could be a better option than something completely custom.

**Comment by rrousselGit** [comment]
On that note, is there anything I can do in the short term?

I originally wanted to fork `test` to add custom features, but I quickly realised that it'd basically require forking Flutter too

**Comment by rrousselGit** [comment]
There is a precedent though:

```sh
dart pub global active --source path <path-to-source>
```

where `--source` takes two arguments and is based on the order

**Comment by jakemac53** [comment]
Fwiw I am also super confused by the way that `--source` works for `pub global activate` lol. Their implementation also wouldn't work for multiple options - the `args` package does support trailing arbitrary arguments at the very end of the list, which is how they deal with it. But that only works for a single option like that, and it has to be the final option supplied as well.

**Comment by rrousselGit** [comment]
Oh interesting, I didn't know we could do `Uri.parse('<file path>#name')`

But if we encode the test name, wouldn't this hinder the ability to use regex as name as @DanTup wanted?

**Comment by DanTup** [comment]
> It looks like this would also allow passing the same query string multiple times

I presume you mean so we can do:

```
dart test test/my_test.dart?name=foo&name=bar
```

? It might be a bit strange for cases where there's some relationship between them:

```
# Which are ANDs and which ORs?
dart test test/my_test.dart?line=1&col=1  # expect and?
dart test test/my_test.dart?name=foo&name=bar # expect or?
```

Although if the rules are clear and we could also pass them as separate URIs if it didn't fit the needs, sgtm :-)

**Comment by jakemac53** [comment]
> If we're going for lines+col, "full_name" & co, do we want to support other filters too? Like tags

Maybe, depending on implementation effort to also support that? I think initially it would be good to just support the specific things we need right now though. Using the query string gives us a good way to extend support for tags etc later.

**Comment by rrousselGit** [comment]
> TODO: Should we allow multiple name query parameters?

If they perform an `and`, sure, as this is how `--name` behaves. If we're expecting an `or`, that'd be confusing I think

**Comment by jakemac53** [comment]
> So that if you specify --exact-test, the command fails if you specify files or other options

Note that my updated proposal removes this argument - it just adds query parameter support to the existing file path arguments which are just `rest` arguments. 

I think we do want to support the other global arguments still, it shouldn't add much complexity (actually may even be simpler in some ways).

**Comment by rrousselGit** [comment]
Oh, I didn't realise that the syntax changed.

I see, then `dart test <path>?query` sounds good to me. That's closer to what I originally wanted

**Comment by jakemac53** [comment]
> Would this be considered as a breaking change though? As file paths could technically contain `?`

That should be uncommon enough for us to not consider it breaking? Granted people do weird things...but that would be very weird, especially in a dart file path.

**Comment by natebosch** [comment]
I do think if you use this approach the full argument should be URI safe, not just the query string. It would mean on windows you'd need to use `/` instead of `\`, but it would cut down surface area for bugs and misinterpretation. If there is any weirdness in the path like a `?`, it can be handled by the user by URI encoding the path components as well.

**Comment by natebosch** [comment]
> we could roll it into the same release imo.

That's fine if we can get them both done, but I wouldn't gate one on the other.

**Comment by jakemac53** [comment]
@rrousselGit were you still interested in taking a shot at implementing this?

**Comment by jakemac53** [comment]
> It might be a little bit funky to pass the extra information along, you might want to merge it into the SuiteConfiguration object that is created for each suite (`_config.suiteDefaults`).

Ya it looks like you could just use the existing `patterns` field (create an exact match regex for full_name). Create a new suite config with just that option specified and merge it with the `_config.suiteDefaults`. That would automatically give us the merging of global + individual options we want also.

**Comment by rrousselGit** [comment]
Coming back to this, I may be missing something but it seems like `dart test test/my_test.dart?name=foo` causes problems with zsh

We have to do:

```sh
dart test "test/my_test.dart?name=foo"
```
