### ISSUE TITLE
Browser launch timeout needs to be increased or customizable

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/test#1610]
When running from a CI server the default 30s of timeout to have the browser connected is too low!

Note that CI servers are not powerful, usually are running multiple tasks, since they are a shared resource.

https://github.com/dart-lang/test/blob/497900fd3349a5f53a023922413655d8e0883f73/pkgs/test/lib/src/runner/browser/browser_manager.dart#L130

**Comment by kevmoo** [comment]
Maybe also https://github.com/dart-lang/test/issues/1616 ?
