### ISSUE TITLE
Internet Explorer tests time out on windows

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#1614]

**Comment by natebosch** [comment]
@sigmundch - has dart2js dropped support for IE?

I wonder if we should just remove support for IE from the test runner. Would anyone even notice?

**Comment by gmpassos** [comment]
I don't think that anyone should incentivize the use IE, ate least since 2016.

I hope this won't break Edge support.

**Comment by jakemac53** [comment]
We probably could just drop IE support. Edge should continue to work fine.

**Comment by sigmundch** [comment]
Agree, feel free to drop IE coverage. We dropped support for IE two years ago now, since Dart 2.14. See https://github.com/dart-lang/sdk/issues/46545
