### ISSUE TITLE
Often getting `Test timed out after 12 minutes`

### ISSUE THREAD

**Issue by marandaneto** [dart-lang/test#1622]
TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 333:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1420:47                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 331:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 287:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1428:13                      _rootRun
  dart:async/zone.dart 1328:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 286:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 395:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 426:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 192:12      _RawReceivePortImpl._handleMessage

eg https://github.com/getsentry/sentry-dart/runs/3994055172?check_suite_focus=true

**Comment by marandaneto** [comment]
The very same issue happens on windows-latest as well now: https://github.com/getsentry/sentry-dart/runs/5646627135?check_suite_focus=true

**Comment by natebosch** [comment]
The last change we had in this area was to add retry, but that was on a version of the package release 2022-03-16, and the latest comments on this issue suggest the problem was still happening.
https://github.com/dart-lang/test/pull/1676

It looks like the output was also a little different.

I don't think we've been seeing chrome issues in our github action runs lately.

**Comment by natebosch** [comment]
Looking at the error message and stack trace, I wonder if the problem isn't within the test bodies.

Is it possible there is a flaky bug with an `expectAsync` callback that never gets called, or an `expect(someFuture, completes)` where the Future  never completes or something along those lines?

I don't think I've seen other reports of a timeout _within_ the running tests, as opposed to a timeout of the infrastructure talking to the browser.

**Comment by marandaneto** [comment]
We've debugged and tried to reproduce it plenty of times, but we could not find a bug in the tests or reproduce it.
Also, happening only on specific OSs was another indication that could be a bug in the test infrastructure.

We don't use `expectAsync` at all but `expect` with futures, yes.

Right now we are running tests on `chrome` only using Linux, never experienced this issue again.

**Comment by natebosch** [comment]
I'm not sure how to get more output from chrome to get a better idea of what is happening.

We are running with flags that I would expect to give us verbose output on `stdout`

https://github.com/dart-lang/test/blob/0e5c028d239b8801581852aa31a19ecc9f64f500/pkgs/test/lib/src/runner/browser/chrome.dart#L52-L53

But the only message I've been able to see is the "DevTools listenening" message.

We might need to look in to always attaching to devtools and forwarding messages or errors from there?

**Comment by marandaneto** [comment]
Yeah not sure, currently using `dart test -p chrome --test-randomize-ordering-seed=random --chain-stack-traces`

> Info: Compiling with sound null safety.
>   Compiled 11,865,262 characters Dart to 1,271,437 characters JavaScript in 8.70 seconds using 373.520 MB of memory
>   Dart file /C:/Users/runneradmin/AppData/Local/Temp/dart_test_2be0ef33/runInBrowser.dart compiled to JavaScript: /C:/Users/runneradmin/AppData/Local/Temp/dart_test_6b2d06a5/test_4ef4e285/client_report_recorder_test.dart.browser_test.dart.js
>   
>   Failed to load "test\client_reports\client_report_recorder_test.dart":
>   Timed out waiting for Chrome to connect.
>   Browser output: 
>   DevTools listening on ws://127.0.0.1:56[75](https://github.com/getsentry/sentry-dart/actions/runs/4436266334/jobs/7784480420#step:4:76)8/devtools/browser/3bc493ec-e9f3-4602-b6c1-499d5c165109
>   
>   package:test/src/runner/browser/browser_manager.dart 143:9  BrowserManager._start.<fn>
>   dart:async/zone.dart 1390:47                                _rootRun
>   dart:async/zone.dart 1300:19                                _CustomZone.run
>   dart:async/future_impl.dart 8[82](https://github.com/getsentry/sentry-dart/actions/runs/4436266334/jobs/7784480420#step:4:83):34                          Future.timeout.<fn>
>   dart:async/zone.dart 1390:47                                _rootRun
>   dart:async/zone.dart 1300:19                                _CustomZone.run
>   dart:async/zone.dart 1208:7                                 _CustomZone.runGuarded
>   dart:async/zone.dart 1248:23                                _CustomZone.bindCallbackGuarded.<fn>
>   dart:async/zone.dart 1398:13                                _rootRun
>   dart:async/zone.dart 1300:19                                _CustomZone.run
>   dart:async/zone.dart 1232:23                                _CustomZone.bindCallback.<fn>
>   dart:async-patch/timer_patch.dart 18:15                     Timer._createTimer.<fn>
>   dart:isolate-patch/timer_impl.dart 398:19                   _Timer._runTimers
>   dart:isolate-patch/timer_impl.dart 429:5                    _Timer._handleMessage
>   dart:isolate-patch/isolate_patch.dart 1[89](https://github.com/getsentry/sentry-dart/actions/runs/4436266334/jobs/7784480420#step:4:90):12                _RawReceivePort._handleMessage

**Comment by natebosch** [comment]
We've made some changes to the browser startup process which didn't seem to make a difference with the flakes. See discussion at #1104 

In the end a chrome update seems to have fixed it.  It still this reproing for you?
