### ISSUE TITLE
Add a flag to ignore timeouts to avoid tests accidentally timing out if debugging/stepping

### ISSUE THREAD

**Issue by DanTup** [dart-lang/test#1634]
This came up at https://github.com/Dart-Code/Dart-Code/issues/3687. When debugging tests in an IDE, you may accidentally trigger test timeouts because you were paused for some part of the test execution.

For now we're discussing having some option to have `--timeout 1hr` or similar when debugging, however there are some drawbacks to this:

1. It only sets the _default_ timeout, so doesn't override any with explicit timeouts set (that are not Factors)
2. The arbitrary value of 1h (or whatever) seems a little odd given the real goal is to disable them

It could be nice if there was a `--ignore-timeouts` flag or similar, which just entirely disabled timeouts for all tests.

**Comment by jakemac53** [comment]
Ya this is a common issue I have faced, seems reasonable

**Comment by DanTup** [comment]
Awesome, thanks! :)
