### ISSUE TITLE
How to test Timer.periodic callback

### ISSUE THREAD

**Issue by msayed-net** [dart-lang/test#1655]
Hello and thanks for your great effort,

I'm new to testing and trying to test Timer.periodic callback, but always not covered and don't know what to do.

<img width="840" alt="Screen Shot 2021-12-29 at 9 26 37 PM" src="https://user-images.githubusercontent.com/25801517/147696789-991a5a83-9bd5-42c6-8165-49b5bba2e0a3.png">

please feel free to see the code at [this url](https://github.com/PalestineDevelopers/connection/blob/main/lib/src/palestine_connection_base.dart)
 and test cases [here](https://github.com/PalestineDevelopers/connection/blob/main/test/palestine_connection_base_test.dart)

Thanks in advance..

**Comment by jakemac53** [comment]
In general your test probably is completing before this timer ever triggers.

The best way to deal with that general problem is to expose some sort of `Future` from this class, which your test can wait for, before completing.

You could do that with a `Completer`, which you complete inside the callback.

**Comment by msayed-net** [comment]
Thank you so much, reached 100% test coverage...
