### ISSUE TITLE
Timeout value problem

### ISSUE THREAD

**Issue by kostadin24** [dart-lang/test#1669]
timeout: Timeout(Duration(minutes: 5))); // Hardcode value works fine

timeout: Timeout(Duration(minutes: _timeoutMinutes)));// Provided by parameter set in setUp() fails with:

 [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The method '_mulFromInteger' was called on null.
E/flutter ( 1503): Receiver: null
E/flutter ( 1503): Tried calling: _mulFromInteger(60000000)
E/flutter ( 1503): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68:5)
E/flutter ( 1503): #1      int.* (dart:core-patch/integers.dart:22:38)
E/flutter ( 1503): #2      new Duration (dart:core/duration.dart:143:35)
E/flutter ( 1503): #3      main (file:///C:/Projects/hn-app-flutter/test/getNO_test.dart:48:23)
E/flutter ( 1503): #4      main (file:///C:/Projects/hn-app-flutter/.dart_tool/flutter_build/generated_main.dart:124:42)
E/flutter ( 1503): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:127:38)
E/flutter ( 1503): #6      _rootRun (dart:async/zone.dart:1428:13)
E/flutter ( 1503): #7      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 1503): #8      _runZoned (dart:async/zone.dart:1863:10)
E/flutter ( 1503): #9      runZonedGuarded (dart:async/zone.dart:1851:12)
E/flutter ( 1503): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:125:5)
E/flutter ( 1503): #11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter ( 1503): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by kostadin24** [comment]
Tested 3 variants
  //}, timeout: Timeout(Duration(minutes: _timeoutMinutes)));//Exception
  }, timeout: Timeout(Duration(minutes: 5)));// Works fine
  //}, timeout: _timeout);//Object _timeout is created insetUp() => Default 30 seconds applied - so FAILS in 30 sec

**Comment by jakemac53** [comment]
This is working as intended - these values are read before `setUp` is called, only the body of the test function can rely on values initialized in `setUp`.

**Comment by jakemac53** [comment]
Actually it sounds like I was wrong about that if your 3rd variant works. But the 2nd variant fails because this is an argument passed to the call to `test` - it is evaluated when `test` is called, which definitely does happen prior to the `setUp` callback being invoked.

**Comment by kostadin24** [comment]
Some tests depend on specific conditions and hardcoding them is not OK.
They frequently need manually 'fixing' or best case is calculated timeout to apply somehow.
