### ISSUE TITLE
Should `throwsA` mark tests pending when the value is a `Future`?

### ISSUE THREAD

**Issue by natebosch** [dart-lang/test#1670]
It's possible to lose test failures if you use `throwsA` against a `Future` which does not complete until after all other tests are done.

If we see a `Future` that we expect to throw, should we mark the test pending until it completes?

**Comment by jakemac53** [comment]
Seems like we should imo, yes. I always thought it worked that way...

**Comment by natebosch** [comment]
hmm, I may be wrong about the root cause of that test not failing... I think the intention is this async work should be captured by https://github.com/dart-lang/test/blob/e0be5ec076c59d621de1892b108727f560f217bc/pkgs/test_api/lib/src/expect/expect.dart#L106

I'm not sure why this failure is slipping through

**Comment by natebosch** [comment]
Ah, this bug is related to our use of zones in the build system.

The root cause is that we're running test expectations in a nested zone which has it's own uncaught error handler. This test failure is getting ignored due to https://github.com/dart-lang/build/pull/2599

I can't find the conversation now, but I think at one point we had discussed making `fail()` an API on `TestHandle`. If we do that then we can allow communicating this failure more directly without relying on the uncaught async error behavior.

**Comment by natebosch** [comment]
Closing in favor of https://github.com/dart-lang/test/issues/1671
