### ISSUE TITLE
[Problem] Dart test missing his own methods

### ISSUE THREAD

**Issue by l-borkowski** [dart-lang/test#1674]
Hi I've some strange problem with running tests in my app cause I can't run tests in the package folder of my Flutter app via VSC so I tried doing it manually, and this is what happened 
![image](https://user-images.githubusercontent.com/79083099/157270848-52e67637-8175-4453-a17b-4c7cd1ca0ff5.png)
dart test is failing with throwing hundreds of exceptions with missing his own methods like 

Error: 'PointerDeviceKind' isn't a type.
Error: 'Offset' isn't a type.
Error: The method 'loadFontFromList' isn't defined for the class 'FontLoader'

and much more when the flutter test works fine

**Comment by jakemac53** [comment]
(note that this is because `dart test` uses the Dart SDK which does not include flutter)
