### ISSUE TITLE
Match specific element in a list

### ISSUE THREAD

**Issue by docputs** [dart-lang/test#1681]
Is there any `Matcher` that takes a list and access a specific element in it?

For instance, say I have a list of names `['David', 'Michael', 'John']` and I want to check whether the element at index 1 has a String that starts with `'Mic'`

How can I do that using the available matchers?

**Comment by natebosch** [comment]
`expect(values[1], startsWith('Mic'))`

We typically pull values out of collections when we want to check individual elements, unless we also want to assert other conditions. For instance if you want to also check that it's a 3 item list, but don't care about the values at index 0 or 2, `expect(values, [anything, startsWith('Mic'), anything])`
