### ISSUE TITLE
Print a usable reproduction command of failed tests.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/test#1734]
Currently a failing test prints a line like so:
```
08:28 +54 ~9 -1: test/integration.shard/command_output_test.dart: flutter run --machine uses AppRunLogger [E] 
```

Running that single test again from the command-line is kind of cumbersome. One has to

* write `flutter test` or `dart test`
* copy-paste the test filename
* write something like `-n ""<backarrow>`
* copy paste the test name.

It would be awesome if the whole command could be printed. Something like:
```
08:28 +54 ~9 -1: test/integration.shard/command_output_test.dart: flutter run --machine uses AppRunLogger [E] 
To run this test again: `flutter test test/integration.shard/command_output_test.dart --plain-name="flutter run --machine uses AppRunLogger"`
```
With escaping of tricky characters in the name string.

**Comment by sigurdm** [comment]
I would personally use both of these features.

Sometimes you want to drill down into a single failed test.
Sometimes you want to see if you managed to fix all the last failures

**Comment by jakemac53** [comment]
This one is also significantly easier to implement I think
