### ISSUE TITLE
Why is `@Skip` only available to libraries?

### ISSUE THREAD

**Issue by SvenSchoene** [dart-lang/test#1741]
See: https://github.com/dart-lang/test/blob/master/pkgs/test_api/lib/src/backend/configuration/skip.dart#L8

I have an unusual use case where I would like to have certain test files in my `./test`-folder, which I never expect to run with `flutter test` (e.g. they should never run in CI pipelines).

I **only** intend to run them by hand via my IDE.

This is simply there to help me discover the API of a complex feature / package quickly, test things out, and have some code that I can remember months later and copy&paste it when I need it.

Ideally these "not real"-test files are excluded when I run `flutter test` and do _not_ show up in the list of skipped tests:

> 00:02 +0 ~6: All tests skipped.

I actually do not know if `@Skip` makes test files not show up in the output. But I at least wanted to give it a try.

Currently, as a "workaround", I'm grouping all tests in these files and mark them as `skip: true`.

Regardless of whether `@Skip` would actually not make those files appear in the output, I would love to know the reason as to why `@Skip` is only available for libraries in the first place?

This is by the way not even mentioned in the docs as far as I can see:

> Skipping Tests 
> 
> If a test, group, or entire suite isn't working yet, and you just want it to stop complaining, you can mark it as "skipped". The test or tests won't be run, and, if you supply a reason why, that reason will be printed. In general, skipping tests indicates that they should run but is temporarily not working. If they're fundamentally incompatible with a platform, [@TestOn/testOn](https://pub.dev/packages/test#restricting-tests-to-certain-platforms) should be used instead.

**Comment by jakemac53** [comment]
I would suggest just moving these files to some directory other than `test`, `tool` would be a good candidate. You could also just name the files so they don't end with `_test.dart` and they won't run automatically.

> Regardless of whether `@Skip` would actually not make those files appear in the output, I would love to know the reason as to why `@Skip` is only available for libraries in the first place?

I don't understand the question, where do you expect @Skip to be available that it isn't?  You can also skip groups, tests, and individual expectations.

**Comment by SvenSchoene** [comment]
> I would suggest just moving these files to some directory other than test, tool would be a good candidate. ou could also just name the files so they don't end with _test.dart and they won't run automatically.

Sounds good... if I knew how to run the code in these files!

`flutter run tool/test.dart` is a pretty heavy operation, because it starts building an entire app:

```
Running Gradle task 'assembleDebug'...
```

Which is understandable, because the command line help for that command says:

>  **run              Run your Flutter app on an attached device.**
>  test              Run Flutter unit tests for the current project.

If I do `dart run tool/test.dart` I get lots of errors like this:

> ../../../SDKs/Flutter/packages/flutter_test/lib/src/_goldens_io.dart:9:8: Error: Not found: 'dart:ui'
> import 'dart:ui';

Which makes sense if Flutter dependencies are not available without using the `flutter`-command (https://stackoverflow.com/questions/52483773/dartui1-error-not-found-dartui-flutter-dart).

All I want is the simplicity of `flutter test`, and not the heaviness of `flutter run`.

---

Aaaaah! The solution is extremely simple: I didn't know I could run `flutter test tool/test_test.dart`, or even `flutter test tool/test.dart` (without the `_test`)! In both cases tests are run normally like one would expect / hope.
My issue was that I believed that `flutter test` would only run tests in the `test`-directory. 
So your suggested approach is working quite well!

The only downside here is that I cannot seem to be able to click on `Test | Debug` in my IDE, see:

![flutter_tests_IDE_01](https://user-images.githubusercontent.com/7631673/180337160-7aa3a74f-aa70-436f-8113-506588e472ed.png)

This can be useful for debugging, see:

![image](https://user-images.githubusercontent.com/7631673/180337249-a2464bf4-e199-472b-9065-34882949e5a8.png)

Any ideas I regarding this that I may be overlooking are appreciated.

**Comment by SvenSchoene** [comment]
Regarding the `@Skip`: I get the following hint when I try to use it in my app tests:
![image](https://user-images.githubusercontent.com/7631673/180337537-8ad7c1ab-5be6-44cf-a43d-35d8af3c2c8f.png)

Which makes sense, because it's defined as targetting libraries only: https://github.com/dart-lang/test/blob/master/pkgs/test_api/lib/src/backend/configuration/skip.dart#L8

I wonder why it's defined for libraries-only? Why would a library have the need to mark an entire file as skippable, but the same need does not arise for apps? Libraries can also use the "normal" `skip: true`-parameters on `group()` and `test()`. From not knowing the reasoning behind this I'd argue: If there is a need for a library to mark an entire file with `@Skip`, then the same reason might exist in app code. So I would love to understand the thought process behind this.

Regarding "Why would one want to use `@Skip` if one can skip files another way?": Because of this comment I found in a discussion in this repository:

>Top-level annotations work a little differently because loading suites is expensive (especially when they need to be compiled) and we use top-level @Skip and @TestOn annotations to decide whether to load them at all.

(source: https://github.com/dart-lang/test/issues/545#issuecomment-281803617)

After I read that, my hope was that I could use `@Skip` to be able to keep my "not real test"-files in my `test`-directory, so that my IDE would still pick up on them as tests. But since they would be fully skipped, potentially not even parsed, I would not get a message like this:

> 00:02 +0 ~6: All tests skipped.

If the parsing of the file was fully skipped, it couldn't display that message to me, because it wouldn't know how many test cases it contained. That was my thinking.

**Comment by jakemac53** [comment]
> I wonder why it's defined for libraries-only? Why would a library have the need to mark an entire file as skippable, but the same need does not arise for apps?

Sorry I am not understanding what feature you are asking for here? Can you elaborate as to exactly what you want to achieve that you can't?

**Comment by jakemac53** [comment]
> The only downside here is that I cannot seem to be able to click on `Test | Debug` in my IDE, see:

You may be able to use tags instead of Skip, see https://pub.dev/packages/test#tagging-tests

**Comment by SvenSchoene** [comment]
Sorry for keeping this thread open. I was on vacation. :)

> Sorry I am not understanding what feature you are asking for here? Can you elaborate as to exactly what you want to achieve that you can't?

At this point I'm not asking for a feature. I'm trying to understand: What was the idea behind making `@Skip` only available to library code, and not application code?

> You may be able to use tags instead of Skip, see https://pub.dev/packages/test#tagging-tests, and then [whole package configuration](https://pub.dev/packages/test#whole-package-configuration) to set the default tags.

Thanks, that looks interesting! That unfortunately doesn't cause the testing system to skip the entire file like `@Skip` does, though, because it needs to parse each individual test declaration to know whether or not to skip it -- and therefore it notifies the user when running the test, that the test was skipped (which is good to know in **every** use case but my super-edge-case).

Let me be thorough for anyone else who stumbles across this (unlikely, but who knows):

Here is an example with tags:

dart_test.yaml:
```yaml
tags:
  not_a_real_test:
    skip: "Not a real test"
```

test1_test.dart:
```dart
import 'package:flutter_test/flutter_test.dart';

void main() {
  test("Real test", (() async {
    expect(true, true);
  }));
}

```

test2_test.dart:
```dart
import 'package:flutter_test/flutter_test.dart';

void main() {
  test("Not real test", (() async {
    expect(true, true);
  }), tags: ["not_a_real_test"]);
}
```

Output:
```bash
> flutter test
00:02 +1: [.../test_app]/test/test2_test.dart: Not real test <-- I want this to not be displayed, but only for these particular skipped tests, not in general
  Skip: Not a real test <-- I want this to not be displayed, but only for these particular skipped tests, not in general
00:02 +1 ~1: All tests passed!
```

My biggest hope was `@Skip`, because it instructs the test system to not even parse the individual tests:

> Top-level annotations work a little differently because loading suites is expensive (especially when they need to be compiled) and we use top-level @Skip and https://github.com/teston annotations to decide whether to load them at all.

---

But it's okay! I can accept my fate that this is not possible. Still, the question why `@Skip` is not available in application test code (and why this isn't documented, as far as I can tell) nags me. :)

**Comment by jakemac53** [comment]
> At this point I'm not asking for a feature. I'm trying to understand: What was the idea behind making `@Skip` only available to library code, and not application code?

I can't answer that question without understanding what you expect to achieve by using @Skip on "application code". I don't understand what you are asking :).

But in general, the annotations in package:test are _all_ library level. They give you a way of setting the defaults for the entire test. They are all parsed before actually reading the test, and it's much easier to reason about library level annotations only in that scenario. 

Configuring individual tests/groups is done with parameters to the functions, because it is easier, and accessing metadata annotations at runtime is not possible to do on all platforms (and not supported on any).

**Comment by jakemac53** [comment]
I am going to close this issue but feel free to follow up with more questions if you have them
