### ISSUE TITLE
setUpAll() and tearDownAll() for 'dart' tests

### ISSUE THREAD

**Issue by dotjon0** [dart-lang/test#1759]
flutter_test has https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html the follows (below) - are there plans to support this in the 'test' package also? This would be very useful to be able to run a function before 'all tests files' execute in a 'dart' only repo (i.e. not a 'flutter' repo).

_Before a test file is executed, the Flutter test framework will scan up the directory hierarchy, starting from the directory in which the test file resides, looking for a file named flutter_test_config.dart. If it finds such a configuration file, the file will be assumed to have a main method with the following signature:_

**Comment by jakemac53** [comment]
There are no plans to support this, no, but it has also never been proposed afaik.

I haven't really seen a use case for it in plain dart tests - the pattern might be more specific to flutter. We don't allow `main` to accept arguments, so you couldn't pass any data into the test. But you could I suppose invoke `setUpAll` and/or `tearDownAll`?

The test package also has to support various platforms (web, vm, node, etc) which introduces extra complexity here. We could just not try to solve those problems though, and force users to deal with any issues that arise from platform specific imports in those files.

The other complexity here is that package:test actually has a somewhat public API for how tests are bootstrapped (it supports a "precompiled" mode where it does not do the bootstrapping). The other packages doing bootstrapping (ie: build_test) would probably have to duplicate this logic.

**Comment by jakemac53** [comment]
Another con to this is it would break your ability to run dart tests directly just by invoking them (`dart <test-file>`).

**Comment by dotjon0** [comment]
Thanks for your detailed feedback @jakemac53  - our use case is to (a) open 1 x DB connection and then share this DB connection over all test files (1 x connection over all files, not 1 x connection per file), and (b) to setup a client on a 3rd party API that is then shared for all tests - both use cases for a server side plain dart environment. Jest in nodeJS supports this approach (including support for running tests directly). So having a shared function at the top of the main of each test will create lots of unnecessary DB connections...  

May we ask why this is available in flutter_test, what were the use cases around this ? Just so we can understand why these use case(s) do not extend to dart also.

Many thanks again

**Comment by jakemac53** [comment]
Ah, so I missed a bit your original suggestion of having this happen only once for _all files_. That also implies a much deeper change - and also shared global state generally between all tests. Today each test runs completely separately from all other tests. I do understand the use case now though.

However, that does not appear to be the functionality that flutter_test provides - when I read the docs it appears to still invoke the same file separately once per test, which is how I originally interpreted this request.

> May we ask why this is available in flutter_test, what were the use cases around this ? Just so we can understand why these use case(s) do not extend to dart also.

The flutter_test team is different from the team that maintains package:test. They never discussed this functionality with us as far as I know, and just built this on top. I have never heard of this feature :).

**Comment by jakemac53** [comment]
Fwiw, you can get your desired behavior by creating a single test entrypoint, which imports all your actual test files explicitly and calls their `main` methods (or maybe some other convention you come up with) explicitly, as well as calling `setUpAll`, `tearDownAll`, etc. That is what I would recommend you do here, but it might not play well with IDE integration.

You would also lose parallelism, but any solution would. If we were to support this feature I think we would have to essentially do the same thing under the hood, it would just be more automatic.

**Comment by dotjon0** [comment]
That sounds like a plan @jakemac53 - thank you for the suggestion and for being so helpful / super fast (!) - will get our team to put this in place in the meantime. I think you are right in that we misread the Flutter https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html article.

To help out, here is the functionality that we have raised in this issue in Jest (just in case you decide to implement in dart test):

1. **Global Setup** - runs 1 x file before all tests (once, not before each test) https://jestjs.io/docs/configuration#globalsetup-string
2. **Global Tear Down** - runs 1 x file before all tests (once, not before each test) https://jestjs.io/docs/configuration#globalteardown-string

Thank you again and hope you have a great rest of week!

**Comment by jakemac53** [comment]
Thanks for the feature request! I see a clear reason you want this functionality, but I do think it is not compatible technically with the approach used to run tests today (where they each get their own isolate). I also don't think we want to establish an entire other mode of running tests just to support it, especially given you can replicate the behavior with some extra boilerplate.

I am going to close this issue as not planned, but do appreciate the well explained feature request. Thanks!

**Comment by dotjon0** [comment]
Hi @jakemac53 just checking to see if there has been any further discussions internally around this feature request?

**Comment by jakemac53** [comment]
No, there isn't any ongoing discussion right now that I am aware of

**Comment by dotjon0** [comment]
> No, there isn't any ongoing discussion right now that I am aware of

Thank you for the update @jakemac53 and happy new year
