### ISSUE TITLE
Multiple tests execution

### ISSUE THREAD

**Issue by grafovdenis** [dart-lang/test#1760]
## Bug description

Once you're trying to run test, which description contains variable or type used in other test, multiple tests would be executed.
This could be annoying if you're using some kind of BLoC/Redux actions, which types may be located in multiple test descriptions.

## Example

See [full reference](https://github.com/grafovdenis/dart_test_description_bug).

``` dart
import 'package:test/test.dart';

class MyObj {
  final number = 10;

  bool foo() => true;
}

void main() {
  group('$MyObj', () {
    late MyObj myObj;

    setUp(() {
      myObj = MyObj();
    });

    test('is $Object', () {
      expect(myObj, isA<Object>());
    });

    test('foo returns true and is $Object', () {
      expect(myObj.foo(), isTrue);

      expect(myObj, isA<Object>());
    });

    test('number equals 10', () {
      expect(myObj.number, equals(10));
    });
  });
}

```

## Expectation 

Running `'is $Object'` test, via CLI or IDE would execute only selected test.

## Reality

It also executes `'foo returns true and is $Object'` both using CLI and in IDE.

![image](https://user-images.githubusercontent.com/20505376/188468576-6767c2a4-705e-4571-80d0-48c5cb0163b7.png)

**Comment by grafovdenis** [comment]
UPD: If argument value under "-N" flag doesn't fully fit another test, it it would be also executed.

<img width="797" alt="image" src="https://user-images.githubusercontent.com/20505376/188471236-a87fbdcf-dbf1-49c4-a477-47117302e56d.png">

**Comment by grafovdenis** [comment]
Hey, @jakemac53!
I don't think that it works as intended.

Flags:
``` bash
-n, --name                            A substring of the name of the test to run.
                                      Regular expression syntax is supported.
                                      If passed multiple times, tests must match all substrings.
-N, --plain-name                      A plain-text substring of the name of the test to run.
```

Let's modify `'foo returns true and is $Object'` description to `'foo returns true and is an $Object'`.

Now, `'is $Object'` is not a substring of `'foo returns true and is an $Object'`, and the expectation is not to see this test running, but it does. 

<img width="844" alt="image" src="https://user-images.githubusercontent.com/20505376/188674347-624e0fdd-6437-4de5-b364-47f801f26fb3.png">

**Comment by jakemac53** [comment]
In the dart code it is doing a string interpolation, so `$Object` is actually `MyObject.toString()`.

On the command line you are passing `is $Object` which is likely being interpreted as a regex, which as a regex doesn't really make sense. I am surprised it matches anything.

**Comment by jakemac53** [comment]
Oh actually I didn't notice you were also trying a plain name match.

On second thought I think what is actually happening is the `$Object` etc are being treated as bash variables. Probably they are having the empty string substituted in.

**Comment by grafovdenis** [comment]
Thanks for the replies.

Yeah, it seems like `$Object` is being interpreted as env.
And it appears to be that VSCode does the same, it runs `dart test test/my_obj_test.dart -N "is $Object"` once you click "Run" on a specific test.

<img width="609" alt="Screenshot 2022-09-06 at 19 06 41" src="https://user-images.githubusercontent.com/20505376/188686062-c54e24fe-7327-47ee-a965-3182991212d3.png">

**Comment by jakemac53** [comment]
> And it appears to be that VSCode does the same, it runs `dart test test/my_obj_test.dart -N "is $Object"` once you click "Run" on a specific test.

Yeah, I don't think VSCode can do anything here, it doesn't know the runtime value of `$Object`.

In general, I would avoid using variables inside test names wherever possible, it won't generally work out great with the IDE run experience.

**Comment by grafovdenis** [comment]
Get it, thanks.
The reason I use `$` syntax is that it helps in renaming a lot, and now I understand the cons :)

**Comment by jakemac53** [comment]
Fwiw, you could file an issue on DartCode (the vs code plugin), they could just recognize these and replace them with some wildcard matching regex or something. It wouldn't totally solve the problem but probably better than just using the empty string haha.

**Comment by DanTup** [comment]
> Fwiw, you could file an issue on DartCode (the vs code plugin), they could just recognize these and replace them with some wildcard matching regex or something.

This is actually what Dart-Code already does - it replaces variables with `.*`, and it also wraps tests with `^` and `$` to try to reduce false positives (it only prefixes groups with `^` since we can't use `$` at the end, so that's less reliable).

I do plan to switch to using line/cols to start tests in future (something added to `package:test` a while back). There are some possible edge cases with that (eg. unsaved file with different line numbers to disk), but I think it should generally handle this better. That's being tracked in https://github.com/Dart-Code/Dart-Code/issues/4021.
