### ISSUE TITLE
Feature request: Improve expect failure messages

### ISSUE THREAD

**Issue by WorikQCI** [dart-lang/test#1769]
Was https://github.com/flutter/flutter/issues/111925#issue-1378572673.  But I was sent over here.....

## Use case

I have two classes each with `hashCode` and `operator==` impplemented

In a test when there is a subtle difference the `expect(thing1, thing2)` function's error message on screen is:

```
Exception has occurred.
TestFailure (Expected: <Instance of 'PersistentGlobalVariables'>
  Actual: <Instance of 'PersistentGlobalVariables'>
)
```

That is nonsensical.

To trigger this I have:

```
    thing2.someIntField = 18;
    expect(thing1, thing2);
```

because the test succeeds and for this report I wished to make it fail.  So one field is different.

If you cannot find the actual cause of the failure please fix the error message so it makes sense.

Better would be:

`arguments differ.`

**Comment by jakemac53** [comment]
If you want a better error message here the best option is to write your own custom [matcher](https://pub.dev/documentation/matcher/latest/matcher/Matcher-class.html), then you can check exactly whichever fields you like and produce whichever message you like, for your custom objects.

All that the default `expect` does is check `==` and then give you the `toString` of each object. The default `toString()` in Dart does not list all the fields (for good reasons, largely regarding compiled binary size). I don't think we can do much better here.
