### ISSUE TITLE
dart run test fails

### ISSUE THREAD

**Issue by WorikQCI** [dart-lang/test#1772]
The documentation herein says: `A single test file can be run just using dart test path/to/test.dart`

My results:
```
% dart test test/<name of test>_test.dart        
Could not find a file named "pubspec.yaml" in "/Users/<my name>/.pub-cache/hosted/pub.dartlang.org/quiver-3.1.0".
```

```
% dart --version
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "macos_arm64"
```

Running the tests using flutter works as expected, just change `dart` to `flutter`.

**Comment by jakemac53** [comment]
Sounds like you probably need to run `dart pub upgrade`. It sounds like your `flutter` and `dart` sdks are set up to use different pub cache directories.

For a while flutter used to ship with a pre-populated pub cache, which caused this problem. I can't remember exactly where it lived though, but I think somewhere under your flutter SDK directory. If you just delete that, then Flutter and Dart would share the same pub cache.

**Comment by jakemac53** [comment]
I am going to close this but feel free to re-open if this doesn't solve the issue.
