### ISSUE TITLE
Indicate number of mismatched event for emitsInOrder

### ISSUE THREAD

**Issue by AAAbramenko** [dart-lang/test#1783]
Message for mismatched events from tested stream by [emitsInOrder](https://api.flutter.dev/flutter/package-test_api_expect/StreamMatcher-class.html) looks like:
```
Expected: should do the following in order:
          * emit an event that <0>
          * emit an event that <1>
          * emit an event that <3>
          * be done
  Actual: <Instance of '_ControllerStream<int>'>
   Which: emitted * 0
                  * 1
                  * 2
                  x Stream closed.
            which didn't emit an event that <3>
```
This case is simple, but sometimes It`s needed to test streams with great number of different events (also produced from freezed).
What is about to add position/index of mismatched event to test message? Make message looks like for testing Iterables:
```
00:00 +0: test
00:00 +0: test [E]
  Expected: [0, 1, 3]
    Actual: [0, 1, 2]
     Which: at location [2] is <2> instead of <3>
```
This will simplify analyzing test failed messages.

**Comment by natebosch** [comment]
We don't plan on making further enhancements to matchers. Once `package:checks` reaches stable the replacement `emitsInOrder` does specify which index failed to match.

If someone wants to take a try at this it would involve adding the index to the message at https://github.com/dart-lang/matcher/blob/5bc765db9838e025a59fc42e375bd6c1f52194f1/lib/src/expect/stream_matchers.dart#L180
