### ISSUE TITLE
rev the dep on package:glob and publish new versions

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/test#1784]
This is a tracking issue for:
- reving the package:test_core dep on package:glob to `2.1.1` (not yet published version)
- publish new versions of the test package(s) with this change

That will help mitigate breakages that users see from https://github.com/dart-lang/sdk/issues/49647 (older versions of package:file running on newer - Dart 2.19.0-dev and later - SDKs).

**Comment by jakemac53** [comment]
I don't believe this is worthwhile - package upgrading is all or nothing anyways so people will get the latest glob when they update to a version of package:test that would give them the new constraint anyways

**Comment by jakemac53** [comment]
And if they can't for some reason get the latest glob, they would just get an older version of package test selected which we wouldn't want

**Comment by devoncarew** [comment]
> I don't believe this is worthwhile - package upgrading is all or nothing anyways so people will get the latest glob when they update to a version of package:test that would give them the new constraint anyways

That's true if they run `dart pub upgrade` but not true for `dart pub get`.

> And if they can't for some reason get the latest glob

The deps for glob (and file) haven't otherwised changed so there shouldn't be any issues resolving it.

**Comment by jakemac53** [comment]
> That's true if they run `dart pub upgrade` but not true for `dart pub get`.

It is true for `dart pub get` as well. Users will be on the same (old) version of package:test if they do that. Or, if its a new clone they will get the latest version of test + glob. Or if they check in their pubspec.lock it will give them the old test & glob.

**Comment by jakemac53** [comment]
> The deps for glob (and file) haven't otherwised changed so there shouldn't be any issues resolving it.

It would be rare I agree but if some other package had an upper bound constraint on glob that was weirdly tight, then it could happen.

**Comment by natebosch** [comment]
Closing since I don't think that bumping this dependency is going to have a meaningful impact on user experience - the set of users who happen to manually change their `test` dependency before a `pub get` is likely to be small.
