### ISSUE TITLE
Versioning issue with Flutter_test

### ISSUE THREAD

**Issue by Shalom-Nankam** [dart-lang/test#1796]
Check the error displayed in the output below and help with a resolution

<img width="1116" alt="Screenshot 2022-11-23 at 16 31 46" src="https://user-images.githubusercontent.com/105394231/203586478-61f21953-cf04-42d7-b48e-61d33b4ef957.png">

**Comment by jakemac53** [comment]
You will need to loosen your constraint on package:test to a version compatible with your version of flutter
