### ISSUE TITLE
Prepare for Dart 3

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/test#1811]
The source currently contains several references to APIs scheduled for removal in Dart 3 ([details here](https://github.com/dart-lang/sdk/issues/49529)):

* [`CyclicInitializationError`](https://github.com/search?q=repo%3Adart-lang%2Ftest+CyclicInitializationError&type=code)
* [`NullThrownError`](https://github.com/search?q=repo%3Adart-lang%2Ftest+NullThrownError&type=code)

Can we move the min up to 3.0, and start working on a dev release version for this?

**Comment by jakemac53** [comment]
We also reference `CastError`.

**Comment by jakemac53** [comment]
cc @mit-mit what is the timeline here? How soon with this package break in dart 3 (or is it already broken?).

**Comment by mit-mit** [comment]
The plan was to land changes removing the APIs starting Monday, Dec 12th, in Dart main.

The potential breaking is in google3, where there's a copy of the package, which would then fail analysis after a google3 roll of the SDK.

**Comment by jakemac53** [comment]
Ok, so its a P0 then?

**Comment by mit-mit** [comment]
Yes, I believe so
