### ISSUE TITLE
feat: Fail fast option

### ISSUE THREAD

**Issue by jtdLab** [dart-lang/test#1841]
Add an option `--fail-fast` to exit the test process when the first failed test occurs.

This is especially useful in CI environments where running more tests leads to unnecessary costs.

**Comment by natebosch** [comment]
I can imagine two levels of fast failure - one level would skip the `tearDown` and any pending async work for the current test, and try to exit as fast as possible. The other would wait for any ongoing test and still run `tearDown`, but wouldn't run any more `setUp` or `test`.

Which level would be most useful? I'd lean towards implementing the latter, but I could also imagine implementing both.

**Comment by jtdLab** [comment]
The 2nd approach sounds good to me.
