### ISSUE TITLE
Tests should handle test cases better.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/test#1860]
When a test loops through test cases, there are two issues:

1. I have to pass reason to every `expect`
2. When code throws exception, there is no way to see case name.

It would be amazing if it was possible to set test name in test context somehow.

```
  test('parses dependencies ', () async {
    for (final t in layeringTests) {
      final analyzer = Analyzer(t.input);
      expect(analyzer.files, hasLength(t.input.length), reason: t.name);
      expect(analyzer.nodes, hasLength(t.nodes), reason: t.name);
      expect(
        analyzer.root.children,
        hasLength(t.rootChildren),
        reason: t.name,
      );
    }
  });
```

**Comment by polina-c** [comment]
@natebosch

**Comment by jakemac53** [comment]
Fwiw you can do:

```dart
  for (final t in layeringTests) {
    test('parses dependencies ', () async {
      final analyzer = Analyzer(t.input);
      expect(analyzer.files, hasLength(t.input.length), reason: t.name);
      expect(analyzer.nodes, hasLength(t.nodes), reason: t.name);
      expect(
        analyzer.root.children,
        hasLength(t.rootChildren),
        reason: t.name,
      );
    });
  }
```

Which creates a separate test per case and allows you to customize the name using string interpolation. This may not however play very nicely with IDE support for running tests.

**Comment by natebosch** [comment]
I don't think it is possible to have a pattern that supports dynamically changing test names, or dynamically adding tests, which also plays nicely with IDE support for running tests.

We can run all the tests defined in the loop by line number, or a human can predict a name and run a test by all or part of the name.

Calling `test` within a loop is the best pattern for this.

**Comment by jakemac53** [comment]
Beyond even just IDE support we couldn't support running tests by name at all if the names could change in the middle of a test, or new tests could be added dynamically in the middle of a test.

**Comment by natebosch** [comment]
I'm going to close for now - if anyone has a proposal for an API that might better allow IDEs to understand parameterized tests compared to a for loop I'd be happy to discuss, but with the limiting factor of never being able to statically determine test cases that depend on reading external files I don't think there is much we can do.
