### ISSUE TITLE
"dart test file:///foo.dart" doesn't work without a query string

### ISSUE THREAD

**Issue by DanTup** [dart-lang/test#1891]
`dart test` accepts a file URI if there is a querystring:

```
danny@Dannys-MacBook-Pro dart_sample % dart test "file:///Users/danny/Desktop/dart_sample/test/line2_test.dart?name=a"
00:00 +1: All tests passed! 
```

But if there's no querystring, you get an error:

```
danny@Dannys-MacBook-Pro dart_sample % dart test "file:///Users/danny/Desktop/dart_sample/test/line2_test.dart"       
00:00 +0 -1: loading file:///Users/danny/Desktop/dart_sample/test/line2_test.dart [E]                                                                      
  Failed to load "file:///Users/danny/Desktop/dart_sample/test/line2_test.dart": Does not exist.

To run this test again: dart test file:///Users/danny/Desktop/dart_sample/test/line2_test.dart -p vm --plain-name 'loading file:///Users/danny/Desktop/dart_sample/test/line2_test.dart'
00:00 +0 -1: Some tests failed.   
```

I don't know if this is intended, but I'm trying to pass URIs through from `flutter_tools` and wanted to just stick with `file://` URIs for consistency if possible.

**Comment by DanTup** [comment]
(perhaps without a `?` this just looks like a relative path? but maybe a `file://` prefix can be special cased?)

**Comment by jakemac53** [comment]
Seems like a bug to me

**Comment by jakemac53** [comment]
I hadn't realized this was actually not specific to windows also, on windows would we expect to see a drive letter?

**Comment by DanTup** [comment]
Correct, this was on macOS. Yep, on Windows I would expect it include the drive letter (and colon).

I would expect whatever is passed could be parsed with `Uri.parse` and if `.isScheme('file')` then use it as-is, and otherwise treat it as a path (which you can probably do `Uri.file()` on to get also as a Uri, perhaps something like `Uri.base.resolve(Uri.file(input))` if it needs to be absolute?).

**Comment by jakemac53** [comment]
Yeah ok I am working on essentially that change in the linked PR. I want to also make sure we retain the ability to run tests with windows style relative paths also though (test\my_test.dart). Not sure that we can parse that as a Uri but we will see what it does.

**Comment by DanTup** [comment]
I'm not on Windows to test, but if I do `print(Uri.file('foo\\bar.dart', windows: true));` on dartpad, that does seem to work (you get a relative Uri of `foo/bar.dart`). On Windows you don't need `windows: true`, but using it should let you test how it'd work on Windows from non-Windows.
