### ISSUE TITLE
Running tests by line doesn't work on Windows

### ISSUE THREAD

**Issue by DanTup** [dart-lang/test#1899]
@jakemac53 feel free to roll this into #1891 if you think they're the same cause, I wasn't sure. This is Windows-specific.

If you do `dart test foo\test.dart?line=1` on Windows, you're told to use URI format:

![image](https://user-images.githubusercontent.com/1078012/216303905-2bc30aeb-74b7-4daf-9657-8632113d9ce5.png)

However if you try this, it never seems to match the test:

![image](https://user-images.githubusercontent.com/1078012/216303963-20729358-ac73-45ad-8104-f7bd442a8315.png)

And if you try with a full valid `file://` URI you get this:

![image](https://user-images.githubusercontent.com/1078012/216304079-d7ed0e49-5126-40f2-a07b-6ae474433d24.png)

(that one is similar to #1891 except it's still happening when there is a querystring)

**Comment by jakemac53** [comment]
Interesting I think this will be the same fix, I'll add a test for it to my PR
