### ISSUE TITLE
GitHub CI integration: write to GITHUB_STEP_SUMMARY

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#1925]
See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary

Might be cool to have a roll-up summary of # of successes or failures, list of failed tests, etc

**Comment by kevmoo** [comment]
CC @natebosch @devoncarew

**Comment by natebosch** [comment]
#1866
