### ISSUE TITLE
Needs more documentation.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/test#1930]
I'm converting a small package from test to checks.

Firstly having to import 'import 'package:test/scaffolding.dart' doesn't seem to 
conform to convention.
I expected to just import 'package:checks/checks.dart';

The next is documentation.

I tried to implement check().throws and had to go look through checks unit tests to find an example.

This is a more general issue as the readme currently only shows trivial examples.

As to the throws implementation 

- from async_test.dart:44

``` dart
await check(_futureFail()).throws<UnimplementedError>(
            it()..has((p0) => p0.message, 'message').isNull());
```

I was expecting the syntax to be more like:

```dart
await check(_futureFail()).throws<UnimplementedError>((e) => 
           e..has((p0) => p0.message, 'message').isNull());
```
The usage of `it` seems strange.

It also isn't clear what `.isNull()` is doing here?

I've not used it in my test cases and they seem to work.

```dart
await check(validator.validate('!')).throws<AskValidatorException>(
        it()..has(
            (e) => e.message, red(r'Input does not match: ^[a-zA-Z0-9_\-]+')),
      );
```

**Comment by natebosch** [comment]
> Firstly having to import 'import 'package:test/scaffolding.dart' doesn't seem to
> conform to convention.
> I expected to just import 'package:checks/checks.dart';

This is going to be the long term pattern (although we may change it back to `package:test/test.dart` sometime soon when we can pull `matcher` out from the test package).

One downside to a single import `package:checks/checks.dart` (or exporting these APIs in `package:test/test.dart`) is that a breaking change in _either_ part of the API becomes a painful major version bump. With separate packages a version bump of either will still be painful, but bumps of `checks` are likely to be easier.

One upside to separate imports is that we'll leave room in the ecosystem for other folks to fill in matching libraries that have different syntaxes, or different preferences.

> I tried to implement check().throws and had to go look through checks unit tests to find an example.

The doc on `Context` are intended to be the main point to read for implementing extensions over the README. What do you think is missing?
https://pub.dev/documentation/checks/latest/context/Context-class.html

> I was expecting the syntax to be more like:
> 
> ```dart
> await check(_futureFail()).throws<UnimplementedError>((e) => 
>            e..has((p0) => p0.message, 'message').isNull());
> ```
> 
> The usage of `it` seems strange.

The `void Function(Subject)` argument was the original approach. It was changed in https://github.com/dart-lang/test/pull/1846

One downside to using `void Function(Subject<T>)` is that in some places, like in a collection in `deepEquals` or `containsAll`, there is no inference to help. Without inference, the utility of `it()` becomes more clear, `(Subject<String> e) => e.endsWith('foo')` becomes `it<String>()..endsWith('foo')`.

I tend to prefer to avoid `is` checks against function types when I can. The `Condition` API which has clear intent conveyed through the nominal type check, but a function type check can be easily fooled by a function with `Object` argument types and the right arity. I suspect the UX is better when `it()` is misused within a collection, but I'll admit I haven't specifically compared the failure scenarios.

We could go back to the function typed argument, either for all places (and drop `Condition`), or just for the calls that take the argument directly, and leave `Condition` for mixed usage within collections.

My preference leans towards using `it()` everywhere, but I can definitely see an argument that it's too novel to lean on so heavily.

I've taken a note of this feedback, I think this is the second time I've seen someone mention that a callback would feel more natural than the `it()` utility. We've had a little positive feedback about that syntax too.


> It also isn't clear what `.isNull()` is doing here?

It is asserting that the `message` field for the exception is `null`.

The matcher way to write this was

```dart
    await expectLater(
        _futureFail(),
        throwsA(isA<UnimplementedError>()
            .having((e) => e.message, 'message', isNull)));
```


> I've not used it in my test cases and they seem to work.
> 
> ```dart
> await check(validator.validate('!')).throws<AskValidatorException>(
>         it()..has(
>             (e) => e.message, red(r'Input does not match: ^[a-zA-Z0-9_\-]+')),
>       );
> ```

I think you want

```dart
    await check(validator.validate('!')).throws<AskValidatorException>(it()
      ..has((e) => e.message, 'message')
          .isNotNull()
          .equals(red(r'Input does not match: ^[a-zA-Z0-9_\-]+')));
```

I'll add a note about `.having` and `.has` to the migration guide.
`.having` took a `matcher` (or a value for `equals`) argument to check directly, `.has` returns a `Subject` to do the further checks.
