### ISSUE TITLE
How do I get a test directory ?

### ISSUE THREAD

**Issue by TheCarpetMerchant** [dart-lang/test#1945]
When running tests, to path obtained via `Platform.script.path` seemingly isn't valid. How can I get a directory in which I can do file operations during tests ?
This folder must be the same across isolates.

**Comment by natebosch** [comment]
Some discussion at https://github.com/dart-lang/test/issues/110

Although our plan for the workaround didn't involve writing to any directory, only reading.

Can you expand on your use case?

**Comment by TheCarpetMerchant** [comment]
Use case is to test the behavior around accessing locked files (locking a file in a Isolate, does the error handling work correctly in another Isolate)

**Comment by natebosch** [comment]
A temp directory seems like it would be more appropriate for that use case, with the main difficulty being communicating what directory to use.

Have you investigated any patterns for communicating the path to a temp directory across the isolates you spawn and using that instead of the package directory?

**Comment by TheCarpetMerchant** [comment]
Well of course you could have a global variable transmitted between isolates via a static function call (main isolate sets the variable, transmits it to other isolates as a parameter to a function setting that global variable for themselves), or use something like path_provider to end up in the same directory ; but I was hoping to get a temporary directory specifically for the tests, which can be cleaned up afterwards.

**Comment by nex3** [comment]
@TheCarpetMerchant I think the [`test_descriptor`](https://pub.dev/packages/test_descriptor) directory may be what you're looking for?

**Comment by TheCarpetMerchant** [comment]
@nex3 Looking at the code for that [here](https://github.com/dart-lang/test_descriptor/blob/master/lib/src/sandbox.dart), the answer would be no as this wouldn't yield the same result across isolates.

**Comment by jamesderlin** [comment]
How about [the comment I recently added to #110](https://github.com/dart-lang/test/issues/110#issuecomment-1445333192)?

**Comment by TheCarpetMerchant** [comment]
> How about [the comment I recently added to #110](https://github.com/dart-lang/test/issues/110#issuecomment-1445333192)?

Yep, that works for me. Hacky but hey, at least it allows for tests to run properly.
I'll close this since #110 is the relevant issue for larger discussion on the subject. Thanks James !
