### ISSUE TITLE
`group` and `test` definitions are in a deprecated library (making them deprecated)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/test#1990]
See discussions at https://github.com/Dart-Code/Dart-Code/issues/4480.

Currently these declarations are in `scaffolding.dart` which is marked `@Deprecated`, meaning these declarations are technically deprecated too.

The analysis server doesn't currently consider them deprecated, but apparently should. Fixing that will result in all calls to `group`/`test` generating diagnostics, so this should be addressed first.

Some more info on the intended use/interpretation at https://github.com/Dart-Code/Dart-Code/issues/4480#issuecomment-1497990136

**Comment by jakemac53** [comment]
One thing to consider here if we move forward with the change to import/export `src/` libraries, is trying to keep the API boundary as explicit as possible still. We could for instance create a `src/api` directory where we put the "friend package" apis.

I am going back and forth on this whole idea though, the existing strategy has worked well for us. Curious what @natebosch thinks.

**Comment by natebosch** [comment]
We could also consider removing the deprecations, they didn't seem to dissuade the flutter repos from adding a bunch of incorrect imports and ignoring the diagnostic, and that pattern got repeated some in the ecosystem.

https://github.com/search?q=repo%3Aflutter%2Fflutter%20%22package%3Atest_api%2Ftest_api%22&type=code

**Comment by jakemac53** [comment]
I would be fine with just removing the deprecations also 🤷‍♂️
