### ISSUE TITLE
Remove usages of deprecated NamedType.name field

### ISSUE THREAD

**Issue by natebosch** [dart-lang/test#2013]
https://github.com/dart-lang/test/blob/0b306dd5a8f9736fb428533b3ff3146e67380204/pkgs/test_core/lib/src/runner/parse_metadata.dart#L357

https://github.com/dart-lang/test/blob/0b306dd5a8f9736fb428533b3ff3146e67380204/pkgs/test_core/lib/src/runner/parse_metadata.dart#L221

@scheglov - can you help with this? I'm not sure how to use the `Token` in place of the `Identifier`

**Comment by scheglov** [comment]
https://github.com/dart-lang/test/pull/2015 contains changes that I think are the replacement for `analyzer 5.12.0`.
The key is that for `ConstructorName` we already have decided what is the `NamedType`, and what is the optional constructor name.

Although now looking at `_findConstructorNameFromInstantiation`, we maybe don't have to create `Pair` instance at all.
And it fails bots.
So, maybe I made a mistake.
