### ISSUE TITLE
Error with running flutter on iOS

### ISSUE THREAD

**Issue by muhammadkamel** [dart-lang/test#2017]
I encountered an error while debugging the Flutter app on iOS.

Error (Xcode): /Users/muhammad/flutter/packages/flutter_test/lib/src/_goldens_io.dart:12:8: Error: Error when reading '/Users/muhammad/.pub-cache/hosted/pub.dev/test_api-0.6.0/lib/expect.dart': No such file or directory
Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.

**Comment by Xplatforms** [comment]
Same here, Building for iOS fails booth in XCode and with 'flutter build ios' directly:
`Error (Xcode): ../flutter/packages/flutter_test/lib/src/_goldens_io.dart:12:8: Error: Error when reading '../../.pub-cache/hosted/pub.dev/test_api-0.6.0/lib/expect.dart': No such file or directory`

**Comment by muhammadkamel** [comment]
This fixed my issue:
dependency_overrides:
   test_api: ^0.5.2

**Comment by hicnar** [comment]
It looks like a breaking change has somewhere been introduced without properly versioning the package and announcing it in the change log. Just as a reminder, you appear to be using semantic versioning approach, which is fine, but when breaking changes are introduced you should bump the major version number unlike it was done when breaking changes were announced 0.4.18 -> 0.5.0. After that the version should have been 1.0.0 because of the breaking changes that were introduced.

**Comment by jakemac53** [comment]
@muhammadkamel @Xplatforms do you have any dependency overrides in place? Can you give more information or ideally a full reproduction project?

**Comment by jakemac53** [comment]
Flutter version, pubspec, result of `pub deps`, would be a good start. (but a git repo I can clone to reproduce the issue is always preferrable)

**Comment by muhammadkamel** [comment]
Because no versions of wakelock_windows match >0.2.1 <0.3.0 and wakelock_windows <0.2.1 depends on win32 ^2.0.0,
  wakelock_windows <0.2.1-∞ or >0.2.1 <0.3.0 requires win32 ^2.0.0.
And because wakelock_windows 0.2.1 depends on win32 ^3.0.0, wakelock_windows <0.3.0 requires win32 ^2.0.0 or ^3.0.0.
Because no versions of wakelock match >0.6.2 <0.7.0 and wakelock 0.6.2 depends on wakelock_windows ^0.2.0, wakelock ^0.6.2
  requires wakelock_windows ^0.2.0.
Thus, wakelock ^0.6.2 requires win32 ^2.0.0 or ^3.0.0.
And because package_info_plus >=4.0.0 depends on win32 ^4.0.0, wakelock ^0.6.2 is incompatible with package_info_plus >=4.0.0.
So, because epg_schools depends on both package_info_plus ^4.0.0 and wakelock ^0.6.2, version solving failed.

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-x64,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

pubspec.yaml:
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.4
  intl: ^0.18.0
  # flutter_inappwebview: ^5.7.2+2
  google_fonts: ^4.0.3
  dotted_border: ^2.0.0+3
  table_calendar: ^3.0.8
  dio: ^5.1.1
  lottie: ^2.3.2
  showcaseview: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  path_provider: ^2.0.14
  url_launcher: ^6.1.10
  youtube_player_flutter: 8.0.0
  video_player: ^2.6.1
  file_picker: ^5.2.7
  external_path: ^1.0.3
  permission_handler: ^10.2.0
  timeago: ^3.3.0
  firebase_messaging: ^14.4.0
  firebase_core: ^2.13.0
  awesome_notifications: ^0.7.4+1
  carousel_slider: ^4.2.1
  flutter_html: ^3.0.0-alpha.6
  package_info_plus: ^4.0.0
  open_filex: ^4.3.2

  # razorpay_flutter: ^1.3.4
  flutter_stripe: ^9.0.0+1

  encrypt: ^5.0.1
  flutter_tex: ^4.0.3+4

  flutter_windowmanager: ^0.2.0
  wakelock: ^0.6.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.1

dependency_overrides:
  test_api: ^0.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/
    - assets/images/epg/
    - assets/animations/

**Comment by jakemac53** [comment]
None of those packages depend on `flutter_test`? Possibly another case of https://github.com/flutter/flutter/issues/91107.

If you want to use `flutter test`, you must depend on `flutter_test`.

I don't see any regular dependencies on `test` either though so I am quite confused.

**Comment by natebosch** [comment]
Yes, this does look like an example of https://github.com/flutter/flutter/issues/91107

If you are using `flutter test` command, add a dependency on `flutter_test` in your pubsec. Without that constraint you are getting a newer version of `test_api` than is compatible with `flutter_test` because the pub solve was not using `flutter_test` constraints. Pinning your version of `test_api` works around it by adding in the constraint that would have been imposed by the `flutter_test` dependency.
