### ISSUE TITLE
Tests hang when exception throw from `runZonedGuarded` in `>=1.22.2`

### ISSUE THREAD

**Issue by felangel** [dart-lang/test#2020]
```dart
import 'dart:async';
import 'package:test/test.dart';

void main() {
  test('...', () async {
    await runZonedGuarded(
      () async => throw Exception('oops'),
      (error, stack) => throw Exception('caught exception $error'),
    );
  });
}
```

With `<=1.22.1` the test fails immediately as expected:

```
✖ time dart test
00:00 +0 -1: test/main_test.dart: ... [E]                                                                                                    
  Exception: caught exception Exception: oops
  test/main_test.dart 8:25  main.<fn>.<fn>
  

To run this test again: dart test test/main_test.dart -p vm --plain-name '...'
00:00 +0 -1: Some tests failed.                                                                                                              

Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
dart test  0.68s user 0.15s system 116% cpu 0.717 total
```

With `>=1.22.2` the test hangs and times out after 30 seconds.

```
✖ time dart test
00:00 +0 -1: test/main_test.dart: ... [E]                                                                                                    
  Exception: caught exception Exception: oops
  test/main_test.dart 8:25  main.<fn>.<fn>
  
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
  dart:isolate  _RawReceivePort._handleMessage
  

To run this test again: dart test test/main_test.dart -p vm --plain-name '...'
00:30 +0 -1: Some tests failed.                                                                                                              

Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
dart test  1.41s user 0.21s system 5% cpu 31.077 total
```

**Comment by slaci** [comment]
In this commit: https://github.com/dart-lang/test/commit/89a8b12bc7998b01e801cbeed82b3f64f49d1ef9 in the `pkgs/test_api/lib/src/backend/invoker.dart` file's line 350 the following line was removed: `zone.run(() => _outstandingCallbacks.complete());` (well, it was moved).

If I add this line back, then the test does not hang. When adding breakpoints it seems like this `_timeoutTimer = Zone.root.createTimer(timeout, () {` callback (where the outstandingCallbacks complete was moved to) does not run at all.

**Comment by natebosch** [comment]
This looks like an expected outcome for the change in #1815 (good find @slaci !)

In the commit message I wrote:

> Some tests that previously would have failed quickly will now result in
a timeout. This should be uncommon, and will only impact tests that
fail anyway.

(I maybe should have also copied that somewhere more user facing like the CHANGELOG... sorry about that!)

What is happening in this example is that the `Future` returned by the test body never completes, so the test times out. Prior to that change the test would have immediately failed with the unhandled async error, and `tearDown` callbacks may have been invoked earlier than planned. (See discussion in #1512).

Another way to demonstrate this behavior which may make it more clear what is happening. This test would also have a failure followed by a timeout:

```dart
import 'dart:async';

import 'package:test/test.dart';

void main() {
  test('foo', () {
    Future.error('sad'); // unhandled async error fails the test
    return Completer().future; // never completed
  });
}
```

I don't think there is much we can do about this - from the issue that was raised I do think it's safer to not consider the test complete before the returned `Future` is complete. Unfortunately this most likely needs to be solved on the user side by avoiding writing a test body that returns a Future that never completes. Use of `runZonedGuarded` needs to be careful, and if it results in a non-completing future a timeout may be the best expression of that behavior.
