### ISSUE TITLE
Test url/line/col are missing in JSON output on Windows

### ISSUE THREAD

**Issue by DanTup** [dart-lang/test#2037]
VS Code uses the url/line/col information provided in the JSON output for marking test locations. It seems like they're not being provided on Windows (I think this is likely a recent break, but I'm not certain).

For a new Flutter app, running the default `widget_test.dart` on macOS provides JSON like this:

```
{
	"test": {
		"id": 3,
		"name": "Counter increments smoke test",
		"line": 160,
		"column": 5,
		"url": "package:flutter_test/src/widget_tester.dart",
		"root_line": 14,
		"root_column": 3,
		"root_url": "file:///Users/danny/Desktop/dart_samples/dartcode_4586/test/widget_test.dart"
	},
	"type": "testStart"
}
```

But on Windows it looks like this:

```
{
	"test": {
		"id": 3,
		"name": "Counter increments smoke test",
		"line": 153,
		"column": 5,
		"url": "package:flutter_test/src/widget_tester.dart"
	},
	"type": "testStart"
}
```

Dart-Code incorrectly uses the `line` here and tries to put the market on line 153. The real line (14) is not in the JSON anywhere.

**Comment by DanTup** [comment]
hmmm, I used a dependency override to get Flutter to use the latest code, and now I'm not seeing this - so I think it may have already been fixed...

**Comment by jakemac53** [comment]
Yeah this is an absolute mess lol. I don't have a lot of time to look at it right now myself unfortunately, but maybe @natebosch does or I can circle back to this in a couple weeks.

**Comment by natebosch** [comment]
I suspect we should be able to do something like `p.canonicalize(frame.uri.toFilePath() == p.canonicalize(absoluteSuitePath)`

**Comment by natebosch** [comment]
@DanTup - if you have a chance could you try overriding your `test_core` dependency to confirm the fix?

```yaml
dependency_overrides:
  test_core:
    git:
      url: https://github.com/dart-lang/test.git
      path: pkgs/test_core
      ref: missing-windows-root-line
```

**Comment by DanTup** [comment]
I had to override test_api too ("Because every version of test_core from git depends on test_api 0.6.1 and flutter_tools depends on test_api 0.6.0"), but that seems to have done the job :-)

```
PS C:\Dev\Test Projects\dartcode_4586> flutter test -r json | Select-String testStart | Select-String widget_tester

{"test":{"id":3,"name":"Counter increments smoke test","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":160,"column":5,"
url":"package:flutter_test/src/widget_tester.dart","root_line":14,"root_column":3,"root_url":"file:///C:/Dev/Test%20Projects/dartcode_4586/test/widge
t_test.dart"},"type":"testStart","time":981}
```

**Comment by DanTup** [comment]
@natebosch thanks!
