### ISSUE TITLE
Support `analyzer` 6.0.0

### ISSUE THREAD

**Issue by incendial** [dart-lang/test#2044]
Hello!

Do you have plans to migrate to the newest analyzer version?
Can create a PR.

**Comment by jakemac53** [comment]
We definitely can/will update, I wasn't aware it was out yet :).

I think we had a pending PR to fix up some things in preparation for it, but need to chase down out the status of that.

**Comment by jakemac53** [comment]
Actually re-opening this as things aren't published yet, a few more little things I need to do before publishing

**Comment by jakemac53** [comment]
published
