### ISSUE TITLE
final SuitePlatform breaks flutter framework tests

### ISSUE THREAD

**Issue by aam** [dart-lang/test#2062]
Marking SuitePlatform as final breaks flutter where it is implemented for mocking purposes in the test:

https://github.com/dart-lang/test/blob/3429712b44b9c6222437312601044c44dc6f5e4e/pkgs/test_api/lib/src/backend/suite_platform.dart#L10

Flutter use:

https://github.com/flutter/flutter/blob/ce508286693e63454e4d43f8aac4fbcad36d10d7/packages/flutter_tools/test/general.shard/flutter_platform_test.dart#L123

This was discovered during dart->engine->framework roll https://github.com/flutter/flutter/pull/130163. An attempt to use actual SuitePlatform was made, it required further tweaks to the tests.

**Comment by natebosch** [comment]
Sorry I missed this issue - it looks like flutter was able to migrate to `SuitePlatform(Runtime.vm)`.
