### ISSUE TITLE
Test timeout doesn't work on synchronous operations.

### ISSUE THREAD

**Issue by SandPod** [dart-lang/test#2077]
**Describe the bug**
Given a test with synchronous operations the [default timeout nor a test configured timeout](https://pub.dev/packages/test#timeouts) works as expected.

**To Reproduce**
Create and run either of these two tests:
``` dart
import 'package:test/test.dart';

void main() {
  test('timeout works as expected for synchronous operation.', () {
    var count = 0;
    for (var i = 0;; i++) {
      count++;
    }
    expect(true, isTrue);
  }, timeout: const Timeout(Duration(seconds: 1)));
  test('timeout works as expected for synchronous operation done async,', () async {
    var count = await Future(() {
      var count = 0;
      for (var i = 0;; i++) {
        count++;
      }
      return count;
    });
    expect(true, isTrue);
  }, timeout: const Timeout(Duration(seconds: 1)));
}
```

**Expected behavior**
Test runner should timeout test according to documentation and report as test failure.

**Environment**
- Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "macos_arm64"
- Operating system: macOS Ventura 13.4.1 (c)
- Package version: Test 1.24.6

**Comment by SandPod** [comment]
@jakemac53 Aah, my bad. Missed that part of the documentation.
Thanks for the clarification.

Is there any support from the framework to limit the test execution time regardless if the test is making progress or not?

**Comment by jakemac53** [comment]
There is not a general timeout mechanism at this time. It is a bit hard to implement in Dart due to the single threaded nature, but we should be able to implement it on the test host side of things.

I am not sure how we would want to surface this to users though. Would you mind filing a separate issue for that?

**Comment by SandPod** [comment]
I can fix that!

For anyone ending up here looking for a temp solution you could use isolates like this:

```
import 'dart:async';
import 'dart:isolate';

import 'package:test/test.dart';

int countForever(int n) {
  var count = 0;
  for (var i = 0; i < n; i++) {
    count++;
  }

  return count;
}

class RunWithTimeout {
  final Duration timeout;
  final Function function;
  String reason;

  _runWithPort(SendPort sendPort) {
    var value = function();
    sendPort.send(value);
  }

  RunWithTimeout(this.timeout, this.function, this.reason);

  Future run() async {
    var receivePort = ReceivePort();
    var isolate = await Isolate.spawn(_runWithPort, receivePort.sendPort);
    var resultStream = receivePort.asBroadcastStream();

    try {
      var result = await resultStream.first.timeout(timeout);
      return result;
    } on TimeoutException {
      fail(reason);
    } finally {
      // Close the isolate
      isolate.kill(priority: Isolate.immediate);
    }
  }
}

void main() {
  test('Test 3', () async {
    var timeout = Duration(seconds: 2);
    var result = await RunWithTimeout(
      timeout,
      () => countForever(10000000000000000),
      'Computation did not complete in time',
    ).run();
    expect(result, equals(10));
  });
}
```

**Comment by jakemac53** [comment]
Yeah the test host is already a separate app from the main one, so we should also be able to do a timeout there which is purely time based.

A solution like you have here works for some cases but not all, since you don't have shared state with the other isolate.

**Comment by SandPod** [comment]
Added a feature suggestion here now: https://github.com/dart-lang/test/issues/2078.

Thanks for the support @jakemac53
