### ISSUE TITLE
[ERROR] Deferred library load doesn't work inside browser tests

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/test#2088]
When `dart2js` is used by the package [test][pkg_test_github] it's not
able to serve the `...part.js` file.

You can reproduce the bug running the test of this repository:
https://github.com/gmpassos/deferred_lib_issue

```shell
dart test -p chrome
```

Error output:
```text
...

00:08 +0 -1: test/main_test.dart: View Test [E]                                                                                                                                                       
  DeferredLoadException: 'Loading http://localhost:50656/Sa1ttbh3Sd59FoFnteBXDihHx9rZDIUn/test/main_test.dart.browser_test.dart.js_1.part.js?dart2jsRetry=3 failed: Instance of 'Event'
  Context: js-failure-wrapper
  event log:
  {"p":"main_test.dart.browser_test.dart.js_1.part.js","e":"downloadFailure","l":"view_deferred","s":"http://localhost:50656/Sa1ttbh3Sd59FoFnteBXDihHx9rZDIUn/test/main_test.dart.browser_test.dart.js","i":13}
  {"p":"main_test.dart.browser_test.dart.js_1.part.js","e":"download","l":"view_deferred","i":12}
  {"p":"main_test.dart.browser_test.dart.js_1.part.js","e":"startLoad","l":"view_deferred","i":11}
  {"p":"main_test.dart.browser_test.dart.js_1.part.js","e":"retry2","l":"view_deferred","i":10}
  {"p":"main_test.dart.browser_test.dart.js_1.part.js","e":"download","l":"view_deferred","i":9}
  {"p":"main_test.dart.browser_test.dart.js_1.part.js","e":"startLoad","l":"view_deferred","i":8}
  {"p":"main_test.dart.browser_test.dart.js_1.part.js","e":"retry1","l":"view_deferred","i":7}
  {"p":"main_test.dart.browser_test.dart.js_1.part.js","e":"download","l":"view_deferred","i":6}
  {"p":"main_test.dart.browser_test.dart.js_1.part.js","e":"startLoad","l":"view_deferred","i":5}
  {"p":"main_test.dart.browser_test.dart.js_1.part.js","e":"retry0","l":"view_deferred","i":4}
  {"p":"main_test.dart.browser_test.dart.js_1.part.js","e":"download","l":"view_deferred","i":3}
  {"p":"main_test.dart.browser_test.dart.js_1.part.js","e":"startLoad","l":"view_deferred","i":2}
  {"p":"main","e":"beginPart","i":1}
  '

...
```

### Dart Version:
```shell
dart --version
```

```text
Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_x64"
```

------

The issue can be fixed at:

https://github.com/dart-lang/test/blob/master/pkgs/test/lib/src/runner/browser/platform.dart

[pkg_test_github]: https://github.com/dart-lang/test/blob/master/pkgs/test

**Comment by sigmundch** [comment]
Thanks so much for filing this issue! I've transferred it to the package:test github issue tracker, since this appears to be an issue there.

Sometimes it's valuable to be able to write tests that use deferred loading, but I agree it can often be helpful to just disable it.

There is a dart2js flag to disable the split: `--disable-program-split`, so it would just be a matter of plumbing this through.

**Comment by sigmundch** [comment]
According to https://pub.dev/packages/test#compiler-flags, it seems possible to pass this flag when invoking the test runner. Does your test work if you pass `--dart2js-args="--disable-program-split"`? (to be honest, I'm not sure if this is the right flag format)

**Comment by gmpassos** [comment]
I have tested it with `--dart2js-args="--disable-program-split"` and now it's working (after fix the test).

I have updated the project and added an extra CI workflow job. Now you can see that the test with the default configuration (`test_chrome_normal`) is failing and the one disabling deferred libraries (`test_chrome_disable_program_split`) is working:

https://github.com/gmpassos/deferred_lib_issue/actions/runs/6089670634/job/16522963991

**Comment by sigmundch** [comment]
The flag is designed to preserve semantics, modulo loading files from the network, so the only downside is that it's loading more code upfront that may not be necessary. It's rare that developers want to test the actual network loading in their unit tests, but that's the other piece that would be missing from using the flag.

I think using the flag makes sense, unless you think the alternative is simple to support (e.g. to serve all the .js files together)

**Comment by jakemac53** [comment]
The flag would be easier, but I am sure we could do it either way.

**Comment by gmpassos** [comment]
You just need to make 'Dart2JsCompilerPool.compile' to return the output files. Then you can use this list to map the files to serve.

**Comment by jakemac53** [comment]
> You just need to make 'Dart2JsCompilerPool.compile' to return the output files. Then you can use this list to map the files to serve.

Dart2js doesn't actually tell you all the output files, but yeah we can likely just glob for them, which I plan to try first.
