### ISSUE TITLE
Use source maps to Dartify browser stack traces

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#21]
Once we support browser tests, we should use the source maps generated by dart2js to convert their JS stack traces back into Dart traces. @cbracken has some code to do this, but it's not currently written in Dart.

**Comment by zoechi** [comment]
https://pub.dartlang.org/packages/source_maps seems to do that

**Comment by nex3** [comment]
I don't think it has that feature yet... what API are you looking at?

**Comment by zoechi** [comment]
I just wanted to point it out. 
I thought
> A parser that reads the source map format and provides APIs to read the mapping information.
should be what is needed to implement translation from JS stack trace to Dart stack trace.
I tried to implement it myself in test but wasn't able to figure out yet where this should be added.

**Comment by nex3** [comment]
It certainly parses source maps, but that's not the same as using them to resolve stack traces.
