### ISSUE TITLE
setUp and setUpAll show as deprecated in Dart projects because scaffolding.dart is marked deprecated

### ISSUE THREAD

**Issue by DanTup** [dart-lang/test#2111]
(raised by @osaxma at https://github.com/Dart-Code/Dart-Code/issues/4766)

This is similar to https://github.com/dart-lang/test/issues/1990 which was fixed by https://github.com/dart-lang/test/pull/1994. However, the removal of `@Deprecated` was only done to `test_api` and it's still in `test_core`:

https://github.com/dart-lang/test/blob/de324cc78efb3ecc10bcf97d560db72bab1c5ee5/pkgs/test_core/lib/scaffolding.dart#L5-L6

This causes `setUp` and `setUpAll` to show as deprecated in a Dart project:

![image](https://github.com/dart-lang/test/assets/1078012/4d262eff-7135-4ff1-a1c7-aae44768f65d)

**Comment by natebosch** [comment]
@bwilkerson - are there any bugs files for inconsistency between which deprecated diagnostics show up in `dart analyze`, and which show up as deprecated during autocomplete?

I'd be fine removing the deprecation from the defining library and move it to deprecating a library with only an `export` - will that resolve the autocomplete experience?

**Comment by DanTup** [comment]
https://github.com/dart-lang/sdk/issues/52163 (and the comment at https://github.com/dart-lang/sdk/issues/52163#issuecomment-1522065904) seem related.
