### ISSUE TITLE
next roll to dart-lang/sdk will require some test expectations updates

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/test#2126]
The next roll to dart-lang/sdk will require some test expectations updates (in CFE tests, and perhaps the debugger stepping tests?).

Potentially as a result of this commit: https://github.com/dart-lang/test/commit/ba050ae2a49a00c382dae6996ba171849d089f81.

**Comment by jakemac53** [comment]
@natebosch can you handle this one?

**Comment by natebosch** [comment]
Yes. I'll start rolling in https://dart-review.googlesource.com/c/sdk/+/334300 and see what fails
