### ISSUE TITLE
VM platform fails to compile tests under `lib`

### ISSUE THREAD

**Issue by koutaro-masaki** [dart-lang/test#2142]
I want to follow the principle of colocation and place test code next to the code being tested. However, when the code being tested uses a combination of relative and absolute imports within a dependency, and also involves class inheritance, the inheritance hierarchy breaks during test execution, resulting in an error. Is there a way to avoid this?

While importing the code being tested with absolute imports from the test code prevents errors, I would prefer not to do this if possible, as it might not clearly indicate that the code being tested is imported from the colocated test. Alternatively, it is possible to avoid errors by enforcing the use of either absolute or relative imports exclusively within the library code, but this is not practical.

This is the minimal reproducing code.
https://github.com/koutaro-masaki/dart_test_issue_sample

```
00:01 +0 -1: loading lib/bar_test.dart [E]                                                                                                                                                                                             
  Failed to load "lib/bar_test.dart":
  lib/bar.dart:6:12: Error: The argument type 'Bar' can't be assigned to the parameter type 'Foo'.
   - 'Bar' is from 'lib/bar.dart'.
   - 'Foo' is from 'package:dart_test_issue_sample/foo.dart' ('lib/foo.dart').
    return f(Bar());
             ^
```

**Comment by jakemac53** [comment]
> I want to follow the principle of colocation and place test code next to the code being tested.

Following this strictly will not work well in dart, because it doesn't follow our [package layout conventions](https://dart.dev/tools/pub/package-layout).

And in fact, doing this for a package dependency would have concrete negative effects (dependencies which should be dev only dependencies for the package would become real dependencies).

What many packages instead do is mirror the structure of their `lib` directory under their `test` directory, which still allows you to easily find the tests for any given file based on convention, so `lib/bar.dart` would be tested at `test/bar_test.dart` for instance.

**Comment by jakemac53** [comment]
It is worth noting though that typically a Uri like `lib/bar.dart` should have been converted to the corresponding `package:` uri, to avoid the issue you are seeing. I am not sure exactly why that isn't happening, maybe frontend_server (which we use for compilation) does not automatically do this conversion like `dart compile <path>` does, and we should be doing it before calling frontend_server.

**Comment by koutaro-masaki** [comment]
We believe that mirroring poses challenges in terms of operational and maintenance aspects of the codebase, and this is precisely why it requires colocation. 
https://kentcdodds.com/blog/colocation#tests

Maintaining mirroring incurs significant costs. Every time a file is moved or deleted, attention must be paid to also move the corresponding test code. As the codebase grows, the costs increase, and this unconsciously leads to avoiding the organization of the codebase, hindering refactoring efforts. Additionally, Verifying test existence becomes challenging and more prone to developer oversight.

If there are technical reasons that make colocating test code challenging, I understand. However, I believe it would be even more beneficial if this becomes feasible.

**Comment by jakemac53** [comment]
Regardless of the merits (I think there are trade-offs either way), I do think that the test package should support being able to execute test files in _any_ directory. You will have to do some manual configuration to actually run the tests (changing the default glob for test files), but that is fine.

I am happy to leave this issue open as I think there is a legitimate bug involved with the URIs not being canonicalized to their `package:` equivalents.

**Comment by natebosch** [comment]
> I would prefer not to do this if possible, as it might not clearly indicate that the code being tested is imported from the colocated test.

I don't understand this. Are you saying you rely on a convention that a relative import indicates something unique about that import compared to the others?

> Alternatively, it is possible to avoid errors by enforcing the use of either absolute or relative imports exclusively within the library code, but this is not practical.

What makes it impractical? AFAIK many projects are using lints to enforce absolute imports without complaint.
https://dart.dev/tools/linter-rules/always_use_package_imports

> I do think that the test package should support being able to execute test files in _any_ directory.

+1. If we wanted to be more forceful about the structure we should have done it from the start. Making `test/` an enforced directory over a convention is likely to cause more pain for users than it benefits us as maintainers. Making test code under `lib/` run smoothly would be better.

> I am happy to leave this issue open as I think there is a legitimate bug involved with the URIs not being canonicalized to their `package:` equivalents.

Yeah I'd be happy to accept a  PR that makes them work well. I don't think it should be a priority given that using full `package:` URIs can workaround the issue.

**Comment by jakemac53** [comment]
I do have a regression test for this ready so I could also send that out (will be skipped since it fails). That might make a future fix easier

**Comment by koutaro-masaki** [comment]
> > I would prefer not to do this if possible, as it might not clearly indicate that the code being tested is imported from the colocated test.

> I don't understand this. Are you saying you rely on a convention that a relative import indicates something unique about that import compared to the others?

If you follow [the rule of 'placing test code files next to the files they are testing,'](https://kentcdodds.com/blog/colocation#tests) using relative imports helps make it clearer that you are importing code from the nearby file under test. While this might be a matter of personal preference, I personally find it more intuitive. 

> > Alternatively, it is possible to avoid errors by enforcing the use of either absolute or relative imports exclusively within the library code, but this is not practical.

> What makes it impractical? AFAIK many projects are using lints to enforce absolute imports without complaint.
https://dart.dev/tools/linter-rules/always_use_package_imports

I am not a native English speaker and rely on machine translation, so if I unintentionally made overly strong or offensive claims, I apologize.
I meant to convey that, 'Relative imports have their own merits, and in projects that already support and extensively use relative imports, changing them solely to avoid peculiar behavior during test execution might be hard to understand.'

**Comment by jakemac53** [comment]
I do think it is worth mentioning, that regardless of whether we fix this, it is not an issue that has come up before. So you would be in the strong minority (quite possibly only person in the Dart ecosystem) who is doing it this way.

Whatever benefits you believe you are getting by following this pattern, it is going against the ecosystem norms, which will be likely to cause you other problems with other tools.

Generally, the Dart ecosystem relies on "convention over configuration" pretty heavily, which simplifies our tooling and brings consistency to the ecosystem. Pretty much all packages have the same basic layout, etc. There are a ton of small benefits that this provides, which you would lose when you step outside of those conventions.

**Comment by jakemac53** [comment]
> I am not a native English speaker and rely on machine translation, so if I unintentionally made overly strong or offensive claims, I apologize.

Your tone was perfectly respectable, no worries 👍 ! Nate was just seeking clarification.
