### ISSUE TITLE
Add `@doNotSubmit` to the `test` method's `solo` parameter

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/test#2205]
In the latest version of `package:meta`, we added a [`@doNotSubmit`](https://pub.dev/documentation/meta/latest/meta/doNotSubmit-constant.html) annotation:

> Used to annotate a method, getter or top-level getter or function that is not intended to be accessed in checked-in code, but might be ephemerally used during development or local testing.
>
> The intention of this annotation is to signify an API is available for temporary or ephemeral use (such as debugging or local testing), but should be removed before the code is submitted or merged into a tested branch of the repository (e.g. main or similar).

I'd like to replace the `@Deprecated` on `solo` with `@doNotSubmit`. This would mean that it becomes an analysis diagnostic, even for projects that ignore deprecated warnings, or have opted-out using `// ignore: ...`. In practice I think the effects of this change are minimal. For example:

- No [usages of `/bsolo/b` in `org:flutter`](https://github.com/search?q=org%3Aflutter+%2F%5Cbsolo%5Cb%2F&type=code)
- No [usages of `/bsolo/b` in `org:dart-lang`](https://github.com/search?q=org%3Adart-lang+%2F%5Cbsolo%5Cb%2F&type=code)
- A [wider search](https://github.com/search?q=lang%3Adart+%2F%5Cbsolo%5Cb%5Cs*%3A%5Cs*%2F&type=code) also does not show anything checked-in.
- Google3 has a few examples of this being used, I suspect they are accidents and should be fixed anyway.

Anyway, writing this for transparency and to get feedback, if any.

/cc @natebosch @kevmoo @yjbanov

**Comment by jakemac53** [comment]
SGTM :shipit:

**Comment by kevmoo** [comment]
Please!

**Comment by natebosch** [comment]
SGTM.

When we make the switch users who are not on the latest SDK will not get any diagnostic. I don't think the missing deprecation message is likely to have a wide impact. I'm inclined to switch over at once instead of leave something to clean up later - but we could leave both annotations for some time if anyone is concerned.

**Comment by matanlurey** [comment]
My take is to just switch over, it's a hint not a lint so I don't think _removing_ the deprecation affects anyone?

**Comment by natebosch** [comment]
> I don't think _removing_ the deprecation affects anyone?

It would only effect folks who are failing CI on deprecation diagnostics and relying on that to avoid checking in a `solo:` argument.

**Comment by matanlurey** [comment]
> It would only effect folks who are failing CI on deprecation diagnostics and relying on that

But then they would start failing on `invalid_use_do_not_submit_member`. I guess you're suggesting folks might have turned off all _other_ failures. I would _also_ be OK with keeping it for a release in that case.

**Comment by natebosch** [comment]
> But then they would start failing on `invalid_use_do_not_submit_member`

Only if they are on a new enough SDK. A typical CI setup should use a new SDK so I'd expect most problems should still be caught.
