### ISSUE TITLE
../../.pub-cache/hosted/pub.dev/test_api-0.7.3/lib/src/scaffolding/test_structure.dart:81:32: Error: Undefined name 'doNotSubmit'.

### ISSUE THREAD

**Issue by Henrydykee** [dart-lang/test#2416]
Describe the bug in detail.
Include the specific command you ran and any relevant details about the
environment, including operating system, Dart SDK version, and the version of
`package:test` you are using.
Whenever possible, include a full reproduction example that we can run to
observe the problem.

**Comment by jakemac53** [comment]
This was introduced in [package:meta 1.14.0](https://pub.dev/packages/meta/changelog#1140) which matches the constraint set [when this usage was introduced](https://github.com/dart-lang/test/pull/2206/files#diff-80e1967179ddeafb92df396f3362284a243c1b1ec5d03441b967b2d96b6d1180R14).

So, you most likely have some `dependency_overrides` which are causing the issue. You will need to ensure you have a version of package:meta that is at least `1.14.0` to fix this issue.
