### ISSUE TITLE
`dart fix --fail-fast` runs full loops to complete

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/test#2417]
Coming from https://github.com/dart-lang/sdk/issues/57118.

We have 100 runs for the following code for `Test $i`. Even with `--fail-fast` the full loops are completed before the test stops. Can this be fixed so that if a test fails (with `--fail-fast`) it works as a `break` in all loops or something?

Repro:

```dart
import 'package:test/test.dart';

void main() {
  group('Tests', () {
    for (var i = 0; i < 100; i++) {
      group('Tests J $i', () {
        for (var j = 0; j < 100; j++) {
          print('Test $i - $j');
          test('Test $i', () {
            expect(i, 1);
            expect(j, 1);
          });
        }
      });
    }
  });
}
```

**Comment by jakemac53** [comment]
`group`, `test`, `setUp`, and `tearDown` calls all just define tests to run later. They do not immediately run when the function is invoked.

When using `--fail-fast`, we will still collect all tests, and after `main` completes (waiting for any future it returns), then we will actually run tests (one at a time), and exit immediately on the first failure.

**Comment by jakemac53** [comment]
(if you move the print inside the call to `test` you should see that the other tests don't run)

**Comment by FMorschel** [comment]
As a background. This is coming from my package https://github.com/FMorschel/due_date/. If you take a look at this group https://github.com/FMorschel/due_date/blob/main/test/date_validator_test.dart#L233-L291 you can see there are lots of inner loops so it's easier to test a lot of cases. But when running this with `fail-fast` (and making a test fail there) you'll see that it takes some seconds to wrap things up after the test has already failed. I was the one who asked you this on Discord.

By your definition of how it works, I don't see how they would keep processing anything before it stops, but it does _something_.

Sorry if I wasn't clear enough.

**Comment by jakemac53** [comment]
That link doesn't work for me, so I can't take a look at it (maybe it needs to point at a branch?).

> By your definition of how it works, I don't see how they would keep processing anything before it stops, but it does _something_.

It will still run any `tearDown` functions, as well as completing the `test` function for the test that failed (these are considered a part of the test).

What is the output  you see? How many tests does it report as having been ran?

**Comment by jakemac53** [comment]
Another thing is making sure any significant setup logic is done inside a `setUp` or `setUpAll` function. Otherwise if it happens outside a `test` function, it will still always run.

**Comment by FMorschel** [comment]
This group - I'd just refactored this package for easier maintenance- here is a link to that commit: https://github.com/FMorschel/due_date/blob/2e0d940e8a17bbdd3908070583ae183562cc8447/test/date_validator_test.dart#L233-L291

After my refactor to separate the groups for classes into different files it runs just fine. 

> Another thing is making sure any significant setup logic is done inside a setUp or setUpAll function. Otherwise if it happens outside a test function, it will still always run.

Maybe I could try and refactor it with this? I'm not sure.

> What is the output you see? How many tests does it report as having been ran?

It still says the right amount, it just stays there after the first failing one for a few seconds before ending the process.

**Comment by jakemac53** [comment]
> It still says the right amount, it just stays there after the first failing one for a few seconds before ending the process.

I can't repro this behavior, for instance adding this test at the top of main:

```dart
  test('test', () {
    expect(true, isFalse);
  });
```

It exists essentially immediately as soon as that test fails.

I also tried adding a failing expectation inside the inner loop, and as soon as a test failed it exits for me.

**Comment by jakemac53** [comment]
In general though you could have fewer `test` function calls, and instead move most of the loops inside of the `test` functions. You can still get nice error text by providing a `reason` to each of the expect calls.

**Comment by FMorschel** [comment]
Alright then, I'll try that. Thanks a lot!
