### ISSUE TITLE
Add stream matchers

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#25]
Currently there's no good way to validate stream values other than calling `toList()` and validating that. This isn't a great option for ensuring that streams produce the right values at the right times, or for streams that never close.

`scheduled_test`'s [`ScheduledStream` matchers](http://www.dartdocs.org/documentation/scheduled_test/0.11.7/index.html#scheduled_test/scheduled_test-scheduled_stream) are a good baseline for functionality. We don't want to depend on `ScheduledStream`, but the `async` package has a `StreamQueue` class that provides similar functionality without being tightly coupled with `scheduled_test`. For maximum flexibility, the new stream matchers should work against either a raw `Stream` or a `StreamQueue`.

It would also be good to support a `both(streamMatcher1, streamMatcher2)` matcher, which asserts that both matchers match the stream. Like `either()`, the stream should be consumed up to the maximum consumed by both matchers.

**Comment by kevmoo** [comment]
Should this go into the https://github.com/dart-lang/matcher package?

**Comment by nex3** [comment]
No; like the other asynchronous matchers, this belongs here.

**Comment by nex3** [comment]
This was done in 192b6c4d.
