### ISSUE TITLE
Can't catch errors in when mocking Future.error

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/test#269]
When a mockito mock returns a `Future.error()`, tests will fail if there are any functions using async/await that are handling errors.

It's unclear if this is an issue with mockito, async/await, or the test package, so I also created an [issue for mockito](https://github.com/fibulwinter/dart-mockito/issues/13#issuecomment-110771786).

[Heres an example project to help illustrate the problem](https://github.com/johnpryan/mockito_async).  It is using the latest version of [test](https://pub.dartlang.org/packages/test) and mockito.  This issue also occurs with unittest 0.11.x and mockito 0.8.x.

@nex3  @kevmoo

**Comment by nex3** [comment]
This definitely isn't an issue with `test`. It reproduces with the following test-free script:

```dart
import 'dart:async';
import 'package:mockito/mockito.dart';

import 'package:mockito_async/foo.dart';

class MockFoo extends Mock implements Foo {
  noSuchMethod(inv) => super.noSuchMethod(inv);
}

class MockFooSync extends Mock implements FooSync {
  noSuchMethod(inv) => super.noSuchMethod(inv);
}

void main() {
  var foo = new MockFoo();
  when(foo.doStuff()).thenReturn(new Future.error('mock error'));

  tryFoo(foo).catchError((e) {
    // Do nothing
  });
}
```

Keep in mind that `new Future.error()` will top-level an error itself if a `catchError` isn't *synchronously* added to it after it's created. I suspect that's the root of the problem, although I don't know why your `catchError` isn't working.

**Comment by bunopus** [comment]
This problem could be solved with thenAnswer
```dart
when(foo.doStuff()).thenAnswer((_) => new Future.error('mock error'));
```
https://github.com/fibulwinter/dart-mockito/issues/13#issuecomment-116013145
