### ISSUE TITLE
What are the differences/trade-offs between these two ways of running tests?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/test#272]
Hi,

Can you help me understand the pros/cons of these two ways to run the tests?

`dart --checked test/all.dart`

or

`pub run test`  (assumes I have the latest SDK and checked mode is turned on)

?

Thanks!

**Comment by sethladd** [comment]
One difference, is that `dart --checked test/all.dart` is 5 seconds faster than `pub run test` on dartdoc tests on my machine.

Not sure what's the difference?

**Comment by kevmoo** [comment]
`pub run test`
* Requires the pub infrastructure to warm up. @nex3 recently added some code that should (?) make this faster.
* It does discovery of tests, which requires parsing through each test file looking for annotations, etc.

If you have many tests in separate files, you'll likely get a win with `pub run test` because it can run each test file in a separate isolate.

**Comment by sethladd** [comment]
Are you saying that there are no other differences between the two?

Meanwhile, what does "pub infrastructure to warm up" mean? Why do I need pub infrastructure to run my tests? (what are the benefits?)

**Comment by zoechi** [comment]
What I have gathered `dart --checked test/all.dart` will decease to be supported when debugging works with `pub run ...`. You can't use some of the features of `pub run test` like selecting the platform or which tests to run (see `pub run test -h` for more details) 
Currently debugging and choosing checked/production mode is only supported with `dart -c test/xxx.dart`. 
You can't run browser tests with `dart -c test/xxx.dart`.

**Comment by nex3** [comment]
@sethladd

Running a test file manually via `dart` is meant as a quick-and-dirty shortcut, but it doesn't (and can't) support many of the features of the test runner, including parsing command-line arguments (which means that there's no way of selecting a single test to run) or suite-level metadata (which means there's no way of only running test suites on platforms they support). Many features that are planned for the future, like configuration files and plugins, also won't work with files run directly via `dart`.

> One difference, is that `dart --checked test/all.dart` is 5 seconds faster than `pub run test` on dartdoc tests on my machine. It's the difference between 10 secs and 15 seconds.

@kevmoo's right that I have a patch to help mitigate this; see f5efdf6a412f9ae72e40e5d2f7b0c7f50ff05505. A lot of it is just dart-lang/sdk#20470, though; `pub run test` loads pub, the test runner, and a bunch of test files in separate isolates, which means that the VM's code-loading performance becomes very important.

@zoechi 

> What I have gathered `dart --checked test/all.dart` will decease to be supported when debugging works with `pub run ...`.

This isn't quite accurate. We will no longer support running test files directly *in the browser* once we have a good debugging story. We plan to support running test files directly from the command line indefinitely.

**Comment by zoechi** [comment]
@nex3 thanks for clarification, I'm glad to hear this can also be used in the future.

**Comment by sethladd** [comment]
Thanks for the background info! It's really helpful to understand why someone might choose to run tests via `pub run`.

> Many features that are planned for the future, like configuration files and plugins, also won't work with files run directly via dart.

Curious, why is that?

**Comment by kevmoo** [comment]
> Curious, why is that?

When you just run `dart test/foo_test.dart` there is NO plumbing. It's a very simple run that effectively maps to what the old `unittest` did.

The plumbing is what Natalie talked about: configuration files, plugins, parsing platform information, etc.

**Comment by sethladd** [comment]
> When you just run dart test/foo_test.dart there is NO plumbing

Ah, so the plumbing is only booted by by `pub run test`... gotcha. I guess the equivalent would be something like: `dart packages/test/lib/test.dart --find-tests etc`

**Comment by nex3** [comment]
> > Curious, why is that?
> 
> When you just run `dart test/foo_test.dart` there is NO plumbing. It's a very simple run that effectively maps to what the old `unittest` did.

Also, the test file itself has to be cross-platform (since it's imported in the browser). There's no way to use `dart:io` to do something like reading and parsing the file text.
