### ISSUE TITLE
"Dummy exception to set exit code"

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/test#278]
While using test in an asynchronous environment, I got that error message from within test somewhere.

I located the origin, and it's on this line, a `Future.error` object: https://github.com/dart-lang/test/blob/master/lib/test.dart#L69

What does it mean to get this error? Is it supposed to reach end users or is this a bug?

(This is the complete stacktrace, must it be useful: https://gist.github.com/stevenroose/7a10a74413f319ac091c)

**Comment by nex3** [comment]
What do you mean by "using test in an asynchronous environment"?

This exception is only intended to arise when running a test file directly using `dart path/to/file.dart`, but it may happen if you're calling `test()` or `group()` from non-test code (something that is emphatically not supported).

**Comment by stevenroose** [comment]
I meant that I'm using a test server so that all tests are async. But they use the "completes" expector, so they should be fine. The exact test from which the error rises is here:
https://github.com/stevenroose/ripple-lib-dart/blob/master/test/remote/remote_requests.dart#L58

So it is in a test inside a group. I run the tests using IntelliJ IDEA (not the "Run tests in file.dart" run config, but just "Run file.dart").

**Comment by nex3** [comment]
How do you know that's where the test comes from? Are you sure the tests aren't just failing? This is the expected behavior for failing tests if you're running them directly (which is presumably what your IDE is doing).

**Comment by stevenroose** [comment]
Well, the test was failing, why should a Dummy exception be thrown instead of a test failed message?

**Comment by nex3** [comment]
It should be thrown in addition to the error message, and it should always happen.

As the exception message indicates, it exists to set the exit code. It's important that a failing test have a non-zero exit code so that it can be scripted, and an unhandled exception is the only way to make that happen without using `dart:io`, which `dart path/to/file.dart` can't use. Dart's own test infrastructure relies on this, for example.

In general, you should be running your tests through `pub run test`. There's probably a way to configure your IDE to do that.

**Comment by stevenroose** [comment]
Ah, I get it. The Dummy exception is just the "Some tests failed" exception that `unittest` used to throw?

On the IDE fun configs, now that IDEA/WebStorm is the suggested Dart IDE, I suppose `pub run test` will arrive in the Dart plugin sooner or later?

**Comment by nex3** [comment]
You'd have to ask @jwren or someone else working on the plugin.

**Comment by zoechi** [comment]
https://youtrack.jetbrains.com/issue/WEB-16053
