### ISSUE TITLE
Support failing_test for the red phase in TDD

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/test#28]
It would be cool if there was a way to signify that a test is supposed to fail (without changing the test body itself). This happens in the first phase of TDD.

Something like: failing_test('description', () {...}). This would allow me to checkin tests with the correct expectation and when I make the tests go green, I can just change it to the normal test without changing the test body itself.

**Comment by nex3** [comment]
I think #395 is the best way to handle something like this.
