### ISSUE TITLE
can I test IE on a mac (using parallels)

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/test#280]
I have IE installed at my mac using parallels, it is somehow possible to run my test on internet explorer using the test package ?

**Comment by kevmoo** [comment]
You'd have to get your code onto the parallels image and run them there.

**Comment by nex3** [comment]
#99 is tracking the ability to write custom plugins for launching browsers; once that's in place, you'll be able to write a plugin that communicates to your Windows instance and gets it to start the browser. This isn't something we're planning to support directly, though.

**Comment by kasperpeulen** [comment]
@kevmoo ah okay, I just thought it would be really nice if I could test all 5 major browsers in one run

@nex3 nice :)
