### ISSUE TITLE
support filtering tests e.g. by filename or annotation

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/test#282]
I have some tests that are integration tests and take a little longer to run. I'd like to be able to do things like: run units tests but skip integration tests or vice versa.

Two obvious implementation options:

- filename pattern (all mine are named <name>_integration_test.dart)
- annotation (e.g. @TestType('integration'))

**Comment by zoechi** [comment]
There are two name options already for group and test description. You can specify the folder where tests should be looked up and there is an open issue to support tags. Do you really think there should be additional options?

**Comment by Andersmholmgren** [comment]
My context is from running via [jefe](https://pub.dartlang.org/packages/jefe)

I have a command

```
jefe test
```

which executes `pub run test` on all my projects that have a test dir and does this concurrently.

I manage over 40 dart packages in one go and this saves a loooot of time.

But also I execute the tests as part of the release flow `jefe release` so that a package will not be released if its tests don't pass.

So for this use case it is not practical to know all the filenames I want to test in all the (> 40) projects. I need some general way to classify tests.

Unless I'm missing something I don't see anything that currently supports this use case

**Comment by nex3** [comment]
You're effectively describing tags as they're described in #16.
