### ISSUE TITLE
Adding node.js as a testing target.

### ISSUE THREAD

**Issue by mbullington** [dart-lang/test#284]
Hello, would you be open to adding node.js as a target for the test package? I currently need this for a Dart project that uses dart:js to access node.js modules.

I'd be fine with implementing this in the form of a pull request, just wanted to gather some feedback first on how you'd like this implemented.

A prerequisite of this would be having a dart2js preamble for node.js that works well, which you can find the issue for [here](https://codereview.chromium.org/1229663002).

**Comment by nex3** [comment]
I think this is a good use-case for a launcher plugin (see #99), rather than something built into the runner itself.
