### ISSUE TITLE
Running tests in unchecked mode

### ISSUE THREAD

**Issue by joeconwaystk** [dart-lang/test#285]
I have reviewed previous issues indicating that there is not a compelling reason to allow for tests in unchecked mode. Sometimes, though, in dynamically typed languages it makes sense to 'abuse' the type system to support certain features. For example, I'd like to deserialize a JSON object (or the result of a DB query) into a Model object. Not all properties in the model object will get set if they are not available in the source data, but some properties may have an explicit null value, e.g. a model object defines as:

```dart
class Model {
    String id;
    String name;
}
```

Parsing JSON containing just 'id':

```json
{ "id" : "123567"}
```

Would yield a Model object where expect(model.name, null) is true. However, the following JSON would yield the same result:

```json
{"id" : "123567", "name" : null}
```

Here, a viable solution would be to have some object that represents either 'Explicitly Null' or 'Undefined Null'. This object would have to be assignable to many types - so testing it becomes impossible given the current test framework. If I were to submit a pull request that allowed an explicit disable of checked mode, would it be accepted? (I see that the boolean param for runInIsolate contains this option, but is always called with true.)

**Comment by nex3** [comment]
The answer is the same as for #111: code that only runs in unchecked mode runs strongly counter to Dart best practices. The test framework isn't going to add a feature that's primarily useful for bad Dart.

For your use case, it seems like you could probably just use more untyped variables. As far as I know, there are no situations where checked mode will complain that couldn't also be addressed by removing type annotations.
