### ISSUE TITLE
content-shell seems to be run without `--dump-render-tree`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#289]
I think the main purpose of content-shell is to be able to run browser tests on a headless system. Without `--dump-render-tree` there is no real difference to running the tests in Dartium.

See also travis-ci/travis-ci#3851

**Comment by kevmoo** [comment]
I think we do...

https://github.com/dart-lang/test/blob/master/lib/src/runner/browser/content_shell.dart#L36

**Comment by zoechi** [comment]
Weird, I searched the code and didn't come up with a search result for `dump-render-tree`. Stupid GitHub. Searching for `--dump-render-tree` works. Thanks! Any idea why `pub run test --pcontent-shell` might fail on travis without `xvfb`?

**Comment by kevmoo** [comment]
It always needs some UI stack – even headless. It still renders everything, it just doesn't open any windows.
