### ISSUE TITLE
Feature Request: print number of tests than ran

### ISSUE THREAD

**Issue by juliemr** [dart-lang/test#291]
It would be a good sanity check to know how many tests actually ran, especially when tests can be skipped because you're not running on the right platform.

**Comment by nex3** [comment]
I'm confused... doesn't the final line of output for both the compact and expanded runners (e.g. `00:04 +102: All tests passed!`) include this information?

**Comment by juliemr** [comment]
Oops, my bag. I ignored the `+XXX` bit, I had been assuming it was test duration.

**Comment by juliemr** [comment]
(Maybe this is a sign that the interface isn't obvious enough though? Or maybe I'm just oblivious.)

**Comment by nex3** [comment]
It's always a tough balance between making it clear and making it terse, especially in a line that shares limited real estate with potentially-long test names. Hopefully most of the time it's clear enough.
