### ISSUE TITLE
Feature Request: print number of tests skipped

### ISSUE THREAD

**Issue by juliemr** [dart-lang/test#292]
It would be nice to know if some test files were skipped because they were not on the correct platform.

**Comment by nex3** [comment]
This is more or less what the `@Skip` annotation is for: skipping tests visibly. I think it would mostly just be distracting if all tests whose platforms didn't match produced visible output. Also, it's not really possible to do accurately; we need to load the test file to determine what tests it defines, and it's not possible to load a test that imports `dart:io` on the browser or `dart:html` in the VM.

If you want to make sure you're running on all the relevant platforms, #46 will allow you to define which ones get used by default.

**Comment by juliemr** [comment]
I don't  know, it seems to me that without a warning, it would be very easy to miss a failure that you introduced but didn't actually run the tests for. I'd be happy with a warning that there were _some_ tests that were skipped, without needing to actually parse the file to get a number.

Sounds like #46 could take care of making sure that a random contributor (or normal contributor who is distracted) doesn't accidentally miss some command line flags.
