### ISSUE TITLE
Support --pause-after-load in visible browsers

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#294]
The simplest way to debug browsers is using the dev inspector, but by default the test runner doesn't make that easy, since browsers start and complete quickly and without user input. We should add a flag (e.g. `--pause-after-load`) that pauses the test runner after a browser has loaded a test suite to allow users to access the dev console, set breakpoints, and so forth. They should then be able to resume the test either via the command line or by clicking a link on the host page.

Obviously this will only work for browsers with visible windows. #295 and #296 track support for debugging headless browsers.

**Comment by michalpie** [comment]
When I run tests on Windows using the newest (1.16) release with

pub run test -p dartium --pause-after-load

then the test is paused, but the 'Play' button is not shown. It seems there is no way to start the tests.

**Comment by zoechi** [comment]
@michalpie I think you should create a new issue for this.
