### ISSUE TITLE
Support the Dart analyzer as a pseudo-platform

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#30]
It would be nice to be able to run the analyzer via the test runner and have any errors (or, configurably, warnings or hints) looks like test failures. It shouldn't be treated exactly like other platforms, since we want it to analyze every Dart file (even those in `lib/`) once and only once, but driving it through the test runner would be useful.

**Comment by Stargator** [comment]
What about also using the analyzer to tell us which files were recently changed? Then our framework can use it based on configuration options

**Comment by nex3** [comment]
@Stargator I'm not sure what you mean. Can you provide more details?

**Comment by Stargator** [comment]
I was thinking about having test run tests against recently changed files.

And I so I was wondering how we might get that information. It seems to me that analyze may track changes as they occur. but I'm not sure

**Comment by nex3** [comment]
It doesn't. You'd need some sort of long-running process, which is outside of the scope of this test runner.

**Comment by Stargator** [comment]
Understood, thanks @nex3

**Comment by natebosch** [comment]
We've gotten a lot of mileage out of the `dartanalyzer` cli. I don't think there is much more value we can provide from test.
