### ISSUE TITLE
pub get error: Package test has no versions that match >=0.12.3+9 <0.13.0

### ISSUE THREAD

**Issue by Kayes-Islam** [dart-lang/test#309]
Hi,

I'm adding the following to my pubspec.yaml. 
dependencies:
  test: "^0.12.3+9"

Then doing a pub get shows this error message:
Package test has no versions that match >=0.12.3+9 <0.13.0 derived from:
- <myApplication> depends on version ^0.12.3+9

I've also run pub cache repair, deleted my pubspec.lock file then did pub get again but the same error.

**Comment by zoechi** [comment]
I guess all `dependencies`, `dev_dependencies` (and `dependency_overrides`) are necessary to debug this issue. It's probably a general pub issue not test specific.

**Comment by Kayes-Islam** [comment]
Here's my pubspec.yaml:


environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  sass: '>=0.4.0 <0.5.0'
  angular: "1.1.0"
  web_components: "0.10.1"
  angular_ui: '^0.6.8'
  bootstrap: '^3.3.4'
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
  mock: ">=0.11.0+2 <0.12.0"

transformers:
- angular
- sass

**Comment by Kayes-Islam** [comment]
These are my dependencies:

dependencies:
  browser: '>=0.10.0 <0.11.0'
  sass: '>=0.4.0 <0.5.0'
  angular: "1.1.0"
  web_components: "0.10.1"
  angular_ui: '^0.6.8'
  bootstrap: '^3.3.4'
dev_dependencies:
  test: "^0.12.3+9"

**Comment by kevmoo** [comment]
This is not an issue with the test package.

`angular` restricts its use of analyzer to `<0.23.0`.
`test` requires analyzer `>= 0.23.0`

One could argue that pub could give a more helpful error here, though.

**Comment by nex3** [comment]
> One could argue that pub could give a more helpful error here, though.

This is tracked by dart-lang/pub#912.
