### ISSUE TITLE
Add a reporter that lists completed tests

### ISSUE THREAD

**Issue by enyo** [dart-lang/test#311]
As reported by #89 the current `expanded` reporter output is not what users expect of it and repeats the same .
Thank you @nex3 for explaining what is actually going on in that output, but I think that a reporter that actually lists the tests that have successfully run would be a great addition.

**Comment by nex3** [comment]
This isn't something we want to add for the same reason that we don't want to change the behavior of the existing reporter. The test package's job is to help users identify and solve problems, and one of those problems is tests that deadlock and/or time out. This means it's more important for the runner to surface which tests are currently running and thus taking a long time than it is for it to ensure that it prints every test name.
