### ISSUE TITLE
Gracefully report runtime syntax errors

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#312]
It's possible for the Dart VM to detect syntax errors at runtime. Currently the test runner handles this poorly; these error crash the test isolate, causing it to fail to report any updates to the host runner, which ultimately makes the test runner spin forever.

Fixing this is blocked on dart-lang/sdk#23684.

**Comment by nex3** [comment]
@skybrian, RE [this comment](https://github.com/dart-lang/test/issues/290#issuecomment-127843738):

The issue isn't isolate startup. Syntax errors on isolate startup are handled well; you can see for yourself if you have something like unmatched parens or curly braces. The problematic errors are ones that only occur at runtime, often while executing a specific test. Even if we determined there was an error, it would be very difficult to associate it with the correct test. This is another place where I want to get the fix in the underlying system rather than add a lot of complexity to work around it.

**Comment by kevmoo** [comment]
FYI: SDK Fixed https://github.com/dart-lang/sdk/issues/23684
