### ISSUE TITLE
group_name_test: nested empty groups are not trimmed correctly (in old unittest)

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/test#314]
I've added the following to group_name_test and it fails expectations:
```
  expectTestResults('empty group name test', () {
    group('', () {
      test('a', () {});
      group('', () {
        test('b', () {});
      });
    });
  }, [{'description': 'a'}, {'description': 'b'}]);
```
```
  Expected: b
    Actual:   b
            ^
   Differ at offset 0
```
(I assume this won't be fixed, but I'll use this as a tracking bug nonetheless.)

**Comment by nex3** [comment]
What's your goal in defining a nameless group?

**Comment by BlackHC** [comment]
Chaining setUps and tearDowns in our infrastructure code, so we wrap them
in empty groups ^^

**Comment by nex3** [comment]
That will be fixed by #313, right?

**Comment by kevmoo** [comment]
I think so...

**Comment by BlackHC** [comment]
Even then, I think this is a different issue. Empty group names should be
treated consistently. It doesn't make sense to treat a single group with an
empty name differently than nested groups with empty names. Imo, empty
names should always be collapsed.
Alternatively, empty names could be disallowed, but I think that would make
testing infrastructure code harder to write without special support for
fixtures.

**Comment by nex3** [comment]
> Even then, I think this is a different issue. Empty group names should be treated consistently.

They *are* treated consistently. They're consistent with every other group name: they're concatenated using spaces. You're asking for a special case specifically for empty names.

Groups exist for semantically organizing test cases. Unless there's a compelling use case for using them in some other way, I don't want to add a special case that makes them easier to use non-semantically.

> It doesn't make sense to treat a single group with an empty name differently than nested groups with empty names. Imo, empty names should always be collapsed.

A single group with an empty name is also concatenated using spaces, just like all groups.

**Comment by nex3** [comment]
For the record, I missed that this was "in old unittest". That may have special-cased empty description names, but we didn't carry that behavior over to 0.12.x for the reasons I outlined above.
