### ISSUE TITLE
Errors not shown when using --pub-serve

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#316]
Possibly a duplicate of https://github.com/dart-lang/test/issues/86.

When I run the tests via `pub run test -pchrome --pub-serve=8080` for the [polymer_elements](https://github.com/dart-lang/polymer_elements) repo, I see that there were failures but not which tests failed or what the errors were. 

Example output:
```
...
03:30 +110 ~3: compiling test/iron_iconset_svg_test.dart                                           
"pub serve" is compiling test/iron_iconset_svg_test.dart...
03:38 +115 ~3 -1: compiling test/iron_selector_next_previous_test.dart                             
"pub serve" is compiling test/iron_selector_next_previous_test.dart...
...
04:44 +150 ~4 -1: compiling test/iron_icon_test.dart                                               
"pub serve" is compiling test/iron_icon_test.dart...
04:51 +150 ~4 -2: compiling test/iron_pages_attr_for_selected_test.dart                            
"pub serve" is compiling test/iron_pages_attr_for_selected_test.dart...
...
07:06 +210 ~7 -2: Some tests failed.
```

With `--reporter=expanded`:
```
...
00:08 +115 ~4: test/iron_collapse_test.dart: horizontal set opened to false
00:08 +115 ~4 -1: test/iron_collapse_test.dart: horizontal set opened to false
...
00:13 +156 ~4 -1: test/google_calendar_list_basic_test.dart: <google-calendar-list> can fetch calendars
00:13 +156 ~4 -2: test/iron_list_basic_test.dart: basic features defaults
...
00:20 +210 ~7 -2: Some tests failed.
```

I also get lots of messages about the same test being ran, as you can see in the second example, but that looks like a known [issue](https://github.com/dart-lang/test/issues/86).

**Comment by jakemac53** [comment]
I am running version `0.12.4` of `test`.

**Comment by nex3** [comment]
What's in the "..."s? Can you reproduce this with a simpler setup, preferably not requiring polymer?

**Comment by jakemac53** [comment]
Here is a gist with full console output https://gist.github.com/jakemac53/09a4a256da289864bef1. I can put some work into creating a smaller repro later today or tomorrow.

**Comment by jakemac53** [comment]
hmm, I can't seem to get a simple repro for this :(

**Comment by jakemac53** [comment]
Ok, I narrowed down one of the failures to this test https://github.com/dart-lang/polymer_elements/blob/master/test/iron_localstorage_basic_test.dart#L75. Here is the output given:

```
pub run test -pchrome --pub-serve=8080 --reporter=expanded test/iron_localstorage_basic_test.dart
00:00 +0: compiling test/iron_localstorage_basic_test.dart
"pub serve" is compiling test/iron_localstorage_basic_test.dart...
00:00 +0: basic load
00:00 +1: basic save
00:00 +2: basic delete
00:00 +3: basic event iron-localstorage-load
00:00 +4: basic event iron-localstorage-load-empty
00:00 +5: basic auto-save sub-properties
00:00 +5 -1: Some tests failed.
```

**Comment by jakemac53** [comment]
looks like there was a javascript exception being thrown, which probably has something to do with it

**Comment by jakemac53** [comment]
Ok, I was able to fix each of the tests and they both were the result of errors in js-land. I can probably make a reasonable repro from that.

**Comment by jakemac53** [comment]
Ok, heres a repro https://gist.github.com/jakemac53/b1c025504ce24f461c64. It looks its only specific types of failures which cause this.

**Comment by nex3** [comment]
This looks like a bug in `dart2js`/`dart:js` not translating some JS errors into Dart-catchable errors. I suggest filing an issue on the SDK repo.

**Comment by nex3** [comment]
Actually, before you do that, let me dive a little deeper into this. It looks like test *is* seeing the error, just not reacting in the right way.

**Comment by nex3** [comment]
Yeah, it looks like this is actually a test issue—caused by a stack_trace issue. I'll work on a fix.
