### ISSUE TITLE
Allow individual tests to be annotated as "do not parallelize".

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/test#319]
Many behaviors of the analyzer_cli package depend on the current working directory.  As a result, some of its unit tests change the working directory in their setUp() function and restore it in their tearDown() function.  Since the current working directory state is shared across all isolates, these tests aren't safe to run in parallel with each other, nor are they safe to run in parallel with any of the other analyzer_cli unit tests.

Currently we are working around this problem by running our tests with the `-j1` option (which forces all tests to run serially).  But that seems like overkill, because only some of the analyzer_cli tests are unsafe to parallelize.  It would be nice if there were some way to annotate the tests themselves so that the test runner would know which ones were safe to run in parallel and which ones weren't.

**Comment by grouma** [comment]
`-j1` is the supported solution. I don't think we'll make progress on this as there are more hi priority items.

**Comment by srawlins** [comment]
This would be a great feature. The ability to tag a `group` or `test` as `@serial` or `@Concurrency(1)` or something. cc @leonsenft

**Comment by Tokenyet** [comment]
This feature is great If some of the tests could affect the other as op said, I think It should be a way to specify the later test. Let's give the test that might be affected, given an annotation `@later` on the top of file.

```
80+ parallel test, (ignore @later test)
(await all parallel test complete)
10+ (@later test here)
```

Just a concept to make It work, this is really useful for any **Singleton pattern patients**. 😄
