### ISSUE TITLE
Support running tests with user-authored HTML

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#32]
Currently tests are always run with a `unittest`-provided HTML shim. The user should be able to provide their own HTML page. In practice, most people who do this with the old unittest have `whatever_test.html` alongside `whatever_test.dart`, so we should just detect that pattern.

**Comment by travissanderson-wf** [comment]
For our use case we wanted to be able to provide a default HTML file instead of one for every test file so we have this PR into test_runner.dart https://github.com/google/test_runner.dart/pull/35

**Comment by nex3** [comment]
Can you open a separate enchancement request for that? It's worth looking into, but it's got broader consequences than this one (it requires global configuration and some sort of templating system) so it's unlikely it'll make it into 0.12.0.

**Comment by travissanderson-wf** [comment]
Added https://github.com/dart-lang/unittest/issues/39
