### ISSUE TITLE
Time out waiting for test to connect to content shell

### ISSUE THREAD

**Issue by ErikGrimes** [dart-lang/test#324]
I recently updated my Mac to OS X Yosemite 10.10.5.  Now I'm unable to run tests with content-shell.

```
pub run test -p content-shell test/paper_ripple_test.dart

01:00 +0 -1: loading test/paper_ripple_test.dart                                
01:00 +0 -1: loading test/paper_ripple_test.dart  
Failed to load "test/paper_ripple_test.dart": Timed out waiting for the test suite to connect on Dartium Content Shell.
01:00 +0 -1: Some tests failed.

```

This occurs on 1.11.3 and 1.12.0-dev.5.1 with test 0.12.4+5

**Comment by nex3** [comment]
What version of Dart is your content shell running? Did you install it via Homebrew or by manually downloading it? Does manually running content shell on Dart applications work?

**Comment by ErikGrimes** [comment]
- I've tried content shell with both 1.11.3 and 1.12.0-dev-5.1 sdks (assuming content_shell is picking dart up from my path)
- I install and switch sdks/content_shell via Homebrew (brew install --with-content-shell --with-dartium, brew remove)
- dart applications work manually with content_shell in both sdk's

**Comment by nex3** [comment]
> I've tried content shell with both 1.11.3 and 1.12.0-dev-5.1 sdks (assuming content_shell is picking dart up from my path)

It is not. Content shell bundles its own Dart VM. I don't know how this interacts with Homebrew, though. @kevmoo, can you shed some light?

**Comment by ErikGrimes** [comment]
I have the same issue when run against Dartium.  Dartium ishows two warnings in yellow warning boxes,  'You are using an unsupported command-line flag --no sandbox' and 'Google API keys are missing'.

**Comment by zoechi** [comment]
API keys http://www.chromium.org/developers/how-tos/api-keys  
see also https://github.com/dart-lang/sdk/issues/13100

**Comment by zoechi** [comment]
See
-  https://github.com/dart-lang/sdk/issues/13100
- https://github.com/dart-lang/www.dartlang.org/issues/1308

**Comment by ErikGrimes** [comment]
Did a bit of debugging and test is getting stuck waiting for Process.start in the ContentShell factory constructor:

```
factory ContentShell(url, {String executable, bool debug: false}) {
...
 var process = await Process.start(executable, args,
            environment: {"DART_FLAGS": "--checked"});
```
Content Shell and two Content Shell Helpers get spawned; I can see them in Activity Monitor.

I can spawn Content Shell from my own script with the same arguments that test is passing to it and Process.start returns with Content Shell running.  In this case the two Content Shell Helpers are missing.

```
var args = ["--dump-render-tree","http://localhost:57777/drfL-owTnz4BaysfLYt6tKwUlFQSE6W_/packages/test/src/runner/browser/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A57777%2FdrfL-owTnz4BaysfLYt6tKwUlFQSE6W_%2F0"];
  var process = await Process.start(executable, args,
  environment: {"DART_FLAGS": "--checked"});
```

Not sure if this helps or not.

**Comment by ErikGrimes** [comment]
@zoechi Thanks for the references.

**Comment by ErikGrimes** [comment]
Just to clarify, looks like this is confined to a specific project (polymer_elements). I cloned the upstream repo and content-shell tests work fine, so it's something specific to my fork/local version.  Not sure it's related to my Mac upgrade at all :)

**Comment by ErikGrimes** [comment]
Confirmed it's specific to my repo.  I cloned my repo [ErikGrimes/polymer_elements](https://github.com/ErikGrimes/polymer_elements) on my Mac @ work and it crashed content shell ("Content Shell quit unexpectedly").  Here's the console:
```
pub run test -p content-shell test/iron_ajax_test.dart 
 00:00 +0: loading test/iron_ajax_test.dart                                     
 00:01 +0: loading test/iron_ajax_test.dart                                     
 00:02 +0: loading test/iron_ajax_test.dart                                     
 00:03 +0: loading test/iron_ajax_test.dart                                     
 00:04 +0: loading test/iron_ajax_test.dart                                      
 00:05 +0: loading test/iron_ajax_test.dart                                      
 00:06 +0: loading test/iron_ajax_test.dart                                      
 00:07 +0: loading test/iron_ajax_test.dart                                      
 00:08 +0: loading test/iron_ajax_test.dart                                      
 00:08 +0 -1: loading test/iron_ajax_test.dart                                  
 00:08 +0 -1: loading test/iron_ajax_test.dart                                                      
  
Failed to run Content Shell: Content Shell failed with exit code -5..
  dart:isolate  _RawReceivePortImpl._handleMessage
  
00:08 +0 -1: Some tests failed.                         
```

Is this the appropriate home for this issue?  If not, where should I file it?

**Comment by nex3** [comment]
If `Process.start` isn't returning at all, then this is either an issue with `dart:io` or content shell itself. Either way, you should file the issue in the dart-lang/sdk repo.
