### ISSUE TITLE
Use docker to run tests

### ISSUE THREAD

**Issue by a14n** [dart-lang/test#325]
Sometimes the user or CI doesn't not support to run tests on some platforms. It would be great if the test could be run inside its own containers (if `--use-docker` option is set). Thus the only requirement would be to have docker on the machine.

This would allow:
- to test against several versions of a browser
- to reduce the concerns when you try to install content_shell (or when its installation fails randomly)
- to test on platforms not supported nativelly (eg. phantomJS2 is not available on travis)

Btw [as of today, we can use Docker as part of our build](http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/).

What do you think ?

**Comment by nex3** [comment]
This is a great use-case for a plugin (#49 and/or #99), but it's not something I want to put in the core test package.
