### ISSUE TITLE
Support running without a packages/ directory

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#327]
`pub run test`

```
 (master) $ pub run test
00:00 +0 -1: loading test/server_build/find_dependencies_test.dart                                 
  Failed to load "test/server_build/find_dependencies_test.dart":
  "package:test/src/backend/metadata.dart": Error loading file:///home/myuser/dart/pubs/packages/test/src/backend/metadata.dart:
    Cannot open file, path = '/home/myuser/dart/pubs/packages/test/src/backend/metadata.dart' (OS Error: No such file or directory, errno = 2)
  #0      _asyncLoadErrorCallback (dart:_builtin:149)
  #1      _asyncLoadError (dart:_builtin:541)
  #2      _handleLoaderReply (dart:_builtin:364)
  #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

```
Dart VM version: 1.13.0-edge.41840f374008c8430c1bf034f65af1c2c39e19f5 (Fri Aug 21 16:18:10 2015) on "linux_x64"
test 0.12.4+6

**Comment by rayk** [comment]
## Same Problem - Earlier Version of dart

Dart VM version: 1.12.0-dev.5.8 (Thu Aug 20 07:16:22 2015) on "macos_x64"
test version: "0.12.4+6"

------------

```pub run test```

```
00:00 +0 -1: loading test/comXsGraph_test.dart                                                     
  Failed to load "test/comXsGraph_test.dart":
  "package:test/src/backend/metadata.dart": Error loading file:///Users/rayk/Projects/comXsGraph/packages/test/src/backend/metadata.dart:
    Cannot open file, path = '/Users/rayk/Projects/comXsGraph/packages/test/src/backend/metadata.dart' (OS Error: No such file or directory, errno = 2)
  #0      _asyncLoadErrorCallback (dart:_builtin:149)
  #1      _asyncLoadError (dart:_builtin:541)
  #2      _handleLoaderReply (dart:_builtin:364)
  #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
00:00 +0 -1: Some tests failed.       
```

------------
```pub run test -p content-shell  test/comXsStore_test.dart```

```
00:00 +0 -1: loading test/comXsStore_test.dart                                                     
  Invalid argument(s): A directory corresponding to fileSystemPath "/Users/rayk/Projects/comXsGraph/packages" could not be found
  package:shelf_static/src/static_handler.dart 37  createStaticHandler
  ===== asynchronous gap ===========================
  dart:async                                       Future.Future.sync
  package:async/src/async_memoizer.dart 44         AsyncMemoizer.runOnce
  
00:00 +0 -1: Some tests failed.        
```

-------------

Where I am not using a ```.packages``` file, it appears to run.

Thanks in advance.
R.

**Comment by nex3** [comment]
The test runner doesn't yet support running without a `packages` directory. Doing so is blocked on sdk#23990.

Note that the `--no-package-symlinks` option to `pub get` is hidden on bleeding edge and `1.12-dev`, which is an indication that it's not expected to work everywhere yet.

**Comment by sethladd** [comment]
For those following along: all the (known) blockers for this are captured in https://github.com/dart-lang/sdk/issues/24112

**Comment by mit-mit** [comment]
@nex3, do you have an update on when a fix to this might land?

**Comment by pulyaevskiy** [comment]
Looks like dart-lang/sdk#23990 has been resolved a while ago, so "blocked" tag can be removed from this issue?

**Comment by nex3** [comment]
There's still ongoing work to land and verify stable package-introspection APIs. Many of them are in place but the verification work is still ongoing.

**Comment by abarth** [comment]
For what it's worth, Flutter is switching over to using `--no-package-symlinks`.  We've worked around this issue, but ideally we'd like to go back to using `pub run test` for our tests that run in the standalone DartVM.

**Comment by nex3** [comment]
You're of course welcome to do whatever you need to get your code working, but please keep in mind that `--no-package-symlinks` is still considered experimental and any package may break under it at any time.

**Comment by abarth** [comment]
Yeah, we wanted to try it out.  If too much stuff is broken, we can go back to having the symlinks around.

**Comment by eseidelGoogle** [comment]
We ran into this again, but have worked around it for now by adding a `pub get` call to `flutter drive` in https://github.com/flutter/flutter/pull/4259.

**Comment by kevmoo** [comment]
@lrhn is working hard on testing here. That should unblock work for this.

**Comment by eseidelGoogle** [comment]
Just checking in on this.  No huge rush (I know @nex3 is hard at work on other things).  This I believe is the last remaining issue Flutter is running into with our use of .packages files. :)

**Comment by eseidelGoogle** [comment]
My bad.  I just checked Natalie's things-to-do-soon list and this is on the top of it.  Apologies for the noise.

**Comment by kevmoo** [comment]
https://codereview.chromium.org/2184543002/
