### ISSUE TITLE
Get pkg/test working on the Dart package bots

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#332]
These are the issues we are tracking against core SDK infrastructure
- [ ] Add Dartium path to the bots: https://github.com/dart-lang/sdk/issues/23816
- [ ] Support phantomJS on the bots: https://github.com/dart-lang/sdk/issues/23195

**Comment by matanlurey** [comment]
Dartium and has been removed from the SDK and I assume phantomJS is not important.
