### ISSUE TITLE
Test hangs in FF via test runner, but not standalone.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#334]
fyi: I am running FF 40.0.3 on linux.

[This test](https://github.com/dart-lang/polymer_interop/blob/617bc4b4d1325afecb2f7c55273801df96d00b86/test/convert_test.dart) is hanging when I run the test runner, it never appears to start running the tests at all. 

Repro instructions: Check out the [0.2.0-dev branch](https://github.com/dart-lang/polymer_interop/tree/0.2.0-dev), run `pub serve test` and then `pub run test -pfirefox --pub-serve=8080 test/convert_test.dart` from the package root.

If I run it standalone then all the tests pass just fine. You can modify `test/convert_test.html` to do this by changing:

``` html
  <link rel="x-dart-test" href="convert_test.dart">
  <!--<script type="application/dart" src="convert_test.dart"></script>-->
  <!--<script src="packages/browser/dart.js"></script>-->
  <script src="packages/test/dart.js"></script>
```

to

``` html
  <!--<link rel="x-dart-test" href="convert_test.dart">-->
  <script type="application/dart" src="convert_test.dart"></script>
  <script src="packages/browser/dart.js"></script>
  <!--<script src="packages/test/dart.js"></script>-->
```

I did notice one error, but I couldn't tell for sure if it was related. It looks like the [window.onMessage](https://github.com/dart-lang/test/blob/a635337bce85dd49ed74a24eeb6dc9c8ed7652ed/lib/src/runner/browser/iframe_listener.dart#L94) stream is getting a `JsObject`, not a `MessageEvent`. I tried messing with that a bit and it didn't seem to help, but debugging is fairly difficult since it only happens in the test runner itself.

I tried to get a simple repro, but was unfortunately unable to figure out what is actually triggering the error.

**Comment by zoechi** [comment]
You could try if it still works standalone when you load the test from an iframe similar to #274

**Comment by jakemac53** [comment]
Just tried that, still works standalone even in an iframe

**Comment by nex3** [comment]
> I did notice one error, but I couldn't tell for sure if it was related. It looks like the [window.onMessage](https://github.com/dart-lang/test/blob/a635337bce85dd49ed74a24eeb6dc9c8ed7652ed/lib/src/runner/browser/iframe_listener.dart#L94) stream is getting a `JsObject`, not a `MessageEvent`. I tried messing with that a bit and it didn't seem to help, but debugging is fairly difficult since it only happens in the test runner itself.

This sounds like a potential `dart:html` bug. @alan-knight, can you confirm?

**Comment by alan-knight** [comment]
It is indeed pretty painful to do any debugging from the test runner. But what seems to be happening is that the event comes in to dispatchOriginalEvent in webcomponents.js, and that calls wrap(originalEvent), which then returns an Object (not a JsObject). In the internals of wrap it seems to call getWrapperConstructor, which has an isFirefox test in it, which seems rather suspicious. But basically something is going on inside webcomponents.js that is wrapping the event and passing something with no prototype on to us. It does not appear to be related to dart:html.

**Comment by nex3** [comment]
@jakemac53 Can you reproduce this without Polymer in the loop? If not, based on Alan's investigation, it seems like Polymer is doing something wrong here.

**Comment by jakemac53** [comment]
Thanks for the investigation @alan-knight. I will try investigating this a bit more, but I did just try simply adding web_components.js to a test, and it did not cause this issue which is surprising.

**Comment by jakemac53** [comment]
Actually, I guess its not that surprising because its only this one specific test file which is failing in FF for polymer, the rest of them are working fine.
