### ISSUE TITLE
Support a headless browser

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#34]
At least one headless browser should be supported so users can run their tests without popping up an unwieldy window. [PhantomJS](http://phantomjs.org/) is probably the best option here, since it's widely-used and easy to install, but we could also do `content_shell`.

**Comment by zoechi** [comment]
`content_shell` support would be great, it allows to run the tests without the build step.

**Comment by nex3** [comment]
Yeah, we definitely intend to support `content_shell` as well. It's somewhat lower-priority than PhantomJS, since it's generally harder to install, but it occupies an important niche.

**Comment by zoechi** [comment]
Interesting that you see content_shell as harder to install (never used PhantomJS). It's just a script in the SDK to execute. 
PhantomJS is only useful for integration tests. dart2js is way to slow for TDD even with `pub serve`.

**Comment by nex3** [comment]
It's neither bundled with the SDK nor with Dartium. The only way I can find to get it is by running the `download_contentshell.sh` script in the depths of the Editor download.

**Comment by zoechi** [comment]
That was what I meant. Just running this script and it will be installed. How can PhantomJS be easier?

**Comment by nex3** [comment]
The script to run is undocumented and hidden away in a tarball that many Dart users don't have and most who do don't inspect manually. PhantomJS has an easily-searchable download page as well as packages for Linux distributions and Homebrew.

**Comment by a14n** [comment]
One thing to notice is that `content_shell` can be easily installed on travis-ci (see http://docs.travis-ci.com/user/languages/dart/#Default-Test-Script). BTW I'd like to know the future of [test_runner package](https://pub.dartlang.org/packages/test_runner) regarding the evolution of this `test` package.

**Comment by kevmoo** [comment]
@a14n supporting `content_shell` is on our radar.

`test_runner` was inspiration of a lot of this work. It may stick around and provide richer status reporting, etc.

No specific plans yet.

**Comment by nex3** [comment]
It looks like PhantomJS [doesn't support the latest WebSocket spec](http://phantomjs.org/inter-process-communication.html), which is the only spec that Dart supports. Until that gets fixed, `content_shell` will of necessity be the only headless testing option for the runner.
