### ISSUE TITLE
Searching for "Dart test API" lands me on the github as first result, but no link to API docs

### ISSUE THREAD

**Issue by sethladd** [dart-lang/test#343]
Hi,

I'm working with a customer who typed "Dart test API" and the first result is the main github page for this project. Not too bad. Expect there's no link from the README to the API docs. Customer took a long time to find the API docs.

We might want to consider linking to the API docs (http://www.dartdocs.org/documentation/test/latest) from the README.

**Comment by HansMuller** [comment]
As the customer in question, I agree it would be nice if it was easier to find the test API docs. :+1:

**Comment by nex3** [comment]
All of the function names in the documentation are links to their respective API docs; that's just method-by-method documentation, but that's the only value the API docs add over the README to begin with.

Do you have a suggestion for how to fluidly add a link to the documentation? I don't want to just add "also the API docs are here" but if it can nicely integrate with the prose I'd be fine with it.

**Comment by sethladd** [comment]
> Do you have a suggestion for how to fluidly add a link to the documentation?

At the very end of the README:

```
## Learning more

The [API docs](http://www.dartdocs.org/documentation/test/latest) are also available.
```

> I don't want to just add "also the API docs are here"

What's the harm in that? Is there a big cost for that link? If a developer lands on the GitHub project for a Dart library, they should easily be able to jump to the docs.

Let's make it easy for our developers to jump to docs, especially when search fails to lead the developer to the right place.
