### ISSUE TITLE
documentate setUp() and teardown() in the README.md

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/test#347]
I'm beginner with tests, and I just learned about `setUp` and `tearDown` at the dart slack.

I wasn't aware of this by just reading the instructions here. I think it would be useful if there was some information about these 2 function in the readme.

**Comment by nex3** [comment]
The README is meant to be a broad overview of the major features of the test runner, not a comprehensive reference manual for everything it can do. That's what the [API docs](http://www.dartdocs.org/documentation/test/0.12.4%2B9/index.html#test/test@id_setUp) are for, and `setUp`/`tearDown` are well-documented there.

**Comment by kasperpeulen** [comment]
> The README is meant to be a broad overview of the major features of the test runner, not a comprehensive reference manual for everything it can do. 

This issue is not asking to make the README a comprehensive reference manual...

I think it makes sense that the `setUp()` and `tearDown()` functions would be named in this "broad overview". As they are major features of the rest runner.

Maybe people don't even think about that the test runner provides these features, and so are not even looking for them. Just like people may not know, that they can skip a test with an @Skip annotation, therefore it is useful that this is documented in the README.

Even if you are going to read everything in the API. There are 100 (literally) other properties and functions that you comes first in the API, before you end up with docs about the `setUp` function.

**Comment by zoechi** [comment]
An introductory tutorial on dartlang.org might be a better place for that. The few blog posts about unit testing with Dart are outdated (for the unittest package).

**Comment by nex3** [comment]
Okay, I'm convinced. We can probably fit it in in the opening section.
