### ISSUE TITLE
Provide test duration

### ISSUE THREAD

**Issue by Fox32** [dart-lang/test#348]
I was about to write a custom reporter for a CI server (see [here](https://github.com/Fox32/test/blob/master/lib/src/runner/reporter/teamcity.dart)). One thing I really missed was a way to access the execution duration of each test after it was finished. I know that the time is already tracked (for the timeout) but not passed to the reporter. For now I do the timing for myself, but it's not very accurate. It's very useful to find timeout problems.

I also have problems on Windows, looks like it is crashing always on exit, independent from the result of the tests and browser windows aren't closed.

Dart VM version: 1.13.0-dev.6.0 (Wed Oct 07 08:06:44 2015) on "windows_x64"

**Comment by nex3** [comment]
I think it's best for a reporter to measure this itself. The timer that the invoker maintains for each test doesn't measure the duration; it gets reset each time the test interacts with the frontend. And even if it had the information you wanted, it's in a different isolate or in a browser; we don't want to send a message to the main isolate every tick.

**Comment by Fox32** [comment]
Any ideas about the Windows chrashes? I have Windows 8.1. If I run with -p chrome it crashes on every exit (independent from the result of the tests) and chrome isn't closed.

**Comment by nex3** [comment]
Can you file a separate issue for that? Please include the text of the crash and the version of `test` you're using.
