### ISSUE TITLE
pub run test -p dartium looks for the `dartium` binary; the binary is actually named `chrome`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#353]
_From @jirkadanek on October 17, 2015 17:55_

I'm running dart test using the `test` package..

    pub run test -p dartium

When I execute the command above, I get the following error.

    Failed to run Dartium: No such file or directory
        Command: dartium --user-data-dir=/tmp/dart_test_pLppGJ http://localhost:59531/nI6HuPYC2TYNlxlFC2UiMNf4eBs9I0iJ/packages/test/src/runner/browser/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A59531%2FnI6HuPYC2TYNlxlFC2UiMNf4eBs9I0iJ%2F0 --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate.
    dart:isolate  _RawReceivePortImpl._handleMessage

I have both dartium and dart.sdk downloaded and in PATH.
The version is 1.13.0-dev.7.0 (Wed Oct 14 06:04:50 2015) on "linux_x64"

The same issue was discussed four months ago at https://stackoverflow.com/questions/30675583/failed-to-load-dartium-when-running-test
The solution described there, `ln -s chrome dartium` in the directory where I unpacked Dartium works for me.

I would expect pub run test to work without me having to create any symlinks.

_Copied from original issue: dart-lang/sdk#24616_

**Comment by nex3** [comment]
As [the README](https://github.com/dart-lang/test#running-tests-on-dartium) notes, this is intentional. We can't very well search for an executable called `chrome` and expect it to be Dartium. We need some way of having the user explicitly specify where Dartium in particular is, and this is the most straightforward (and compatible with Homebrew).

Once #63 is fixed, there will be a more explicit way of configuring your Dartium location.

**Comment by jirkadanek** [comment]
What about renaming the Dartium executable in dartium-linux-x64-release.zip to `dartium`? That is why I originally opened the issue at https://github.com/dart-lang/sdk/issues/24616 --- I think the SDK should be changed, not the `test` package.

**Comment by nex3** [comment]
For that, I suggest opening another issue against the SDK that's more specific about what change you're asking for.

**Comment by jirkadanek** [comment]
@nex3 So you think this is a good idea? I was a bit worried that renaming anything would break compatibility with previous releases, and having both `chrome` and `dartium` in the directory would be a confusing mess. In that case I'll fill the issue.

**Comment by nex3** [comment]
It's not my decision. I've always thought it was a bit strange that it was called `chrome`, but I'm not in a great position to weight the costs and benefits of changing it.
