### ISSUE TITLE
Feature request: Parametrizing tests

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/test#355]
Okay, this is inspired by a feature of a python test package (pytest). Basicly, often I feel like want to run one test a couple of times for multiple parameters, but there doesn't is a built in way to do this in the test package. In pytest you can basicly,do something like this:

```python
@pytest.mark.parametrize("number,squared", [
    (1, 1),
    (2, 4),
    (3, 9),
])
def test_squaring(number, squared):
    assert number**2 == squared
```

In dart I would probably write something like:

```dart
  test("math.pow does really square", () {
    expect(math.pow(1, 2), 1);
    expect(math.pow(2, 2), 4);
    expect(math.pow(3, 2), 9);
  });
```

But this is of course not dry at all. But if I go for dry ways, it becomes a bit ugly:
```dart
  test("math.pow does really square", () {
    [
      [1, 1],
      [2, 4],
      [3, 9]
    ].forEach((arguments) => expect(math.pow(arguments[0], 2), arguments[1]));
  });
```

So I want to propose a different built-in syntax for writing things like this. I think it is really intuitive:

```dart
  test("math.pow does really square", (int number, int squared) {
    expect(math.pow(number, 2), squared);
  }, arguments: [
    [1, 1],
    [2, 4],
    [3, 9]
  ]);
```

This syntax is really easy to implement, and non breaking. I think the biggest advantage is that, with this syntax, any test you ever wrote, can be easily extended to test for different cases. For example:

```dart
  test("String.trim() removes surrounding whitespace", () {
    var string = "  foo ";
    expect(string.trim(), equals("foo"));
  });
```

can be extended to:
```dart
  test("String.trim() removes surrounding whitespace", (String string) {
    expect(string.trim(), equals("foo"));
  }, arguments: [
    [" foo"],
    ["foo "],
    [" foo "],
    ["foo\n"],
    ["\nfoo"]
  ]);
```

I got this syntax already working for myself, so it wouldn't hard to write a PR if you guys like this feature:
```dart
import 'package:test/test.dart' hide test;
import 'package:test/test.dart' as dart_test;

void test(String description, body,
    {List<List<dynamic>> arguments: const [const []],
    String testOn,
    Timeout timeout,
    skip,
    Map<String, dynamic> onPlatform}) {
  dart_test.test(description, () {
    arguments.forEach((args) => Function.apply(body, args));
  }, testOn: testOn, timeout: timeout, skip: skip, onPlatform: onPlatform);
}
```

**Comment by nex3** [comment]
I don't think this adds much value at all over just explicitly writing a `for`/`in` loop. Adding a specialized way of doing that that only works for tests will make them harder to read and understand for new users.

**Comment by yjbanov** [comment]
@kasperpeulen unlike Python (and Java) Dart's test API is imperative, so you can put your loop _outside_ the test declaration, making it look almost exactly like that in Python with some minor syntactic differences:

```dart
{
  1: 1,
  2: 4,
  3: 9,
}.forEach((number, squared) {
  test('$number squared should equal $squared', () {
    expect(math.pow(number, 2), squared);
  });
});
```
