### ISSUE TITLE
Seeing strange exit codes when running `test` on windows

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/test#356]
I've seen this for two different projects - `pub run test` runs fine, and reports that all tests passed, but then reports a non-zero exit code.
- https://ci.appveyor.com/project/devoncarew/tools/build/1.0.3
- https://ci.appveyor.com/project/devoncarew/grinder-dart/build/1.0.370

`failed with exit code -1073741819`

This is for projects running on windows, on the appveyor CI system. To workaround this we've changed from running the tests through `test` to executing them directly - `pub run test` ==> `dart -c test\all.dart`.

**Comment by Fox32** [comment]
I expect that this is a duplicate of my issue: #351

**Comment by devoncarew** [comment]
Hmm, maybe, but I'm not running any browser tests, just CLI ones, and don't see a windows error dialog on failure.

**Comment by Fox32** [comment]
You are right, vm only tests work fine for me.

**Comment by nex3** [comment]
It looks like you're using `test` 0.12.4+9, which is a little outdated. Can you reproduce with 0.12.5+1?

**Comment by devoncarew** [comment]
Yup, the second of those 2 builds used `test 0.12.5+1`. Not sure what constraint on the first caused the older test version to be selected.

**Comment by nex3** [comment]
Have you been able to reproduce this locally? Does it happen for you with *all* VM tests, or only certain ones?

**Comment by devoncarew** [comment]
I have not tested the exit code locally. I was seeing it consistently on appveyor for the grinder tests for several weeks. When I added a windows bot for the flutter tools project, I saw it there as well (also appveyor). Not sure if it's just appveyor or would repro locally as well.

**Comment by nex3** [comment]
Okay, let me know when you get that information. There's not much I can do until I can tell how to reproduce it.

**Comment by natebosch** [comment]
We've been running on appveyor for a few different projects successfully for a while now. I suspect this  is no longer a problem. Please reopen if we see more examples.
