### ISSUE TITLE
Provide a way to get the group metadata from the test

### ISSUE THREAD

**Issue by keertip** [dart-lang/test#358]
@nex3, Currently there is no way to get any group information for `Test` or `LiveTest`. This information is very useful in report generation for tests.

**Comment by nex3** [comment]
This generally falls under #48; right now, there's no public API for the test package at all, so be aware that any attempt to any of the package's internals has no stability or backwards-compatibility guarantees at all.

In a more specific sense, I'm not sure what you're asking for. What do you mean by "group information"? Where are you getting your `Test`s and `LiveTest`s? What do you need this information for?
