### ISSUE TITLE
Run tests through selenium

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/test#359]
It would be great to have a way to run unit tests through selenium to allow a CI system to trigger testing on a selenium grid instance. Something along the lines of https://github.com/PixnBits/karma-selenium-webdriver-launcher would work well.

**Comment by nex3** [comment]
This is a good use-case for a plugin, although it's not something that's likely to go in the core test framework. See also #99.

**Comment by donny-dont** [comment]
Makes sense. Will follow the related issue.
