### ISSUE TITLE
Widen SDK constraint to support Dart 1.14-xxx

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#360]

**Comment by devoncarew** [comment]
Right now, if you run pub upgrade/get w/ a 1.14.0-dev sdk, `test` gets downgraded to `0.12.3+9`, and `test` fails when run w/:

```
'package:test/src/runner/engine.dart': malformed type: line 95: type 'DelegatingSink' is not loaded
  Sink < Suite > get suiteSink => new DelegatingSink(_suiteController.sink);
                                      ^
type error.
dart:core                               _TypeError._throwNew
package:test/src/runner/engine.dart 95  Engine.suiteSink
package:test/src/runner.dart 155        Runner._loadSuites.<async>.<fn>.<fn>
dart:async                              Future.Future.sync
package:test/src/runner.dart 154        Runner._loadSuites.<async>.<fn>
```

**Comment by Hixie** [comment]
This affects flutter. We require a newer version of `test` (`^0.12.5`) and the `dev` SDK (currently 1.14.x), but no matching version of `test` supports the `dev` SDK, so we can't build.

For now we've downgraded to the `stable` SDK, but that will only work until the `dev` SDK release a feature we want to use.

**Comment by kevmoo** [comment]
@nex3 has a CL out – https://codereview.chromium.org/1463023002/

Just need to land it

**Comment by sethladd** [comment]
Ah, this might also fix https://github.com/flutter/flutter/issues/548

**Comment by kevmoo** [comment]
@Hixie We'll get this fixed today
