### ISSUE TITLE
Test engine has duplicate import of `DelegatingSink`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/test#361]
Seems it has its own implementation in `util.dart` which now conflicts with the one added to `package:async`.

See http://build.chromium.org/p/client.dart.packages/builders/packages-windows-collection/builds/389/steps/Pub%20build%20on%20test/logs/stdio

**Comment by nex3** [comment]
`test` hasn't had a definition of `DelegatingSink` since 653ef174e456b4e49b1c09de2905bc078b94ad47 removed it back in 0.12.4.

**Comment by kevmoo** [comment]
@lrhn could this be that we haven't updated the version of pkg/test on the bots?

**Comment by lrhn** [comment]
@ricowind 
Possible (aka, I have no clue, but it fits the symptoms). I'm just seeing red bots.

**Comment by ricowind** [comment]
@kevmoo / @lrhn : what do you meen the bots have not updated the version of pkg/test? This is a package bot, packages are pulled using pub, nothing is on the bots.
You  can see what pub pulls down in the pub upgrade step:
http://build.chromium.org/p/client.dart.packages/builders/packages-windows-collection/builds/389/steps/Pub%20upgrade/logs/stdio

**Comment by nex3** [comment]
> test 0.12.3+9 (0.12.5+1 available)

Looks like something's holding back the upgrade. What Dart version are the bots using?

**Comment by ricowind** [comment]
They use 1.14.0-dev.1.0, there is also a download sdk step:
http://build.chromium.org/p/client.dart.packages/builders/packages-windows-collection/builds/389/steps/Get%20sdk/logs/stdio

**Comment by ricowind** [comment]
I did not see that this was 4 days old, they may have used something older.

Let me add a step that prints the version out to rule out confusion in the future.

**Comment by ricowind** [comment]
https://chromiumcodereview.appspot.com/1473573002
