### ISSUE TITLE
type 'DelegatingSink' is not loaded

### ISSUE THREAD

**Issue by kelegorm** [dart-lang/test#364]
$ pub run test  test/editors_test.dart 
'package:test/src/runner/engine.dart': malformed type: line 95: type 'DelegatingSink' is not loaded
  Sink < Suite > get suiteSink => new DelegatingSink(_suiteController.sink);
                                      ^
type error.
dart:core                               _TypeError._throwNew
package:test/src/runner/engine.dart 95  Engine.suiteSink
package:test/src/runner.dart 155        Runner._loadSuites.<async>.<fn>.<fn>
dart:async                              Future.Future.sync
package:test/src/runner.dart 154        Runner._loadSuites.<async>.<fn>

This is an unexpected error. Please file an issue at http://github.com/dart-lang/test
with the stack trace and instructions for reproducing the error.

**Comment by kevmoo** [comment]
Would you run `pub upgrade` and try it again?

If it fails, please include the output of `pub upgrade`

**Comment by kelegorm** [comment]
Oh, it works now. Thank you. I was afraid upgrade it because have bad experience with polymer. Sorry :)
