### ISSUE TITLE
Add option to count tests to be run

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/test#366]
For IDEs that use package:test to run unit tests, and have a UI designed to monitor progress, it would be very useful to know how many tests are going to be run prior to running any.

This should be straight-forward to implement. Add another loading phase that does nothing but load tests, and does not run any, which (obviously) runs prior to the normal load-and-run phase. Then add another attribute to the JSON 'start' event to include the test count.

As a specific example, IntelliJ IDEA shows a progress bar while running unit tests. For languages other than Dart the progress bar is incremented each time a test completes. For Dart, it has two states: 50% while tests are running and 100% when all tests finish.

**Comment by clayberg** [comment]
That would be a great product excellence feature to better support IDEs.

**Comment by nex3** [comment]
This is unfortunately not possible. The test runner doesn't load all the test suites at once, since that can cause it to run out of memory. Instead, it loads a few, runs their tests, and loads more as old ones finish running. This means that it doesn't have any way of knowing how many tests will run until it's almost finished running them.

**Comment by clayberg** [comment]
"Not possible" sounds a bit strong. Why not create an optional loading and counting phase that would load all of the tests as it does now but not actually run them? Obviously, that is a bit of extra processing work, but it would also be optional and something that an IDE could choose to do.

The requirement of supplying a total count is entirely reasonable here, but the count itself does not have to be 100% accurate (it is just being used to make the progress bar more accurate). That is very important feedback to the IDE user, but it would be OK if it were a ballpark estimate (maybe +-10-20%).

**Comment by scheglov** [comment]
Actually, if we accept that the `test` package has more than one use case, it turns out to be pretty logical to provide features that are required for one use case, but are not needed or are not feasible for other use cases. Nobody is going to run tests suites of the size that would not fit into the heap from their IDEs. But everyone likes to see progress bars and know that the computer is working for them! :-)

**Comment by nex3** [comment]
@clayberg 

> "Not possible" sounds a bit strong. Why not create an optional loading and counting phase that would load all of the tests as it does now but not actually run them? Obviously, that is a bit of extra processing work, but it would also be optional and something that an IDE could choose to do.

We could do something like this, but we'd still have to do the initial load in a rolling manner, and it would add a very noticeable amount of startup time—a quickly hacked-together implementation suggest that the `test` package tests would take an extra two seconds to start running on the VM. On `content-shell`, it's closer to nine seconds. And this is for a package with a pretty moderate number of tests—for a full-scale application, it'll be much worse.

> The requirement of supplying a total count is entirely reasonable here, but the count itself does not have to be 100% accurate (it is just being used to make the progress bar more accurate). That is very important feedback to the IDE user, but it would be OK if it were a ballpark estimate (maybe +-10-20%).

If an approximate number is allowable, we could supply the number of test *suites*. It would be up to the IDE to determine how to approximate the number of tests based on that, though.

@scheglov 

>  Nobody is going to run tests suites of the size that would not fit into the heap from their IDEs. But everyone likes to see progress bars and know that the computer is working for them! :-)

You'd be surprised how few suites you actually need to load before you start to hit painful limits. Browser suites each have their own pages with their own DOMs and everything, and even VM isolates are pretty heavyweight for large applications. This isn't a speculative feature—we ran into apps we couldn't test (`pub` for instance) very soon after we started rolling out `test`.

**Comment by kevmoo** [comment]
I have ideas here. I'll chat w/ @nex3 tomorrow and will follow up.

**Comment by scheglov** [comment]
> You'd be surprised how few suites you actually need to load before you start to hit painful limits. Browser suites each have their own pages with their own DOMs and everything, and even VM isolates are pretty heavyweight for large applications. This isn't a speculative feature—we ran into apps we couldn't test (pub for instance) very soon after we started rolling out test.

But we don't need to run these tests - we need just to count the number of them.

**Comment by nex3** [comment]
> But we don't need to run these tests - we need just to count the number of them.

Because tests are defined dynamically by code, you need to load a test suite into memory and execute at least its `main()` method in order to count its tests.

**Comment by scheglov** [comment]
> Because tests are defined dynamically by code, you need to load a test suite into memory and execute at least its main() method in order to count its tests.

Ouch... That's sad.
Do we know at least the number of test suites?

**Comment by nex3** [comment]
> Do we know at least the number of test suites?

Not immediately, but pretty quickly. If that's sufficient, we could definitely surface it.

**Comment by stevemessick** [comment]
Counting suites instead of tests would be inconsistent with what is done
for all (that I know of) other languages supported by IntelliJ. I think
most users value consistency, so they would probably question why it is
different for Dart.

We'd have to check with JetBrains, but we might be able to add an option to
the test controller to determine if the initial count is needed. That way,
for sufficiently slow test runs, the user could disable it if they didn't
care about the progress bar. (After writing that paragraph I found myself
thinking it is probably not a good UX but might as well see what others
think.)

On Wed, Dec 2, 2015 at 4:41 PM, Natalie Weizenbaum <notifications@github.com

**Comment by nex3** [comment]
The idea with reporting suites is that you could then figure out an estimate of the number of tests based on some tests per suite average. You could even update that over time as you (and the test runner) learn more about test suites.

I'm not very comfortable with the idea of adding an option to the test runner for this. I'm reticent to add options in general because they muddy the user interface, and this seems like a very narrow one that would make the user experience worse in almost all cases.

**Comment by kevmoo** [comment]
We can work to provide enough data to generate a "monotonically increasing" number – say from 0.0 to 1.0.

* We know how many suites will be run early.
* Once a suite starts running, it knows how many individual tests it contains.

So if we have 2 suites: `A` with 5 tests and `B` with 10 tests.

* Every tests that completes in A increases the "done" value by 0.1 – `1/2 * 1/5`
* Every tests that completes in B increases "done" by value by 0.05 – `1/2 * 1/10`.

Easy.

Obviously we could have two suites: one with 100 slow tests and one with 1 fast test. In this case, we'd get to 50% **really** fast – but I think that's okay. Every bump test that completes (pass or fail) psedo-percent done.
