### ISSUE TITLE
Should be able to run tests in a custom zone

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#375]
I currently can't migrate the `observe` package off of unittest because [this test](https://github.com/dart-lang/observe/blob/5197403cf003704df704589ea71a4510ff7c0213/test/observe_test.dart) is failing. It requires that all tests are ran in the `dirtyCheckingZone()` in order for changes to be recognized. It appears that the test runner is calling each test body in its own zone which overrides the `dirtyCheckingZone()`.

Is there any way to override this behavior or some other workaround that can be used?

**Comment by nex3** [comment]
Can't you just wrap the test body in the zone?

**Comment by jakemac53** [comment]
I briefly tried this but I was getting timeouts so I assumed the test package didn't support it, I can try again though if you don't think it should be an issue (timeouts may have been unrelated).

**Comment by jakemac53** [comment]
Ok - I was able to just implement my own sets/group/setUp/tearDown methods which do this and got things working. For some reason I could only get it to work by using `bindCallback` and then invoking that, instead of just calling `run`, not sure what the exact difference is there.

**Comment by nex3** [comment]
As far as I know there shouldn't be a difference between `zone.bindCallback(fn)()` and `zone.run(fn)`. If there is, that might be a bug in the zone or even `dart:async`.

**Comment by jakemac53** [comment]
I looked into this a bit with @kevmoo and the difference is that `bindCallback` calls `registerCallback` and then `run`.
