### ISSUE TITLE
No loading events for dependent test files

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/test#376]
Consider quiver-dart. It has a *test/all_tests.dart* file that runs all tests.
```dart
library quiver.all_tests;

import 'async/all_tests.dart' as async;
import 'cache/map_cache_test.dart' as cache;
import 'check_test.dart' as check;
import 'collection/all_tests.dart' as collection;
import 'core/all_tests.dart' as core;
import 'io_test.dart' as io;
import 'iterables/all_tests.dart' as iterables;
import 'mirrors_test.dart' as mirrors;
import 'pattern/all_tests.dart' as pattern;
import 'strings_test.dart' as strings;
import 'testing/all_tests.dart' as testing;
import 'time/all_tests.dart' as time;

main() {
  async.main();
  cache.main();
  check.main();
  collection.main();
  core.main();
  io.main();
  iterables.main();
  mirrors.main();
  pattern.main();
  strings.main();
  testing.main();
  time.main();
}
```
IntelliJ receives only one loading event, for *all_tests.dart*, which is clearly not useful for any practical purpose. It needs loading events for each file to support navigation from test results to test source code.

**Comment by kevmoo** [comment]
The model for test has been that each file should stand alone. Moving to pkg/test should mean we no longer need a `all_tests.dart` file – except, maybe, for folks generating coverage who need a single entry point.

**Comment by nex3** [comment]
Yeah, as Kevin points out, this is not the recommended means of running tests in the new world.

**Comment by clayberg** [comment]
Just out of curiosity, how are you preventing folks from doing this using pkg/test? That seems like a very common pattern that people will follow whether it is recommended or not.

**Comment by kevmoo** [comment]
Let's put this another way – there is **zero** difference between the pattern above and just having all of the tests in each of those file all inline `all_tests.dart`. `test` does some magic, but it's limited magic. All of the calls to `test(..)` within one `test_***.dart` file are grouped with that file.

If you want the benefit of the UI of having many suites and many load events – you need to put tests in separate files.


...or we need to define some new construct for a user to define multiple suites within one file – but that just sounds like another layer of grouping to me. A suite is a unit of compilation – it's just a library.

**Comment by zoechi** [comment]
I hope this will not be necessary anymore for coverage as well eventually.

**Comment by stevemessick** [comment]
I have never been a big fan of telling users they have to change their behavior when there is no obvious benefit. And there is none here. Users who are accustomed to running tests from (existing) test drivers will have to change their scripts and expectations and they still get the same results, as far as I can tell. But, for the sake of discussion, if everyone thinks this is the right way to go, then let's agree that the users will accept the change.

We still need to provide a way for programmers who use IntelliJ to work with tests in the IDE. We can't do that today. There is no way that I can find to implement navigation.

Here's the first part of the JSON emitted when running quiver tests the accepted way. Note that this is run in the same project that contains the original Dart code snippet in the OP.
```bash
messick-macbookpro2:quiver-dart messick$ pub run test:test -r json
{"protocolVersion":"0.1.0","runnerVersion":"0.12.6","type":"start","time":0}
{"test":{"id":0,"name":"loading test/async/collect_test.dart","groupIDs":[],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":0}
{"test":{"id":1,"name":"loading test/async/concat_test.dart","groupIDs":[],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":1}
{"test":{"id":2,"name":"loading test/async/countdown_timer_test.dart","groupIDs":[],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":1}
{"test":{"id":3,"name":"loading test/async/create_timer_test.dart","groupIDs":[],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":2}
{"test":{"id":4,"name":"loading test/async/enumerate_test.dart","groupIDs":[],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":2}
{"test":{"id":5,"name":"loading test/async/future_group_test.dart","groupIDs":[],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":3}
{"test":{"id":6,"name":"loading test/async/future_stream_test.dart","groupIDs":[],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":3}
{"test":{"id":7,"name":"loading test/async/iteration_test.dart","groupIDs":[],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":4}
{"testID":4,"result":"success","hidden":true,"type":"testDone","time":521}
{"group":{"id":8,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null}},"type":"group","time":526}
{"group":{"id":9,"parentID":8,"name":"enumerate","metadata":{"skip":false,"skipReason":null}},"type":"group","time":526}
{"test":{"id":10,"name":"enumerate should add indices to its argument","groupIDs":[8,9],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":527}
{"testID":5,"result":"success","hidden":true,"type":"testDone","time":528}
{"group":{"id":11,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null}},"type":"group","time":528}
{"group":{"id":12,"parentID":11,"name":"FutureGroup","metadata":{"skip":false,"skipReason":null}},"type":"group","time":528}
{"test":{"id":13,"name":"FutureGroup should complete when all added futures are complete","groupIDs":[11,12],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":528}
{"testID":2,"result":"success","hidden":true,"type":"testDone","time":529}
{"group":{"id":14,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null}},"type":"group","time":529}
{"group":{"id":15,"parentID":14,"name":"CountdownTimer","metadata":{"skip":false,"skipReason":null}},"type":"group","time":529}
{"test":{"id":16,"name":"CountdownTimer should countdown","groupIDs":[14,15],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":529}
{"testID":1,"result":"success","hidden":true,"type":"testDone","time":531}
{"group":{"id":17,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null}},"type":"group","time":531}
{"group":{"id":18,"parentID":17,"name":"concat","metadata":{"skip":false,"skipReason":null}},"type":"group","time":531}
{"test":{"id":19,"name":"concat should produce no events for no streams","groupIDs":[17,18],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":532}
{"testID":0,"result":"success","hidden":true,"type":"testDone","time":532}
{"testID":7,"result":"success","hidden":true,"type":"testDone","time":532}
{"testID":3,"result":"success","hidden":true,"type":"testDone","time":532}
{"testID":6,"result":"success","hidden":true,"type":"testDone","time":532}
{"testID":13,"result":"success","hidden":false,"type":"testDone","time":567}
{"test":{"id":20,"name":"FutureGroup should throw if adding a future after the group is completed","groupIDs":[11,12],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":568}
{"testID":20,"result":"success","hidden":false,"type":"testDone","time":571}
```
So yes, doing it properly does provide loading events. But, there is still no linkage from group and test events back to the loading event. Given a test, there is still no way to find which file it is defined in. We cannot rely on ordering; as shown above several files can be loaded before any tests defined in them are run. The outer group for each file has no parent and no way to determine which file it is defined in.

Is this just a minor bug that can be fixed by defining a parent for a parent-less group to be the loading event that preceded it? If so, can we get that fixed? Otherwise we still have a big problem.

**Comment by stevemessick** [comment]
(Accidentally submitted the comment before I was finished.)
Let's consider a specific test. There is a test named "should add indices to its argument" that is in group "enumerate" that is defined in enumerate_test.dart. In this case, it is the first user-defined test to run, with test event id=1. We get a test event with id=4 when that file is loaded. You'll see that it is the sixth of eight sequential loading events. Test id=10 has parents with id=9 and id=8. Those identify group events. Group id=9 is the "enumerate" event, and its parent is id=8. Group id=8 is the synthetic group for the file. It has no parent. The test id=4 event has no children, so there is no way to tell that this specific test is in the file enumerate_test.dart.

Now imagine that this specific test fails. The IntelliJ UI shows the test clearly, with red icon, as failing. Users (of many tools, not just IntelliJ) expect to click something that stands out and be provided with more information. In this case, JetBrains has trained its customers to expect the "more information" to be provided by jumping to the source code in the editor. That's what we need to implement.

**Comment by nex3** [comment]
@stevemessick Associating a test with the file it's contained in sounds like a different issue than #376. Can you open a separate issue for that?

**Comment by stevemessick** [comment]
And lose all this context? No. If you understand the problem then please fix it.

**Comment by kevmoo** [comment]
Moved to this bug - https://github.com/dart-lang/test/issues/380

**Comment by kevmoo** [comment]
We're not going to add a separate "file load" event for dependent test files. Discussions about adding information to the `group` and `testStarted` events ar at #380
