### ISSUE TITLE
pub run test -p "chrome" seems to run untransformed code

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/test#383]
While [investigating an error of using reflectable](https://github.com/dart-lang/reflectable/issues/64#issuecomment-171308462), it appears as if `pub run test -p "chrome"` does not run code transformers.

Is this possible? If so, why doesn't do it? `pub run test -p "chrome"` uses dart2js compilation, so it should also use code transformers, just like dart2js does.

**Comment by kevmoo** [comment]
To get transformers working, you need to spin up `pub serve` – see https://github.com/dart-lang/test#testing-with-barback
