### ISSUE TITLE
Platform "vm" and --pub-server don't go together

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/test#384]
I have a project that uses reflectable and has tests for both dart:io and dart:html, but when I run `pub run test -p vm,chrome --pub-serve=8080`, the dart:io tests fail while they don't fail without `--pub-serve` set.
This is the error it throws

```
Failed to load "test/io_without_env_test.dart": Unsupported operation: The transformed code is running with the untransformed reflectable package. Remember to set your package-root to 'build/.../packages'.
  http://localhost:8080/io_without_env_test.dart 27:5  _initializeReflectable
  http://localhost:8080/io_without_env_test.dart 17:3  main
```

**Comment by nex3** [comment]
It's possible that we're failing to get dependencies from the `pub serve` URL. Can you produce a minimal reproduction?

**Comment by natebosch** [comment]
`--pub-serve` hasn't been removed but it's no longer the expected way to run tests. If you are using codegen with your package it should now be going through `pub run build_runner` and you should be able to use `pub run build_runner test -- -p vm,chrome`
