### ISSUE TITLE
Barback integration on Windows

### ISSUE THREAD

**Issue by Fox32** [dart-lang/test#385]
When using the Barback integration on Windows, I get an error message for every test like this:

```
...
00:00 +0 -4: compiling test\collections\pool_test.dart
  Failed to load "test\collections\pool_test.dart":
  Error getting http://localhost:8081/collections%5Cpool_test.html.polymer.boots
trap.dart.browser_test.dart.js.map: 404 Not Found
  Make sure "pub serve" is serving the test/ directory.
....
```

pub serve shows the corresponding error message:

```
...
[test] GET collections%5Cpool_test.html.polymer.bootstrap.dart.browser_test.dart
.js.map => Could not find asset projectz|test/collections%5Cpool_test.html.polym
er.bootstrap.dart.browser_test.dart.js.map.
...
```

Looks like the test package is using the Windows path separator for http urls but shouldn't. I don't provide a test case as I think any simple test should work. When I fix the url and open it in a browser, it also doesn't load, but that is maybe another problem.

Im using:
Dart VM version: 1.14.0-dev.6.0 (Wed Jan 06 04:27:24 2016) on "windows_x64"
test version 0.12.5

**Comment by nex3** [comment]
I don't have an easy way to test on Windows at the moment. Can you try [the pub-serve-windows branch](https://github.com/dart-lang/test/tree/pub-serve-windows) and let me know if that addresses the issue?

**Comment by Fox32** [comment]
That seems to fix the path issue, even though I still get the same error message. But that is a different issue that I will try to investigate myself first.

**Comment by nex3** [comment]
Can you paste in the new error message you're getting?

**Comment by Fox32** [comment]
It's the same as above, just with the correct slashes. If I try to request the url in my browser I get a 404.
The test output (I only copied one of the message, but I get the same for every test):
```
...
00:00 +0 -4: compiling test\collections\pool_test.dart
  Failed to load "test\collections\pool_test.dart":
  Error getting http://localhost:8081/collections/pool_test.html.polymer.bootstr
ap.dart.browser_test.dart.js.map: 404 Not Found
...
```

pub serve:
```
...
[test] GET collections/pool_test.html.polymer.bootstrap.dart.browser_test.dart.j
s.map => Could not find asset projectz|test/collections/pool_test.html.polymer.b
ootstrap.dart.browser_test.dart.js.map.
...
```
I think it's a problem with my transformer setup. I have the polymer first, followed by the test transformer and then the dart2js transformer. I'm using polymer in my application but in none of my tests. I did more investigation by opening the urls in my browser:

http://localhost:8081/collections/pool_test.html => works
links to http://localhost:8081/collections/pool_test.dart.browser_test.dart.js => works
http://localhost:8081/collections/pool_test.dart.browser_test.dart.js.map => works




Btw. I'm now using:
Dart VM version: 1.14.0-dev.7.2 (Wed Jan 20 10:57:58 2016) on "windows_x64"

**Comment by nex3** [comment]
I have no idea why your request would be succeeding when you do it manually but failing from test.

I'm going to see if I can reproduce this outside Windows. Can you link me to your project, or email me a zip file?

**Comment by Fox32** [comment]
Sorry for confusing you, but they don't work because I'm manually requesting them, but because I use another url. The non-polymer urls, work but I can't get the polymer ones to work. I don't use polymer in the tests, but in other parts of my application.

I will try to create a simple test case in the next days, but in general I think that your branch with the fix can be merged, and the current issue is a separate one.

**Comment by grouma** [comment]
@natebosch this can be closed right?

**Comment by natebosch** [comment]
Yeah barback isn't supported anymore.
