### ISSUE TITLE
Support a default HTML wrapper

### ISSUE THREAD

**Issue by travissanderson-wf** [dart-lang/test#39]
For our use case we want to be able to provide a default HTML file instead of one for every test file.  See have this PR into test_runner.dart google/test_runner.dart#35 for how we are accomplishing that there.

**Comment by natebosch** [comment]
We have default HTML files which are automatically provided when the test does not have it's own.

**Comment by travissanderson-wf** [comment]
The purpose of this request was for us to be able to provide a customized default HTML file besides the auto-generated one that the runner creates.  Is that capability available now?

**Comment by natebosch** [comment]
Ah I see, no that isn't an option today. Will leave this open for consideration.

**Comment by travissanderson-wf** [comment]
👍

**Comment by natebosch** [comment]
I think what this would take is adding some support for configuration in `dart_test.yaml` to point to a template to use instead of the default one provided by the test runner. We won't have bandwidth to implement this any time soon but we'd be happy to review a pull request adding this.

**Comment by wytrych** [comment]
@natebosch are you still open for a PR on this feature? I'd be happy to look into this.

**Comment by jakemac53** [comment]
Another option here would be to do this with a builder - it would be pretty trivial but would require the use of build_runner. However that is already a dependency for almost any web project.

That way the `test` package doesn't have to own this logic (or add the deps required to support it), and it would be easier for people to iterate? It would also allow for multiple templating languages etc.

**Comment by wytrych** [comment]
Using `build_runner` is doing something very different though, it tries to build the whole package first, not only pulling in the necessary dependencies. In a big project that is a big difference.

**Comment by jakemac53** [comment]
> Using `build_runner` is doing something very different though, it tries to build the whole package first, not only pulling in the necessary dependencies. In a big project that is a big difference.

You can't run the tests (in debug mode at least) until the whole package is built anyways - so I think for most users this wouldn't matter.

Note that it does also now have the ability to only build a specific app or glob of files via the `--build-filter` option.

**Comment by wytrych** [comment]
Hmm when I run a single test it only builds the files that are actually imported from that test (and their dependency graph ofc)

**Comment by jakemac53** [comment]
If you run `pub run test -p chrome` then yes it does that - but it compiles with dart2js which isn't easy to debug. It isn't really something we recommend people to do.

Also, as I mentioned you can now do the same with `build_runner` (only compile a single test). We need better documentation around this to be sure but its possible to do.

**Comment by jakemac53** [comment]
I talked with @natebosch a bit about this. We would be open to taking a PR for this in the test package.

We would however like to ensure that it is very limited in scope. Most likely this means only supporting a single special placeholder in the template, which is for test file name. This would be string replaced to create the resulting html file.

This will ensure we don't need to add any additional dependencies, and the maintenance burden would be very low.

**Comment by wytrych** [comment]
Ok, sounds good, I'll see what I can do.

**Comment by wytrych** [comment]
@jakemac53 I got something working, but I'm wondering what is the best way to create the resulting html file? Is just just `File().writeAsStringSync` or is there some way to create a virtual file somehow?

**Comment by jakemac53** [comment]
It should be possible to never write this file to disk at all but simply add an extra handler to the test server which knows how to serve it when requested. I believe that is how the existing default html files are done.

You can look at the browser platform code probably to find this - I can dig a bit and see if I can find a good link for you.

**Comment by jakemac53** [comment]
https://github.com/dart-lang/test/blob/master/pkgs/test/lib/src/runner/browser/platform.dart#L160

**Comment by wytrych** [comment]
Thanks @jakemac53 that's interesting, I was actually looking at https://github.com/dart-lang/test/blob/ba98412ebf61fc77a785a882b62deea4d6689d69/pkgs/test/lib/src/runner/browser/platform.dart#L264 since this seems to be the place that is tested in https://github.com/dart-lang/test/blob/ba98412ebf61fc77a785a882b62deea4d6689d69/pkgs/test/test/runner/browser/runner_test.dart#L293  

When are these different codepaths taken?

**Comment by jakemac53** [comment]
I believe that what I linked is always what is used unless running in `pub-serve` mode which isn't really a supported mode at all any more (basically it allows you to run tests against a running server).

That part you linked is just where it is assigning the URL from which the suite should be loaded - but it doesn't actually generate the html. That is done in the handler, when the files are requested (assuming no explicit custom html file).

**Comment by wytrych** [comment]
Ah that makes sense. I missed the point that the handler will get called only when there isn't an actual file found. Thanks!
