### ISSUE TITLE
Add option to run skipped tests

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#393]
Skipped tests can tend to pile up, because they can easily be left skipped even though the underlying issue was resolved. It would be great to have an option to run all skipped tests, so that package authors can quickly tell which skipped tests were resolved by any particular issue.

Alternatively, there could be a `fail` option which is like `skip` except it asserts test failure, and the test runs every time you run `pub run test`.

**Comment by nex3** [comment]
I think this is worth doing as a flag, something like `--no-skip` or `--ignore-skip`.

> Alternatively, there could be a `fail` option which is like `skip` except it asserts test failure, and the test runs every time you run `pub run test`.

This is pretty easy to do without any explicit support from the test runner. Just use the `throwsA()` matcher, or even something like

```dart
test("...", () {
  runZoned(() {
    // ...
  }, onError: expectAsync((_) {}, max: 0));
});
```

**Comment by kevmoo** [comment]
I love the 'fail' option.

On Fri, Feb 5, 2016 at 3:02 PM, Natalie Weizenbaum <notifications@github.com

**Comment by nex3** [comment]
Another issue with a blanket "this test fails" annotation is that it doesn't distinguish between the failure you expect and any other failure that might happen. Writing your failure assertions in the test itself allows you to be explicit about what exactly is expected to fail.

**Comment by jakemac53** [comment]
> I think this is worth doing as a flag, something like --no-skip or --ignore-skip

I agree this would be a good solution, and I think it should be implemented regardless of an additional `fail` option.

> This is pretty easy to do without any explicit support from the test runner. Just use the throwsA() matcher, or even something like ...

The `fail` option I was envisioning covers a different use case than this. Specifically, it would be used for tests that are expected to _pass_ but are failing due to a _known issue_. In that case I think it makes the most sense for the test to stay "pure" (ie: describe expected behavior), and for the failure to be marked on the side (via annotation or named arg). Essentially, it has a 1:1 mapping with all use cases of `skip` today, except that it actually runs any time you run the tests, and if it passes then that is marked as a failure.

**Comment by nex3** [comment]
In the example I used above, you can include the "pure" test case in the middle of the `runZoned()` call. But I feel strongly that we shouldn't encourage users to assert that *any error* occurred. That's how the SDK repo test runner works, and I've seen plenty of times where it covered up useful information.

**Comment by jakemac53** [comment]
> In the example I used above, you can include the "pure" test case in the middle of the runZoned() call. But I feel strongly that we shouldn't encourage users to assert that any error occurred. That's how the SDK repo test runner works, and I've seen plenty of times where it covered up useful information.

I agree generally with the sentiment, and have experienced the same issues in the past. However, I actually see the `fail` option as the solution, and `skip` as the problem. The problem with `skip` is that especially as skipped tests pile up they never get "unskipped", even when the issue gets resolved. Later on a different bug that would have been caught by a skipped test never gets ran, and so you gradually pick up bugs. With `fail` at least the chance of a test being marked as passing later on is increased, since when it starts passing the user will be automatically notified.

Also, `skip` is already being used today by people to mark tests as arbitrarily failing, so I think the ship has sailed on that. `fail` would be strictly better imo, and I would almost never use `skip` if I had it.

Another possible option to solve this general issue would be allowing `skip` etc on calls to `expect`, instead of (or in addition to) `test`. For larger tests especially this would allow you to more specifically target the expectation that is failing, but still run the rest of the test.

**Comment by nex3** [comment]
> The problem with `skip` is that especially as skipped tests pile up they never get "unskipped", even when the issue gets resolved.

I've tried to make the test runner pretty obnoxious when you've skipped a test. You get this bright yellow number, and you don't get to see "All tests passed". I'd hope that that annoyance would be enough to discourage people from permanently skipping tests.

> Also, `skip` is already being used today by people to mark tests as arbitrarily failing, so I think the ship has sailed on that. `fail` would be strictly better imo, and I would almost never use `skip` if I had it.

Then why don't you use one of the techniques I described above to assert failures instead of skipping today?

> Another possible option to solve this general issue would be allowing `skip` etc on calls to `expect`, instead of (or in addition to) `test`. For larger tests especially this would allow you to more specifically target the expectation that is failing, but still run the rest of the test.

Although in general I'd discourage the creation of large tests, I think this is reasonable. Can you file a separate issue for it?

**Comment by jakemac53** [comment]
> I've tried to make the test runner pretty obnoxious when you've skipped a test. You get this bright yellow number, and you don't get to see "All tests passed". I'd hope that that annoyance would be enough to discourage people from permanently skipping tests.

I didn't specify earlier, but I would absolutely expect the same behavior for anything marked as "failing" (although probably a different color).

For many projects they will always be in a state of having some tests be skipped, so while good for getting an idea of overall test health, I don't think this is going to prevent anybody from using it.

> Then why don't you use one of the techniques I described above to assert failures instead of skipping today?

Because I want the complaints in the console like you get from `skip`. It is much better for getting an overall view of test health to see the number of failing/skipped tests each time you run.

> Although in general I'd discourage the creation of large tests, I think this is reasonable. Can you file a separate issue for it?

done, https://github.com/dart-lang/test/issues/394

**Comment by nex3** [comment]
> Because I want the complaints in the console like you get from `skip`. It is much better for getting an overall view of test health to see the number of failing/skipped tests each time you run.

What about something like:

```dart
void unwantedErrors(testBody(), Matcher errorMatcher) {
  runZoned(testBody, catchError: expectAsync((error, stackTrace) {
    print("\u001b[33mExpected failure!\u001b[0m");
    expect(error, errorMatcher);
  }, max: 0));
}
```

I'd be okay adding something like that to `test`.

**Comment by jakemac53** [comment]
> What about something like:
> 
> void unwantedErrors(testBody(), Matcher errorMatcher) {
>   runZoned(testBody, catchError: expectAsync((error, stackTrace) {
>     print("\u001b[33mExpected failure!\u001b[0m");
>     expect(error, errorMatcher);
>   }, max: 0));
> }
> I'd be okay adding something like that to test.

Ideally, it would also fail if no error was found, and it would print a summary at the end just like `skip` does. I do like the general idea of providing an errorMatcher though, as that would at least help make sure the tests are still failing for the expected reason. 

In general I don't see a reason to break from the named argument pattern that is used for other `test` options. For instance something like:

```dart
test('failing test', () {
  expect(1, equals(2));
}, expectedFailure: allOf([contains('Expected 1'), contains('Actual 2')]));
```

**Comment by nex3** [comment]
> Ideally, it would also fail if no error was found

The above code does that, more or less. It blocks until an error occurs, and if none does it will time out. I could make it more clever than that, too.

> a summary at the end just like `skip` does

Do you mean printing the reason the test was skipped?

> In general I don't see a reason to break from the named argument pattern that is used for other `test` options. For instance something like:
>
> ```dart
> test('failing test', () {
>   expect(1, equals(2));
> }, expectedFailure: allOf([contains('Expected 1'), contains('Actual 2')]));
> ```
> 
> It might be useful to have aspecial matcher or something as well for these?

Named arguments are for testing metadata; this is actually setting up expectations, which is not serializable and needs to happen within the test zone anyway.

I've filed #395 to track this.

**Comment by jakemac53** [comment]
> Do you mean printing the reason the test was skipped?

I mean the `~` part in the final message: `+87 ~1: All tests passed!`.

> Named arguments are for testing metadata; this is actually setting up expectations, which is not serializable and needs to happen within the test zone anyway.
> 
> I've filed #395 to track this.

sgtm
