### ISSUE TITLE
Tests in different files can overwrite each others' descriptions

### ISSUE THREAD

**Issue by dougmill** [dart-lang/test#398]
I run `pub run test` on the following two files:
one:

    import 'package:test/test.dart';

    void main() {
      for (int i = 1; i < 1000; i++) {
        test("test ${i}", ()  {
        });
      }
    }
and two:

    import 'package:test/test.dart';

    void main() {
      for (int i = 1000; i < 2000; i++) {
        test("test ${i}", ()  {
        });
      }
    }

In the output, there are numerous sequences such as this:

    00:00 +1704: test/test_test2.dart: test 1856
    00:00 +1705: test/test_test.dart: test 849
    00:00 +1706: test/test_test2.dart: test 1857
    00:00 +1707: test/test_test2.dart: test 1857
    00:00 +1708: test/test_test2.dart: test 1857
    00:00 +1709: test/test_test2.dart: test 1857
    00:00 +1710: test/test_test.dart: test 853
    00:00 +1711: test/test_test2.dart: test 1858
    00:00 +1712: test/test_test.dart: test 854
    00:00 +1713: test/test_test2.dart: test 1859
    00:00 +1714: test/test_test.dart: test 855

At apparently random points, the description of one test from one file, including its source file, is used in place of the description of the test that is actually being done from the other file. The stretches of a single repeated description for many tests are a lot longer in my actual project, I suspect in large part due to a lot of them being asynchronous and some having time based delays.

I don't think this affects the failure reports, but it's harder to spot patterns in those.

**Comment by nex3** [comment]
This looks like the expected behavior to me. Different test files are run in parallel, and the reporter prints the name of the oldest running test in the status line. Your status lines are just alternating between different files' oldest running tests.

**Comment by dougmill** [comment]
Why the hell would a report of "a test is being started" print the name of the oldest running test rather than the test that prompted the print? If this is expected behavior, then it is extremely counterintuitive.

**Comment by nex3** [comment]
If a test is in the process of timing out, or if it just takes a long time, it's important to provide that information to the user. If we printed the names of each test as it began running, there would be no visibility into slow tests when running in parallel. The alternative is just printing test names in the order they appear in the files, which doesn't provide useful new information.

If you want, you can avoid running tests in parallel at all by passing `-j 1`. When there's only one test running at any given time, you'll see each test name in sequence.

**Comment by dougmill** [comment]
All right, that makes sense, but it needs to be in the documentation or, better, in the output. I just checked https://www.dartdocs.org/documentation/test/0.12.10%2B2/ and I could find no mention anywhere of what each part of the output means. A lot of information about how to use the package, but nothing about how to interpret its output.

When I see a long sequence of output scrolling up the screen, or listed in an output dump, my first and usually correct assumption is that it's a series of reports on events, not a series of reports on current status. Breaking that assumption without telling me makes me suspect something is wrong, and I'd be surprised if that assumption isn't common.
