### ISSUE TITLE
Test description gets cut off and makes test output useless

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/test#402]
00:00 +10 -1: test/srcs/md_parser/md_parser_test.dart: ... at the end  that emits same document again

How can I show the full description? The output is useless for me right now :(

**Comment by nex3** [comment]
You can see the full test name by using the `expanded` reporter or by printing something in the test. In addition, if the test experiences an error, it will print the full name. Once #86 is fixed, you'll also be able to see it by expanding your terminal window.
