### ISSUE TITLE
Ubuntu no longer includes fonts ttf-kochi-mincho or ttf-kochi-gothic

### ISSUE THREAD

**Issue by vpigrad** [dart-lang/test#415]
This blocks running tests that need content_shell.  They recommend "fonts-vlgothic" or "fonts-ipafont-gothic" which are more up to date.  I don't think the kochi fonts have been updated in over a decade:

https://launchpad.net/ubuntu/xenial/+package/ttf-kochi-gothic

**Comment by zoechi** [comment]
As a workaround I created symlinks to arbitrary other fonts to make it work but that shouldn't be necessary.

(Debian - some of these fonts might be available as package for Ubuntu but aren't for Debian)

```bash
apt-get install msttcorefonts fonts-indic fonts-tlwg-garuda-otf
mkdir /usr/share/fonts/truetype/kochi
cd /usr/share/fonts/truetype/kochi
ln -s ../dejavu/DejaVuSans-Bold.ttf kochi-gothic.ttf
ln -s ../dejavu/DejaVuSans-Bold.ttf kochi-mincho.ttf
mkdir /usr/share/fonts/truetype/ttf-indic-fonts-core/
cd /usr/share/fonts/truetype/ttf-indic-fonts-core/
ln -s ../dejavu/DejaVuSans-Bold.ttf lohit_hi.ttf
ln -s ../dejavu/DejaVuSans-Bold.ttf lohit_ta.ttf
ln -s ../dejavu/DejaVuSans-Bold.ttf MuktiNarrow.ttf
mkdir /usr/share/fonts/truetype/ttf-punjabi-fonts/
cd /usr/share/fonts/truetype/ttf-punjabi-fonts/
ln -s ../dejavu/DejaVuSans-Bold.ttf lohit_pa.ttf

ln -s dejavu/ ttf-dejavu
cd /usr/share/fonts/truetype
ln -s dejavu/ ttf-dejavu
```

**Comment by nex3** [comment]
This issue was moved to dart-lang/sdk#26119
