### ISSUE TITLE
Add the ability to customize which packages' frames are folded

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#416]
Right now, we have some hard-coded logic for folding stack chains that come from test errors. We fold core library frames and frames from the `test`, `stack_trace`, and `stream_channel` packages. We should make this set of packages customizable, at least by allowing users to add to it. The config for this could look something like:

``` yaml
folded_packages:
- pool
- async
```

I'm not super happy with that name—it only makes sense to people who know that "folding" is a thing that can be done to stack traces. But I also don't want to make it too verbose, and I'm having trouble coming up with a better alternative.

**Comment by kevmoo** [comment]
A thought: this will rarely be configured. Verbose is not a huge issue for something rarely used.

For rarely used features, discoverability is more important IMHO

**Comment by nex3** [comment]
@kevmoo Do you have a name suggestion?

**Comment by kevmoo** [comment]
`stack_trace_folded_packages` ?

**Comment by nex3** [comment]
I think the following would be a good format for this:

```yaml
fold_stack_frames:
  only:
  - pool
  - async

# or
fold_stack_frames:
  except:
  - pool
  - async
```
