### ISSUE TITLE
Add a neverCalled function

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#417]
It's common to call `expectAsync((_) {}, count: 0)` when passing in a callback that should never be invoked, but this is verbose and won't work well with strong mode. We should have a dedicated function for this; we could do it with a signature like:

``` dart
T neverCalled<T>([_1, _2, _3, _4, _5, _6, _7, _8, _9, _10]);
```

This can then be used as a tearoff so things like `stream.every(neverCalled)` type-check correctly thanks to the magic of inference.

This (or some shared infrastructure) could be used to implement #24.

**Comment by grouma** [comment]
I'm a little confused as to the intent behind this function. Could this function simply wrap a fail call with a message stating that it should never be called?

**Comment by nex3** [comment]
I think it would be cleaner to forward to `expectAsync()`, since it already handles this case. But yes, the implementation will be pretty slim.

Looking at the `expectAsync()` implementation, it looks like it doesn't pump the event queue for 0-count assertions, so it would be good to add that as well.
