### ISSUE TITLE
Add exact test/group location in JSON reporter

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/test#420]
This is a follow-up of #380.
In JSON test result reporter it would be great to have file path, line and column for each test and group that starts.
See discussion here: https://github.com/dart-lang/test/issues/380#issuecomment-174665377

>...
The hard way would get closer to your ideal output. We'd have to capture a stack trace at the point a test is declared and pipe that all the way through to the reporter. This is doable, but it will take more time and consequently be further down on the priority list (although certainly still a priority for Q1).

**Comment by nex3** [comment]
How urgent is this?

**Comment by alexander-doroshko** [comment]
I'd assign medium priority. Like 'nice to have' feature.

**Comment by nex3** [comment]
Okay, I'll do my best to get to it this quarter.

**Comment by kevmoo** [comment]
@jwren @stevemessick We should get an associated issue open on IntelliJ to leverage this goodness ASAP 😄

**Comment by alexander-doroshko** [comment]
Support in IDE is done, works like a charm, thanks a lot!
