### ISSUE TITLE
Support configuring the analyzer via the package config file

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#422]
Once we support running the analyzer (#30), we should add configuration file support as well. This would probably involve an `analyzer:` option that allowed the same contents as the corresponding key in the `.analyzer_options` file. Supporting this in the test config would allow for different presets with different analysis configuration.

**Comment by zoechi** [comment]
Why limiting to the `analyzer:` key? What about linter rules? I would prefer lint rules to be treated the same as analyzer-built-in checks.

IMHO an `analyzer_options_file:` key that is passed to the analyzers

```
 --options                      Path to an analysis options file.
```

parameter. Otherwise it's likely that analyzer settings need to be duplicated unnecessarily (for example in different presets if you want to use more than one).

**Comment by nex3** [comment]
Supporting a linter pseudo-platform is, from a UI perspective, entirely different than supporting one for the analyzer. If we were to add support for it, it would have its own top-level `linter:` key in the config.

**Comment by bwilkerson** [comment]
Just FYI, the content of the analysis options file is made available to analyzer plugins, such as lint rules, so they can use their own top-level keys. Not providing access to the whole file could potentially limit future tooling. It's not a problem today, of course, because no-one (that I know of) is taking advantage of that support.

**Comment by nex3** [comment]
Don't analyzer plugins work by creating their own entrypoints that load in the necessary changes? I don't know that we'll be able to support that sort of thing anyway.

**Comment by bwilkerson** [comment]
Good point.

**Comment by zoechi** [comment]
When I run 

```bash
dartanalyzer */**.dart
```
with an existing `.analysis_options` file containing linter rules, lints are checked.  
I would find it surprising when `test` runs `dartanalyzer` but with a different behavior (ignoring lints).

If you have reasons to not implement it this way I can still run `dartanalyzer` like I do it currently using `grinder` where my default task runs `dartformat`, `dartanalyzer`, `pub run test`, ...

I'm wondering if running `dartanalyzer` to `test` would move `test` towards the domain of a task runner and if it weren't better to invest that energy in improving `grinder` instead.

Just my thoughts, there are always lots of different ways of doing things ...

**Comment by nex3** [comment]
@bwilkerson Can you provide some more context here? I thought [the linter](https://github.com/dart-lang/linter) was a separate application than the analyzer.

**Comment by bwilkerson** [comment]
The linter is a separate application from the user's perspective, but it basically just runs the same code as the command-line analyzer, enabling lints and suppressing non-lint messages. The command-line analyzer does not produce lint messages by default, but there is a "--lints" flag that will enable them.

**Comment by nex3** [comment]
Are there any top-level options in the `.analysis_options` file that the `dartanalyzer` executable will respect *other than* `analyzer:` and `linter:`?

**Comment by bwilkerson** [comment]
Not as far as I can remember, but there's no guarantee that there won't be at some point.

**Comment by nex3** [comment]
Can you give an example of another top-level key that could theoretically be added? It seems like the `analyzer:` key is so broad semantically it's hard for me to imagine configuration that *wouldn't* make sense beneath it (other than linter configuration I suppose).

**Comment by natebosch** [comment]
I don't think we have immediate plans to integrate the analyzer with the test package, and if we end up doing that we'll probably want to let analyzer keep using it's normal configuration paths rather than have a separate configuration used within test.
