### ISSUE TITLE
Use MessageChannels for communicating with iframes

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#423]
Now that Firefox supports [the MessageChannel API](https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel), we should use it to communicate between the host frame and its iframes. This is not only more elegant, it will avoid issues with the Google-internal continuous test runner where multiple instances of the same suite could step on one another's events.

The best way to do this is probably to create a `MessagePortChannel` which provides a StreamChannel API for a MessagePort. It might even be worth putting this in `stream_channel` itself.

/cc @goderbauer

**Comment by nex3** [comment]
This is blocked on dart-lang/sdk#26349.

**Comment by nex3** [comment]
Removing the milestone because Q2 is past and there doesn't seem to be any work being done on the blocking issues.

**Comment by kevmoo** [comment]
Seems a slam-dunk browser-support wise - http://caniuse.com/#search=MessageChannel

**Comment by kevmoo** [comment]
Should be in `2.0.0-dev.43.0`

**Comment by kevmoo** [comment]
Issue with calling `start` has been fixed. Should be golden in `2.0.0-dev.44.0`+
