### ISSUE TITLE
Per-test tearDown

### ISSUE THREAD

**Issue by Hixie** [dart-lang/test#426]
Right now if I want to run some post-test tear-down logic for a particular test, even in the case of an async timeout, the only way I could find to do it is to put the test in a group. The problem with that is that the name of the test gets affected by this.

One possible solution would be to have `setUp` and `tearDown` arguments to `test()`. Another would be to make `group('', ...)` (with no name) not affect the name of the subtests.

**Comment by nex3** [comment]
I think this is covered by #93, which would allow a test to add to its own tear-down like so:

```dart
test("starts a server", () async {
  var server = await HttpServer.bind('localhost', 0);
  addTearDown(() => server.close());

  // ...
});
```

**Comment by Hixie** [comment]
Yup, that would be great.
