### ISSUE TITLE
Actual: ?:<I don't know how to get rid of the weird punctuation>

### ISSUE THREAD

**Issue by Hixie** [dart-lang/test#428]
When `expect` notices an error, it outputs an Expected: Actual: Which: block of text.

The Actual: line, however, often seems to have weird punctuation wrapped around it.

I couldn't find any documentation on why this is happening or how to stop it.

**Comment by nex3** [comment]
This comes from [`matcher`](/dart-lang/matcher), and it has to do with how it pretty-prints values. You can see all the logic for it [here](https://github.com/dart-lang/matcher/blob/master/lib/src/pretty_print.dart).

The specific output you're seeing comes from the way unknown objects are printed. Those objects are always of the form `Type:<ToString>`, there *Type* is the name of the object's runtime type and *ToString* is the result of calling `toString()` on it. However, if the type name is private, matcher prints `?` instead. There's [an outstanding TODO](https://github.com/dart-lang/matcher/blob/master/lib/src/pretty_print.dart#L121-L122) to find a public type name to print instead, but I believe there still aren't cross-platform APIs available to do that.

**Comment by Hixie** [comment]
Ah, I see. Is there any way to fully control what appears on that line? I'd rather not have any angle brackets, because the value I want to print isn't a literal value, it's just an English-prose vague description of the value (the value itself is a gigantic tree that takes pages and pages to print and isn't useful to print in this context).

**Comment by nex3** [comment]
There is not, currently. Feel free to file a feature request on the matcher repo.

**Comment by Hixie** [comment]
Will do, thanks!

**Comment by Hixie** [comment]
Filed https://github.com/dart-lang/matcher/issues/32
