### ISSUE TITLE
unittest: Uncaught exceptions in setUp can cause timeouts without any error information

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/test#430]
If setUp returns a Completer and the code that should complete the completer throws an exception, it is possible that the exception gets caught by unittest's uncaughtExceptionHandler and is correctly registered with the framework. However, this means that the exception is not displayed on the console (or anywhere) at this point. Moreover, because the Completer does not complete, internal_test_case does not continue. The test times out without the exception ever being displayed anywhere even though it was registered :(

This hides important information from users and forces users to debug tests locally.

Please also consider implications for package:test. It might exhibit similar behavior. By the looks of it, tearDown might also be affected. Only the test method itself is hardened against such issues at the moment.

**Comment by nex3** [comment]
It sounds like you might be using version 0.11.x—is that correct? That version series is no longer maintained; if you're still using it, you should upgrade to 0.12.x as soon as possible.

**Comment by BlackHC** [comment]
Thanks, I'm using the version we have in google3 :) is it fixed in
package:test anyhow or should I check and file another bug? Regardless, is
it okay if I sent a CL to fix it locally for Google in third_party/dart?

I don't think we are going to migrate to package:test anytime soon.

Thanks,
Andreas

**Comment by nex3** [comment]
Google3 has a copy of 0.11 under the name `unittest` and a copy of 0.12 under the name `test`. It sounds like you're using the former.

> is it fixed in package:test anyhow or should I check and file another bug?

0.12 involves more or less a full rewrite of the internals, so it shouldn't carry forward any bugs. I'm pretty sure we test this case specifically, too.

> Regardless, is it okay if I sent a CL to fix it locally for Google in third_party/dart?

Sure.

> I don't think we are going to migrate to package:test anytime soon.

Can you go into more detail about why, either here or via IM? 0.12 mostly API-compatible with 0.11, and my impression was that it was fully functional in google3 at this point.
