### ISSUE TITLE
Connection closed before test suite is loaded

### ISSUE THREAD

**Issue by drmovi** [dart-lang/test#431]
when trying to use dartium for test the following error occurs

```
Failed to load "C:/Users/dmovi/WebstormProjects/LaravaelCrud/test/Dartium\laravel_form_test.dart": Connection closed before test suite loaded.

dart:async                                                    _StreamController.close
package:web_socket_channel/src/copy/web_socket_impl.dart 728  WebSocketImpl.WebSocketImpl.fromSocket.<fn>
dart:async                                                    _EventSinkWrapper.close
package:web_socket_channel/src/copy/web_socket_impl.dart 110  _WebSocketProtocolTransformer.close
===== asynchronous gap ===========================
dart:async                                                    _StreamController.close
package:web_socket_channel/src/copy/web_socket_impl.dart 728  WebSocketImpl.WebSocketImpl.fromSocket.<fn>
dart:async                                                    _EventSinkWrapper.close
package:web_socket_channel/src/copy/web_socket_impl.dart 110  _WebSocketProtocolTransformer.close
===== asynchronous gap ===========================
dart:async                                                    Future.Future.sync
package:pool/pool.dart 120                                    Pool.withResource.<fn>
===== asynchronous gap ===========================
dart:async                                                    _Future.then
package:pool/pool.dart 119                                    Pool.withResource
===== asynchronous gap ===========================
dart:async                                                    _SyncCompleter.complete
package:http_multi_server/http_multi_server.dart 136          HttpMultiServer._loopback.<async>
```

Process finished with exit code 1

any suggestions ?

**Comment by nex3** [comment]
What version of `test` are you using? What version of Dartium? Can you post your `pubspec.lock` file?

**Comment by drmovi** [comment]
sure here it is
name: 'LaravaelCrud'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  test: "^0.12.13+1"

transformers:
- dart_to_js_script_rewriter

**Comment by nex3** [comment]
That's your `pubspec.yaml` file; I need your `pubspec.lock` file. I also need to know what version of Dartium you're using.

**Comment by drmovi** [comment]
# Generated by pub
# See http://pub.dartlang.org/doc/glossary.html#lockfile
packages:
  analyzer:
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.27.2"
  args:
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.4+2"
  async:
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.11.0"
  barback:
    description:
      name: barback
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.2+7"
  boolean_selector:
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  browser:
    description:
      name: browser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.0+2"
  charcode:
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  collection:
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  convert:
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  crypto:
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  csslib:
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.2"
  dart_to_js_script_rewriter:
    description:
      name: dart_to_js_script_rewriter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  glob:
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  html:
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.2+2"
  http_multi_server:
    description:
      name: http_multi_server
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  http_parser:
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.0"
  logging:
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3"
  matcher:
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.0+2"
  mime:
    description:
      name: mime
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.3"
  package_config:
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.3"
  path:
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.9"
  plugin:
    description:
      name: plugin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0"
  pool:
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.4"
  pub_semver:
    description:
      name: pub_semver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.4"
  shelf:
    description:
      name: shelf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.5+2"
  shelf_static:
    description:
      name: shelf_static
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.3+4"
  shelf_web_socket:
    description:
      name: shelf_web_socket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.1"
  source_map_stack_trace:
    description:
      name: source_map_stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  source_maps:
    description:
      name: source_maps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.1+1"
  source_span:
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.2"
  stack_trace:
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.5"
  stream_channel:
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  string_scanner:
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.4+1"
  test:
    description:
      name: test
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.13+1"
  typed_data:
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  utf:
    description:
      name: utf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.0+3"
  watcher:
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7+2"
  web_socket_channel:
    description:
      name: web_socket_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  yaml:
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.9"
sdk: ">=1.16.0 <1.18.0"

**Comment by drmovi** [comment]
darium Version 45.0.2454.104

**Comment by nex3** [comment]
I can't reproduce this on Linux with the same versions, so I'm going to need you to do some more debugging for me.

Does Dartium open at all when you run your tests? If so, can you see anything printed on the dev console?

**Comment by drmovi** [comment]
suddenly all things works again after updating and restarting my PC. thx Natalie

**Comment by nex3** [comment]
Neat!

![shrug](https://cloud.githubusercontent.com/assets/188/15376897/c8c4ad90-1d0c-11e6-9b7f-d093170bf3c1.gif)
