### ISSUE TITLE
Add support for precompiled tests

### ISSUE THREAD

**Issue by mgiambalvo** [dart-lang/test#433]
We'd like to be able to run tests against non-Dartium browsers using precompiled javascript, rather than compiling it on the fly. We'll pass in a path to a directory of compiled javascript that mirrors the structure of the tests, just with all the .dart files already compiled to .js.

**Comment by nex3** [comment]
It's worth noting that this will be a Google-internal feature only, and so won't have a publicly-supported API.

**Comment by nex3** [comment]
Fixed in 686195a40e8b85050be834dfc9efb56866654ca8.

**Comment by nex3** [comment]
Fixed in 686195a40e8b85050be834dfc9efb56866654ca8.
