### ISSUE TITLE
Add an option to retry a test

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#441]
Some tests are inherently flaky in ways that aren't feasible to fix by modifying the test itself. In order to support running in environments where flakiness is undesirable, such as CI servers, the user should be able to mark tests to be retried a certain number of times in case they fail.

I think the best way for this to work is to add a named `int retry` parameter to `test()` and `group()`, an `@Retry(int times)` metadata annotation, and a `retry: !int` test-level field to the configuration file. A test experiencing an error—that is, any non-`TestFailure` exception—would be re-run that many times before actually being marked as a failure.

We could add more detailed logic to the parameter to allow users to specify exactly which exception type(s) cause retries, but I expect retrying mostly to be specified in configuration files (e.g. saying "all browser tests get three retries when running on Travis"), where there's not a good cross-platform way of specifying Dart types.

**Comment by nex3** [comment]
I believe since #632 landed this is largely done. One last piece which would be nice is a `--no-retry` flag and corresponding runner configuration, which would be useful for iterating locally on a test with retry configuration that's failing non-flakily.

**Comment by grouma** [comment]
This was completed with: https://github.com/dart-lang/test/pull/633
