### ISSUE TITLE
feature: debugging for content-shell in IntelliJ

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/test#443]
Please!!!!! add this feature. It's not possible to debug such tests. 1.17 and I have to mess around with log-outputs.

**Comment by nex3** [comment]
Please file this against IntelliJ, not `test`. This repo only tracks issues that can be fixed in the `test` codebase itself.

**Comment by alexander-doroshko** [comment]
@nex3 Is it already technically possible? Can you please give a hint/link about how it could be done at IDE side? May be any reference implementation, protocol spec or something.

**Comment by nex3** [comment]
Well, the IDE can invoke `test` with `--pause-after-load` and parse the resulting message. There's not currently any integration with the JSON reporter, though. If that would be helpful, feel free to file a separate issue with the information you'd like exposed.

**Comment by alexander-doroshko** [comment]
Sorry for the dumb question, I didn't play with content-shell. How can `--pause-after-load` and parsing message help to set breakpoints, step in/out/over, explore variables, resume, etc?

**Comment by nex3** [comment]
`--pause-after-load` gives you the Observatory URL and the Chrome remote debugger URL. You can use the [VM service protocol](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md) to control the VM using the former, and the [Chrome debugging protocol](https://developer.chrome.com/devtools/docs/debugger-protocol) to control the webpage using the latter.
