### ISSUE TITLE
"The system cannot move the file to a different disk drive" running "pub run test"

### ISSUE THREAD

**Issue by DanTup** [dart-lang/test#444]
I don't know if `pub run test` is the righty way to run tests (I thought there was a `pub test?!`) however I got this strange error when running it...

I'm on Windows 10, happens in both PowerShell and standard command windows.

I cloned https://github.com/dart-lang/convert, ran `pub get` then `pub run test` and got the following:

```
PS M:\Coding\Applications\convert> pub run test
Directory listing failed, path = 'test\packages\analyzer\dart\*' (OS Error: The system cannot move the file to a different disk drive.
, errno = 17)
dart:io                                    _Directory.listSync
package:test/src/runner/loader.dart 91:49  Loader.loadDir
package:test/src/runner.dart 240:60        Runner._loadSuites.<fn>
dart:_internal                             ListIterable.forEach
package:async/src/stream_group.dart 58:13  StreamGroup.merge
package:test/src/runner.dart 239:24        Runner._loadSuites
package:test/src/runner.dart 116:18        Runner.run.<async>

This is an unexpected error. Please file an issue at http://github.com/dart-lang/test
with the stack trace and instructions for reproducing the error.
PS M:\Coding\Applications\convert>
```

I've gotta go out, but I'll try and do some more debugging later.

**Comment by zoechi** [comment]
AFAIK you can't have the Dart code on network drives.

**Comment by DanTup** [comment]
This isn't a network drive; I think it's just a standard partition (I'll
confirm later; on my tablet it's a locally mapped drive, but I'm sure it's
just a plain partition here)

**Comment by DanTup** [comment]
Yup, just a normal drive (see attached). I'll do some more debugging...

**Comment by DanTup** [comment]
It's just a standard drive:

![disks](https://cloud.githubusercontent.com/assets/1078012/17083964/59995b84-51a8-11e6-8044-5f1a81be90b8.png)

**Comment by DanTup** [comment]
My guess is that it's related to something (pub cache?) being on a different drive to my Dart code, but why the error suggests it's trying to move something within _Directory.listSync I do not know!

**Comment by DanTup** [comment]
Ok, this is because pub cache is on a different drive. Therefore this is a dupe of #880. It kinda sucks, but the symlinks stuff kinda sucks anyway. For me it's trivial for me to move my cache so it's not a big deal.

**Comment by zoechi** [comment]
dart-lang/pub#880
