### ISSUE TITLE
slow performance or incorrect time measurement for -p chrome|firefox|ie

### ISSUE THREAD

**Issue by EdSv** [dart-lang/test#450]
I consider test package as runner not only for unit tests but also for performance tests. 
But if in case of  unit tests i didn't have any problem when I started  to use  that package as runner for performance test I faced with problem of incorrect time measurement(deviation in some cases is 1-2 orders of magnitude), which appears if we instead of dartium select chrome (or firefox, ie) in option -p . 
here link to this question on stackoverflow http://stackoverflow.com/questions/38918515/performance-testing-in-dart-using-test-0-12-153-lib  , where I posted code which demonstrate that problem on example sorting of array with comparator. But it looks like such problem will happens not only for that code. 
While if we run that code in chrome as webapp such huge deviation doesn't happen and results is acceptable. But we need correct results from running as test too.

**Comment by nex3** [comment]
The test runner is not intended as a tool for performance tests. It makes several changes to the environment to aid debuggability that may affect the performance of code it runs.

**Comment by EdSv** [comment]
Yes, that package is not specialized for precise benchmarking. But it would be great  to use only one test runner for all tests. 
Also i didn't find yet other runner with option choice of platforms.
Concerning debugging,  in my case i don't use option  --pause-after-load for interactive debugging   or  overhead is caused by stacktrace feature??
In such case maybe would be good and flexible  to provide new option on|off debug mode  in future, just to allow to use test runner as launcher for performance tests ,  without performance overhead related with debugging?
