### ISSUE TITLE
Pub run test performs http-request twice

### ISSUE THREAD

**Issue by YuriKulaghin** [dart-lang/test#451]
See simplest [run_test.zip](https://github.com/dart-lang/test/files/424797/run_test.zip) with cllient and server - client sends http-request to server, server responses with 'Hello, world!'. When test.html is launched directly by Dartium (WebStorm -> Run 'test.html') then server receives one request, as expected. When test is launched by `pub run test -p dartium test\test.html` server recieves two equal requests! Why?! Effect is reproduced on Windows and Linux, with dart-sdk/dartium 1.18.1 and older, with test 0.12.15+3 and 0.12.14+1.

**Comment by zoechi** [comment]
I wouldn't expect other people to download arbitrary zip files and expand them on their local disc ;-)
It would be better to publish the repo case as  GitHub repository where the code can be browsed online.

**Comment by YuriKulaghin** [comment]
Thanks, Gunter, run_test.zip is published as https://github.com/YuriKulaghin/dartlang_test_issue451.

**Comment by zoechi** [comment]
Could this be because of `<script type="application/dart" src="test.dart"></script>` in our `index.html`? Can you please try without?

**Comment by nex3** [comment]
Yeah, it looks to me like @zoechi is right: you're double-including your test script.

**Comment by vpigrad** [comment]
You suggested doing that to us in order to fix --pause-after-load.  That is required for debugging in the browser and to run the test at the command line.  See:

https://github.com/dart-lang/test/issues/409

Again, we need to be able to debug to develop tests and also be able to run them at the command line.  We have thousands of tests.

**Comment by nex3** [comment]
I believe what I said was "be aware that you're using `test` in a non-standard way" and "I can't offer any guarantees that that won't be broken" :wink:. The only supported way of debugging tests is to use `--pause-after-load`.

**Comment by zoechi** [comment]
@vpigrad As a **non-standard** way, you can comment in/out this script tag in order to be able to debug from WebStorm, or what I'm usually doing is, to create a copy of that file (without `_test` in the name) for debugging purposes only containing the dart script tag (and not the x-dart-test tag).

**Comment by YuriKulaghin** [comment]
Thanks for all, it's true - second script including in the body of html-file (for debug with browser) gives double script running under `pub run test`.
