### ISSUE TITLE
Please bump and publish a version compatible with the latest analyzer (0.28.*).

### ISSUE THREAD

**Issue by pq** [dart-lang/test#452]
This is a pressing issue for Flutter since it means we can't update to the latest SDK and get a corresponding version of analyzer (for `flutter analyze`).

**Comment by pq** [comment]
A start here: https://codereview.chromium.org/2255083003/

You'll likely have other bits to add to the `CHANGELOG`.

**Comment by pq** [comment]
cc @nex3

**Comment by pq** [comment]
Gentle ping.  A stable version of `analyzer` has been released so I think the immediate unease has been addressed.  In the meantime we've got another dev release of the SDK that we can't integrate until this gets resolved.  Let me know if there's anything I can do to move it along.

Thanks in advance!

cc @nex3

**Comment by pq** [comment]
Source updated as of 91b3156b19d3778e84571f5256f0f56748395116.

Now we just need to publish.

Thanks!

cc @nex3 @munificent

**Comment by nex3** [comment]
I'll publish in an hour or so.

**Comment by pq** [comment]
Thanks!

**Comment by nex3** [comment]
0.12.15+4 is published!

**Comment by pq** [comment]
Awesome.  Thank you!
