### ISSUE TITLE
Support a content shell executable named "Content Shell" on Mac OS

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#455]
Our official content shell downloads for Mac OS include an executable named `Content Shell` rather than `content_shell`. Homebrew, on the other hand, uses `content_shell`. We should support both names on Mac OS, and document that `Content Shell` is a valid name in the README.

**Comment by nex3** [comment]
cc @scheglov

**Comment by natebosch** [comment]
Dart no long ships content shell so I don't think there is anything to do here.
