### ISSUE TITLE
Option to chunk up compiled tests into the shame shard

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#456]
Often dart2js compilation is the slowest aspect of running a test.

Duplicate compilation of the same test suite across different shards causes duplicate work that is often not made up by added parallelism.

It'd be nice to have a flag to group/chunk compiled shards to minimize this duplication.

**Comment by nex3** [comment]
I'm not entirely sure what you're concretely suggesting, but the point of sharding is that the individual shards can be run in isolation. Somehow grouping them or communicating information (including compiled JS) between them would break that isolation.

**Comment by kevmoo** [comment]
* Imagine I have two suites (a, b) with 4 suites each.
* I run test w/ two shards
* I notice that different tests run on each shard: cool.
* I notice that both shards run tests from suites a & b
  * For vm tests: not a big deal
  * For dart2js tests, it means compiling the same test twice – which slows things down

Request: at least when doing dart2js, have some way to have shard 0 run tests in suite A and shard 1 run tests in suite B to avoid duplicated dart2js.

...or I'm completely missing something.

**Comment by nex3** [comment]
Internally, I believe each test target generally only runs a single suite, so I don't know that this would actually do anything. Also, it's possible for blaze to just compile everything ahead-of-time and provide it to the runner anyway, which should eliminate this entirely.

**Comment by kevmoo** [comment]
CC @grouma as we discuss improving test throughput on Travis
