### ISSUE TITLE
Add a package-level config file

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#46]
As more and more aspects of tests become configurable in various ways, it will become necessary to have project-level configuration files. These might be used for configuration that would otherwise be included declaratively on tests, since if all tests would share the same configuration it would be a drag to mark it over and over again. They might also be used for configuration that would otherwise be passed on the command-line, to make it easy to provide custom defaults on a per-package basis.

Some things the config file should definitely support:

* Default platform(s) to run tests on.
* Default files to consider tests.
* Default test timeout (see #9).
* Default reporter (see #12).
* Configuration for various plugins.

As time goes on, more configuration will likely be added as well.

**Comment by kaendfinger** [comment]
I take it this would be in YAML?

**Comment by nex3** [comment]
Very likely.

**Comment by zoechi** [comment]
It should be possible 
- to specify a specific configuration file using a command line argument.
- configure a logging level (for example to suppress test log output)

**Comment by nex3** [comment]
> to specify a specific configuration file using a command line argument.

Agreed.

> configure a logging level (for example to suppress test log output)

This is a separate feature request; it's out-of-scope for this issue.

**Comment by zoechi** [comment]
Could logging possibility be solved in a custom reporter when they are supported?

**Comment by nex3** [comment]
Most of the output does come from the reporter. The test runner itself prints some errors for things like invalid command-line arguments, but anything that happens within a test is passed to the runner.
