### ISSUE TITLE
Add ability to run dartium in arbitrary profile

### ISSUE THREAD

**Issue by Rodsevich** [dart-lang/test#465]
When running dartium it creates it's own _ad hoc_ profile in the /tmp dir, which takes long enough time to fill before the browser justs opens.
If, I think _everybody_, downloads dartium just to tests theirs own Dart projects, why would those profiles be created instead of a single one that would be used several times?

**Comment by zoechi** [comment]
That would hurt reproducibility. What if your profile has some history data (localstorage or whatever), plugins, ...,  that influence tests, then you might wonder eventually why the test run a while ago but doesn't anymore? Starting with a clean slate avoids that.

**Comment by Rodsevich** [comment]
And what about preloading that custom profile made in /tmp with the minimal profile customized by user:

1. I configure my own desired profile
2. I make a copy of that profile in, i.e. /etc/dartium/dart_tests/default_profile
3. test executes and, in addition to creating the *ad hoc* /tmp profile, it populates it with the contents of the previous point

**Comment by zoechi** [comment]
That definitely makes more sense to me.

**Comment by nex3** [comment]
This is something we could probably support in the config file once we have configurable platforms (#391).

**Comment by patkujawa-wf** [comment]
How about now? :)

**Comment by matanlurey** [comment]
Dartium has been discontinued so I don't think this is planned.
