### ISSUE TITLE
Allow changing the timeout for LoadSuite

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#470]
See https://github.com/dart-lang/test/blob/bf8a455fffdb84097f8ef54c1eef3ce28fc9de78/lib/src/runner/load_suite.dart#L124

We have a few Angular tests that timeout only on Travis (just slower than my dev machine, I guess).

I realized there is no way increase this timeout. We're having to skip tests on Travis because of this.

**Comment by nex3** [comment]
Duplicate of #390.
