### ISSUE TITLE
Provide a programmatic API

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#48]
Currently the only APIs that `unittest` exposes publicly are the frontend APIs used to define tests: `test()`, `group()`, `expect()`, and so on. However, it has a lot of backend code that would be useful for external packages to extend the platform. Plugins are the most obvious example of this, since they need to at least implement some backend classes and likely call out to other APIs, but one could also imagine something like a custom runner that spins up a long-lived server and re-runs tests when their sources change.

**Comment by grouma** [comment]
This is quite generic and is covered by other issues.
