### ISSUE TITLE
"Throws" matcher should handle functions that return futures

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/test#498]
Exception is caught and expected.

```dart
expect(() => throw new StateError('Test'), throwsStateError);
```

Exception is caught and expected

```dart
expect(new Future(() => throw new StateError('Test')), throwsStateError);
```

Exception is not caught, test fails

```dart
expect(() => new Future(() => throw new StateError('Test'))), throwStateError);
```

If a `Function` returns a `Future`, it should be handled like the second case above. Otherwise if a function is capable of throwing a synchronous or asynchronous error, it's not possible to catch both. For example, the following:

```dart
Future<Null> mayFail(String name) {
  if (name == null) {
    throw new ArgumentError.notNull(name);
  }
  return doAsyncTaskThatMayFail();
}
```

**Comment by nex3** [comment]
I believe this was fixed by c81de6b.
