### ISSUE TITLE
Pub get fails on current HEAD version 0.12.17-dev

### ISSUE THREAD

**Issue by whesse** [dart-lang/test#499]
Running pub get on a checkout of this package fails, I think because scheduled_test has the pubspec
test: >0.12.15 <0.12.17

I remember a discussion about how <0.12.17 would not match a version like 0.12.17-dev when there was a  stable version like 0.12.16 available.  Could we add an override for scheduled_test to the pubspec.yaml in this file until there is a compatible version of scheduled_test available on pub?

This failure shows on all of the package bots for this package, like https://build.chromium.org/p/client.dart.packages/builders/packages-linux-test

**Comment by nex3** [comment]
I've released a new `scheduled_test` version, so this should be fixed now.
