### ISSUE TITLE
Support debugging VM tests

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#50]
The test runner should make it very easy to run an interactive debugger for VM tests, whether it be via the command line, observatory, or an IDE. This is blocked on [issue 23320](https://code.google.com/p/dart/issues/detail?id=23320), which will allow the test runner to enable the observatory server at runtime.

**Comment by kevmoo** [comment]
@nex3 FYI: update this issue with description RE observatory

**Comment by kevmoo** [comment]
Also would like/need ability to start an isolate in checked mode - https://code.google.com/p/dart/issues/detail?id=21791

**Comment by johnpryan** [comment]
[sdk issue 23320](https://code.google.com/p/dart/issues/detail?id=23320) is marked as 'not planned'.  Could we get some clarification on what that means exactly?

It's still possible to debug tests by creating an HTML file with `<script>` tags and debug in WebStorm, but that file needs to be maintained, and you cant use the `-n` flag or `solo_` to filter tests.

**Comment by kevmoo** [comment]
See my comments here: https://github.com/dart-lang/pub/issues/1018#issuecomment-157204503

Short version: we'll mark this work

**Comment by alorenzen** [comment]
Any update on this?

**Comment by nex3** [comment]
The blocking issue is still blocking.

**Comment by nex3** [comment]
The [`Service`](https://api.dartlang.org/dev/1.21.0-dev.6.0/dart-developer/Service-class.html) class should enable this, so I'm going to unmark this as blocked.

**Comment by nex3** [comment]
This is currently blocked on dart-lang/sdk#31308.
