### ISSUE TITLE
DDC or any compiled test (dart2js) should emit source-mapped errors

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/test#502]
_Please close this issue if the feature already exists and I am just missing how to do it_

I'd like to see the following behavior when a test fails and the source language is not Dart:

1. A source map is loaded, and applied (using `package:source_map_stack_trace`?)
2. The emitted error by the test runner/test is the source-mapped stack trace back to Dart

Example use, if we want to make this experimental:

```bash
$ pub run test -p chrome --experimental-use-source-maps
```

Internal issue `33069916`, which is assigned to @jacob314 

/cc @dgrove

**Comment by nex3** [comment]
We support this for compilation we manage, but we don't currently support it for `--precompiled` mode which is used for DDC internally (and hopefully also dart2js at some point). We can probably handle it fairly easily by checking to see if an appropriate source map file exists in the precompiled directory.

**Comment by matanlurey** [comment]
Ping - just because this is making rolling out DDC much more difficult right now :-/

**Comment by nex3** [comment]
I believe @jacobr is actively working on this.

**Comment by nex3** [comment]
Fixed by a873b14df1f425eca644a89487b0dc348fe3ba5b.
