### ISSUE TITLE
Testing against https-Rest-Server - strange behavior (needs localhost instead of IP)

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/test#505]
My https-Server (Jetty 9.3) runs on 192.168.0.42 (local Test-Machine) inside of a docker container . The https-Server returns a cert for 192.168.0.42. 192.168.0.42 is one (the first) of two network cards in this machine. The https-Server is https only, no http. 

https://192.168.0.42:8080/<path> in the browser works as expected, https://localhost:8080/<path> returns the expected "NET::ERR_CERT_COMMON_NAME_INVALIDE" (This is not a secure connection...) error message

Now the weird thing - My integration-tests need localhost instead of 192.168.0.42.
E.g. https://localhost:8080/api/v1/account/names - works and returns a list of names
https://192.168.0.42:8080/api/v1/account/names - hangs and returns after ~30secs with a timeout

Very strange...

**Comment by MikeMitterer** [comment]
I forgot to mention - All my Dart-Applications work as expected if I use 192.168.0.42 for my REST-Requests (They fail with localhost which is right)

**Comment by nex3** [comment]
What does this have to do with the `test` package?

**Comment by MikeMitterer** [comment]
I don't know where this bug comes from! The test package? Content-Shell - who is responsible for this??? It only happens if I test against content-shell with the test package - so I thought it must have something todo with this package.

**Comment by nex3** [comment]
Can you come up with a minimal reproduction?
