### ISSUE TITLE
Add a flag to print the slowest test cases

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#508]
Users who are working on speeding up their test runs would find it useful to see which test cases are the slowest. We should add a flag (maybe `--print-slowest`) that causes `test` to print the test cases that are running for the longest amount of time. I'm imagining `--print-slowest=N`, where `N` is the number of test cases to print, as well as maybe `--print-slowest=all` to print all test cases.

**Comment by grouma** [comment]
This isn't planned.
