### ISSUE TITLE
Broken link to Dart docs (404)

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/test#516]
https://www.dartdocs.org/documentation/test/0.12.18/

which is linked from its pub page (https://pub.dartlang.org/packages/test)

gives a 404 error.

Same for the link to the sources (https://www.crossdart.info/p/test/0.12.18/)

**Comment by matanlurey** [comment]
Looks like it "caught up" FWIW.

**Comment by matanlurey** [comment]
Rather dartdoc did, crossdart is still behind/404ing

**Comment by nex3** [comment]
This issue was moved to astashov/dartdocs.org#38
