### ISSUE TITLE
Package test has dartanalyzer errors after last commit

### ISSUE THREAD

**Issue by whesse** [dart-lang/test#519]
Pull request https://github.com/dart-lang/test/pull/514 introduces analyzer errors to the test package, and these also show up in any package that imports test.

The lines like
typedef _Func3(A a, B b, C c);
fail in the analyzer because classes A B and C are not defined.  Should these be generic type parameters for this typedef?

**Comment by whesse** [comment]
It also looks like there may be a problem in package collection, where it needs more than 6 arguments:
Invalid argument(s): The wrapped function has more than 6 required arguments
  package:test                                                                               expectAsync
  out/ReleaseIA32/package_copy/collection/build/test/typed_wrapper/iterable_test.dart 75:28  main.<fn>.<fn>

**Comment by nex3** [comment]
Fixed by 56475dc28e6d9b1c7e7d24f4d7ef8f666e66489b.
