### ISSUE TITLE
Command to initialize a test file

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/test#52]
Note: This could be an IDE feature, but this package will have more knowledge about how to do it, and this way it would be automatically kept up to date.

In package `foo`, I could run:

`pub run test:init src/bar`

and it would check if `lib/src/bar.dart` exists.  If not, it will create it, something like:

```dart
library foo.src.bar;

// TODO: Library auto-generated by `pub run test:init`.
```

and would then create a test file for it at `test/src/bar_test.dart`:

```dart
library foo.test.src.bar;

import 'package:foo/src/bar.dart';
import 'package:test/test.dart';

main() {
  group('<group>', () {
    test('<test>', () {
      fail('Auto generated by `pub run test:init`.');
    }
  }
}
```

**Comment by zoechi** [comment]
Would be even more helpful for browser tests.

**Comment by nex3** [comment]
I'd rather this go in a package for creating files based on templates.
