### ISSUE TITLE
Allow tests to nicely format stack traces

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#527]
Test currently supports various nice stack-trace related features, such as Dart-ifying JS traces and folding out frames from certain packages (which will be configurable eventually, see #416). It also allows the user to selectively enable and disable these. We should expose all this to tests, so they can generate stack traces nicely and according to the user's configuration.

One major obstacle to this currently is that the `source_map_stack_trace` package, which we use to Dart-ify JS frames, relies on `package_resolver` which imports `dart:io` and thus isn't usable on the browser. We could work around this by having the stack resolution function do a round-trip with the server, which would force it to be asynchronous, or by compiling tests with a flag to allow `dart:io` imports, which may hide useful errors.

**Comment by natebosch** [comment]
https://pub.dev/documentation/test_api/latest/hooks/TestHandle/formatStackTrace.html
