### ISSUE TITLE
Please add travis support

### ISSUE THREAD

**Issue by eseidel** [dart-lang/test#537]
It's extremely easy. :)

All you do is add a `.travis.yml` with:
```
language: dart
dart:
 - dev
```
That's it!  (it will run `pub run test` by default).  More instructions here:
https://docs.travis-ci.com/user/languages/dart

And then some member of dart-lang turns on travis at:
https://travis-ci.org

And likely add the little banner to your README.md.  It will help catch things like:
https://github.com/dart-lang/test/issues/536

**Comment by kevmoo** [comment]
@eseidel Natalie is working on rewriting the Travis Dart support as we speak 😄

**Comment by eseidel** [comment]
I mean to this repository. :)  So that we know when it's busted vs. not.

**Comment by kevmoo** [comment]
> I mean to this repository. :) So that we know when it's busted vs. not.

Oh, I know. Although the issue you brought up would fail travis – until scheduled test is fixed.

I think Natalie is cranking to remove the scheduled_test dependency so this is no longer an issue...i think

**Comment by eseidel** [comment]
I'll just post a PR from @eseidelGoogle tomorrow.  This will take literally 5 minutes with dart-lang privs. :D

**Comment by kevmoo** [comment]
Well, not that easy. `pkg/test` tests run chrome, safari, etc. Need to hack through the defaults and create test configurations, etc. Shouldn't be hard, but not trivial.

@nex3 should comment

**Comment by eseidel** [comment]
Ah, true.  I live in blissful vm-only ignorance.

**Comment by kevmoo** [comment]
> Ah, true. I live in blissful vm-only ignorance.

The web is *great*. Let me know if you want a quick intro. 😜

**Comment by nex3** [comment]
The existing Travis support for Dart is shaky and ill-maintained, particularly when it comes to `test` package support. One of my goals for this quarter is to spruce it up, but until then I'm not interested in working around the flaws in the existing support.

**Comment by daniel-v** [comment]
Can we get an update on this, @nex3?

**Comment by nex3** [comment]
I believe @kevmoo has now enabled Travis.

**Comment by kevmoo** [comment]
Yup, @daniel-v see https://docs.travis-ci.com/user/languages/dart

**Comment by daniel-v** [comment]
Thanks!
