### ISSUE TITLE
Several test failures on mac

### ISSUE THREAD

**Issue by eseidel** [dart-lang/test#538]
I have f7ef5ed1c8122552fe7e2d1a7ab13f5eaac68f93.  I'm attempting to `pub run test` to sanity check my setup before I attempt any changes to package:test, but I'm getting lots of errors.

Dart VM version: 1.22.0-dev.10.5 (Mon Feb  6 16:19:34 2017) on "macos_x64"

Example:
```
00:50 +259 ~1 -5: test/runner/browser/chrome_test.dart: can run failing tests                      
  ScheduleError:
  | 'package:scheduled_test/scheduled_stream.dart': malformed type: line 121 pos 25: type 'StreamMatcher' is not loaded
  |     streamMatcher = new StreamMatcher.wrap(streamMatcher);
  |                         ^
  
  Stack chain:
  | dart:core                                            _TypeError._throwNew
  | package:scheduled_test/scheduled_stream.dart 121:25  ScheduledStream.expect
  | test/runner/browser/chrome_test.dart 85:17           main.<fn>
  | package:scheduled_test/scheduled_test.dart 69:27     test.<fn>.<fn>
  | package:scheduled_test/src/schedule.dart 83:16       Schedule.run.<fn>.<fn>
  | dart:async                                           runZoned
  | package:scheduled_test/src/schedule.dart 81:14       Schedule.run.<fn>
  | package:test/src/backend/invoker.dart 204:17         Invoker.waitForOutstandingCallbacks.<fn>.<fn>.<async>
  
  Error detected when waiting for out-of-band callbacks in queue "tasks".
  
```

This may just be a dupe of https://github.com/dart-lang/test/issues/535 for example (maybe linux is required to run the tests?).

Thanks!

**Comment by nex3** [comment]
This is actually a bug in `scheduled_test`. I added a `StreamMatcher` class in `test` which shadows `scheduled_test`'s class of the same name, and I forgot to hide the former in `scheduled_test`'s export.

**Comment by nex3** [comment]
This issue was moved to dart-lang/scheduled_test#30
