### ISSUE TITLE
isNot(throws) broken in 0.12.18

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/test#539]
The following test used to pass, but fails after upgrading from 0.12.17 to 0.12.18.
```dart
import 'package:test/test.dart';

main() {
  test('isNot(throws)', () {
    expect(() {}, isNot(throws));
  });
}
```
```
$ pub run test test/test_test.dart
00:00 +0 -1: isNot(throws)
  Expected: not throws
    Actual: <Closure: () => dynamic>

  package:test             expect
  test/test_test.dart 5:5  main.<fn>

00:00 +0 -1: Some tests failed.
```

I know that `returnsNormally` should be used instead, but `isNot(throws)` should still work.

**Comment by matanlurey** [comment]
I'm seeing this also.

**Comment by kevmoo** [comment]
Have you tried `returnsNormally`?

**Comment by matanlurey** [comment]
Did not know that existed... It's pretty hard to navigate the matchers 😞 

In either case, I think this was accidentally a breaking change.

**Comment by greglittlefield-wf** [comment]
Yes, `returnsNormally` still works as expected, and I've switched all of my usages of `isNot(throws)` over to use that. Sorry I didn't mention that in the original description.

**Comment by kevmoo** [comment]
Thoughts, @nex3 ?
