### ISSUE TITLE
Request: More on package:test on the www-dartlang site

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/test#540]
I think we've gotten past the point where just having a README and Dartdocs is enough to use this library, the matchers, the binary/running, the configuration, and everything else that comes with this. Is this something that can happen?

/cc @kevmoo

**Comment by nex3** [comment]
Shouldn't this be filed against [site-www](https://github.com/dart-lang/site-www)?

**Comment by daniel-v** [comment]
I don't know where this issue should be, but I definitely give it as many thumb ups as Github will allow me.

**Comment by matanlurey** [comment]
@nex3:

> Shouldn't this be filed against [site-www](https://github.com/dart-lang/site-www)?

Maybe? Though maybe we just want to have a sub-site for this package? I'll let @kevmoo and @kwalrath advise here - but I'd really like to see _something_, even if it's just a stub for future work - i.e. ultimate a best practices testing guide, etc.

**Comment by kwalrath** [comment]
This sounds like https://github.com/dart-lang/site-www/issues/91 (which is a really old bug, sadly). Agreed that we need this. I'm thinking we can add a stub soon, and start real work in Q2.

**Comment by nex3** [comment]
Closing here since this is covered by dart-lang/site-www#91.
