### ISSUE TITLE
skip on group should override skip on test

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/test#545]
My test:

```dart
import 'package:test/test.dart';

main() {
  group('skipped group', () {
    test('failing test', () {
      fail('I am a failure');
    }, skip: false);
  }, skip: true);
}
```

Actual output:
```shell
C:\src\bla> C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe -c .\test\skipped_test.dart
00:00 +0: skipped group failing test
00:00 +0 -1: skipped group failing test
  I am a failure
  package:test                fail
  test\skipped_test.dart 6:4  main.<fn>.<fn>

00:00 +0 -1: Some tests failed.
```

I expected the failing test to be skipped because the `skip: true` on the group should override the `skip: false` on the test.

This behavior changed somewhere between version `0.12.15+9` and `0.12.18+2`. Version `0.12.15+9` shows the expected behavior.

**Comment by nex3** [comment]
This is the intended behavior. For any kind of configuration in `test`, the narrowest scope always has the highest precedence—this allows you to declare defaults and then override them for specific cases.

**Comment by goderbauer** [comment]
Why does the behaviour change when I move the skip to the highest (file-level) scope?

```dart
@Skip("Don't run these tests")

import 'package:test/test.dart';

main() {
  group('some group', () {
    test('failing test', () {
      fail("I am a failure");
    }, skip: false);
  });
}
```

With what you said before, I would have now expected the `failing test` to actually run because in the narrowest scope it says `skip: false`. However, that's not what happens:

```shell
C:\src\bla> C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat run test
00:00 +0: test\skipped_test.dart: (suite)
  Skip: Don't run these tests
00:00 +0 ~1: All tests skipped.
```

**Comment by nex3** [comment]
Top-level annotations work a little differently because loading suites is expensive (especially when they need to be compiled) and we use top-level `@Skip` and `@TestOn` annotations to decide whether to load them at all. I'm not a big fan of the inconsistency, but I think this is more often the behavior users expect.
