### ISSUE TITLE
A version of expect() that doesn't do anything asynchronous

### ISSUE THREAD

**Issue by Hixie** [dart-lang/test#552]
In Flutter's test harness, you can't use Futures, because we run the tests in a Zone where we carefully step the system through frames and microtasks in a very tightly controlled fashion. Code that just calls "await" will just hang. Code that attempts to use Futures, like any call to `test.expect()` that passes in a Future, will hang or not complete, or complete at unexpected times later while the microtask queue is being flushed as part of pumping another frame.

It would be very helpful if there was a version of `expect` we could use that did not support anything asynchronous (e.g. threw if the value was a Future, or something).

I have no opinion on the name. We're already wrapping `expect` anyway (we add extra tests with each expect call).

**Comment by nex3** [comment]
I don't think this is something broadly-applicable enough to build into the `test` package itself, but if you have a wrapper anyway you could add an assertion that the first argument isn't a future. That's not bulletproof—user-defined matchers could always do weird Future-y stuff—but then again, a built-in expect variant wouldn't be future-proof either.
