### ISSUE TITLE
Add an option to print a failure summary after tests run

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#554]
At the moment, there is no clean way to copy-paste failures after a run.

Even printing "FAILURE" on the line when a new failure is found would be useful – then one could search/grep

**Comment by nex3** [comment]
I'm not sure what output you're envisioning exactly. Today, if you're using the default compact reporter, the only output after the test finishes running is the names of failing tests and the errors they failed with. What more information do you need?

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/test/issues/555

That dump, without stack traces. Make it scannable so one can figure out if the failures are clustered in a few suites, etc.

**Comment by nex3** [comment]
Adding additional configuration to the CLI has a fairly high complexity cost—do you think this is useful enough across a broad set of circumstances to incur that cost? In most cases stack traces aren't going to be as gargantuan as they are for `test`, and even there I'm glad to have information available about *what* errors you were seeing even if that information is verbose.

**Comment by kevmoo** [comment]
Yes. At the moment it's a burden to scan the test output. I want an easy way to read all of the failure lines.

Right now I scan up looking for the first `-1` to find the first failure, etc.

I'd take an easily grep'd/searched string for each failure line

**Comment by nex3** [comment]
What if we added `[F]` at the end of a failure line?

**Comment by kevmoo** [comment]
That'd be HUGE! I can grep from there 😄 

Or [E], etc
