### ISSUE TITLE
There seems to be no way to disable a test in 0.12.0-xxx

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#56]
skip_test isn't available anymore. Is there a replacement?
I tried to use an invalid `testOn` argument but this didn't do the trick either.

**Comment by nex3** [comment]
#14 covers adding a new means to skip tests.

As a workaround for now, you can either continue to use `unittest`, which has the deprecated compatibility functions. Alternately, you could use `testOn: "!dart-vm && !js"`.

**Comment by zoechi** [comment]
Nice workaround.
