### ISSUE TITLE
pub run test -p chrome headless?

### ISSUE THREAD

**Issue by CRTX** [dart-lang/test#563]
I'm running `pub run test -p chrome` in a `docker` container.

Is there a way to use `dart_test.yaml` to pass the `--headless` parameter to chrome?

I can't seem to find any documentation on it.

Launching `$ chrome` alone shows:

```
[3904:3920:0308/120151.485964:ERROR:bus.cc(427)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[3904:3904:0308/120151.551795:ERROR:desktop_window_tree_host_x11.cc(1127)] Not implemented reached in virtual void views::DesktopWindowTreeHostX11::InitModalType(ui::ModalType)

(chrome:3904): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
/usr/bin/dbus-launch terminated abnormally without any error message
[4118:4118:0308/120151.629507:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process. 
[3904:3932:0308/120151.630898:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.
```

I'm not sure if this is due to chrome needing that flag or something else.

**Comment by daniel-v** [comment]
In general, you won't be able to run chrome in a headless way. For that, there is the `content_shell`. You can download it from here: http://gsdview.appspot.com/dart-archive/channels/stable/release/latest/dartium/

Also, make sure you are aware of `xvfb-run` command. I do this to run tests is `chrome` on Linux:

`xvfb-run -a pub run test -p chrome`

**Comment by CRTX** [comment]
So `-p chrome` isn't meant for Continuous Integration testing?

**Comment by daniel-v** [comment]
`-p chrome` only means that the test runner should run tests in chrome. It can be made to work in CI as well with xvfb.

It is not dart specific by the way. It's the same with all test runners. If you want to run tests in a non-headless browser, you need some kind of GUI or framebuffer. That's what xvfb was made for.

**Comment by CRTX** [comment]
I forgot to mention I have `xvfb` running in the background already. `-p content-shell` and `p dartium` works and the test passes.

However, with `-p chrome` it fails. Here's the error straight when I run the command:

```
00:30 +0 -1: compiling test/example_test.dart [E]                                                  
  Failed to load "test/example_test.dart": Timed out waiting for Chrome to connect.
  dart:async                                            _SyncCompleter.complete
  package:http_multi_server/http_multi_server.dart 140  HttpMultiServer._loopback.<async>
  
00:30 +0 -1: Some tests failed. 
```

**Comment by nex3** [comment]
Testing locally, I can't get the `--headless` flag to work at all. Chrome just crashes immediately. However, `-p chrome` has always worked for me in Travis CI, which I know uses Docker.

Regardless, you'll be able to configure the flags passed to various browsers with #391, so I'm closing this as a duplicate.
