### ISSUE TITLE
Missing dependency on package:js

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#567]
It is referenced under lib here https://github.com/dart-lang/test/blob/1325b694f42412be2a597bbb8d94995a7e763e3b/lib/src/runner/browser/static/host.dart#L11 but not listed in the pubspec.yaml.

**Comment by kevmoo** [comment]
This may be a special case.

It's compiled and checked-in at https://github.com/dart-lang/test/blob/1325b694f42412be2a597bbb8d94995a7e763e3b/lib/src/runner/browser/static/host.dart.js

Perhaps it shouldn't be in the lib directory, then.

**Comment by jakemac53** [comment]
Hmmm ya, I noticed this because dartdevc chokes on it if you try to compile this package naively (all srcs under lib). It does seem like this shouldn't be under lib though if its compiled/deployed separately and no user should be able to reach the code.
