### ISSUE TITLE
Un-deprecate Throws class

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#574]
I think we want to deprecate the optional-ness of the ctor.

I'm imagining there will be more than a few folks using the `const`-ness of this class.

We can't even migrate our own `throwsXException` methods to `throwsA` because they would cease to be `const`.

**Comment by nex3** [comment]
I don't really care about matchers being const—it's not feasible to use matchers in a const context anyway since the vast majority of them aren't possible to const-ify, so I don't think there's any benefit relative to just making them final.
