### ISSUE TITLE
Exception handling in expect(...) is inconsistent/difficult

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/test#579]
**NOTE**: This is primarily a product excellence issue, and I could see it short-term to be a documentation issue, but it would be nice to keep this in mind as the package evolves.

I originally filed a background issue here: https://github.com/dart-lang/test/issues/498

1. Catching synchronous errors require a closure:

Here is how I can catch a synchronous error (for an example):

```dart
expect(() => doThrow(), throwsA(anything));
```
2. Catching asynchronous error requires _not_ using a closure:

```dart
expect(doThrowAsync(), throwsA(anything));
```

---

My suggestion here is for sync, require a closure, and for async, require `expectLater` so we can have a consistent API, i.e.:

```dart
expectLater(() => doThrowAsync(), throwsA(anything));
```

Right now this doesn't work though:

```
Expected: throws an instance of AssetNotFoundException
  Actual: <Closure: () => dynamic>
   Which: returned <Instance of '_Future'>
```

This does:

```dart
await expectLater(assetReader.readAsString(idC), throwsAssetNotFound);
```

**Comment by nex3** [comment]
I like making `throwsA()` work for asynchronous closures like it does for synchronous ones. I don't think I understand the value in *requiring* `expectLater()`, though—that would be a major breaking change and I'm not sure what benefit it would provide.

**Comment by matanlurey** [comment]
Thanks!
