### ISSUE TITLE
Is there some way in 0.12.0 to configure tests when not executed using the test runner 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#59]
for example when I run `dart test/my_test.dart` from command line or from an IDE?

Current problem:
The debugger console in WebStorm doesn't display color codes. 
Is there a way to disable them when tests are run this way? 
Might be just a bug in terminal recognition though.

**Comment by Fox32** [comment]
The same for the Dart Editor (I tried to report it here #19). How about disabling the color by default?

**Comment by zoechi** [comment]
I thought this might be a different issue because it is not run by `pub` but you are right this seems to be the same as your issue with DartEditor.
