### ISSUE TITLE
Groups with spaces in their name always pass their tests

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/test#61]
OK, a few caveats - in the Dart repo, using test.py, and with useHtmlIndividualConfiguration. I suspect the fault is at least partially in test.py, but it might be easier to deal with in the test package. For an example, in a Dart repo checkout, add a file foo_test.dart, like

      import 'dart:html';
      import 'package:unittest/unittest.dart';
      import 'package:unittest/html_individual_config.dart';

      main() {
        useHtmlIndividualConfiguration();

        group('You have got to be kidding me', () {

          test("failure", () {
            expect(false, isTrue);
          });
        });

        group('it_works_if_you_have_no_spaces_in_the_group_name', () {

          test("also_failure", () {
            expect(false, isTrue);
           });
        });
      }

Run this from the top-level directory with a command-line like 

      tools/test.py -m release -c dart2js -r chrome -j 1 html/foo_test

I get one pass and one failure.

**Comment by alan-knight** [comment]
The file goes in dart/tests/html/foo_test.dart

**Comment by alan-knight** [comment]
Repo bug is at https://code.google.com/p/dart/issues/detail?id=23156

There's something more to it, because there are other files that have these characteristics that don't suffer from this problem, but I don't at this point know what the difference is.

**Comment by nex3** [comment]
What output are you seeing? Where does it say it passes, in the `unittest` output or the test runner output? If you can't tell, just paste it here and I'll take a look.

**Comment by alan-knight** [comment]
https://gist.github.com/alan-knight/31a2e15c086cef0bb271

**Comment by zoechi** [comment]
Isn't this mentioned somewhere that spaces in test/group name isn't supported for html tests. I stumbled upon this when I worked on a testrunner last year but don't remember where.

**Comment by whesse** [comment]
The unittest framework is not supporting spaces in the group name that is passed in in the url.  Both the urls
http://127.0.0.1:36966/root_build/generated_tests/dart2js-chrome/tests_html_foo_test/test.html?crossOriginPort=58705&group=You%20have%20got%20to%20be%20kidding%20me
and
http://127.0.0.1:36966/root_build/generated_tests/dart2js-chrome/tests_html_foo_test/test.html?crossOriginPort=58705&group=You+have+got+to+be+kidding+me

report "Pass" in the browser, in the actual web page displayed.  The latter, with + signs, is what test.py is using to run the test.

**Comment by whesse** [comment]
The problem seems to be in line 37 of https://github.com/dart-lang/test/blob/stable/lib/html_individual_config.dart.  The group name is taken from the URL, and compared with the group name in the test case description.  If spaces are not escaped in the test case description, then they need to be un-escaped in the name from the URL, before the comparison.  I guess a simple hack that replaces "+" and "%20" with " " would do it.

Verified - Adding the line
        testGroupName =
            testGroupName.replaceAll('+', ' ').replaceAll('%20', ' ');
fixes the bug, and makes test.py report both groups as failing.

**Comment by alan-knight** [comment]
It's not obvious to me that the query parameter is getting decoded at all there. According to http://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20 the "+" should be decoded as space in a query parameter. Where are we even decoding the "%20"?

**Comment by nex3** [comment]
No, it looks like the code parsing the URL is very outdated (not too surprising, since this is the oldest Dart package). It doesn't do any escaping at all, nor does it use the core-library URL-parsing functionality; it just uses some custom string munging.

**Comment by kevmoo** [comment]
https://codereview.chromium.org/1128383002/

**Comment by kevmoo** [comment]
dart-lang/test@e11f429
