### ISSUE TITLE
Analyzer errors with new Dart SDK (Dart VM version: 1.24.0-dev.4.0)

### ISSUE THREAD

**Issue by grouma** [dart-lang/test#611]
error • Element 'StreamGroup' from SDK library 'async.dart' is implicitly hidden by 'stream_group.dart' at lib/src/runner.dart:215:12 • conflicting_dart_import
  error • Element 'StreamGroup' from SDK library 'async.dart' is implicitly hidden by 'stream_group.dart' at lib/src/runner/engine.dart:169:35 • conflicting_dart_import
  error • Element 'StreamGroup' from SDK library 'async.dart' is implicitly hidden by 'stream_group.dart' at lib/src/runner/loader.dart:93:12 • conflicting_dart_import

**Comment by keertip** [comment]
@grouma , this was fixed with Lasse's cl  https://codereview.chromium.org/2872263003/

**Comment by grouma** [comment]
This should now be resolved.
