### ISSUE TITLE
Accept a flag that force runs all skipped tests

### ISSUE THREAD

**Issue by srawlins** [dart-lang/test#617]
I'd love a flag (`--run-skipped`?) that ignores all `skip: true` and `@Skip` markers, and just runs all the tests, to find test cases that I _thought_ were failing, but are no longer failing.

**Comment by nex3** [comment]
[You're in luck.](https://github.com/dart-lang/test/blob/master/lib/src/runner/configuration/args.dart#L59-L60)

**Comment by srawlins** [comment]
*facepalm* sorry. I didn't see anything in the README, and I thought I skimmed `pub run test --help` as well, but I missed this ☹️
