### ISSUE TITLE
Validate browsers are installed [on travis, etc]

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/test#621]
As mentioned on https://github.com/dart-lang/test/issues/619, we don't always have guarantees that all browsers being run by `pub run test` always are installed on the current machine. For example, on a non-OSX machine there will never be `safari`, and by default some browsers are not installed on environments like travis.

Suggestions:

- [ ] Collect a list of all browsers being executed in a given session

(i.e. from `dart_test.yaml` or `pub run test -p ...`)

- [ ] Validate all browsers are installed, failing early if one or more are missing and/or
- [ ] Skip all browsers that are not installed

**Comment by nex3** [comment]
We can definitely improve the error message when a browser isn't found, but I'm not sure how much benefit failing early has versus failing the suites that are set to run with that browser. I think we still want to run all the test suites that we can, so the best we can do is print an error message and somehow tie that into the executable's exit code, and at that point we might as well just print the error in the suite itself.

Also, I really don't want `test` to be in the position of duplicating the operating system's path-resolution logic. That seems like it would bring up a bunch of edge cases—I don't want us to accidentally declare "this browser isn't installed" when in fact it is.

**Comment by matanlurey** [comment]
Maybe it's possible, given something, to at least run a `-v` to verify?

**Comment by nex3** [comment]
But what benefit does that provide over trying to load the test files?

**Comment by matanlurey** [comment]
For the end user? In my case, 30 less errors that `chrome` couldn't be run, with a simple "could not run chrome".

**Comment by nex3** [comment]
What if only the first Chrome load failure printed a message, and the rest just printed status lines?

**Comment by matanlurey** [comment]
Obviously an improvement, but my dream scenario is the following:

```bash
$ pub run test -p firefox,ie,safari,chrome,dartium

> WARNING: There is no platform "firefox" installed on the host system, tests will be skipped.

Running platform "chrome" (Version 59):
...

Running platform "firefox" (Version ..):
...
```

**Comment by nex3** [comment]
So you want it to run tests on Firefox after it determines that Firefox isn't installed?

**Comment by natebosch** [comment]
I think that was a typo...

```
$ pub run test -p firefox,ie,safari,chrome,dartium

> WARNING: There is no platform "firefox" installed on the host system, tests will be skipped.

Running platform "chrome" (Version 59):
...

Running platform "safari" (Version ..):
...
```

**Comment by matanlurey** [comment]
^ What he said

**Comment by nex3** [comment]
I found a way to only print browser load errors once per browser, which should handle this gracefully without needing any additional processes to be run. See #627.
