### ISSUE TITLE
Consider using pub serve for all JS compilation

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#624]
Today if you run in a normal browser you either need to pass `--pub-serve` and point it at an already running pub serve instance, or it will do some magic under the covers and run dart2js.

I propose that instead of however dart2js is currently ran, we would automatically run `pub serve` and then use that. This would have several benefits:

- Supports running tests that require transformers in travis
- Removes confusion around the different ways of running tests
- Get dartdevc compiler support for almost free (just need to pass the arg through to pub serve) 
- Delete all custom dart2js related code in package:test

You could still support pointing at an existing pub serve instance as well with the flag, but it wouldn't be required.

What are the downsides of this approach? Is is significantly slower to run dart2js via pub serve?

**Comment by jakemac53** [comment]
cc @kevmoo

**Comment by nex3** [comment]
The support for `--pub-serve` is inherently shaky (see #587 for details), so I'm not excited about the possibility of doubling down on it. I think it's almost certain that it would impose a substantial speed penalty as well, especially for DDC where we can take advantage of modularity in test-specific ways.

**Comment by jakemac53** [comment]
Fwiw, the upcoming support for ddc in pub serve works great for testing out of the box (other than the fact that you have to use pub serve and the --pub-serve arg to pub run test).

It puts all shared code (in other packages or relative imports) inside shared modules so they are only compiled once. The only thing it doesn't really do is cache modules between pub serve runs, but there is a path to making that happen as well if we think it is necessary.

What kinds of test specific things were you thinking of doing with ddc?

**Comment by nex3** [comment]
We discussed this offline and decided not to go in this direction.
