### ISSUE TITLE
Use @Required for optional arguments in metadata

### ISSUE THREAD

**Issue by grouma** [dart-lang/test#626]
@Required from package:meta will significantly help with adding new configuration options. It was hard tracking down all the locations that needed to be updated.

**Comment by nex3** [comment]
What specific arguments do you think should be annotated?

**Comment by grouma** [comment]
Adding a new metadata field is prone to errors due to all the locations that need to be updated in backend/metadata.dart. Whenever we call the various factory methods we always pass all the optional arguments. Marking all optional arguments as required will prevent the mistake of not assigning the value, something that happened to me in the recent past.

**Comment by nex3** [comment]
Factory constructors like `new Metadata()`? At some point we'll expose those outside the package, and I don't want to force users to construct them with all their parameters.

**Comment by grouma** [comment]
Yeah I was referring to new Metadata and the various locations it gets called, e.g. parse, deserialize etc. This doesn't make sense if we want to expose this outside the package though. I guess I'll just have to be more careful in the future.
