### ISSUE TITLE
Add a global config file

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#63]
There should be a way to globally configure the test runner. There may be system-specific configuration that shouldn't be checked in to a given package. For example, a user may have unusual browser executable locations or might have a slow computer and want to increase their baseline timeout.

See also #46.

**Comment by jirkadanek** [comment]
What about renaming the Dartium executable in dartium-linux-x64-release.zip to `dartium`? That is why I originally opened the issue at https://github.com/dart-lang/sdk/issues/24616 --- I think the SDK should be changed, not the `test` package.
