### ISSUE TITLE
`pub run test` crash

### ISSUE THREAD

**Issue by filiph** [dart-lang/test#630]
I started upgrading https://life-time-value.appspot.com/ to modern Dart. First step: go from unittest to test. When I was done and ran `pub run test` (via IntelliJ or otherwise) I got this:

```
'package:glob/glob.dart': error: line 95: illegal implicit access to receiver 'this'
      context == null ? p.context : context,
                        ^

package:test/src/runner/configuration/values.dart 19  defaultFilename
package:test/src/runner/configuration/values.dart 19  defaultFilename
package:test/src/runner/configuration.dart 107        Configuration.filename
package:test/src/runner/loader.dart 97                Loader.loadDir.<fn>
dart:_internal                                        ListIterable.forEach
package:async/src/stream_group.dart 58                StreamGroup.merge
package:test/src/runner/loader.dart 94                Loader.loadDir
package:test/src/runner.dart 217                      Runner._loadSuites.<fn>
dart:_internal                                        ListIterable.forEach
package:async/src/stream_group.dart 58                StreamGroup.merge
package:test/src/runner.dart 215                      Runner._loadSuites
package:test/src/runner.dart 89                       Runner.run.<fn>
dart:async                                            runZoned
package:test/src/runner/configuration.dart 352        Configuration.asCurrent
package:test/src/runner.dart 82                       Runner.run
package:test/src/executable.dart 171                  main

This is an unexpected error. Please file an issue at http://github.com/dart-lang/test
with the stack trace and instructions for reproducing the error.
```

The whole package is dartanalyzer clean. I did not touch the test file except changing the import statement from pkg:unittest to pkg:test.

I expect there's some semantic difference between those packages but it's not showing up as a static error.

Details:

* Dart VM version: 1.23.0 (Fri Apr 21 03:07:31 2017) on "macos_x64"
* pkg test version: 0.12.20+13

I'm attaching the code as a zip file: [Archive.zip](https://github.com/dart-lang/test/files/1048828/Archive.zip). If anything is missing from there, I can give you access to the private repo. (For my own reference, the commit hash is 632b30bea34afd1b52b0fbd6af4c0f7636728511).

**Comment by grouma** [comment]
I was able to reproduce the error. However a simple 'pub upgrade' resolved the issue. Try that and let me know if it also resolves your problem.

**Comment by filiph** [comment]
Ah, that fixed it, thanks!

This looks like an insufficient constraint somewhere. Looks like `string_scanner` was the culprit. Anyway, feel free to close this unless you see an easy way to fix the version constraint.

**Comment by nex3** [comment]
It's more likely that there was a bug that got fixed in a later version—version constraints unfortunately can't predict bugs.
