### ISSUE TITLE
Make the test runner see other functions than main()

### ISSUE THREAD

**Issue by Pacane** [dart-lang/test#64]
I feel like having to put all the tests in a `main()` function for every test file is a bit wrong. What if I want to setup a test hierarchy, or instantiate stuff? I have to do it in the global scope, right?

I think a good way to work around this would be to annotate test classes/methods like JUnit does on Java. That way we could setup a closed scope for the test, providing all the DI setups in a clean way.

Maybe I'm just not used to the current way of writing tests, but it looks messy to me. Is there some resource that documents how to organize test suites in Dart?

**Comment by zoechi** [comment]
The tests don't have to be in main.
The call of `group()` and `test()` registers groups and tests to run. It doesn't matter where `group()` and `test()` are called from.
I'm not exactly sure though what actually causes the framework to start executing tests (how long it waits for tests to be registered).

I'm not against an annotation but I can't see any advantage either.

A weird example ;-)

```dart
import 'package:test/test.dart';
import 'somefile.dart' as some;

main() {
  group('a_group', () { // not necessary
    some.tests();
  }); //                     - " -
}
```
```dart
library some;
import 'package:test/test.dart';

testSomething() {
  expect('x', equals('x'));
}

testSomethingElse() {
  expect('y', equals('y'));
}

tests() {
  group('sub_group', () {
    test('something', testSomething);
    test('something else', testSomethingElse);
  });
}
```

Or is it something else you want to do?

**Comment by kevmoo** [comment]
@Pacane There is a difference between front-end and back-end in the new API>

The front end (functions like `test`, `group`, etc) are just an opinionated API. You could do an API of your choosing on top of `Declarer`.

**Comment by Pacane** [comment]
@zoechi I was mainly talking about the principle of having tests classes. I'm just not used of using top-level functions like this I guess. I was trying to setup some base test class where I could wire-up things with Injector modules from di.dart. I guess I can do all that setup in a separate library with top-level members as well.

**Comment by Pacane** [comment]
@kevmoo Thanks for the tip!
