### ISSUE TITLE
Request: show how to run the tests in the README

### ISSUE THREAD

**Issue by sethladd** [dart-lang/test#65]
thanks!

**Comment by Pacane** [comment]
Is the only way to run the tests with `pub global` ? If so, I can document it :)

**Comment by Pacane** [comment]
@sethladd It's already done in master! https://github.com/dart-lang/test/blob/master/README.md

**Comment by kevmoo** [comment]
Actually, you always run `pub run test:test` in the root of your project.

Pretty easy.

**Comment by Pacane** [comment]
I see that the second gif in the readme is outdated, it uses `unittest` instead of `test`.

**Comment by kevmoo** [comment]
@Pacane Please open a bug for that! CC @nex3
