### ISSUE TITLE
Platform selectors for dart2js/dartdevc

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/test#652]
There is the potential for behavioral differences between dart2js and the dev compiler, and it would be nice to be able to be able to use platform selectors to run tests on one and not the other. (Is this even possible, since running tests in the DDC relies on a separate Pub server that the test package has no knowledge of?)

For instance, there are some known bugs in the dev compiler output that break certain tests, and we'd like to avoid running those tests until the bugs are fixed in the SDK.

For now, we're using tags, but it'd be nice to not have to pass those in when running the tests.

**Comment by grouma** [comment]
One possible solution is to use the 'tag' feature and 'tag' tests accordingly.

**Comment by nex3** [comment]
Currently `test` doesn't have any built-in support for DDC. We can access it through `pub serve`, but in that case we don't know which compiler produced the JS we're receiving, so we can't propagate that information down into the platform selectors.

At some point I want to make it possible to use preset names in platform selectors, which will allow you to pass `-P dartdevc` and use that in platform selectors, but unfortunately that's not currently possible.

I'm marking this as blocked on #414.
