### ISSUE TITLE
Running pub run test leaves terminal in bad state

### ISSUE THREAD

**Issue by cbracken** [dart-lang/test#656]
After invoking `pub run test`, my terminal is almost inevitably left in a bad state, requiring me to invoke `stty sane` to clean things back up. I wonder if `package:test` is failing to issue a reset for the ansi colour escape codes it issues, before exiting?

The most common issues I end up with after running pub run test:
* `ctrl-R` reverse history searches fail to display any text.
* a blank line shows up before the output of any command I issue.

For reference, I use stock zsh on macOS 10.12 (Sierra) with a pretty [minimal config](https://github.com/cbracken/dotfiles/blob/master/.zshrc).

Example:
![screen shot 2017-06-23 at 10 57 41 am](https://user-images.githubusercontent.com/351029/27494457-d4582d62-5802-11e7-9e2d-a3b26dc7c20b.png)

**Comment by cbracken** [comment]
Example of some weirdness -- notice the text of the test is showing in black instead of white.
![screen shot 2017-06-23 at 10 37 59 am](https://user-images.githubusercontent.com/351029/27494300-22a5013a-5802-11e7-8f9e-8f038f7563bf.png)

**Comment by cbracken** [comment]
Note that when I run with `-r expanded` I *do not* see this behaviour.

**Comment by nex3** [comment]
This seems like a `zsh` bug. We're not doing anything fancy: just ANSI color codes and `\r` to start writing from the beginning of the current line. Both of these are very common techniques for command-line programs.

If you can figure out what specific output we're producing that causes this, and if there's a way to work around that that doesn't break the UI for other shells, I'm happy to add a workaround.

**Comment by cbracken** [comment]
I can repro this in two different terminals: iTerm2 and the default macOS Terminal
I can repro this in two different shells: zsh and bash

The issue appears to be that running `pub run test` is changing the tty `echonl` local mode from off to on.

**Comment by nex3** [comment]
@zanderso @lrhn Could you provide some insight into `dart:io`'s behavior here? What could cause it to change this mode in the terminal?

**Comment by cbracken** [comment]
For reference, the only reference to `ECHONL` in the SDK appears to be in `Stdin::SetEchoMode(bool)` in the stdio_X.cc platform implementations. 

Other than where it's bound as `Stdin.echoMode` in `dart:io`, I don't see `Stdin::SetEchoMode` invoked anywhere in the SDK. Nor do I see `Stdin.echoMode` set other than in tests (and `pkg/front_end` which is unrelated). Nor do I see Stdin.echoMode` set in `package:test` or its transitive closure of dependencies.

**Comment by cbracken** [comment]
Closing this, turns out the code under test in both projects I ran into this, invoked a program that set `echoMode`. I've opened dart-lang/sdk#30318.
