### ISSUE TITLE
expectAsync and tearDown

### ISSUE THREAD

**Issue by jeroencranendonk-wf** [dart-lang/test#658]
I'm running into reproducible test failures that appear to be due to tearDown running earlier than expected for tests that use expectAsync. Is it expected that tearDown runs before all expectAsync callbacks complete?

**Comment by nex3** [comment]
`tearDown()` should only be run after all outstanding callbacks are finished (unless an error has occurred). When I run the following sample with test 0.12.23, it behaves as expected:

```dart
import 'dart:async';

import 'package:test/test.dart';

void main() {
  tearDown(() {
    print("running tearDown");
  });

  test('#658 test', () {
    new Future.delayed(new Duration(seconds: 1)).then(expectAsync((_) {
      print("firing callback");
    }));
  });
}
```

If you can find a case where this isn't happening (other than when an error occurs), that's definitely a bug.

**Comment by jeroencranendonk-wf** [comment]
Ah, turns out you are correct: the expectAsync call was being executed more than its expected count, which results in an error that would explain the behavior.
