### ISSUE TITLE
Should two tests with the same name be an error?

### ISSUE THREAD

**Issue by skybrian** [dart-lang/test#661]
In the Dart and (soon) Flutter plugins for IDEA, we use `--name` and `--plain-name` to identify a test to run within a test file. Some folks on the Flutter team are concerned that users might accidentally write two tests with the same name. Could `package:test` check for this?

Followup to discussion in:
https://github.com/flutter/flutter/pull/11020

**Comment by nex3** [comment]
There are a number of issues with this. `--name` works across multiple test suites, and coordinating this restriction across those suites (which may be loaded in parallel, and likely won't all be in memory at the same time) will be difficult. Also, it may be totally reasonable to use the same test name in different contexts—for example, you may well have a test named `"toString()"` in both `widget_test.dart` and `gadget_test.dart`.

Maybe the biggest problem, though, is that this would be a breaking change and we try hard to avoid those in `test`. We could potentially do this when we bump the version to 1.0.0, but it would be an extra compatibility hurdle that would add friction to the upgrade process.

Hopefully when #48 lands it'll be pretty easy to add some sort of linter for this for users who want this restriction.

**Comment by skybrian** [comment]
Okay, thanks!

Just to clarify, I think the Flutter team would only be concerned about uniqueness within a single test file. That is, (filename, test name) could serve as a unique id, since in IDEA, we'd only use this to run tests within one file at a time.

**Comment by nex3** [comment]
I can definitely see how that would make sense for their use-case! But from the perspective of `test` as a whole, we thing about test name selections as a cross-file concern.
