### ISSUE TITLE
Firefox: flag to silence first-run pop-ups?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#67]
Test blocked because firefox asked if it could be my default browser.

More flags that could be passed in?

**Comment by nex3** [comment]
This is supposed to be disabled. We provide it with a `prefs.js` file that has `user_pref("browser.shell.checkDefaultBrowser", false);` set. Can you investigate to see why that's not working for you?

**Comment by kevmoo** [comment]
I tried to reproduce with reset settings and couldn't get it to work. Closing out for now.
