### ISSUE TITLE
Publish 0.12.24+1

### ISSUE THREAD

**Issue by pq** [dart-lang/test#670]
w/ https://github.com/dart-lang/test/pull/668, we've got `0.12.24+1` which plays nice with the alpha analyzer and so, among other things, ungates a linter update to use the (new) analysis driver (https://github.com/dart-lang/linter/pull/754).

Could one of you publish; or add me as an uploader?

Thanks!

@grouma @kevmoo

**Comment by kevmoo** [comment]
Done!
