### ISSUE TITLE
Allow custom HTML template instead of per test file

### ISSUE THREAD

**Issue by avilladsen** [dart-lang/test#673]
Browser tests that depend on assets (e.g. JS interop) will always need a custom HTML file to include those assets. Since in-browser tests within the same package tend to depend on (subsets of) the same set of assets, it would be convenient to be able to specify one custom HTML template for tests, instead of having to essentially duplicate the same custom HTML file for each test file.

For context: right now I'm writing tests for a set of components that all rely on some global CSS (usually not relevant to the tests), and almost all transitively depend on a couple other components that use JS interop. So to get the tests loading and looking right when I step through them, I end up copying the exact same set of script and link tags into a custom HTML element for each new test file I make.

Really I'd like any solution to specify the JS and CSS assets that all my tests (or all tests with a given tag?) should include. A custom HTML template seems like a straightforward way to do that.

**Comment by nex3** [comment]
Right now, associating an HTML file with a test is simple and obvious: you just create an HTML file with the same name as the test. But this simplicity relies on the fact that the association is 1-to-1 (or 1-to-0). Once you have multiple Dart files that use same template, you need a much more complicated association schema that users need to learn and remember. I'd like to avoid that.

With something like [HTML imports](https://w3c.github.io/webcomponents/spec/imports/), you could do this from within the HTML itself. Unless/until those land, I suggest writing a bit of Dart code to dynamically inject those tags into the HTML and re-using that code among your test files.
