### ISSUE TITLE
`-pcontent-shell` doesn't work

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#68]
I activated test form the git repo to try content-shell support.
Dartium works fine already :+1: 
but when I run `pub global run test -pcontent-shell` nothing happens. The command just hangs without any output.

Related to #34

    Dart VM version: 1.11.0-edge.45122 (Mon Apr 13 14:31:22 2015) on "linux_x64"

**Comment by kevmoo** [comment]
Sanity check: you have `content_shell` on your path, right?

**Comment by zoechi** [comment]
Yup, `content_shell` or `content_shell --dump-render-tree http://www.google.com` works just fine.

**Comment by nex3** [comment]
Older content shells are known not to work. The latest bleeding-edge should be fine, but since the content shell isn't shipped with the SDK, it's not guaranteed to have the same version as your `dart` executable or even your `dartium`.

I've filed #69 to track providing a better error for this.

**Comment by zoechi** [comment]
I don't know how to get the version of content_shell but I use bleeding_edge and have updated today.

**Comment by nex3** [comment]
What I'm saying is that using bleeding edge in general doesn't ensure that you're using bleeding edge *for your content shell*. If you download a new one from [this site](http://gsdview.appspot.com/dart-archive/channels/stable/release/latest/dartium/) and make sure that that's the one on your path, it should work.

**Comment by zoechi** [comment]
I see, thanks for the hint.
