### ISSUE TITLE
Support pkg/async v2

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#690]
In many cases it's the only package keeping projects from getting the latest

**Comment by nex3** [comment]
This was fixed in #687.

**Comment by kevmoo** [comment]
Awesome! Guess I'm waiting for publish :-)

**Comment by nex3** [comment]
Published. I don't think this will fix packages, though; pub still has a dependency on async 1.8.0, so we'll need to get a new dev release out with that fix in.
