### ISSUE TITLE
Can't find test package file host.dart.js

### ISSUE THREAD

**Issue by shamblett** [dart-lang/test#698]
When running this command 
'pub run test -p chrome --pub-serve=8080' 
to test my package I get the following error in pub server output 
'test] GET packages/test/src/runner/browser/static/host.dart.js => Could not find asset test|lib/src/runner/browser/static/host.dart.js.'

It doesn't seem to exist, also how do I get test to use a custom HTML file, ie where do I put it?

**Comment by nex3** [comment]
What version of `test` are you using? What about your Dart SDK?

> how do I get test to use a custom HTML file, ie where do I put it?

Put the HTML file next to your test file. See [these docs](https://github.com/dart-lang/test#running-tests-with-custom-html) for details.

**Comment by shamblett** [comment]
Hi, found the problem, the file src/runner/browser/static/host.dart.js. doesn't exist because of a prob with my pub-cache not the test package, fixed it. 
Using Dart 1.24.2 and test-0.12.24+8 btw, all looks good, this issue can be closed.
