### ISSUE TITLE
Possible dart:async conflicting with test package

### ISSUE THREAD

**Issue by Stargator** [dart-lang/test#700]
I created a test for a case involving an error occurring for a component that wouldn't display unless an object was set via @Input

This is what the test function looks like:
```dart
void noInitialInputValue() {
  setUp(() async {
    // Note the beforeChangeDetection is not used to set the @Input value.
    _fixture = await _testBed.create();
    _po = await _fixture.resolvePageObject(ComponentPageObject);
  });

  tearDown(disposeAnyRunningTest);

  test('has empty view', () async {
  // The line using Future is what required dart:async
    expect(new Future<NoSuchMethodError>.error(NoSuchMethodError),
        throwsA(equals(NoSuchMethodError)));
  });
}
```

I needed Future from dart:async, but by importing dart:async caused `pub run angular_test` to return "No tests ran".

Removing the import of dart:async fixed the issue.

I don't think this is intended behavior.

**Comment by nex3** [comment]
Can you reproduce this in a standalone test file (ideally not using Angular)?

**Comment by Stargator** [comment]
@nex3 I'll work on that

**Comment by Stargator** [comment]
@nex3 Seems like I am not getting the same result without angular-based tests
