### ISSUE TITLE
Web test runner should consider serving with the `test` folder as the root.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#709]
Today when it serves test apps, it serves them at a path like `/some_generated_path/test/path_to_test.html`, compared to `pub serve test` which would serve with the test folder as the root (and this is also what the --pub-serve arg requires).

This doesn't allow you to use absolute paths at all, which are the easiest way to correctly refer to a single `packages` directory. Using relative paths to point at `packages` directories is brittle, and accidentally pointing at different `packages` directories can cause all kinds of issues.

**Comment by nex3** [comment]
There are a couple reasons this wouldn't work. First, the `test/` directory isn't canonical; all it is is the default argument to `test`. It's perfectly valid to run test files anywhere in your package, or even at the top level, and our server layout needs to reflect that. But even if we did consider it canonical, the generated secret is an important for security: it ensures that a malicious user with access to localhost can't snoop on files that are being served during a test run.

I feel the pain of resolving package URLs, though. Would it work to resolve them in code? We could provide an API for resolving them that would work across platforms.

**Comment by jakemac53** [comment]
We could provide a custom .packages file, possibly just directly within the --precompiled directory?

**Comment by nex3** [comment]
I'm not sure what that would do...

**Comment by jakemac53** [comment]
It would just tell the test runner where to load packages from, maybe we are talking about different things :)

**Comment by nex3** [comment]
The test runner knows where the packages are—that's how it serves `packages` directories. I thought the question was how to tell the test itself where the packages are.

**Comment by jakemac53** [comment]
That would be another way to approach the problem.

For package:build and ddc specifically, I would primarily need to know where the root of the main package is being served. Today that would essentially just be the name of the generated directory. We could add some hacks in probably to discover that, but that would be..... hacky.

Do you think something like that would be reasonable? How would it be exposed?

**Comment by nex3** [comment]
> For package:build and ddc specifically, I would primarily need to know where the root of the main package is being served. Today that would essentially just be the name of the generated directory.

I'm not sure I understand this. Wouldn't the root of the main package be above the generated directory?

**Comment by jakemac53** [comment]
Sorry for the confusion, by the "generated directory" I meant the one the test runner serves the package under - not the directory under which we are generating files.

**Comment by nex3** [comment]
Oh, I see! I'm thinking we'd provide something like:

```dart
/// The root of the package being tested.
///
/// For browser tests, this is an `http:` URL for the server serving the test
/// files. For VM and Node.js tests, it's a `file:` URL for the root of the
/// package on the filesystem.
Uri get testPackageRoot;

/// A [PackageResolver] that determines package locations for the current test.
///
/// For browser tests, all packages are served over HTTP. For VM and Node.js
/// tests, they're located in the pub package cache.
PackageResolver get testPackageResolver;
```

**Comment by jakemac53** [comment]
So one difficulty with that is that we actually need to know that uri at app bootstrapping time (I want to set up the `baseUrl` for `require.js` to that uri).  The easiest way to do would be with a JS global variable or something along those lines, do you think that would be reasonable to expose?

**Comment by nex3** [comment]
Setting up plain JS stuff is a lot more complicated... it may be easier for you to just use the JS equivalent of `Uri.base.replace(pathSegments: [Uri.base.pathSegments[0]])` as the root. That's unlikely to break in the future.

**Comment by jakemac53** [comment]
Ok, I am fine with doing something like that if you think its relatively safe to do so.

**Comment by nex3** [comment]
I do. I don't see any reason the HTTP structure would change.
