### ISSUE TITLE
All tests are skipped in the latest dev SDK

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/test#717]
`Dart VM version: 2.0.0-dev.5.0 (Thu Oct 26 04:43:38 2017) on "macos_x64"`

Both `pub run test` and right-click run in IntelliJ result in `00:00 +0: All tests skipped.`.

If I manually run a test, i.e. `dart test/my_test.dart`, everything works as expected.

**Comment by matanlurey** [comment]
Fixed by `pub upgrade`... Thanks @grouma

**Comment by nex3** [comment]
@grouma Do we know the underlying cause of this?

**Comment by grouma** [comment]
Not sure what the underlying cause would be. From past experience pub upgrade has resolved these odd issues.

**Comment by johnpryan** [comment]
What's the solution here? I am trying to run tests using the 2.0.0-dev.32.0 sdk.

I ran `pub upgrade` but when I run `pub run test` no tests are run and the message "All tests skipped" is printed out.

**Comment by nex3** [comment]
@johnpryan I can't reproduce this. Can you come up with a minimal repo that reproduces the issue?

**Comment by johnpryan** [comment]
Found the issue - we were using an old version of `test`. To reproduce,  I started with the "Dart Package" template in IntelliJ and changed the dependency constraint:

```yaml
dev_dependencies:
  test: ">=0.12.22 <0.12.24"
```

and then tried to run tests with dart 2. Loosening the constraint fixed the problem for me:

```yaml
dev_dependencies:
  test: ^0.12.25
```
