### ISSUE TITLE
Current version of pkg/test crashes the analyzer <=2.0.0-dev

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/test#725]
pkg/test now uses the "new" generic function syntax:
https://github.com/dart-lang/test/commit/4f701e568017ce13c129fcdcd72f3fc9bb40d639#diff-acbb02c497c2d9bf3ab863b85375a2feR36

but unfortunately that crashes the Dart analyzer (and various other tools) before `2.0.0-dev`.

Either `pkg/test` needs to pull the previous version and declare dev-only or replace all uses of generic function syntax with the older syntax/private typedefs until we are ready to become 2.0.0-dev only.

High priority as it crashes Flutter: @kevmoo @nex3 @grouma

**Comment by nex3** [comment]
What version of the analyzer are you seeing this with? When I run the 1.24.2 analyzer on the lib directory, I get a bunch of hints but no errors or crashes.

**Comment by matanlurey** [comment]
I'm not sure of the exact version, I just know the analyzer never fixed a large series of bugs around generic function syntax until the 2.0.0-dev branch. @kevmoo knows some background.
