### ISSUE TITLE
feature request: Gradle has test.dependsOn and test.finalizedBy - this makes it possible to start Docker before test

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/test#731]
For my integration tests I'm testing against a Docker container. 
This is how my build.grade looks like in Java-Projects:
```
task startContainer() {
    doLast {
        exec {
            executable = 'docker/_ci/run.sh'
            args = ['--start']
        }
    }
}

task stopContainer() {
    doLast {
        exec {
            executable = 'docker/_ci/run.sh'
            args = ['--stop']
        }
    }
}

test.dependsOn startContainer, "prepareCertsFolder"
test.finalizedBy stopContainer
```
`gradle test` starts the container, runs the tests and then shuts down the container.
It would be cool to have something similar for "dart test"

**Comment by nex3** [comment]
Can you use `setUpAll()` and `tearDownAll()` for this?

**Comment by grouma** [comment]
Please reopen if this is still an issue and provide more details.
