### ISSUE TITLE
Change the signature of `fail` to `T fail<T>(...)` to broaden usage

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#740]
It'd be nice to use fail in this case:

```dart
doSomething(callback: (value) => fail('should never be called'));
```

But if `callback` expects a function that returns a value, you get an analyzer warning:

```
error: The function expression type '(Response) → void' isn't of type '(Response) → FutureOr<Response>'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s). (strong_mode_invalid_cast_function_expr at [shelf] test/create_middleware_test.dart:74)
```

**Comment by eernstg** [comment]
It would actually suffice to use the bottom type: `Null fail(...)` (or, with non-null types: `Nothing fail(...)`, which nicely says that "nothing is returned" which matches the fact that a normal completion, "a return", never occurs).
