### ISSUE TITLE
Negate matcher

### ISSUE THREAD

**Issue by passsy** [dart-lang/test#743]
When writing tests I miss some negation matchers. There is a `contains` matcher but not a `doesNotContain` matcher. Same for `equals` which lacks a `isNotEqualTo`. Is this intentional?

I wrote a `not(Matcher)` matcher negating a matcher but it doesn't provide good error messages:

```dart
test("does not contain", () {
  expect([1, 2, 4], not(contains(3))); // success

  expect([1, 2, 4], not(contains(4))); // fail
  // Expected: NOT contains <4>
  //  Actual: [1, 2, 4]
});
```
```dart
Matcher not<T>(Matcher matcher) => new NotMatcher(matcher);

class NotMatcher extends Matcher {
  final Matcher matcher;

  NotMatcher(this.matcher);

  @override
  Description describe(Description description) {
    description.add("NOT ");
    matcher.describe(description);
    return description;
  }

  @override
  Description describeMismatch(
      item, Description mismatchDescription, Map matchState, bool verbose) {
    return matcher.describeMismatch(
        item, mismatchDescription, matchState, verbose);
  }

  @override
  bool matches(item, Map matchState) => !matcher.matches(item, matchState);
}
```

Would the negation patterns be useful for this project? I'd like to add Matchers similar to [AssertJ](http://joel-costigliola.github.io/assertj/).

**Comment by natebosch** [comment]
There is an `isNot` matcher: https://www.dartdocs.org/documentation/test/0.12.29%2B1/test/isNot.html

**Comment by passsy** [comment]
totally missed that!

**Comment by ThinkDigitalSoftware** [comment]
This shoudn't close this issue though, It would be nice to throw a `!` in from of a matcher. I'm looking for the negation of the string matcher endsWith to make sure the string doesn't end with a whitespace char but don't see any in the string matchers class. I could make my own matcher, but if it was possible to just specify that we want successful matches to be considered a failing match, that would make this super easy to use.

**Comment by natebosch** [comment]
@ThinkDigitalSoftware - We can't use `!` but we _could_ use `~`.

The best place to discuss this is at https://github.com/dart-lang/matcher/issues/121

In the proposal there `~endsWith('something')` would be equivalent to `isNot(endsWith('something'))` which is the way you'd write it today.

**Comment by ThinkDigitalSoftware** [comment]
@natebosch oh, I didn't know about that. Thank you!

**Comment by natebosch** [comment]
To be clear, the linked issue hasn't been implemented. It's a feature request at this point. A 👍 will help us understand whether to prioritize it.

**Comment by ThinkDigitalSoftware** [comment]
It's slightly off topic, no? It appears that simply adding 

```dart
extension NegationMatcher on Matcher {
  Matcher inverse() => isNot(this);
}
```
fixes my concern

**Comment by natebosch** [comment]
If you're happy with doing it locally that's great! The issue is for us to consider doing it in the matcher package itself so that all users of `package:test` can use it.

**Comment by ThinkDigitalSoftware** [comment]
OK, I'll add my two cents and my upvote
