### ISSUE TITLE
Should be able to override the default line length when wrapping the test runner

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#749]
If you want to wrap the test runner in a different process the compact reporter doesn't work properly because the line length falls back to the default of 200 which ends up doing weird things if your terminal width is <200 lines.

We should be able to override this with an explicit value, or come up with some other solution for when the test runner isn't directly connected to a terminal.

One way to deal with this would be a global environment variable, DEFAULT_TERMINAL_LINES or similar.

**Comment by nex3** [comment]
Closing since the VM now supports spawning with a PTY.
