### ISSUE TITLE
Consider setting up travis build stages

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#757]
By setting up things to run in stages on travis, you can prevent some jobs from running until another stage completes successfully. This helps limit travis usage so that everybody can get their jobs running more quickly, at a cost of slightly longer travis runs in some cases. In the long run the more packages we get to do this the better it should be overall for everybody.

One potential configuration I would propose is splitting the jobs into 3 stages:

1. analyze and dartformat checks
2. run tests on the latest dart sdk
3. run tests on other sdks

The tests look like they take around 10 minutes to run each shard, and the analyze/format steps only take around 1-2 minutes, so that would lead to a best case presubmit time of somewhere around 20 minutes, but its hard to say exactly how it would pan out in practice.

Current presubmit times appear to usually be just under 30 minutes in practice, although occasionally it looks like you do get full parallelism and the tests complete in around 10 minutes, so there would be a noticable worsening of the best case scenario with separating the tests into separate stages.

**Comment by nex3** [comment]
What's the benefit of running the formatter check before the other stages? We'd usually expect the behavior of tests to be otherwise unaffected by whether they're well-formatted, right?

**Comment by jakemac53** [comment]
> What's the benefit of running the formatter check before the other stages? We'd usually expect the behavior of tests to be otherwise unaffected by whether they're well-formatted, right?

Its true the tests won't be affected (hopefully!), but you are going to have to push another commit anyways so it prevents the tests from running an extra time. I can see how you might want the tests to run anyways though just to get an earlier signal, and that would be fine. You could even run the formatting check last if that is what you would prefer.

Personally, I like having the build fail as quickly as possible (and do as little work as possible) for trivial errors like that. I can quickly format,  push a new commit, and then follow the tests from there.

**Comment by nex3** [comment]
I often push a commit and come back in half an hour to see how the tests did, and I think I'd be pretty frustrated to find that they didn't even run because I forgot to run something trivial. Plus, if everything is green except the formatter, I can safely reformat and then land the PR without waiting for the other tests anyway.

**Comment by jakemac53** [comment]
> I often push a commit and come back in half an hour to see how the tests did, and I think I'd be pretty frustrated to find that they didn't even run because I forgot to run something trivial. Plus, if everything is green except the formatter, I can safely reformat and then land the PR without waiting for the other tests anyway.

Ya, I agree that would be annoying, but it should be a rare case. Those tasks will also run first so if you come back in just a couple minutes you can make sure it actually made it past that first stage.

While its true you don't have to wait for the tests to run after pushing a formatting change, they do still run afaik (even if you merge the pr prior to them finishing) and so other users end up waiting behind them. At the same time travis is going to do a new build on the master branch after the merge. You could go in and cancel the extra jobs from the pull request if you want to be extra nice but that is a bit of a pain to do all the time.

**Comment by nex3** [comment]
I don't know about you, but it's not so rare for me to forget to format otherwise-functional code :stuck_out_tongue_closed_eyes:.

**Comment by jakemac53** [comment]
> I don't know about you, but it's not so rare for me to forget to format otherwise-functional code .

Heh, well I do format on save in my editor so I pretty much never run into it :).

But ya, I am just providing ideas here and a pattern that seems to be working well for us over at the build repo, not trying to force anything specific.

**Comment by jakemac53** [comment]
https://github.com/dart-lang/test/pull/815 is where I started work, but ran into some issues that I didn't want to dive into at the moment.
