### ISSUE TITLE
Exit as a failure if no tests are run

### ISSUE THREAD

**Issue by natebosch** [dart-lang/test#764]
This has come up in the past but I can't track down the discussion...

Refiling the issue since this is a problem all over again and solving it in the test package is the best overall fix. We're currently hacking around this internally by scraping for the string "No tests ran." but I'm worried this is fragile and we have to repeat this in all the places we run tests. We're also going to end up having to repeat this hack externally - https://github.com/dart-lang/build/issues/1000

My preference would be for either no option (no tests is always a failure) or for an option where the default is a failure since it's safest for CI environments. If we have an option where the default is to pass that would also work for us and we can spread the convention to always run with that option enabled.

cc @matanlurey @grouma @jakemac53

**Comment by grouma** [comment]
I would really like to see this as well. I prefer introducing a flag and don't have a strong preference for the default behavior. @nex3 if you agree I can get started on this request.

**Comment by nex3** [comment]
I don't want this to be the default, since it violates the invariant that adding more filters reduces failures (plus it would be a breaking change), but I'm okay adding a flag for it. Maybe `--require-tests`?

**Comment by natebosch** [comment]
> it violates the invariant that adding more filters reduces failures

Is this an invariant today?

`pub run test -n "does not match"` - non-zero exit code
`pub run test test/does_not_exist.dart` - non-zero exit code
`pub run test -t not-a-tag` - zero exit code
`pub run test -n "existing test" -t existing-tag` - zero exit code
`pub run test -n "existing but not tagged test" -t existing-tag` - non-zero exit code

Adding a `-n` can cause failures. Changing platforms or adding tags can, but only(?) when used in combination with `-n`.

**Comment by nex3** [comment]
That's true, `-n` can. That's not ideal... probably also not worth breaking backwards-compat for, but certainly not a decision I'd make today.

Fun fact: this means you *can* force test to error on a lack of tests today by using `-n ""`.
