### ISSUE TITLE
package:test doesn't handle futures correctly

### ISSUE THREAD

**Issue by leiboldm** [dart-lang/test#768]
Run the following two tests.   Note that test 1 passes, but test 2 fails even though the two tests are immaterially different (the lines in the try block are swapped).

```
void main() {
  group('Example repro', () {
    StreamController controller;
    Future future;

    setUp(() {
      controller = new StreamController.broadcast();
      future = controller.stream.first;
    });

    test('should pass', () async {
      controller.addError('err');
      try {
        await future;
        await new Future.value();
      } catch (err) {
        expect(err, 'err');
      }
    });

    test('should also pass' /* but doesn't */, () async {
      controller.addError('err');
      try {
        await new Future.value();
        await future;
      } catch (err) {
        expect(err, 'err');
      }
    });
  });
}
```

**Comment by matanlurey** [comment]
I will add that is considered bad form to use `try/catch` in tests.

There are a few nice matchers that will help, like `throwsA`:

```dart
test('...', () async {
  expect(await future, throwsA(isString));
});
```

**Comment by leiboldm** [comment]
I rooted out the real error in my actual test.  It was because a super class of the class under test was using Stream.forEach but forgot to add error handling to the returned future.  I didn't realize this because the error that failed the test didn't include the forEach call anywhere in its stacktrace.  

I'm not sure if there's anything that can be done about this, but it would be nice if the error/stacktrace gave you more direction as to where the bug is.  

Here's a minimal example demonstrating this:

```
class Parent {
  final StreamController _controller = new StreamController.broadcast();

  Stream get changes => _controller.stream;

  void addError(error) {
    _controller.addError(error);
  }
}

class Child extends Parent {
  void _attachListener() {
    changes.forEach((_) {
      print('change');
    }); // Add "catchError((_) {});" here to make test pass.
  }

  Child() {
    _attachListener();
  }
}

class Grandchild extends Child {
  Future doSomething(Stream stream) async {
    final future = stream.first.catchError((e) => addError(e));
    await new Future.value();
    await future;
  }
}

void main() {
  group('Example repro', () {
    Completer completer;
    Grandchild instance;

    setUp(() {
      instance = new Grandchild();
      completer = new Completer();
    });

    test('doSomething should handle errors', () async {
      instance.changes.first.catchError(expectAsync1((e) {
        expect(e, 'error');
      }));
      instance.doSomething(new Stream.fromFuture(completer.future));
      completer.completeError('error');
    });
  });
}
```

**Comment by natebosch** [comment]
Unfortunately there isn't much package:test can do about this. There isn't a way to recognize the intention "this future _will_ be listened in a test".

In general, if a Future can result in an error the error handling needs to be set up before the Future completes with the error. https://www.dartlang.org/guides/libraries/futures-error-handling#potential-problem-failing-to-register-error-handlers-early

The `Result` class from package:async can help with this. You can `capture` a `Future` into a `Future<Result>` which will never error, then you can `release` it back into a `Future` when you're ready to add the error handling.
