### ISSUE TITLE
Cannot run bin/test.dart directly when `dart` is symlinked outside of dart-sdk

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#79]
If `dart` is symlinked, `Platform.executable` may just return "dart", which blows up when trying to find the SDK path.

Seems be be caused by https://code.google.com/p/dart/issues/detail?id=16994

``` shell
Unhandled exception:
FileSystemException: Cannot open file, path = './version' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:558)
#1      _File.openSync (dart:io/file_impl.dart:410)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:469)
#3      _File.readAsStringSync (dart:io/file_impl.dart:503)
#4      _sdkVersion (package:test/src/util/io.dart:24:26)
#5      _sdkVersion (package:test/src/util/io.dart:22:15)
#6      _supportsPubServe (package:test/src/util/io.dart:65:63)
#7      supportsPubServe (package:test/src/util/io.dart:60:31)
#8      supportsPubServe (package:test/src/util/io.dart:60:12)
#9      main (package:test/src/executable.dart:103:14)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:253)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
```

**Comment by seaneagan** [comment]
http://dartbug.com/22098 would help fix this, no?

**Comment by nex3** [comment]
@kevmoo Can you clarify the title and why this is blocked? In what contexts does `bin/test.dart` not work?

**Comment by kevmoo** [comment]
@nex3 added some notes

**Comment by nex3** [comment]
This is presumably fixed now.

**Comment by kevmoo** [comment]
Not yet. We need to use `Platform.resolvedExecutable` – but that means either adding a catch or requiring at least 1.11

**Comment by nex3** [comment]
Why do we need `Platform.resolvedExecutable`? We already [resolve symbolic links ourselves](https://github.com/dart-lang/test/blob/master/lib/src/util/io.dart#L34). Switching to `resolvedExecutable` shouldn't change the behavior, it should just make the code cleaner.

**Comment by kevmoo** [comment]
`Platform.resolvedExecutable` takes care of `dart` being in your path. Without it, you just get `dart` which resolves to nothing.

**Comment by grouma** [comment]
Closing. If this is still an issue please reopen.
