### ISSUE TITLE
Factor out a "package:test_core" from package:test

### ISSUE THREAD

**Issue by Hixie** [dart-lang/test#797]
package:test today has >60 dependencies, which is a huge problem for Flutter. It would be fantastic if the package:flutter_test package could instead depend on some smaller "core" test package that had less opinion and was more about just running tests and collating data.

**Comment by Hixie** [comment]
See also https://github.com/dart-lang/test/issues/590 for a specialized subset of this.

**Comment by grouma** [comment]
This has been completed for some time.
