### ISSUE TITLE
Better error message when browser test imports `dart:io`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#81]
I run a test with `@TestOn('browser')` which had by mistake transitively imported `dart:io`.
Running this test results in

```
 (master) $ pub run test -pcontent-shell -pvm test/browser
00:00 +0 -1: load error                                                                             
  Failed to load "test/browser/parse_int_test.dart": Timed out waiting for the test suite to connect.
00:00 +0 -1: Some tests failed.                   
```

Would be great if there could be a more informative error message. 
I guess this applies to a broader set of possible errors which might be hard to debug without more informatoin.

**Comment by grouma** [comment]
I think this was mostly addressed with: https://github.com/dart-lang/test/pull/628

Unfortunately I was unable to provide the exact error but hopefully enough of a hint to where the issue may reside.
