### ISSUE TITLE
Remove barback support

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#818]
Once an SDK is released with https://github.com/dart-lang/sdk/commit/94f45c8876b2c4626462e7327f800fd33c842070 (hopefully within days, likely as -dev.51), we should

* Remove the barback dependency in test – and associated code.
    * Is this a breaking change, strictly? The barback bits wouldn't work in the new SDK anyway – to discuss.
* Bump the min SDK to -dev.51
* Publish
* Roll the new version into the Dart SDK
    * And remove the barback dependency there...

**Comment by natebosch** [comment]
Fixed by https://github.com/dart-lang/test/pull/823
