### ISSUE TITLE
Re-enable pub-serve tests or delete the feature

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#821]
The tests are now going to be skipped since the latest sdk doesn't support pub serve.

We can either delete the feature entirely, or do some other sort of test (possibly use build_runner serve).

**Comment by jakemac53** [comment]
If we do retain the flag we should probably rename it as well (although we can support the old version as an alias).

**Comment by kevmoo** [comment]
@jakemac53 @grouma We removed all of this, right?

**Comment by jakemac53** [comment]
This support still exists - we just can't test it

**Comment by natebosch** [comment]
@jakemac53 - are we OK with removing this in the next breaking change bump?

**Comment by jakemac53** [comment]
Well ironically with frontend server we might want to bring it back to official support lol

**Comment by kevmoo** [comment]
> Well ironically with frontend server we might want to bring it back to official support lol

😮

**Comment by natebosch** [comment]
@jakemac53 - do we think there is any use case still?

Would dropping this make the `--compiler` work any easier?

**Comment by jakemac53** [comment]
I could definitely see dropping it, but given precompiled support has to stick around the complexity/decisions are essentially identical.

**Comment by natebosch** [comment]
`--pub-serve` dropped in #2144
