### ISSUE TITLE
Add a quieter reporter that only prints information for failures

### ISSUE THREAD

**Issue by natebosch** [dart-lang/test#829]
In places where the "compact" reporter doesn't work it would be nice to have a reporter that only prints when a test fails and then a summary at the end.

**Comment by jakemac53** [comment]
Note that travis requires some sort of output every 10 minutes, so we would probably need some sort of heartbeat logger that periodically outputs a summary of the status. This would probably be useful anyways and would still be much less noisy than the existing reporters.

**Comment by jakemac53** [comment]
We could rip out the existing heartbeat logging logic from package:build_runner into a package (or add it to the io or cli_utils package). Or we could just re-implement it.

**Comment by grouma** [comment]
I imagine this would be the reporter that is shipped with the `api` package.

**Comment by dnfield** [comment]
This would be nice for Flutter.  The compact reporter doesn't quite manage to print a single line for successes there, and you end up with thousands of lines to sift through.

**Comment by dnfield** [comment]
See #982 which isn't quite all of what this asks for but improves the compact reporter wrt my issue.

**Comment by natebosch** [comment]
> Note that travis requires some sort of output every 10 minutes

I don't think github actions has the same requirement, and I think we'l keep using the github reporter for CI. I think we could get by with a strictly failure output initially and wait for a specific request for heartbeat output before implementing it.
