### ISSUE TITLE
test broken in 0.12.38

### ISSUE THREAD

**Issue by Rockvole** [dart-lang/test#835]
If I change my pubspec.yaml to <code>test: 0.12.38</code>
When I run my tests I get the error :

    Unhandled exception:
    NoSuchMethodError: No static getter 'sigterm' declared in class 'ProcessSignal'.
    Receiver: ProcessSignal
    Tried calling: sigterm
    #0      NoSuchMethodError._throwNew (dart:core-patch/dart:core/errors_patch.dart:196)
    #1      _signals (package:test/src/executable.dart:33:31)
    #2      _signals (package:test/src/executable.dart:30:7)
    #3      main (package:test/src/executable.dart:167:24)
    <asynchronous suspension>
    #4      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
    #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

    Process finished with exit code 255

If I toggle back to <code>test: 0.12.37</code> my tests work as expected.

**Comment by jakemac53** [comment]
This minimum sdk version was appropriately increased for 0.12.38+1, https://github.com/dart-lang/test/commit/735a644d4e3830b02e3a98eec14df017a1209206#diff-fb2d52cd953afedcafc9fe7629c6f132R7.

There is an issue with flutter right now where it doesn't respect sdk constraints correctly, which might be what you are running into https://github.com/flutter/flutter/issues/17656

**Comment by Rockvole** [comment]
Thanks. Although this is not a flutter project, just dart.

**Comment by jakemac53** [comment]
Are you using a dependency override to force the latest test? What version of the sdk do you have (dart --version)?

**Comment by Rockvole** [comment]
I was given the latest test 0.12.38 and I forced the downgrade to get my code working again.

My (working) pubspec.yaml is 

    name: keyboard
    version: 1.0.0
    description: A sample command-line application
    dependencies:
      xml: ^3.0.0
      archive: ^1.0.33
      yaml:
      test: 0.12.37

    dev_dependencies:

When I manually toggle back to 0.12.38 my code breaks.
My dart version
![dart](https://user-images.githubusercontent.com/4139576/40316703-fed7b914-5cd3-11e8-8667-4c9938cd4a67.png)

**Comment by jakemac53** [comment]
It looks like you do have the flutter sdk though - notice the `Dart SDK path` variable? Also note that the version is not normal, its a custom build.

**Comment by Rockvole** [comment]
Ok. I originally developed flutter in Intellij until android studio caught up.

**Comment by jakemac53** [comment]
Going to close this as there is nothing we can do on the package:test side of things :(
