### ISSUE TITLE
How to debug dart tests when using json reporter?

### ISSUE THREAD

**Issue by DanTup** [dart-lang/test#838]
I'm working on integrating tests into VS Code. It's working reasonable for Flutter tests but I'd like to also support Dart CLI tests. When I trying to run `pub run test --reporter json` I get this message:

> Warning: Debugging is currently unsupported on the Dart VM.

So I tried running them directly through `dart` but then it seems like the reporter flag is ignored, so I don't get JSON output.

I've had a quick look in the [IntelliJ source](https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/ide/runner/test/DartTestRunningState.java) but as far as I can tell it's using `pub` so I'm not sure whether debugging is working there (possibly @alexander-doroshko can confirm if it works there, and if so, how).

What is the correct way (assuming there currently is one!) to attach a debugger to tests while getting JSON output?

**Comment by jakemac53** [comment]
There is no way right now I don't believe. If you invoke the script directly that just passes any arguments directly to the `main` in that test file, we don't have any hooks to set up a reporter.

**Comment by DanTup** [comment]
So does this not work in IntelliJ either? Is nobody screaming that they can't debug their tests? :-/

Do you know what the complications are with adding it? Presumably the test package can access the arguments, so maybe it wouldn't be hard to make it output JSON if called through `dart` with `--reporter json`? If there's not some obvious blocking issue, I could take a look.

Detecting whether the end user has a version that supports it even when it's fixed might be trickier though!

**Comment by jakemac53** [comment]
> So does this not work in IntelliJ either? Is nobody screaming that they can't debug their tests? :-/

My (uninformed) guess is that you can debug the test file itself just like any other dart script, because it doesn't need the special reporter to do that.

> Do you know what the complications are with adding it? Presumably the test package can access the arguments, so maybe it wouldn't be hard to make it output JSON if called through dart with --reporter json? If there's not some obvious blocking issue, I could take a look.

There is `Platform.executableArguments`, but those are the dart vm args I believe. I think the actual script arguments would have to be passed through manually in the test.

We could possibly add support for a system environment variable or -D environment variable to set the reporter though.

> Detecting whether the end user has a version that supports it even when it's fixed might be trickier though!

Yep, you would have to get the package:test version from pubspec.lock or something.

**Comment by DanTup** [comment]
> My (uninformed) guess is that you can debug the test file itself just like any other dart script, because it doesn't need the special reporter to do that.

That's what we do in VS Code today, but a few people told me the lack of a test runner is one of the reasons they stuck with IntelliJ so I presumed it worked :(

I found some related issues:

- https://github.com/dart-lang/sdk/issues/31308
- https://github.com/dart-lang/test/issues/50

Seems like this isn't going anywhere fast.

> We could possibly add support for a system environment variable or -D environment variable to set the reporter though

Anything at all would be awesome. It feels really crappy delivering a test runner that doesn't work with Dart CLI but does with Flutter. Though if it's a simple job to use the JSON reporter executing directly through `dart` I'm not sure why it hasn't come up in any of the related threads.

If you think it's doable, I'd be happy to take a crack at this if you're happy for it work like this.

**Comment by jakemac53** [comment]
@natebosch @grouma how do you feel about an environment variable for the reporter?

**Comment by DanTup** [comment]
Oh btw, if the runner isn't reading the args, does this mean running a single test (eg. with `--plain-name`) won't work either?

If not, would it be better to let test just read all the arguments passed to the script (even if that's opt-in with an env var)?

**Comment by jakemac53** [comment]
> Oh btw, if the runner isn't reading the args, does this mean running a single test (eg. with --plain-name) won't work either?
> 
> If not, would it be better to let test just read all the arguments passed to the script (even if that's opt-in with an env var)?

Yes, no arguments will be respected. The test itself could in theory call into some api within package:test with the arguments but you would have to manually write that in all tests. As far as I know there is no way to get the command line arguments for a script from within a library, without the user explicitly giving them to you.

**Comment by jakemac53** [comment]
Was talking a bit with @natebosch as well and it sounds like we might actually be blocked on enabling debugging for vm tests in general so we can try to make progress there.

**Comment by DanTup** [comment]
There were some comments in https://github.com/dart-lang/sdk/issues/31308 about there being a silent flag to solve the issue (which I believe was the Observatory URL being output to stdout) but comments suggest it didn't work. Assuming that's done, what's the work that needs doing here? I'm happy to help out if I can; I'd really like to ship a preview of the test stuff I'm working on soon, and it'd be great to support VM tests (even if it requires being on a dev build or something) - and, I'd personally like to be able to use it for analysis server/flutter tools/LSP projects :-D

**Comment by DanTup** [comment]
Ah, I figured out how IntelliJ is doing this...

```
/Users/dantup/Dev/dart-sdk/dart-2.0.0-dev.43.0/bin/dart --pause_isolates_on_start --enable-vm-service:64147 /Users/dantup/Dev/dart-sdk/dart-2.0.0-dev.43.0/bin/snapshots/pub.dart.snapshot run test -r json /Users/dantup/Dev/Dart-Code/test/test_projects/hello_world/test/my_test.dart
```

It's running via the Dart VM so it can debug, but still running through `pub` do that it can pass the reporter.

@jakemac53 @natebosch How far off a solution do you think we are? I'm happy to look at doing this as a workaround for now.

**Comment by alexander-doroshko** [comment]
Equivalent way would be running standard `pub` script (i.e. ` pub run test -r json`) while `DART_VM_OPTIONS` env var is set to `--pause_isolates_on_start --enable-vm-service:64147`. See pub script contents for details.

Natalie doesn't like the way we debug VM tests in IntelliJ because this way is not official. 
An official way exists so far for Dart Web tests only (see https://github.com/dart-lang/test/pull/483) but it is not supported by IntelliJ yet. I mean IntelliJ doesn't debug Dart web-targeted tests at the moment and debugs VM tests using not official way.

**Comment by DanTup** [comment]
> `--enable-vm-service:64147`

I tried with `--enable-vm-service=0` so I didn't have to figure out an available port, but it didn't seem to provide me the debugger URL (I thought it'd just come in stdout like it does when debugging on the VM normally). I guess that's why you're having to give it a port? Are you just randomly assigning and hoping it's free?

**Comment by DanTup** [comment]
This solution seems to work great! The only issue I had was that my testing helpers assumed there would only be 1 isolate when fetching the call stack (etc.) for verifying. In this case there are three (pub, test, user code) so I'm just filtering out the known pub/test ones (it's only test code).

So, this is much less urgent to me right now. While unofficial, it doesn't seem like this should be particularly fragile. Thanks @alexander-doroshko!

**Comment by DanTup** [comment]
Ok, this isn't as good as I thought :(

Turns out that neither of the codebases I run tests on (Analysis Server and Flutter Tools) work when run through `pub run test`. Since my plan was to always run tests through this new runner, this complicates things a little (even if analysis server dev is not the main use case, not being able to run my own tests would be frustrating and reduce the testing it gets from me!).

As such, the best way to fix this really would be being able to select the JSON reporter when running through the Dart VM as suggested above:

> We could possibly add support for a system environment variable or -D environment variable to set the reporter though.

What are your thoughts on this? It doesn't sound like a massive job so I'm happy to have a crack at it and open a PR if you think it's a fair feature.

**Comment by jakemac53** [comment]
@DanTup sure, we would be willing to accept a PR for this. https://github.com/dart-lang/test/blob/master/lib/src/runner/configuration/reporters.dart#L46 would be the line that needs to be updated, and at least one test would be good.

**Comment by DanTup** [comment]
Great! I've opened https://github.com/dart-lang/test/pull/873 for review :)

**Comment by DanTup** [comment]
Closing this since the PR was abandoned. This is behind a flag for now because there are a few scenarios that don't work (we handle the "SDK" case, but `flutter_tools` tests are also broken because of them wanting Dart v2 semantics - I think that might be fixed in the very latest Dart SDK, but Flutter is a little out of date).
