### ISSUE TITLE
Polymer test works in Dartium but not in Chrome

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#84]
This test https://github.com/bwu-dart/bwu_utils/tree/master/test/browser run with 
`pub run test -pchrome test/browser` just hangs but shows the following output in the browser console.

```
Failed to load resource: the server responded with a status of 404 (Not Found)
html_test.dart.browser_test.dart.js:126876 'webkitAudioContext' is deprecated. Please use 'AudioContext' instead.
html_test.dart.browser_test.dart.js:3041 Uncaught Uncaught Error: Unable to find library at http://localhost:35896/OA7qQJpNhA4esDkkLK7wZ9-opMJCy6Jg/test/browser/child_element.dart.
Stack Trace:
Unable to find library at http://localhost:35896/OA7qQJpNhA4esDkkLK7wZ9-opMJCy6Jg/test/browser/child_element.dart.
    at dart.wrapException (http://localhost:35896/OA7qQJpNhA4esDkkLK7wZ9-opMJCy6Jg/test/browser/html_test.dart.browser_test.dart.js:4391:15)
    at dart.throwExpression (http://localhost:35896/OA7qQJpNhA4esDkkLK7wZ9-opMJCy6Jg/test/browser/html_test.dart.browser_test.dart.js:4404:13)
    at run (http://localhost:35896/OA7qQJpNhA4esDkkLK7wZ9-opMJCy6Jg/test/browser/html_test.dart.browser_test.dart.js:120458:17)
    at _wrapJsFunctionForAsync_closure._captured_protected_1 (http://localhost:35896/OA7qQJpNhA4esDkkLK7wZ9-opMJCy6Jg/test/browser/html_test.dart.browser_test.dart.js:4768:11)
    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$1 (http://localhost:35896/OA7qQJpNhA4esDkkLK7wZ9-opMJCy6Jg/test/browser/html_test.dart.browser_test.dart.js:6760:12)
    at dirtyCheckZoneSpec_wrapUnaryCallback_closure.dart.dirtyCheckZoneSpec_wrapUnaryCallback_closure.call$1 (http://localhost:35896/OA7qQJpNhA4esDkkLK7wZ9-opMJCy6Jg/test/browser/html_test.dart.browser_test.dart.js:96907:34)
    at dart._rootRunUnary (http://localhost:35896/OA7qQJpNhA4esDkkLK7wZ9-opMJCy6Jg/test/browser/html_test.dart.browser_test.dart.js:14731:16)
    at _CustomZone.dart._CustomZone.runUnary$2 (http://localhost:35896/OA7qQJpNhA4esDkkLK7wZ9-opMJCy6Jg/test/browser/html_test.dart.browser_test.dart.js:23837:39)
    at _Future__propagateToListeners_handleValueCallback.dart._Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:35896/OA7qQJpNhA4esDkkLK7wZ9-opMJCy6Jg/test/browser/html_test.dart.browser_test.dart.js:16993:78)
    at dart._Future.static._Future__propagateToListeners (http://localhost:35896/OA7qQJpNhA4esDkkLK7wZ9-opMJCy6Jg/test/browser/html_test.dart.browser_test.dart.js:16862:157)
html_test.dart.js.map:1 GET http://localhost:35896/OA7qQJpNhA4esDkkLK7wZ9-opMJCy6Jg/test/browser/html_test.dart.js.map 404 (Not Found)
```

**Comment by zoechi** [comment]
I also get these errors in the `pub serve` output.
```
Build error:
Transforms {PubServe on bwu_utils|test/browser/html_test.dart} all emitted asset bwu_utils|test/browser/html_test.html.
[Error from ScriptCompactor]:
Found either zero or multiple dart scripts in the entry point `test/browser/html_test.html`. Exactly one was expected.
Build completed with 2 errors.
```

**Comment by nex3** [comment]
I'm confused. `pub run test -pchrome test/browser` doesn't use `pub serve`, so why is its output relevant?

**Comment by nex3** [comment]
It sounds like running Polymer on JS isn't supported without using the `barback` transformer stack, so your first invocation is not expected to work. The `pub serve` error you're seeing is a bug, but not one that should cause problems beyond that warning. It looks like you have other errors when running against `pub serve`, but they aren't JS-specific and I doubt they have to do with the test runner.

**Comment by zoechi** [comment]
I had the impression it uses pub serve, because it produced this output. Maybe just because pub serve was already running and recognized file changes. 
Yes, Polymer needs barback/transformers or maybe pub build. I don't know how I am supposed to run such tests. Any hints?

**Comment by nex3** [comment]
Check out [the README](https://github.com/dart-lang/test/blob/master/README.md#testing-with-barback).

**Comment by zoechi** [comment]
Thanks for the info and sorry for the noise. I somehow missed that section of the readme.

**Comment by kevmoo** [comment]
@zoechi No worries. Thank you **SO** much for kicking the tires and helping us find bugs!

**Comment by zoechi** [comment]
There were several things I missed badly in unittest and this new test package is a huge improvement :)
Thanks for the great work!

**Comment by zoechi** [comment]
I'm still not able to get tests with Polymer working (my example:
https://github.com/bwu-dart/bwu_utils/tree/polymer_test/test/browser/polymer_test_example)

I run `pub serve`

> Serving bwu_utils test on http://localhost:8080

and in another console
`pub run test -pdartium --pub-serve=8080 test/browser/polymer_test_example/`
(same when I use `-pchrome` instead of `-pdartium`)

The browser windows opens and closes and I get this output:

> $ pub run test -pdartium --pub-serve=8080 test/browser/polymer_test_example/
> "pub serve" is compiling test/browser/polymer_test_example/html_test.dart...
> 00:00 +0 -1: load error                                                                             
>   Failed to load "test/browser/polymer_test_example/html_test.dart": Timed out waiting for the test suite to connect on Dartium.
> 00:00 +0 -1: Some tests failed.     

I have added `<script type="application/dart" src="html_test.dart"></script>` in the body because otherwise the Polymer transformer reports an error

> [Error from ScriptCompactor]:
> Found either zero or multiple dart scripts in the entry point `test/browser/polymer_test_example/html_test.html`. Exactly one was expected.
> Build completed with 1 errors.

When I load the test page in the browser manually
`http://localhost:8080/browser/polymer_test_example/html_test.html`
I get this output in the browser console

> Navigated to http://localhost:8080/browser/polymer_test_example/html_test.html
> html_test.html:414 Resource interpreted as Script but transferred with MIME type application/dart: "http://localhost:8080/browser/polymer_test_example/html_test.html.polymer.bootstrap.dart".
> html_test.html.polymer.bootstrap.dart.js:17268 
> 00:00 [32m+0[0m[33m ~1[0m: getParentElement simple DOM elements[0m
> html_test.html.polymer.bootstrap.dart.js:17268   [33mSkip: enable!!![0m
html_test.html.polymer.bootstrap.dart.js:14201 XHR finished loading: GET "http://localhost:8080/browser/polymer_test_example/html_test.html._buildLogs".dart.HttpRequest_request @ html_test.html.polymer.bootstrap.dart.js:14201dart.HttpRequest_getString @ html_test.html.polymer.bootstrap.dart.js:14189dart.LogInjector.injectLogsFromUrl$1 @ html_test.html.polymer.bootstrap.dart.js:22548dart.main0 @ html_test.html.polymer.bootstrap.dart.js:4974dart._IsolateContext.eval$1 @ html_test.html.polymer.bootstrap.dart.js:1949dart.startRootIsolate @ html_test.html.polymer.bootstrap.dart.js:1628(anonymous function) @ html_test.html.polymer.bootstrap.dart.js:30960(anonymous function) @ html_test.html.polymer.bootstrap.dart.js:30961init.currentScript @ html_test.html.polymer.bootstrap.dart.js:30941(anonymous function) @ html_test.html.polymer.bootstrap.dart.js:30952(anonymous function) @ html_test.html.polymer.bootstrap.dart.js:30965
html_test.html.polymer.bootstrap.dart.js:17268 
> 00:00 [32m+0[0m[33m ~2[0m: getParentElement Polymer elements[0m
> html_test.html.polymer.bootstrap.dart.js:17268   [33mSkip: enable!!![0m
> html_test.html.polymer.bootstrap.dart.js:17268 
> 00:00 [32m+1[0m[33m ~2[0m: getParentElement Polymer shadow DOM elements[0m
> html_test.html.polymer.bootstrap.dart.js:17268 
> 00:00 [32m+1[0m[33m ~2[0m: All tests passed![0m

**Comment by nex3** [comment]
@zoechi It looks like the polymer transformers will need to be able to parse our custom `<link>` tag for this to work. I've filed dart-lang/polymer.dart#60 and talked to @jakemac53 about it and that should be possible.

> I have added `<script type="application/dart" src="html_test.dart"></script>` in the body because otherwise the Polymer transformer reports an error

This definitely won't work. Test files need wrappers to run in the browser or they won't work.

**Comment by zoechi** [comment]
Thanks, for checking. I'm positive they add support for this.

**Comment by zoechi** [comment]
That was quick! My example Polymer tests are working just fine now :+1:
