### ISSUE TITLE
Tons of failing tests with `--preview-dart-2`

### ISSUE THREAD

**Issue by grouma** [dart-lang/test#842]
I ran the following:
`DART_VM_OPTIONS=--preview-dart-2 pub run test`

and found tons of failing tests:
`08:46 +796 ~10 -159: Some tests failed.`

This needs to be addressed in the near future.

**Comment by zoechi** [comment]
I get
```
 (dart2) $ pub run test
Unable to spawn isolate: file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/analyzer-0.30.0+4/lib/src/dart/element/element.dart:4968:5: Error: Declared type variables of 'GenericFunctionTypeElementImpl::accept' doesn't match those on overridden method 'Element::accept'.
  T accept<T>(ElementVisitor<T> visitor) {
    ^
file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/analyzer-0.30.0+4/lib/src/dart/element/element.dart:4968:33: Error: The parameter 'visitor' of the method 'GenericFunctionTypeElementImpl::accept' has type analyzer.dart.element.element::ElementVisitor<analyzer.src.dart.element.element::GenericFunctionTypeElementImpl::accept::T>, which does not match the corresponding type in the overridden method (analyzer.dart.element.element::ElementVisitor<dynamic>).
Change to a supertype of analyzer.dart.element.element::ElementVisitor<dynamic> (or, for a covariant parameter, a subtype).
  T accept<T>(ElementVisitor<T> visitor) {
                                ^
file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/analyzer-0.30.0+4/lib/src/cancelable_future.dart:255:17: Error: Declared type variables of '_CancelableCompleterFuture::then' doesn't match those on overridden method 'Future::then'.
  Future/*<S>*/ then/*<S>*/(FutureOr/*<S>*/ onValue(T value),
                ^
file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/analyzer-0.30.0+4/lib/src/cancelable_future.dart:255:17: Error: The return type of the method '_CancelableCompleterFuture::then' is dart.async::Future<dynamic>, which does not match the return type of the overridden method (dart.async::Future<dart.async::Future::then::R>).
Change to a subtype of dart.async::Future<dart.async::Future::then::R>.
  Future/*<S>*/ then/*<S>*/(FutureOr/*<S>*/ onValue(T value),
                ^
file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/analyzer-0.30.0+4/lib/src/cancelable_future.dart:292:17: Error: Declared type variables of '_WrappedFuture::then' doesn't match those on overridden method 'Future::then'.
  Future/*<S>*/ then/*<S>*/(FutureOr/*<S>*/ onValue(T value),
                ^
file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/analyzer-0.30.0+4/lib/src/cancelable_future.dart:292:17: Error: The return type of the method '_WrappedFuture::then' is dart.async::Future<dynamic>, which does not match the return type of the overridden method (dart.async::Future<dart.async::Future::then::R>).
Change to a subtype of dart.async::Future<dart.async::Future::then::R>.
  Future/*<S>*/ then/*<S>*/(FutureOr/*<S>*/ onValue(T value),
                ^
file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.0-alpha.4.1/lib/src/fasta/util/link.dart:117:19: Error: The parameter 'f' of the method 'Link::every' has type (dynamic) → dart.core::bool, which does not matc the corresponding type in the overridden method ((fasta.util.link::Link::T) → dart.core::bool).
Change to a supertype of (fasta.util.link::Link::T) → dart.core::bool (or, for a covariant parameter, a subtype).
  bool every(bool f(T)) {
                  ^
file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.0-alpha.4.1/lib/src/fasta/util/link.dart:141:5: Error: The method 'Link::singleWhere' has fewer named arguments than those of overridden method 'Iterable::singleWhere'.
  T singleWhere(bool f(T e)) => _unsupported('singleWhere');
    ^
file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/analyzer-0.30.0+4/lib/src/fasta/element_store.dart:244:7: Error: Declared type variables of 'AnalyzerLocalVariableElemment::accept' doesn't match those on overridden method 'MockElement::accept'.
class AnalyzerLocalVariableElemment extends MockElement
      ^
file:///Users/zoechi/.pub-cache/hosted/pub.dartlang.org/analyzer-0.30.0+4/lib/src/fasta/element_store.dart: Error: The parameter 'visitor' of the method 'AnalyzerLocalVariableElemment::accept' has type analyzer.dart.element.element::ElementVisitor<dynamic>, which does not match the corresponding type in the overridden method (dynamic).
Change to a supertype of dynamic (or, for a covariant parameter, a subtype).
```

Looks a bit like dart-lang/sdk#32253 but that is closed. (links in dart-lang/sdk#32253 lead to dart-lang/sdk#33180)

```
Dart VM version: 2.0.0-dev.60.0 (Mon Jun 4 22:09:13 2018 +0200) on "macos_x64"
```

**Comment by kevmoo** [comment]
Make sure you are on HEAD and run `pub upgrade`. – you have a very old
analyzer

Nate and Gary are working hard to get the tests running w/ preview-dart-2

**Comment by zoechi** [comment]
`analyzer 0.30.0+4 (0.32.1 available)` 
I forgot the analyzer from my projects dependencies are used for that.

Interestingly a dependency_override forces older `build_config` and `build_runner`

![image](https://user-images.githubusercontent.com/405837/41169148-58636956-6b48-11e8-977a-db0b2ae9836f.png)

I'm not blocked. I just wanted to provide additional information.

**Comment by zoechi** [comment]
@kevmoo @grouma right, I missed that built_redux prevented updating the analyzer `0.30.0+4` to a newer version and I wasn't aware that the analyzer from my dependencies is used for that (instead of the SDK).
I added a dependency-override and the analyzer warnings went away. 
Thanks for the hint :)

**Comment by joeconwaystk** [comment]
`pub run test` is not cleaning up after itself; it is leaking memory consumed by test suites. The process  starts paging to disk, and tests start timing out. Significantly exacerbated by tests that spawn isolates.  This is currently a blocker: can't run in CI, and when --preview-dart-2 becomes the default, we'll be stuck in place.

**Comment by kevmoo** [comment]
> pub run test is not cleaning up after itself; it is leaking memory consumed by test suites. The process starts paging to disk, and tests start timing out. Significantly exacerbated by tests that spawn isolates. This is currently a blocker: can't run in CI, and when --preview-dart-2 becomes the default, we'll be stuck in place.

Thanks for the heads-up, @joeconwaystk 

CC @vsmenon @dgrove

**Comment by grouma** [comment]
@joeconwaystk is `pub run test` leaking memory specifically for the tests in this package? If not, do you have a minimal repro which I can use to debug the issue? If so can you please file a new issue with the details.

**Comment by grouma** [comment]
As of https://github.com/dart-lang/test/commit/4302ce42db8b1f114558a679b3a007cd95dabfbb

I believe only the following files have issues:

- `test/runner/hybrid_test.dart`

  - A number of tests fail due to an `IsolateSpawnException`. Looks like these tests try to spawn an isolate by loading a dart file remotely e.g. `http://localhost:41791/some/path/hybrid.dart`. Further investigation needs to be done to make sure this isn't a `package:test` issue and is in fact an SDK issue.

- `test/runner/pause_after_load_test.dart`

  - Looks like the core functionality of `pause_after_load` works but the test runner doesn't exit properly. This causes a number of tests in this file to timeout.

- `test/runner/configuration/configuration_test.dart`

  - This should be pretty easy to fix. Looks like there is a type issue here: https://github.com/dart-lang/test/blob/master/lib/src/runner/configuration.dart#L297

**Comment by natebosch** [comment]
> - `test/runner/hybrid_test.dart`
>   - A number of tests fail due to an `IsolateSpawnException`. Looks like these tests try to spawn an isolate by loading a dart file remotely e.g. `http://localhost:41791/some/path/hybrid.dart`. Further investigation needs to be done to make sure this isn't a `package:test` issue and is in fact an SDK issue.

I can't repro this. The error looks like it matches https://github.com/dart-lang/sdk/issues/33388 but I am not getting it from this test. Is it maybe coming from somewhere else?

**Comment by grouma** [comment]
For clarity running the following fails at HEAD:

`DART_VM_OPTIONS=--preview-dart-2 pub run test test/runner/hybrid_test.dart -n "spawnHybridUri(): in the browser loads a file in a separate isolate connected via StreamChannel"`

The linked SDK error does seem to be the blocking issue. We likely can skip the corresponding tests until that issue is resolved.  As of https://github.com/dart-lang/test/pull/867 the hybrid tests are the only remaining broken tests. Once we have the skips in we can close this issue.

**Comment by kevmoo** [comment]
Well done, ya'll!
