### ISSUE TITLE
json reporter test will break with next sdk build

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#854]
I happened to be running on a bleeding edge sdk and noticed this - once the next sdk drops the events are going to start coming in a slightly different order.

I don't know if this will break IDE integrations or not, cc @DanTup

**Comment by DanTup** [comment]
Do you have info on what changes order? Currently I'm only using JSON to print some basic results to the console for Flutter tests, so as long as it's nothing crazy (like test results coming before the test definition) I doubt it'll affect me.

**Comment by jakemac53** [comment]
It is mostly the first couple events that change in ordering - `testStart` still always comes before `testEnd` in my testing.

Here is some example output from one of the tests:

```
{"protocolVersion":"0.1.0","runnerVersion":null,"type":"start","time":0}
    {"suite":{"id":0,"platform":"vm","path":"test.dart"},"type":"suite","time":0}
    {"test":{"id":1,"name":"loading test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1}
    {"count":1,"type":"allSuites","time":4}
    {"group":{"id":2,"suiteID":0,"parentID":null,"name":null,"metadata":{"skip":false,"skipReason":null},"testCount":3,"line":null,"column":null,"url":null},"type":"group","time":405}
    {"test":{"id":3,"name":"success 1","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":6,"column":7,"url":"file:///tmp/dart_test_NNTXTR/test.dart"},"type":"testStart","time":407}
    {"testID":1,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":410}
    {"testID":3,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":451}
    {"test":{"id":4,"name":"success 2","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":7,"column":7,"url":"file:///tmp/dart_test_NNTXTR/test.dart"},"type":"testStart","time":452}
    {"testID":4,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":454}
    {"test":{"id":5,"name":"success 3","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":8,"column":7,"url":"file:///tmp/dart_test_NNTXTR/test.dart"},"type":"testStart","time":455}
    {"testID":5,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":457}
    {"success":true,"type":"done","time":468}
```

Specifically, `allSuites` now comes after the first `testStart` - but that first `testStart` is actually weird anyways I don't understand why it exists (it doesn't correspond to a real test, but all test runs seem to have it).

I think there were some other subtle differences as well.

**Comment by jakemac53** [comment]
And actually I am not totally sure this is related to sync-async - it just seems likely.

**Comment by grouma** [comment]
Sorry I didn't chime in earlier. This is a known issue. This sync-async behavior here has changed:
https://github.com/dart-lang/test/issues/842

Closing in favor of: https://github.com/dart-lang/test/issues/842

**Comment by DanTup** [comment]
Slight tangent - what *is* sync-async? I've seen the term a lot lately, and there are many issues about enabling it (or things breaking on the change) but I can't actually figure out what it is!

**Comment by jakemac53** [comment]
Basically, `async` methods used to have an implicit microtask at the start, so no code inside them ever executed synchronously. sync-async is a performance enhancement to get rid of that microtask, so all the synchronous code (code before the first `await` essentially) will run synchronously.

As an illustration, this code has different behavior with/without sync-async:

```dart
void main() async {
  print('a');
  var done = printStuffAsync();
  print('b');
  await done;
  print('c');
}

void printStuffAsync() async {
  print('1');
  await null;
  print('2');
}
```

Without sync-async, it prints:

```
a
b
1
2
c
```

With sync-async, it prints:

```
a
1
b
2
c
```

**Comment by DanTup** [comment]
Aha, gotcha! Didn't realise it previously did that. Thanks!

**Comment by DanTup** [comment]
@jakemac53 

> Specifically, allSuites now comes after the first testStart

I'm not using allSuites so this doesn't affect me. Not sure about IntelliJ etc. though (@pq are you a good person to ask?).

> but that first testStart is actually weird anyways I don't understand why it exists (it doesn't correspond to a real test, but all test runs seem to have it).

I don't like how this works either, but basically it's a "fake" test sent at the start of the run that's called "Loading {suitepath}" and then it "passes" with `hidden=true` when the suite loads. Would be much better as a specific event IMO, as the long text looks super wonky in a test tree so I have to detect it and hide it from my tree:

```ts
// If this is a "loading" test then mark it as hidden because it looks wonky in
// the tree with a full path and we already have the "running" icon on the suite.
if (testNode.test.name.startsWith("loading ") && testNode.parent instanceof SuiteTreeItem)
	testNode.hidden = true;
else
	testNode.hidden = false;
```

Changing it might be breaking though :/

(though if you do want to make breaking changes to improve stuff, maybe we can get shut of that phantom empty group at the root of every suite too ;-))

**Comment by jakemac53** [comment]
> I don't like how this works either, but basically it's a "fake" test sent at the start of the run that's called "Loading {suitepath}" and then it "passes" with hidden=true when the suite loads. Would be much better as a specific event IMO, as the long text looks super wonky in a test tree so I have to detect it and hide it from my tree:

Ya it seems pretty weird but its probably not worth a breaking change at this point :(

**Comment by DanTup** [comment]
A nice non-breaking change would be to put some sort of flag on it to at least indicate it's a fake test (or copy the `hidden` flag to the testStart too). That way we wouldn't need the fragile-looking logic I posted above :-)

**Comment by jakemac53** [comment]
> A nice non-breaking change would be to put some sort of flag on it to at least indicate it's a fake test (or copy the hidden flag to the testStart too). That way we wouldn't need the fragile-looking logic I posted above :-)

True, ya I think adding some sort of special field on the event would at least help here
