### ISSUE TITLE
spawnHybrid* are broken on Dart 2

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#860]
The following file breaks in Dart 2 runtime mode:

```dart
import 'package:test/test.dart';

void main() {
  test("spawn hybrid", () {
    spawnHybridCode("hybridMain(_) {}");
  });
}
```

It produces this error:

```
00:00 +0: spawn hybrid
00:00 +0 -1: spawn hybrid [E]
  type 'CloseGuaranteeChannel<dynamic>' is not a subtype of type 'VirtualChannel<dynamic>'
  package:test   spawnHybridCode
  test.dart 5:5  main.<fn>
  
00:00 +0 -1: Some tests failed.
```

This is blocking Dart Sass's support for Dart 2 runtime semantics, and thus our ability to upgrade our SDK versions.

**Comment by natebosch** [comment]
I know we've hit this one, I think it's fixed by https://github.com/dart-lang/test/pull/851 and we probably just need  a publish. Does it work for you with a git override?

**Comment by nex3** [comment]
Looks like it does.

**Comment by natebosch** [comment]
We've got a few more fixes to get in. Will publish early next week.
