### ISSUE TITLE
`pub run test` leaks memory over time when using `--preview-dart-2`

### ISSUE THREAD

**Issue by joeconwaystk** [dart-lang/test#863]
Reproduction repository is here: https://github.com/joeconwaystk/publeak. Instructions for running are in README. It runs 6 test suites that spawn an isolate, wait for it to ack, and then close isolate. At the end of reach test, it prints memory usage of Dart VM process running the tests (requires macOS). When running with `--preview-dart-2`, memory usage continues to increase for each suite. When running without the flag, memory usage is constant across all test suites.

I don't think this is an issue specific to this package, it occurred when `--preview-dart-2` flag was made usable with `pub`. My guess is that the snapshots are being retained.

**Comment by jakemac53** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/33428
