### ISSUE TITLE
Problems running the new test command

### ISSUE THREAD

**Issue by Fox32** [dart-lang/test#87]
Currently, when I'm in my project and run ```pub run test``` I get a message that dart.exe has stopped working (the Windows dialog). I don't get any console output. The event log contains the following information:

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2015-04-22T12:34:21.000000000Z" /> 
  <EventRecordID>68943</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>snip</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>dart.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>553610cd</Data> 
  <Data>dart.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>553610cd</Data> 
  <Data>40000015</Data> 
  <Data>0000000000399101</Data> 
  <Data>28dc</Data> 
  <Data>01d07cf8a72fa607</Data> 
  <Data>D:\Projekte\Tools\dart\dart-sdk\bin\dart.exe</Data> 
  <Data>D:\Projekte\Tools\dart\dart-sdk\bin\dart.exe</Data> 
  <Data>e5ef3b80-e8eb-11e4-bec3-90e6ba20879e</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

If I exectute ```pub run test --help``` it doesn't crash and works as expected. 

I know that these information aren't really helpful, but If you have an idea how to approach this problem I can try to help you.

**Some details:**
Windows 8.1 64bit
Dart VM version: 1.10.0-dev.1.9 (Tue Apr 21 01:54:39 2015) on "windows_x64"
test 0.12.0-beta.10

**Comment by nex3** [comment]
Windows support is currently totally busted, but I'm working on a fix.

**Comment by Fox32** [comment]
It's working \o/
Now I only have problems with tests using the mock package (http://dartbug.com/23106).
