### ISSUE TITLE
Add the `pid` to the `start` event

### ISSUE THREAD

**Issue by DanTup** [dart-lang/test#889]
Currently when running without the debugger I can't find a way to get the `pid`. Is it possible to add this to the `start` JSON event? (other tools like Flutter and the analysis server do this).

The reason is that in Dart Code we use `shell=true` when spawning processes to work around all sorts of issues we've had with escaping of paths and other things. Unfortunately this means the process we have a reference to is for the shell and not the actual process we spawned. Killing that [shell process is somewhat unreliable](https://github.com/Dart-Code/Dart-Code/issues/1025) and often doesn't terminate the process spawned from it.

When debugging, we get the `pid` from observatory; but when running without the debugger we don't use observatory so we don't have this.

I'm happy to send a PR for this if you'd accept it. I did this in flutter and it was fairly straight forward (https://github.com/flutter/flutter/pull/17873).

**Comment by jakemac53** [comment]
Sounds good to me, I can't think of any reasons not to include it.

**Comment by DanTup** [comment]
Two questions:

1. Is the code that emits the start event always running in the VM? Eg. is it safe to read the process pid here (eg. it doesn't run in the browser?)
2. I see there's a json_reporter.schema.json - is there any way I can test/validate changes to that? And should I change the version number in it (it currently suggests the version will always be `0.1.`?)

**Comment by jakemac53** [comment]
> Is the code that emits the start event always running in the VM? Eg. is it safe to read the process pid here (eg. it doesn't run in the browser?)

As far as I know, it is only imported by the test runner which only runs on the vm.

> I see there's a json_reporter.schema.json - is there any way I can test/validate changes to that? And should I change the version number in it (it currently suggests the version will always be 0.1.?)

News to me! I probably should have updated that with the other schema changes as well....

**Comment by DanTup** [comment]
I've opened https://github.com/dart-lang/test/pull/890; PTAL!
