### ISSUE TITLE
test runner exits before async code executes

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#91]
The following example will run the test in the old unittest package, but not with the new test package:

```dart
library async_test;

import 'dart:async';
import 'package:test/test.dart';
// import 'package:unittest/unittest.dart';

main() {
  new Future.delayed(new Duration(milliseconds: 100), () {
    test('true', () {
      expect(true, isTrue);
    });
  });
}
```

**Comment by kevmoo** [comment]
Explicitly not allowed. All tests must be registered synchronously.

I've imagined tweaks to allow async test definitions, but it'd be a not-trivial change.

**Comment by jakemac53** [comment]
Ok thats fine, just thought it was worth bringing up since it used to work. Fwiw this does mean some extra boilerplate for polymer users, but I don't think its a huge issue.

**Comment by nex3** [comment]
What's the context for polymer users defining tests asynchronously?

**Comment by kevmoo** [comment]
Opened a feature request - https://github.com/dart-lang/test/issues/92

**Comment by jakemac53** [comment]
If this was supported, a polymer test would look like this (and this is how we encourage people to write their normal polymer entrypoints):

```dart
import 'package:test/test.dart';
import 'package:polymer/polymer.dart';
export 'package:polymer/init.dart'; // This defines our main, and initializes polymer.

@whenPolymerReady
void runTests() {
  /// declare tests here
}
```

Instead they will have to manually initialize polymer, so it will look like this:

```dart
import 'package:test/test.dart';
import 'package:polymer/polymer.dart';

void main() {
  Zone zone;
  setUp(() async {
    if (zone == null) zone = await initPolymer();
    await Polymer.onReady;
  });

  test('my test', () => zone.run(() {
    expect(true, isTrue);
  }));
}
```

We could probably clean some of this up with some custom polymer test helpers, but it would be a bit sad to do that. Specifically all the zone stuff is really not pretty to expose to users :(.

**Comment by nex3** [comment]
It looks like `0.11.0` somewhat accidentally handles this by virtue of only starting to listen for tests once the first `test()` call is made. We could do something similar, but it would fall down in the case where no `test()` method is defined at all.

Jake, could Polymer produce a `main()` method that returns a `Future`?

**Comment by kevmoo** [comment]
Would the return future model work stand-alone, though?

**Comment by nex3** [comment]
Yes, standalone already works basically the same way the old runner did.

**Comment by jakemac53** [comment]
Polymers init.dart does already return a future from its main, although not the one that we would need for this case. We could modify that though to return a future that doesn't complete until all functions with an @initMethod have been ran, and possibly @whenPolymerReady methods as well although that is a bit more complicated.

There might be more value in just reverting to the behavior of waiting until at least one call to `test()` is made. This generally does the right thing since a test file without at least one call to `test()` is pointless anyways (at least afaik?). Have we had any issues come up regarding this existing behavior?

**Comment by kevmoo** [comment]
@jakemac53 the issue is how we handle an external controller.

There is now a synchronous call to main from a wrapper script. Once main returns, it assumes all calls to `test` have completed.

One could imagine a `polymerTest` method that wraps up tho logic you lay out above.

The clear thing: this scenario does not require async test registration – it just requires that all tests wait to run until after some  async work completes.

**Comment by jakemac53** [comment]
> There is now a synchronous call to main from a wrapper script. Once main returns, it assumes all calls to test have completed.

As Natalie eluded to earlier, if it can check if a Future was returned from main and wait for that to complete before exiting then we should be able to make that work. The contract seems like it would be relatively simple, and it would provide a lot of flexibility.

> One could imagine a polymerTest method that wraps up tho logic you lay out above.

Absolutely this can be done, and it would get rid of some of the `zone` boilerplate. However, it doesn't solve the issue of having to declare your own main and call initPolymer() directly, instead of using the default main provided in `package:polymer/init.dart`. Also, it would be preferable if tests in polymer could be written and look just like normal tests. Otherwise we have an issue with the discoverability of this special `polymerTest` method.

> The clear thing: this scenario does not require async test registration – it just requires that all tests wait to run until after some async work completes.

The ideal situation would be to allow test registration inside of @initMethod and @whenPolymerReady methods. Typically when using these annotations the developer is not writing a main at all, and these methods get executed asynchronously, so the tests defined in them will be registered asynchronously as well.

**Comment by nex3** [comment]
I'd like to go with the Future-based solution. Although the old behavior would work here, it probably wouldn't work everywhere, and it's a very nonstandard way of making the API work anyway.

**Comment by jakemac53** [comment]
I agree, its framework agnostic and easy to reason about.
