### ISSUE TITLE
vm_service_client 0.2.3 dependency use deleted dart constant

### ISSUE THREAD

**Issue by muzuro** [dart-lang/test#912]
Build fails 
```
dev_dependencies:
  test: ^1.3.0
```
becouse latest `dart 2.0.0-dev.69.2.` don`t contains uppercase constants. Reason is 
vm_service_client: ^0.2.3 dependency. 
Workaround:
```
dependency_overrides:
  vm_service_client: ^0.2.6
```

**Comment by grouma** [comment]
Doing a `pub upgrade` should have resolved the issue. On the same version of the SDK I pull down version `0.2.6`. I'm not sure why a older version was picked up.
