### ISSUE TITLE
Allow annotations to omit `const`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/test#915]
The CFE will already ensure the code is valid, the test package doesn't need to repeat the checks.

**Comment by natebosch** [comment]
Hmm, parts of this are harder than I had hoped.

We use an unresolved `Expression` in order to figure out what constructor is being called. With `const` [this would be an `InstanceCreationExpression`](https://github.com/dart-lang/test/blob/769f0dd9ccb70a3def5834e4a37c00110fbcb068/lib/src/runner/parse_metadata.dart#L388). Without the `const` we end up with a `MethodInvocation`. Getting back to a class and constructor name isn't immediately obvious to me. @bwilkerson, @scheglov - is there a canonical way to handle this? I thought method calls were not allowed in const contexts (we're parsing inside an annotation so it should always be const) - should the analyzer be able to parse it to an `InstanceCreationExpression` in those cases?

**Comment by chalin** [comment]
Any progress on this? /cc @kevmoo @kwalrath

**Comment by natebosch** [comment]
I was able to fix the case for collection literals but haven't published yet.

I have not been able to fix the case for constructor calls like `@Timeout(Duration(seconds: 5))`. Parsing this is much trickier.
