### ISSUE TITLE
Add the ability to add to the tearDown for a running test

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#93]
This is an idea that comes from `scheduled_test`. It makes it possible to create testing APIs that can clean up after themselves without the user having to explicitly pipe them to the tearDown. For example, a `Sandbox` class might tear down the sandbox directory; `ScheduledProcess` uses this to kill dangling processes.

**Comment by greglittlefield-wf** [comment]
Any updates on this issue? This feature would be nice to have.

**Comment by nex3** [comment]
None yet. If you want to contribute though, I'd gladly take a patch!

**Comment by greglittlefield-wf** [comment]
Cool, I'll look into it, then. Thanks!

**Comment by greglittlefield-wf** [comment]
It would be expected that any tearDowns added inside a `test` are run directly afterwards, before any `group` tearDowns, correct?

E.g., the following:
```dart
group('', () {
  tearDown(() => print('tearDown (group)');
  
  test('', {
    tearDown(() => print('tearDown (test)'));
    print('test');
  });
}
```

would output:
```
test
tearDown (test)
tearDown (group)
```

**Comment by nex3** [comment]
That's right. If multiple tear-downs are added within a test, they should also run in last-in-first-out order.
