### ISSUE TITLE
tests fail when --pub-serve is used

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#94]
When I run
`pub serve test`
> Serving bwu_utils_dev test on http://localhost:8080

and then in another console
`pub run test -pvm -pdartium --pub-serve=8080`
I get
> (master) $ pub run test -p vm -p dartium --pub-serve=8080
00:00 +0 -1: test/testing/webdriver/simple_test.dart: load error                                    
  Failed to load "test/testing/webdriver/simple_test.dart":
  Error getting http://localhost:8080/testing/webdriver/simple_test.dart.vm_test.dart: 404 Not Found
  Make sure "pub serve" is serving the test/ directory.
00:00 +0 -2: test/testing/webdriver/polymer/polmymer_test.dart: load error                          
  Failed to load "test/testing/webdriver/polymer/polmymer_test.dart":
  Error getting http://localhost:8080/testing/webdriver/polymer/polmymer_test.dart.vm_test.dart: 404 Not Found
  Make sure "pub serve" is serving the test/ directory.
00:00 +0 -3: test/grinder/dart_archive_downloader_test.dart: load error                             
  Failed to load "test/grinder/dart_archive_downloader_test.dart":
  Error getting http://localhost:8080/grinder/dart_archive_downloader_test.dart.vm_test.dart: 404 Not Found
  Make sure "pub serve" is serving the test/ directory.
00:00 +0 -4: test/testing/polymer_test_example/html_test.dart: load error                           
  Failed to load "test/testing/polymer_test_example/html_test.dart":
  Error getting http://localhost:8080/testing/polymer_test_example/html_test.dart.browser_test.dart.js: 404 Not Found
  Make sure "pub serve" is serving the test/ directory.
00:00 +0 -4: Some tests failed.                                                 

The tests run fine when I don't pass `--pub-serve=8080`.

**Comment by zoechi** [comment]
I updated my `pubspec.yaml` according to the info in the README about the Polymer transformer and now it's working again.

**Comment by kevmoo** [comment]
:metal: Glad this is working for you!
