### ISSUE TITLE
Remove import on `dart:isolate` from the frontend

### ISSUE THREAD

**Issue by grouma** [dart-lang/test#946]
`spawn_hybrid.dart` imports `remote_exception.dart` which imports `dart:isolate`. This is a restrictive import so it should be hidden behind a conditional import.

**Comment by natebosch** [comment]
Looks like it's hacked in to "work" with `dart2js` with the same hack as `io` uses.

https://github.com/dart-lang/sdk/blob/d5e5842971bf9681a592c2be64bff7d96f0de218/sdk/lib/libraries.json#L227-L231

It exists with a patch, but marked as not supported. Imports will succeed but will throw if you try to use anything other than a constant at runtime.

**Comment by natebosch** [comment]
Final issue was fixed in https://github.com/dart-lang/test/pull/990
