### ISSUE TITLE
Looking into dart2js batch mode

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#96]
It's a thing?

**Comment by nex3** [comment]
@peter-ahe-google, is this a thing that's supported for external use? Can you give us some details on how it works?

**Comment by nex3** [comment]
Pinging @floitschG as well.

**Comment by kevmoo** [comment]
@nex3 talking to @floitschG 

Run `dart2js --batch`
Then echo command line args. It does its work.
Then echo another line of args.

...etc

**Comment by nex3** [comment]
Can it run in parallel? We get a fair amount of benefit from running two or three instances at once, and it would be nice not to give that up.

**Comment by floitschG** [comment]
The --batch mode does not run in parallel. It was designed for the build-bots where sharding takes already care of running things in parallel.
I guess it would be relatively easy to write a new dart.file that imports the main-entry file and runs its main several times in parallel (using isolates?)

**Comment by nex3** [comment]
Given that, it's not clear whether batch mode would be faster or not. It's worth experimenting at some point, though, for sure.

**Comment by nex3** [comment]
I think with DDC on the horizon, this isn't likely to happen.
