### ISSUE TITLE
expect(): "If actual is a Future, the test won't complete until the future emits a value." isn't true

### ISSUE THREAD

**Issue by Hixie** [dart-lang/test#965]
The docs for `expect()` say:

> If actual is a Future, the test won't complete until the future emits a value.

...but that doesn't seem to be true. I tried something like:

```
expect(compute(test1, 0), 1);
```

...where `compute` returns a `Future`, and it failed with:

```
  Expected: <1>
    Actual: <Instance of 'Future<int>'>
```

**Comment by jakemac53** [comment]
I think this is probably the specific doc comment you are referring to https://github.com/dart-lang/test/blob/ac21330338e0a7ad68fb19058bb92260706dd6cf/pkgs/test_api/lib/src/frontend/expect.dart#L41.

I believe this is supposed to be taken in the context of the `skip` argument, although it is probably still incorrect or at best misleading? Two paragraphs down accurately describes the  behavior, where certain matchers will block the test from completing until the Future completes https://github.com/dart-lang/test/blob/ac21330338e0a7ad68fb19058bb92260706dd6cf/pkgs/test_api/lib/src/frontend/expect.dart#L49.

**Comment by natebosch** [comment]
The current text of the docs is:

```
Certain matchers, like completion and throwsA, either match or fail asynchronously. When you use expect with these matchers, it ensures that the test doesn't complete until the matcher has either matched or failed. If you want to wait for the matcher to complete before continuing the test, you can call expectLater instead and await the result.
```

The original mischaracterization of behavior is no longer present.
