### ISSUE TITLE
consider updating matcher constraint to include 0.12.4

### ISSUE THREAD

**Issue by pq** [dart-lang/test#969]
https://github.com/dart-lang/test/blob/8e2c86fc8bba6eb42746697b303e286439eef682/pkgs/test_core/pubspec.yaml#L28-L30

Can we bump this to include `0.12.4`?

https://pub.dartlang.org/packages/matcher/versions/0.12.4

/cc @grouma @kevmoo

**Comment by natebosch** [comment]
Closing since new matcher and test versions have been published since this issue.
