### ISSUE TITLE
Why do even simple tests take so long?

### ISSUE THREAD

**Issue by davenotik** [dart-lang/test#98]
I run my group of tests – a simple parser – and it takes 8-11s. What gives?

**Comment by nex3** [comment]
A small set of tests certainly isn't *supposed* to take that long, but without more information there's no way to say what's going on. What operating system are you using? What version of `test` are you using ?Can you provide the code for the tests? What makes you think that the code you're testing isn't slow itself?

**Comment by davenotik** [comment]
Thanks for a great lib, Natalie! Here are my tests: https://github.com/woven/emoji/blob/master/test/all_test.dart

Latest OS X, latest Dart SDK. I figured there's no way the tests themselves are slow given the simple thing I'm doing and that when using the lib directly the code runs fast.

**Comment by nex3** [comment]
Those tests take just over one second to run for me, most of which is the constant-time overhead of loading the file. The same is true when @kevmoo runs it on his OS X machine. Unfortunately, I don't think there's anything we can do here if we can't reproduce it.

**Comment by davenotik** [comment]
FWIW, "proof": http://d.pr/v/1bpfU

**Comment by davenotik** [comment]
Thought maybe I have to use `pub run test` but similar result:

```
DaveMac:emoji dave$ pub run test test/all_test.dart 
00:09 +3: All tests passed!  
```

``
DaveMac:emoji dave$ dart --version
Dart VM version: 1.10.0 (Fri Apr 24 17:32:20 2015) on "macos_x64"
```

**Comment by nex3** [comment]
Don't get me wrong, I believe that it's slow for you, there's just nothing I can do about it without it being slow for me as well :-/. Your best bet would be to dive into the test package yourself and add enough logging so that maybe you can figure out what's going on.
