### ISSUE TITLE
Expose pkgs/test_api/test/utils.dart – somehow – pkg:test_test?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#993]
It'd be nice if folks writing test helpers could leverage these utilities instead of reinventing them.

**Comment by natebosch** [comment]
Can you give an example of a use case? I think most of the stuff in there is based on other details that aren't public.

**Comment by kevmoo** [comment]
https://pub.dartlang.org/documentation/source_gen_test/latest/source_gen_test/testAnnotatedElements.html is a great example.

This function calls `test(..)` a bunch. Which is great. There is no way for me to test it! I can put a function that calls `test` in a test function – without these types of utilities.

I had to create a number of one-off helpers to test parts of my flow. In the end, I can't really validate failure cases, though...

**Comment by natebosch** [comment]
In the medium term this would be blocked by cleaning up the public interface to `test_api` and `test_core`. In the slightly longer term this would likely be blocked by needing to refactor that file to hide the details that we don't want to be public anywhere. The the even longer term it's not a package we'd want to invest in maintaining.

**Comment by kevmoo** [comment]
...uh...okay 😞
